In [1]:
list.of.packages <- c("tidyverse","data.table","stargazer","ggfixest")
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages, repos = "http://cran.us.r-project.org")

invisible(lapply(list.of.packages, library, character.only = TRUE))

options(repr.matrix.max.rows=500, repr.matrix.max.cols=500)

── Attaching core tidyverse packages ────────────────────────────────────────────────────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.2.0     ✔ readr     2.2.0
✔ forcats   1.0.1     ✔ stringr   1.6.0
✔ ggplot2   4.0.2     ✔ tibble    3.3.1
✔ lubridate 1.9.5     ✔ tidyr     1.3.2
✔ purrr     1.2.1
── Conflicts ──────────────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

Attachement du package : ‘data.table’


Les objets suivants sont masqués depuis ‘package:lubridate’:

    hour, isoweek, mday, minute, month, quarter, second, wday, week,
    yday, year


Les objets suivants sont masqués depuis ‘package:dplyr’:

    between, first, last


L'objet suivant est masqué depuis ‘package:purrr’:

    transpose



Please cite as:


 Hlavac, Marek (2022). stargazer: Well-Formatted Regression and Summary Statistics Tables.

 R package version 5.2.3. https://CRAN.R-project.org/package=stargazer


Le chargement a nécessité le package : fixest

In [2]:
T_bins_labels <- c("<=17°C","17,21]","21,23]","23,25]","25,27]","27,29]","29,31]","31,33]",">33°C")
bin_ref_T <-"17,21]"

# Children

In [3]:
df_children <- fread("./2_Regression_datasets/output/df_reg_children.csv")
sprintf("%i rows x %i columns", nrow(df_children), ncol(df_children))
head(df_children,2)

[1] "281812 rows x 321 columns"

  DHS_round DHSCLUST State_2011               District_2011 cell_x_01 cell_y_01
1 2015      10001    Andaman & Nicobar Island South Andaman 92.7      11.7
2 2015      10001    Andaman & Nicobar Island South Andaman 92.7      11.7
  cell_x_025 cell_y_025 HH_ID Mother_id      Child_id Resp_nb Interview_month
1 92.75      11.75      10    01000110    02 1        2       7
2 92.75      11.75      23    01000123    02 1        2       7
  Interview_year Measured_date_CDC Measured_date Measured_day Measured_month
1 2015           42203             2015-07-20    20           7
2 2015           42203             2015-07-20    20           7
  Measured_year Birth_month Birth_year Child_female Child_birth_order
1 2015          6           2011       1            1
2 2015          2           2013       1            1
  Child_alive_age_month Child_hemo_level_alti Child_weight_for_height_zscore
1 49                    112                    0.16
2 29                    118                   -1.10
  Child_diarrhea Child_fever Child_cough Child_still_breastfeeding
1 0              0           1           0
2 0              0           0           0
  Child_given_plain_water Child_given_juice Child_given_milk
1 NA                      NA                NA
2 NA                      NA                NA
  Child_given_baby_formula Child_given_fortified_baby_food Child_given_soup
1 NA                       NA                              NA
2 NA                       NA                              NA
  Child_given_other_liquid Child_given_chicken_duck_birds
1 NA                       NA
2 NA                       NA
  Child_given_bread_noodles_grains Child_given_potatoes_cassava_tubers
1 NA                               NA
2 NA                               NA
  Child_given_eggs Child_given_pumkins_carrots_squash
1 NA               NA
2 NA               NA
  Child_given_green_vegetables Child_given_mangoes_papaya_vitaminAfruits
1 NA                           NA
2 NA                           NA
  Child_given_other_fruits Child_given_liver_heart_organs
1 NA                       NA
2 NA                       NA
  Child_given_fish_sellfish Child_given_beans_peas_lentils_nuts
1 NA                        NA
2 NA                        NA
  Child_given_cheese_yogurt_milk_products
1 NA
2 NA
  Child_given_other_solid_semisolid_food Child_given_other_meat
1 NA                                     NA
2 NA                                     NA
  Child_given_yogurt Child_iron_supplem_7d Mother_no_educ Mother_prim_educ
1 NA                 1                     0              0
2 NA                 0                     0              0
  Mother_second_educ Mother_higher_educ Mother_hindu Mother_muslim
1 1                  0                  1            0
2 0                  1                  1            0
  Mother_not_hindu_nor_muslim Mother_ethni_SC Mother_ethni_ST Mother_ethni_OBC
1 0                            0               0               0
2 0                           NA              NA              NA
  Mother_ethni_other Mother_height Wealth_lowest Wealth_second Wealth_middle
1  1                 1599          0             0             0
2 NA                 1537          0             0             0
  Wealth_fourth Wealth_highest Urban Usual_resident Bednet_slept
1 1             0              1     1              0
2 1             0              1     1              0
  HH_time_water_source HH_air_conditioner HH_treat_water HH_no_toilet
1 0                    0                  1              0
2 0                    0                  1              0
  HH_well_water Interview_cdc Wasted Age_rounded Children_anemia
1 0             NA            0      54          0
2 0             NA            0      30          0
  Child_severe_anemia Child_moderate_anemia Child_mild_anemia Child_no_anemia
1 0                   0                     0                 1000
2 0                   0                     0                 1000
  Season Water_fetching_risk District_ID                            T_i30
1 Kharif 0                   Andaman & Nicobar Island_South Andaman 26.97639
2 Kharif 0                   Andaman & Nicobar Island_South Andaman 26.97639
  T_i20    T_i10   T_i30_bin T_i20_bin T_i10_bin T_Bin_17_21_Nhours_on30
1 26.97292 26.7875 (25,27]   (25,27]   (25,27]   0
2 26.97292 26.7875 (25,27]   (25,27]   (25,27]   0
  T_Bin_21_23_Nhours_on30 T_Bin_23_25_Nhours_on30 T_Bin_25_27_Nhours_on30
1 0                       4                       534
2 0                       4                       534
  T_Bin_27_29_Nhours_on30 T_Bin_29_31_Nhours_on30 T_Bin_inf17_Nhours_on30
1 182                     0                       0
2 182                     0                       0
  T_Bin_31_33_Nhours_on30 T_Bin_sup33_Nhours_on30 T_Bin_17_21_Nhours_on20
1 0                       0                       0
2 0                       0                       0
  T_Bin_21_23_Nhours_on20 T_Bin_23_25_Nhours_on20 T_Bin_25_27_Nhours_on20
1 0                       4                       354
2 0                       4                       354
  T_Bin_27_29_Nhours_on20 T_Bin_29_31_Nhours_on20 T_Bin_inf17_Nhours_on20
1 122                     0                       0
2 122                     0                       0
  T_Bin_31_33_Nhours_on20 T_Bin_sup33_Nhours_on20 T_Bin_17_21_Nhours_on10
1 0                       0                       0
2 0                       0                       0
  T_Bin_21_23_Nhours_on10 T_Bin_23_25_Nhours_on10 T_Bin_25_27_Nhours_on10
1 0                       3                       205
2 0                       3                       205
  T_Bin_27_29_Nhours_on10 T_Bin_29_31_Nhours_on10 T_Bin_inf17_Nhours_on10
1 32                      0                       0
2 32                      0                       0
  T_Bin_31_33_Nhours_on10 T_Bin_sup33_Nhours_on10 T_MeanBin_23_25_Ndays_on30
1 0                       0                       0
2 0                       0                       0
  T_MeanBin_21_23_Ndays_on30 T_MeanBin_25_27_Ndays_on30
1 0                          16
2 0                          16
  T_MeanBin_inf17_Ndays_on30 T_MeanBin_17_21_Ndays_on30
1 0                          0
2 0                          0
  T_MeanBin_27_29_Ndays_on30 T_MeanBin_29_31_Ndays_on30
1 14                         0
2 14                         0
  T_MeanBin_31_33_Ndays_on30 T_MeanBin_sup33_Ndays_on30
1 0                          0
2 0                          0
  T_MeanBin_23_25_Ndays_on20 T_MeanBin_21_23_Ndays_on20
1 0                          0
2 0                          0
  T_MeanBin_25_27_Ndays_on20 T_MeanBin_inf17_Ndays_on20
1 12                         0
2 12                         0
  T_MeanBin_17_21_Ndays_on20 T_MeanBin_27_29_Ndays_on20
1 0                          8
2 0                          8
  T_MeanBin_29_31_Ndays_on20 T_MeanBin_31_33_Ndays_on20
1 0                          0
2 0                          0
  T_MeanBin_sup33_Ndays_on20 T_MeanBin_23_25_Ndays_on10
1 0                          0
2 0                          0
  T_MeanBin_21_23_Ndays_on10 T_MeanBin_25_27_Ndays_on10
1 0                          8
2 0                          8
  T_MeanBin_inf17_Ndays_on10 T_MeanBin_17_21_Ndays_on10
1 0                          0
2 0                          0
  T_MeanBin_27_29_Ndays_on10 T_MeanBin_29_31_Ndays_on10
1 2                          0
2 2                          0
  T_MeanBin_31_33_Ndays_on10 T_MeanBin_sup33_Ndays_on10
1 0                          0
2 0                          0
  T_MinBin_17_19_Ndays_on30 T_MinBin_15_17_Ndays_on30 T_MinBin_19_21_Ndays_on30
1 0                         0                         0
2 0                         0                         0
  T_MinBin_21_23_Ndays_on30 T_MinBin_inf11_Ndays_on30 T_MinBin_11_13_Ndays_on30
1 0                         0                         0
2 0                         0                         0
  T_MinBin_13_15_Ndays_on30 T_MinBin_23_25_Ndays_on30 T_MinBin_sup25_Ndays_on30
1 0                         3                         27
2 0                         3                         27
  T_MinBin_17_19_Ndays_on20 T_MinBin_15_17_Ndays_on20 T_MinBin_19_21_Ndays_on20
1 0                         0                         0
2 0                         0                         0
  T_MinBin_21_23_Ndays_on20 T_MinBin_inf11_Ndays_on20 T_MinBin_11_13_Ndays_on20
1 0                         0                         0
2 0                         0                         0
  T_MinBin_13_15_Ndays_on20 T_MinBin_23_25_Ndays_on20 T_MinBin_sup25_Ndays_on20
1 0                         3                         17
2 0                         3                         17
  T_MinBin_17_19_Ndays_on10 T_MinBin_15_17_Ndays_on10 T_MinBin_19_21_Ndays_on10
1 0                         0                         0
2 0                         0                         0
  T_MinBin_21_23_Ndays_on10 T_MinBin_inf11_Ndays_on10 T_MinBin_11_13_Ndays_on10
1 0                         0                         0
2 0                         0                         0
  T_MinBin_13_15_Ndays_on10 T_MinBin_23_25_Ndays_on10 T_MinBin_sup25_Ndays_on10
1 0                         2                         8
2 0                         2                         8
  T_MaxBin_29_31_Ndays_on30 T_MaxBin_31_33_Ndays_on30 T_MaxBin_27_29_Ndays_on30
1 0                         0                         20
2 0                         0                         20
  T_MaxBin_25_27_Ndays_on30 T_MaxBin_23_25_Ndays_on30 T_MaxBin_inf21_Ndays_on30
1 10                        0                         0
2 10                        0                         0
  T_MaxBin_21_23_Ndays_on30 T_MaxBin_33_35_Ndays_on30 T_MaxBin_sup35_Ndays_on30
1 0                         0                         0
2 0                         0                         0
  T_MaxBin_29_31_Ndays_on20 T_MaxBin_31_33_Ndays_on20 T_MaxBin_27_29_Ndays_on20
1 0                         0                         14
2 0                         0                         14
  T_MaxBin_25_27_Ndays_on20 T_MaxBin_23_25_Ndays_on20 T_MaxBin_inf21_Ndays_on20
1 6                         0                         0
2 6                         0                         0
  T_MaxBin_21_23_Ndays_on20 T_MaxBin_33_35_Ndays_on20 T_MaxBin_sup35_Ndays_on20
1 0                         0                         0
2 0                         0                         0
  T_MaxBin_29_31_Ndays_on10 T_MaxBin_31_33_Ndays_on10 T_MaxBin_27_29_Ndays_on10
1 0                         0                         6
2 0                         0                         6
  T_MaxBin_25_27_Ndays_on10 T_MaxBin_23_25_Ndays_on10 T_MaxBin_inf21_Ndays_on10
1 4                         0                         0
2 4                         0                         0
  T_MaxBin_21_23_Ndays_on10 T_MaxBin_33_35_Ndays_on10 T_MaxBin_sup35_Ndays_on10
1 0                         0                         0
2 0                         0                         0
  WB_i30   WB_i20   WB_i10 WB_i30_bin WB_i20_bin WB_i10_bin
1 26.08194 26.04792 25.95  (26,28]    (26,28]    (24,26]
2 26.08194 26.04792 25.95  (26,28]    (26,28]    (24,26]
  WB_Bin_18_20_Nhours_on30 WB_Bin_20_22_Nhours_on30 WB_Bin_22_24_Nhours_on30
1 0                        0                        0
2 0                        0                        0
  WB_Bin_24_26_Nhours_on30 WB_Bin_16_18_Nhours_on30 WB_Bin_14_16_Nhours_on30
1 564                      0                        0
2 564                      0                        0
  WB_Bin_inf14_Nhours_on30 WB_Bin_26_28_Nhours_on30 WB_Bin_sup28_Nhours_on30
1 0                        156                      0
2 0                        156                      0
  WB_Bin_18_20_Nhours_on20 WB_Bin_20_22_Nhours_on20 WB_Bin_22_24_Nhours_on20
1 0                        0                        0
2 0                        0                        0
  WB_Bin_24_26_Nhours_on20 WB_Bin_16_18_Nhours_on20 WB_Bin_14_16_Nhours_on20
1 390                      0                        0
2 390                      0                        0
  WB_Bin_inf14_Nhours_on20 WB_Bin_26_28_Nhours_on20 WB_Bin_sup28_Nhours_on20
1 0                        90                       0
2 0                        90                       0
  WB_Bin_18_20_Nhours_on10 WB_Bin_20_22_Nhours_on10 WB_Bin_22_24_Nhours_on10
1 0                        0                        0
2 0                        0                        0
  WB_Bin_24_26_Nhours_on10 WB_Bin_16_18_Nhours_on10 WB_Bin_14_16_Nhours_on10
1 211                      0                        0
2 211                      0                        0
  WB_Bin_inf14_Nhours_on10 WB_Bin_26_28_Nhours_on10 WB_Bin_sup28_Nhours_on10
1 0                        29                       0
2 0                        29                       0
  WB_MeanBin_20_22_Ndays_on30 WB_MeanBin_18_20_Ndays_on30
1 0                           0
2 0                           0
  WB_MeanBin_22_24_Ndays_on30 WB_MeanBin_16_18_Ndays_on30
1 0                           0
2 0                           0
  WB_MeanBin_inf14_Ndays_on30 WB_MeanBin_14_16_Ndays_on30
1 0                           0
2 0                           0
  WB_MeanBin_24_26_Ndays_on30 WB_MeanBin_26_28_Ndays_on30
1 14                          16
2 14                          16
  WB_MeanBin_sup28_Ndays_on30 WB_MeanBin_20_22_Ndays_on20
1 0                           0
2 0                           0
  WB_MeanBin_18_20_Ndays_on20 WB_MeanBin_22_24_Ndays_on20
1 0                           0
2 0                           0
  WB_MeanBin_16_18_Ndays_on20 WB_MeanBin_inf14_Ndays_on20
1 0                           0
2 0                           0
  WB_MeanBin_14_16_Ndays_on20 WB_MeanBin_24_26_Ndays_on20
1 0                           11
2 0                           11
  WB_MeanBin_26_28_Ndays_on20 WB_MeanBin_sup28_Ndays_on20
1 9                           0
2 9                           0
  WB_MeanBin_20_22_Ndays_on10 WB_MeanBin_18_20_Ndays_on10
1 0                           0
2 0                           0
  WB_MeanBin_22_24_Ndays_on10 WB_MeanBin_16_18_Ndays_on10
1 0                           0
2 0                           0
  WB_MeanBin_inf14_Ndays_on10 WB_MeanBin_14_16_Ndays_on10
1 0                           0
2 0                           0
  WB_MeanBin_24_26_Ndays_on10 WB_MeanBin_26_28_Ndays_on10
1 7                           3
2 7                           3
  WB_MeanBin_sup28_Ndays_on10 WB_MinBin_18_20_Ndays_on30
1 0                           0
2 0                           0
  WB_MinBin_16_18_Ndays_on30 WB_MinBin_14_16_Ndays_on30
1 0                          0
2 0                          0
  WB_MinBin_12_14_Ndays_on30 WB_MinBin_10_12_Ndays_on30
1 0                          0
2 0                          0
  WB_MinBin_inf10_Ndays_on30 WB_MinBin_20_22_Ndays_on30
1 0                          0
2 0                          0
  WB_MinBin_22_24_Ndays_on30 WB_MinBin_sup24_Ndays_on30
1 0                          30
2 0                          30
  WB_MinBin_18_20_Ndays_on20 WB_MinBin_16_18_Ndays_on20
1 0                          0
2 0                          0
  WB_MinBin_14_16_Ndays_on20 WB_MinBin_12_14_Ndays_on20
1 0                          0
2 0                          0
  WB_MinBin_10_12_Ndays_on20 WB_MinBin_inf10_Ndays_on20
1 0                          0
2 0                          0
  WB_MinBin_20_22_Ndays_on20 WB_MinBin_22_24_Ndays_on20
1 0                          0
2 0                          0
  WB_MinBin_sup24_Ndays_on20 WB_MinBin_18_20_Ndays_on10
1 20                         0
2 20                         0
  WB_MinBin_16_18_Ndays_on10 WB_MinBin_14_16_Ndays_on10
1 0                          0
2 0                          0
  WB_MinBin_12_14_Ndays_on10 WB_MinBin_10_12_Ndays_on10
1 0                          0
2 0                          0
  WB_MinBin_inf10_Ndays_on10 WB_MinBin_20_22_Ndays_on10
1 0                          0
2 0                          0
  WB_MinBin_22_24_Ndays_on10 WB_MinBin_sup24_Ndays_on10
1 0                          10
2 0                          10
  WB_MaxBin_24_26_Ndays_on30 WB_MaxBin_22_24_Ndays_on30
1 11                         0
2 11                         0
  WB_MaxBin_26_28_Ndays_on30 WB_MaxBin_inf18_Ndays_on30
1 19                         0
2 19                         0
  WB_MaxBin_18_20_Ndays_on30 WB_MaxBin_20_22_Ndays_on30
1 0                          0
2 0                          0
  WB_MaxBin_28_30_Ndays_on30 WB_MaxBin_30_32_Ndays_on30
1 0                          0
2 0                          0
  WB_MaxBin_sup32_Ndays_on30 WB_MaxBin_24_26_Ndays_on20
1 0                          8
2 0                          8
  WB_MaxBin_22_24_Ndays_on20 WB_MaxBin_26_28_Ndays_on20
1 0                          12
2 0                          12
  WB_MaxBin_inf18_Ndays_on20 WB_MaxBin_18_20_Ndays_on20
1 0                          0
2 0                          0
  WB_MaxBin_20_22_Ndays_on20 WB_MaxBin_28_30_Ndays_on20
1 0                          0
2 0                          0
  WB_MaxBin_30_32_Ndays_on20 WB_MaxBin_sup32_Ndays_on20
1 0                          0
2 0                          0
  WB_MaxBin_24_26_Ndays_on10 WB_MaxBin_22_24_Ndays_on10
1 5                          0
2 5                          0
  WB_MaxBin_26_28_Ndays_on10 WB_MaxBin_inf18_Ndays_on10
1 5                          0
2 5                          0
  WB_MaxBin_18_20_Ndays_on10 WB_MaxBin_20_22_Ndays_on10
1 0                          0
2 0                          0
  WB_MaxBin_28_30_Ndays_on10 WB_MaxBin_30_32_Ndays_on10
1 0                          0
2 0                          0
  WB_MaxBin_sup32_Ndays_on10 P_tot_30  P_tot_20  P_tot_10 API_sup_1
1 0                          0.2802348 0.1772218 0.117177 0
2 0                          0.2802348 0.1772218 0.117177 0

In [4]:
df_reg_children <- df_children %>%
                mutate(T_i30_bin=factor(gsub("\\(","",T_i30_bin),levels=T_bins_labels))

In [5]:
reg_children_T <- feols(Child_hemo_level_alti ~ i(T_i30_bin,ref=bin_ref_T) + P_tot_30 + 
                                        Child_female + Child_birth_order + Child_alive_age_month +
                                        Mother_prim_educ + Mother_second_educ + Mother_higher_educ +
                                        Mother_muslim + Mother_not_hindu_nor_muslim  + 
                                        Mother_ethni_SC + Mother_ethni_ST + Mother_ethni_OBC +
                                        Wealth_lowest + Wealth_second + Wealth_fourth + Wealth_highest + 
                                        Urban 
                                        |District_ID^Measured_month + District_ID^Measured_year,
                           vcov = ~District_ID,
                           df_reg_children)

NOTES: 16,652 observations removed because of NA values (RHS: 16,652).
       38/7 fixed-effect singletons were removed (38 observations).

In [6]:
main_sample_children <- df_reg_children[obs(reg_children_T), ]

In [7]:
main_sample_children <- data.frame(main_sample_children)
main_sample_children %>% 
    mutate(#Hemoglobin
           Child_anemia =  Children_anemia/1000,
           Child_severe_anemia = Child_severe_anemia/1000,
           Child_moderate_anemia = Child_moderate_anemia/1000,
           Child_mild_anemia = Child_mild_anemia/1000)%>%
    select(#Hemoglobin
           Child_hemo_level_alti,Child_anemia,Child_severe_anemia,Child_moderate_anemia,Child_mild_anemia,
           #Acute malnutrition
           Child_weight_for_height_zscore,
           #Child controls
           Child_female, Child_birth_order, Child_alive_age_month,
           #Diet
           Child_still_breastfeeding,
           Child_given_plain_water,Child_given_juice, Child_given_baby_formula,
           Child_given_fortified_baby_food, Child_given_soup, 
           Child_given_other_liquid, 
           #Animal proteins
           Child_given_milk,Child_given_yogurt,Child_given_cheese_yogurt_milk_products,
           Child_given_eggs,
           Child_given_chicken_duck_birds,Child_given_other_meat,
           Child_given_liver_heart_organs,Child_given_fish_sellfish,
           #Vegetables
           Child_given_bread_noodles_grains,Child_given_potatoes_cassava_tubers,
           Child_given_pumkins_carrots_squash, Child_given_green_vegetables,
           Child_given_mangoes_papaya_vitaminAfruits,Child_given_other_fruits,
           Child_given_beans_peas_lentils_nuts,
           Child_given_other_solid_semisolid_food,
           #Iron
           Child_iron_supplem_7d,
           #Bednet
           Bednet_slept,
           #Mother controls
           Mother_no_educ, Mother_prim_educ, Mother_second_educ, Mother_higher_educ,
           Mother_ethni_SC,Mother_ethni_ST,Mother_ethni_OBC,Mother_ethni_other,
           Mother_hindu, Mother_muslim, Mother_not_hindu_nor_muslim,
           #HH controls
           Wealth_lowest,Wealth_second,Wealth_middle,Wealth_fourth,Wealth_highest,
           HH_air_conditioner,
           Urban,
           #Water
           HH_time_water_source,
           Water_fetching_risk,
           #Malaria
           API_sup_1
          )%>%
    stargazer(nobs=TRUE, digits = 2,
              summary.stat = c("n","mean", "sd","min","p25","median","p75","max"),
              title = c("Summary statistics"),
              covariate.labels = c(#Hemoglobin
                                   "Hemoglobin level (g/L)",
                                   "Anemia (hemo <110)",
                                   "Severe anemia (hemo <70)",
                                   "Moderate anemia (70<hemo<100)",
                                   "Mild anemia (100<hemo<110)",
                                   #Acute malnutrition
                                   "Weight-for-height z-score (WHZ)",
                                    #Child controls
                                   "Female",
                                   "Birth order",
                                   "Age in months",
                                   #Diets
                                   "Still breastfed",
                                   "Diet (past 24h) : Plain water",
                                   "Diet (past 24h) : Juice", 
                                   "Diet (past 24h) : Baby formula",
                                   "Diet (past 24h) : Fortified baby food",
                                   "Diet (past 24h) : Soup",
                                   "Diet (past 24h) : Other liquid",
                                   "Diet (past 24h) : Milk (from animal)",
                                   "Diet (past 24h) : Yogurt",
                                   "Diet (past 24h) : Cheese, milk products",
                                   "Diet (past 24h) : Eggs",
                                   "Diet (past 24h) : Chicken, ducks birds",
                                   "Diet (past 24h) : Other meat",
                                   "Diet (past 24h) : Organs",
                                   "Diet (past 24h) : Fish, sellfish",
                                   "Diet (past 24h) : Bread, noodles, grains",
                                   "Diet (past 24h) : Potatoes, cassava, tubers",
                                   "Diet (past 24h) : Pumkins, carrots, squash",
                                   "Diet (past 24h) : Green vegetables",
                                   "Diet (past 24h) : Vitamin A fruits",
                                   "Diet (past 24h) : Other fruits",
                                   "Diet (past 24h) : Beans, peas, lentils, nuts",
                                   "Diet (past 24h) : Other semisolid food",
                                   #Iron
                                   "Iron supplementation in past 7 days",
                                   #Bednet
                                   "Slept under any bednet",
                                   #Mother controls
                                   "Mother no education",
                                   "Mother primary education",
                                   "Mother secondary education",
                                   "Mother higher education",
                                   "Mother scheduled caste (SC)",
                                   "Mother scheduled tribe (ST)",
                                   "Mother other backward caste (OBC)",
                                   "Mother not SC, ST or OBC",
                                   "Mother hindu",
                                   "Mother muslim",
                                   "Mother not hindu nor muslim",
                                   #HH controls
                                   "Wealth 1st quintile (poorest)",
                                   "Wealth 2nd quintile",
                                   "Wealth 3rd quintile",
                                   "Wealth 4th quintile",
                                   "Wealth 5th quintile (richest)",
                                   "Air conditioner",
                                   "Urban",
                                   #Water
                                   "Time to water source (minutes)",
                                   "Water fetching risk",
                                   #Malaria
                                   "API > 1"
                                   ),
              type="latex"
             )

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: jeu., avril 16, 2026 - 17:53:46
\begin{table}[!htbp] \centering
  \caption{Summary statistics}
  \label{}
\begin{tabular}{@{\extracolsep{5pt}}lcccccccc}
\\[-1.8ex]\hline
\hline \\[-1.8ex]
Statistic & \multicolumn{1}{c}{N} & \multicolumn{1}{c}{Mean} & \multicolumn{1}{c}{St. Dev.} & \multicolumn{1}{c}{Min} & \multicolumn{1}{c}{Pctl(25)} & \multicolumn{1}{c}{Median} & \multicolumn{1}{c}{Pctl(75)} & \multicolumn{1}{c}{Max} \\
\hline \\[-1.8ex]
Hemoglobin level (g/L) & 265,122 & 105.03 & 15.39 & 10 & 96 & 106 & 115 & 239 \\
Anemia (hemo <110) & 265,122 & 0.60 & 0.49 & 0 & 0 & 1 & 1 & 1 \\
Severe anemia (hemo <70) & 265,122 & 0.02 & 0.13 & 0 & 0 & 0 & 0 & 1 \\
Moderate anemia (70<hemo<100) & 265,122 & 0.31 & 0.46 & 0 & 0 & 0 & 1 & 1 \\
Mild anemia (100<hemo<110) & 265,122 & 0.28 & 0.45 & 0 & 0 & 0 & 1 & 1 \\
Weight-for-height z-score (WHZ) & 254,089 & $-$0.94 & 1.39 & $-$5.00 & $-$1.77 & $-$0.92 & $-$0.11 & 5.00 \\
Female & 265,122 & 0.48 & 0.50 & 0 & 0 & 0 & 1 & 1 \\
Birth order & 265,122 & 2.27 & 1.47 & 1 & 1 & 2 & 3 & 17 \\
Age in months & 265,122 & 32.81 & 15.50 & 5 & 19 & 33 & 46 & 59 \\
Still breastfed & 200,329 & 0.55 & 0.50 & 0 & 0 & 1 & 1 & 1 \\
Diet (past 24h) : Plain water & 137,100 & 0.83 & 0.38 & 0 & 1 & 1 & 1 & 1 \\
Diet (past 24h) : Juice & 137,097 & 0.19 & 0.40 & 0 & 0 & 0 & 0 & 1 \\
Diet (past 24h) : Baby formula & 137,041 & 0.10 & 0.30 & 0 & 0 & 0 & 0 & 1 \\
Diet (past 24h) : Fortified baby food & 137,092 & 0.13 & 0.34 & 0 & 0 & 0 & 0 & 1 \\
Diet (past 24h) : Soup & 137,077 & 0.17 & 0.38 & 0 & 0 & 0 & 0 & 1 \\
Diet (past 24h) : Other liquid & 137,063 & 0.21 & 0.40 & 0 & 0 & 0 & 0 & 1 \\
Diet (past 24h) : Milk (from animal) & 137,101 & 0.37 & 0.48 & 0 & 0 & 0 & 1 & 1 \\
Diet (past 24h) : Yogurt & 137,091 & 0.09 & 0.28 & 0 & 0 & 0 & 0 & 1 \\
Diet (past 24h) : Cheese, milk products & 137,109 & 0.10 & 0.30 & 0 & 0 & 0 & 0 & 1 \\
Diet (past 24h) : Eggs & 137,125 & 0.15 & 0.36 & 0 & 0 & 0 & 0 & 1 \\
Diet (past 24h) : Chicken, ducks birds & 137,124 & 0.07 & 0.26 & 0 & 0 & 0 & 0 & 1 \\
Diet (past 24h) : Other meat & 137,116 & 0.06 & 0.23 & 0 & 0 & 0 & 0 & 1 \\
Diet (past 24h) : Organs & 137,114 & 0.07 & 0.25 & 0 & 0 & 0 & 0 & 1 \\
Diet (past 24h) : Fish, sellfish & 137,123 & 0.06 & 0.24 & 0 & 0 & 0 & 0 & 1 \\
Diet (past 24h) : Bread, noodles, grains & 137,129 & 0.59 & 0.49 & 0 & 0 & 1 & 1 & 1 \\
Diet (past 24h) : Potatoes, cassava, tubers & 137,096 & 0.22 & 0.42 & 0 & 0 & 0 & 0 & 1 \\
Diet (past 24h) : Pumkins, carrots, squash & 137,117 & 0.20 & 0.40 & 0 & 0 & 0 & 0 & 1 \\
Diet (past 24h) : Green vegetables & 137,113 & 0.29 & 0.45 & 0 & 0 & 0 & 1 & 1 \\
Diet (past 24h) : Vitamin A fruits & 137,115 & 0.18 & 0.38 & 0 & 0 & 0 & 0 & 1 \\
Diet (past 24h) : Other fruits & 137,119 & 0.24 & 0.43 & 0 & 0 & 0 & 0 & 1 \\
Diet (past 24h) : Beans, peas, lentils, nuts & 137,112 & 0.15 & 0.35 & 0 & 0 & 0 & 0 & 1 \\
Diet (past 24h) : Other semisolid food & 137,044 & 0.22 & 0.41 & 0 & 0 & 0 & 0 & 1 \\
Iron supplementation in past 7 days & 229,499 & 0.26 & 0.44 & 0 & 0 & 0 & 1 & 1 \\
Slept under any bednet & 265,122 & 0.33 & 0.47 & 0 & 0 & 0 & 1 & 1 \\
Mother no education & 265,122 & 0.29 & 0.45 & 0 & 0 & 0 & 1 & 1 \\
Mother primary education & 265,122 & 0.14 & 0.35 & 0 & 0 & 0 & 0 & 1 \\
Mother secondary education & 265,122 & 0.47 & 0.50 & 0 & 0 & 0 & 1 & 1 \\
Mother higher education & 265,122 & 0.10 & 0.30 & 0 & 0 & 0 & 0 & 1 \\
Mother scheduled caste (SC) & 265,122 & 0.20 & 0.40 & 0 & 0 & 0 & 0 & 1 \\
Mother scheduled tribe (ST) & 265,122 & 0.23 & 0.42 & 0 & 0 & 0 & 0 & 1 \\
Mother other backward caste (OBC) & 265,122 & 0.40 & 0.49 & 0 & 0 & 0 & 1 & 1 \\
Mother not SC, ST or OBC & 265,122 & 0.18 & 0.38 & 0 & 0 & 0 & 0 & 1 \\
Mother hindu & 265,122 & 0.72 & 0.45 & 0 & 0 & 1 & 1 & 1 \\
Mother muslim & 265,122 & 0.13 & 0.34 & 0 & 0 & 0 & 0 & 1 \\
Mother not hindu nor muslim & 265,122 & 0.14 & 0.35 & 0 & 0 & 0 & 0 & 1 \\
Wealth 1st quintile (poorest) & 265,122 & 0.27 & 0.44 & 0 & 0 & 0 & 1 & 1 \\
Wealth 2nd quintile & 265,122 & 0.24 & 0.43 & 0 & 0 & 0 & 0 & 1 \\
Wealth 3rd quintile & 265,122 & 0.20 & 0.40 & 0 & 0 & 0 & 0 & 1 \\
Wealth 4th quintile & 265,122 & 0.17 & 0.37 & 0 & 0 & 0 & 0 & 1 \\
Wealth 5th quintile (richest) & 265,122 & 0.12 & 0.33 & 0 & 0 & 0 & 0 & 1 \\
Air conditioner & 265,122 & 0.16 & 0.37 & 0 & 0 & 0 & 0 & 1 \\
Urban & 265,122 & 0.23 & 0.42 & 0 & 0 & 0 & 0 & 1 \\
Time to water source (minutes) & 264,785 & 5.97 & 14.13 & 0 & 0 & 0 & 10 & 900 \\
Water fetching risk & 264,785 & 0.34 & 0.47 & 0 & 0 & 0 & 1 & 1 \\
API > 1 & 262,510 & 0.08 & 0.28 & 0 & 0 & 0 & 0 & 1 \\
\hline \\[-1.8ex]
\end{tabular}
\end{table}

# Men

In [8]:
df_men <- fread("./2_Regression_datasets/output/df_reg_men.csv")
sprintf("%i rows x %i columns", nrow(df_men), ncol(df_men))
head(df_men,2)

[1] "150101 rows x 330 columns"

  DHS_round DHSCLUST State_2011               District_2011 cell_x_01 cell_y_01
1 2015      10001    Andaman & Nicobar Island South Andaman 92.7      11.7
2 2015      10001    Andaman & Nicobar Island South Andaman 92.7      11.7
  cell_x_025 cell_y_025 HH_ID Men_id         Resp_nb Interview_month
1 92.75      11.75      17    01000117     1 1       7
2 92.75      11.75      20    01000120     2 2       7
  Interview_year Interview_day Measured_date_CDC Measured_date Current_age
1 2015           21            42204             2015-07-21    28
2 2015           19            42202             2015-07-19    16
  Age_group Religion_hindu Religion_muslim Religion_not_hindu_nor_muslim
1 25-29     1              0               0
2 15-19     1              0               0
  Ethni_SC Ethni_ST Ethni_OBC Ethni_other N_year_educ Smoker Health_insurance
1 0        0        0         1           10          1      0
2 0        0        0         1           10          0      0
  Profession Blood_pressure_systo Blood_pressure_diasto Blood_glucose_level
1 manual     137                  99                    185
2 no_work    117                  69                    109
  Diet_milk_curd_daily Diet_milk_curd_week Diet_milk_curd_oc
1 0                    1                   0
2 0                    1                   0
  Diet_milk_curd_never Diet_pulses_beans_daily Diet_pulses_beans_week
1 0                    0                       1
2 0                    0                       1
  Diet_pulses_beans_oc Diet_pulses_beans_never Diet_green_veg_daily
1 0                    0                       0
2 0                    0                       0
  Diet_green_veg_week Diet_green_veg_oc Diet_green_veg_never Diet_fruits_daily
1 1                   0                 0                    0
2 1                   0                 0                    0
  Diet_fruits_week Diet_fruits_oc Diet_fruits_never Diet_eggs_daily
1 1                0              0                 0
2 1                0              0                 0
  Diet_eggs_week Diet_eggs_oc Diet_eggs_never Diet_fish_daily Diet_fish_week
1 1              0            0               0               1
2 1              0            0               0               1
  Diet_fish_oc Diet_fish_never Diet_chicken_meat_daily Diet_chicken_meat_week
1 0            0               0                       1
2 0            0               0                       1
  Diet_chicken_meat_oc Diet_chicken_meat_never Diet_fried_food_daily
1 0                    0                       0
2 0                    0                       0
  Diet_fried_food_week Diet_fried_food_oc Diet_fried_food_never
1 1                    0                  0
2 1                    0                  0
  Diet_aerated_drinks_daily Diet_aerated_drinks_week Diet_aerated_drinks_oc
1 0                         0                        1
2 0                         0                        1
  Diet_aerated_drinks_never Wealth_lowest Wealth_second Wealth_middle
1 0                         0             0             1
2 0                         0             0             0
  Wealth_fourth Wealth_highest Urban Usual_resident Blood_hemo_level_alti
1 0             0              1     1              162
2 1             0              1     1              150
  Body_mass_index Bednet_slept HH_time_water_source HH_air_conditioner
1 24.16           1            0                    0
2 21.48           1            0                    0
  HH_treat_water HH_no_toilet HH_well_water cell_x.x cell_y.x cell_x.y cell_y.y
1 0              0            0             92.7     11.7     92.75    11.75
2 1              0            0             92.7     11.7     92.75    11.75
  Measured_month Measured_year Men_anemia Men_severe_anemia Men_moderate_anemia
1 7              2015          0          0                 0
2 7              2015          0          0                 0
  Men_mild_anemia Men_no_anemia BMI_category Blood_hypertension
1 0               1000          Normal       1000
2 0               1000          Normal          0
  Water_fetching_risk District_ID                            T_i30    T_i20
1 0                   Andaman & Nicobar Island_South Andaman 26.98750 27.00625
2 0                   Andaman & Nicobar Island_South Andaman 26.97361 26.94375
  T_i10  T_i30_bin T_i20_bin T_i10_bin T_Bin_17_21_Nhours_on30
1 26.700 (25,27]   (27,29]   (25,27]   0
2 26.875 (25,27]   (25,27]   (25,27]   0
  T_Bin_21_23_Nhours_on30 T_Bin_23_25_Nhours_on30 T_Bin_25_27_Nhours_on30
1 0                       6                       525
2 0                       4                       535
  T_Bin_27_29_Nhours_on30 T_Bin_29_31_Nhours_on30 T_Bin_inf17_Nhours_on30
1 189                     0                       0
2 181                     0                       0
  T_Bin_31_33_Nhours_on30 T_Bin_sup33_Nhours_on30 T_Bin_17_21_Nhours_on20
1 0                       0                       0
2 0                       0                       0
  T_Bin_21_23_Nhours_on20 T_Bin_23_25_Nhours_on20 T_Bin_25_27_Nhours_on20
1 0                       5                       346
2 0                       4                       360
  T_Bin_27_29_Nhours_on20 T_Bin_29_31_Nhours_on20 T_Bin_inf17_Nhours_on20
1 129                     0                       0
2 116                     0                       0
  T_Bin_31_33_Nhours_on20 T_Bin_sup33_Nhours_on20 T_Bin_17_21_Nhours_on10
1 0                       0                       0
2 0                       0                       0
  T_Bin_21_23_Nhours_on10 T_Bin_23_25_Nhours_on10 T_Bin_25_27_Nhours_on10
1 0                       5                       211
2 0                       3                       194
  T_Bin_27_29_Nhours_on10 T_Bin_29_31_Nhours_on10 T_Bin_inf17_Nhours_on10
1 24                      0                       0
2 43                      0                       0
  T_Bin_31_33_Nhours_on10 T_Bin_sup33_Nhours_on10 T_MeanBin_23_25_Ndays_on30
1 0                       0                       0
2 0                       0                       0
  T_MeanBin_21_23_Ndays_on30 T_MeanBin_25_27_Ndays_on30
1 0                          16
2 0                          16
  T_MeanBin_inf17_Ndays_on30 T_MeanBin_17_21_Ndays_on30
1 0                          0
2 0                          0
  T_MeanBin_27_29_Ndays_on30 T_MeanBin_29_31_Ndays_on30
1 14                         0
2 14                         0
  T_MeanBin_31_33_Ndays_on30 T_MeanBin_sup33_Ndays_on30
1 0                          0
2 0                          0
  T_MeanBin_23_25_Ndays_on20 T_MeanBin_21_23_Ndays_on20
1 0                          0
2 0                          0
  T_MeanBin_25_27_Ndays_on20 T_MeanBin_inf17_Ndays_on20
1 12                         0
2 12                         0
  T_MeanBin_17_21_Ndays_on20 T_MeanBin_27_29_Ndays_on20
1 0                          8
2 0                          8
  T_MeanBin_29_31_Ndays_on20 T_MeanBin_31_33_Ndays_on20
1 0                          0
2 0                          0
  T_MeanBin_sup33_Ndays_on20 T_MeanBin_23_25_Ndays_on10
1 0                          0
2 0                          0
  T_MeanBin_21_23_Ndays_on10 T_MeanBin_25_27_Ndays_on10
1 0                          9
2 0                          7
  T_MeanBin_inf17_Ndays_on10 T_MeanBin_17_21_Ndays_on10
1 0                          0
2 0                          0
  T_MeanBin_27_29_Ndays_on10 T_MeanBin_29_31_Ndays_on10
1 1                          0
2 3                          0
  T_MeanBin_31_33_Ndays_on10 T_MeanBin_sup33_Ndays_on10
1 0                          0
2 0                          0
  T_MinBin_17_19_Ndays_on30 T_MinBin_15_17_Ndays_on30 T_MinBin_19_21_Ndays_on30
1 0                         0                         0
2 0                         0                         0
  T_MinBin_21_23_Ndays_on30 T_MinBin_inf11_Ndays_on30 T_MinBin_11_13_Ndays_on30
1 0                         0                         0
2 0                         0                         0
  T_MinBin_13_15_Ndays_on30 T_MinBin_23_25_Ndays_on30 T_MinBin_sup25_Ndays_on30
1 0                         4                         26
2 0                         3                         27
  T_MinBin_17_19_Ndays_on20 T_MinBin_15_17_Ndays_on20 T_MinBin_19_21_Ndays_on20
1 0                         0                         0
2 0                         0                         0
  T_MinBin_21_23_Ndays_on20 T_MinBin_inf11_Ndays_on20 T_MinBin_11_13_Ndays_on20
1 0                         0                         0
2 0                         0                         0
  T_MinBin_13_15_Ndays_on20 T_MinBin_23_25_Ndays_on20 T_MinBin_sup25_Ndays_on20
1 0                         3                         17
2 0                         3                         17
  T_MinBin_17_19_Ndays_on10 T_MinBin_15_17_Ndays_on10 T_MinBin_19_21_Ndays_on10
1 0                         0                         0
2 0                         0                         0
  T_MinBin_21_23_Ndays_on10 T_MinBin_inf11_Ndays_on10 T_MinBin_11_13_Ndays_on10
1 0                         0                         0
2 0                         0                         0
  T_MinBin_13_15_Ndays_on10 T_MinBin_23_25_Ndays_on10 T_MinBin_sup25_Ndays_on10
1 0                         3                         7
2 0                         2                         8
  T_MaxBin_29_31_Ndays_on30 T_MaxBin_31_33_Ndays_on30 T_MaxBin_27_29_Ndays_on30
1 0                         0                         21
2 0                         0                         20
  T_MaxBin_25_27_Ndays_on30 T_MaxBin_23_25_Ndays_on30 T_MaxBin_inf21_Ndays_on30
1  9                        0                         0
2 10                        0                         0
  T_MaxBin_21_23_Ndays_on30 T_MaxBin_33_35_Ndays_on30 T_MaxBin_sup35_Ndays_on30
1 0                         0                         0
2 0                         0                         0
  T_MaxBin_29_31_Ndays_on20 T_MaxBin_31_33_Ndays_on20 T_MaxBin_27_29_Ndays_on20
1 0                         0                         15
2 0                         0                         13
  T_MaxBin_25_27_Ndays_on20 T_MaxBin_23_25_Ndays_on20 T_MaxBin_inf21_Ndays_on20
1 5                         0                         0
2 7                         0                         0
  T_MaxBin_21_23_Ndays_on20 T_MaxBin_33_35_Ndays_on20 T_MaxBin_sup35_Ndays_on20
1 0                         0                         0
2 0                         0                         0
  T_MaxBin_29_31_Ndays_on10 T_MaxBin_31_33_Ndays_on10 T_MaxBin_27_29_Ndays_on10
1 0                         0                         6
2 0                         0                         6
  T_MaxBin_25_27_Ndays_on10 T_MaxBin_23_25_Ndays_on10 T_MaxBin_inf21_Ndays_on10
1 4                         0                         0
2 4                         0                         0
  T_MaxBin_21_23_Ndays_on10 T_MaxBin_33_35_Ndays_on10 T_MaxBin_sup35_Ndays_on10
1 0                         0                         0
2 0                         0                         0
  WB_i30   WB_i20   WB_i10   WB_i30_bin WB_i20_bin WB_i10_bin
1 26.08611 26.08333 25.90833 (26,28]    (26,28]    (24,26]
2 26.08472 26.01042 25.99167 (26,28]    (26,28]    (24,26]
  WB_Bin_18_20_Nhours_on30 WB_Bin_20_22_Nhours_on30 WB_Bin_22_24_Nhours_on30
1 0                        0                        0
2 0                        0                        0
  WB_Bin_24_26_Nhours_on30 WB_Bin_16_18_Nhours_on30 WB_Bin_14_16_Nhours_on30
1 559                      0                        0
2 566                      0                        0
  WB_Bin_inf14_Nhours_on30 WB_Bin_26_28_Nhours_on30 WB_Bin_sup28_Nhours_on30
1 0                        161                      0
2 0                        154                      0
  WB_Bin_18_20_Nhours_on20 WB_Bin_20_22_Nhours_on20 WB_Bin_22_24_Nhours_on20
1 0                        0                        0
2 0                        0                        0
  WB_Bin_24_26_Nhours_on20 WB_Bin_16_18_Nhours_on20 WB_Bin_14_16_Nhours_on20
1 385                      0                        0
2 396                      0                        0
  WB_Bin_inf14_Nhours_on20 WB_Bin_26_28_Nhours_on20 WB_Bin_sup28_Nhours_on20
1 0                        95                       0
2 0                        84                       0
  WB_Bin_18_20_Nhours_on10 WB_Bin_20_22_Nhours_on10 WB_Bin_22_24_Nhours_on10
1 0                        0                        0
2 0                        0                        0
  WB_Bin_24_26_Nhours_on10 WB_Bin_16_18_Nhours_on10 WB_Bin_14_16_Nhours_on10
1 217                      0                        0
2 205                      0                        0
  WB_Bin_inf14_Nhours_on10 WB_Bin_26_28_Nhours_on10 WB_Bin_sup28_Nhours_on10
1 0                        23                       0
2 0                        35                       0
  WB_MeanBin_20_22_Ndays_on30 WB_MeanBin_18_20_Ndays_on30
1 0                           0
2 0                           0
  WB_MeanBin_22_24_Ndays_on30 WB_MeanBin_16_18_Ndays_on30
1 0                           0
2 0                           0
  WB_MeanBin_inf14_Ndays_on30 WB_MeanBin_14_16_Ndays_on30
1 0                           0
2 0                           0
  WB_MeanBin_24_26_Ndays_on30 WB_MeanBin_26_28_Ndays_on30
1 13                          17
2 14                          16
  WB_MeanBin_sup28_Ndays_on30 WB_MeanBin_20_22_Ndays_on20
1 0                           0
2 0                           0
  WB_MeanBin_18_20_Ndays_on20 WB_MeanBin_22_24_Ndays_on20
1 0                           0
2 0                           0
  WB_MeanBin_16_18_Ndays_on20 WB_MeanBin_inf14_Ndays_on20
1 0                           0
2 0                           0
  WB_MeanBin_14_16_Ndays_on20 WB_MeanBin_24_26_Ndays_on20
1 0                           10
2 0                           12
  WB_MeanBin_26_28_Ndays_on20 WB_MeanBin_sup28_Ndays_on20
1 10                          0
2  8                          0
  WB_MeanBin_20_22_Ndays_on10 WB_MeanBin_18_20_Ndays_on10
1 0                           0
2 0                           0
  WB_MeanBin_22_24_Ndays_on10 WB_MeanBin_16_18_Ndays_on10
1 0                           0
2 0                           0
  WB_MeanBin_inf14_Ndays_on10 WB_MeanBin_14_16_Ndays_on10
1 0                           0
2 0                           0
  WB_MeanBin_24_26_Ndays_on10 WB_MeanBin_26_28_Ndays_on10
1 7                           3
2 7                           3
  WB_MeanBin_sup28_Ndays_on10 WB_MinBin_18_20_Ndays_on30
1 0                           0
2 0                           0
  WB_MinBin_16_18_Ndays_on30 WB_MinBin_14_16_Ndays_on30
1 0                          0
2 0                          0
  WB_MinBin_12_14_Ndays_on30 WB_MinBin_10_12_Ndays_on30
1 0                          0
2 0                          0
  WB_MinBin_inf10_Ndays_on30 WB_MinBin_20_22_Ndays_on30
1 0                          0
2 0                          0
  WB_MinBin_22_24_Ndays_on30 WB_MinBin_sup24_Ndays_on30
1 0                          30
2 0                          30
  WB_MinBin_18_20_Ndays_on20 WB_MinBin_16_18_Ndays_on20
1 0                          0
2 0                          0
  WB_MinBin_14_16_Ndays_on20 WB_MinBin_12_14_Ndays_on20
1 0                          0
2 0                          0
  WB_MinBin_10_12_Ndays_on20 WB_MinBin_inf10_Ndays_on20
1 0                          0
2 0                          0
  WB_MinBin_20_22_Ndays_on20 WB_MinBin_22_24_Ndays_on20
1 0                          0
2 0                          0
  WB_MinBin_sup24_Ndays_on20 WB_MinBin_18_20_Ndays_on10
1 20                         0
2 20                         0
  WB_MinBin_16_18_Ndays_on10 WB_MinBin_14_16_Ndays_on10
1 0                          0
2 0                          0
  WB_MinBin_12_14_Ndays_on10 WB_MinBin_10_12_Ndays_on10
1 0                          0
2 0                          0
  WB_MinBin_inf10_Ndays_on10 WB_MinBin_20_22_Ndays_on10
1 0                          0
2 0                          0
  WB_MinBin_22_24_Ndays_on10 WB_MinBin_sup24_Ndays_on10
1 0                          10
2 0                          10
  WB_MaxBin_24_26_Ndays_on30 WB_MaxBin_22_24_Ndays_on30
1 10                         0
2 11                         0
  WB_MaxBin_26_28_Ndays_on30 WB_MaxBin_inf18_Ndays_on30
1 20                         0
2 19                         0
  WB_MaxBin_18_20_Ndays_on30 WB_MaxBin_20_22_Ndays_on30
1 0                          0
2 0                          0
  WB_MaxBin_28_30_Ndays_on30 WB_MaxBin_30_32_Ndays_on30
1 0                          0
2 0                          0
  WB_MaxBin_sup32_Ndays_on30 WB_MaxBin_24_26_Ndays_on20
1 0                          7
2 0                          9
  WB_MaxBin_22_24_Ndays_on20 WB_MaxBin_26_28_Ndays_on20
1 0                          13
2 0                          11
  WB_MaxBin_inf18_Ndays_on20 WB_MaxBin_18_20_Ndays_on20
1 0                          0
2 0                          0
  WB_MaxBin_20_22_Ndays_on20 WB_MaxBin_28_30_Ndays_on20
1 0                          0
2 0                          0
  WB_MaxBin_30_32_Ndays_on20 WB_MaxBin_sup32_Ndays_on20
1 0                          0
2 0                          0
  WB_MaxBin_24_26_Ndays_on10 WB_MaxBin_22_24_Ndays_on10
1 5                          0
2 5                          0
  WB_MaxBin_26_28_Ndays_on10 WB_MaxBin_inf18_Ndays_on10
1 5                          0
2 5                          0
  WB_MaxBin_18_20_Ndays_on10 WB_MaxBin_20_22_Ndays_on10
1 0                          0
2 0                          0
  WB_MaxBin_28_30_Ndays_on10 WB_MaxBin_30_32_Ndays_on10
1 0                          0
2 0                          0
  WB_MaxBin_sup32_Ndays_on10 P_tot_30  P_tot_20  P_tot_10   API_sup_1
1 0                          0.2839093 0.1787939 0.11706638 0
2 0                          0.2566433 0.1496382 0.09978867 0

In [9]:
df_men%>%count(Profession)

  Profession      n
1 agri            46375
2 clerical         2647
3 manual          36213
4 no_work         31144
5 prof_tech_manag  8327
6 sales           12753
7 services        10028
8 NA               2614

In [10]:
df_reg_men <- df_men %>%
                mutate(T_i30_bin=factor(gsub("\\(","",T_i30_bin),levels=T_bins_labels))

In [11]:
reg_men_T <- feols(Blood_hemo_level_alti ~ i(T_i30_bin,ref=bin_ref_T) + P_tot_30 +
                                        Current_age + N_year_educ + Smoker + Health_insurance + 
                                        Religion_muslim + Religion_not_hindu_nor_muslim + 
                                        Ethni_SC + Ethni_ST + Ethni_OBC +
                                        Wealth_lowest + Wealth_second + Wealth_fourth + Wealth_highest + 
                                        Urban 
                                        |District_ID^Measured_month + District_ID^Measured_year,
                           vcov = ~District_ID,
                    df_reg_men)

NOTES: 9,536 observations removed because of NA values (RHS: 9,536).
       13/1 fixed-effect singletons were removed (13 observations).

In [12]:
main_sample_men <- df_reg_men[obs(reg_men_T), ]

In [13]:
df_men_dum <- data.frame(main_sample_men)%>%
                  mutate(Underweight = case_when(BMI_category=="Underweight" ~1,
                                                 is.na(BMI_category) ~ NA,
                                                 TRUE ~ 0),
                         Normal = case_when(BMI_category=="Normal" ~1,
                                                 is.na(BMI_category) ~ NA,
                                                 TRUE ~ 0),
                         Overweight = case_when(BMI_category=="Overweight" ~1,
                                                 is.na(BMI_category) ~ NA,
                                                 TRUE ~ 0),
                         Obese = case_when(BMI_category=="Obese" ~1,
                                                 is.na(BMI_category) ~ NA,
                                                 TRUE ~ 0),
                         Agriculture = case_when(Profession=="agri" ~1,
                                                 is.na(BMI_category) ~ NA,
                                                 TRUE ~ 0),
                         Clerical = case_when(Profession=="clerical" ~1,
                                                 is.na(BMI_category) ~ NA,
                                                 TRUE ~ 0),
                         Manual = case_when(Profession=="manual" ~1,
                                                 is.na(BMI_category) ~ NA,
                                                 TRUE ~ 0),
                         No_work = case_when(Profession=="no_work" ~1,
                                                 is.na(BMI_category) ~ NA,
                                                 TRUE ~ 0),
                         TAM = case_when(Profession=="prof_tech_manag" ~1,
                                                 is.na(BMI_category) ~ NA,
                                                 TRUE ~ 0),
                         Sales = case_when(Profession=="sales" ~1,
                                                 is.na(BMI_category) ~ NA,
                                                 TRUE ~ 0),
                         Services = case_when(Profession=="services" ~1,
                                                 is.na(BMI_category) ~ NA,
                                                 TRUE ~ 0))
head(df_men_dum,2)

  DHS_round DHSCLUST State_2011               District_2011 cell_x_01 cell_y_01
1 2015      10001    Andaman & Nicobar Island South Andaman 92.7      11.7
2 2015      10001    Andaman & Nicobar Island South Andaman 92.7      11.7
  cell_x_025 cell_y_025 HH_ID Men_id         Resp_nb Interview_month
1 92.75      11.75      17    01000117     1 1       7
2 92.75      11.75      20    01000120     2 2       7
  Interview_year Interview_day Measured_date_CDC Measured_date Current_age
1 2015           21            42204             2015-07-21    28
2 2015           19            42202             2015-07-19    16
  Age_group Religion_hindu Religion_muslim Religion_not_hindu_nor_muslim
1 25-29     1              0               0
2 15-19     1              0               0
  Ethni_SC Ethni_ST Ethni_OBC Ethni_other N_year_educ Smoker Health_insurance
1 0        0        0         1           10          1      0
2 0        0        0         1           10          0      0
  Profession Blood_pressure_systo Blood_pressure_diasto Blood_glucose_level
1 manual     137                  99                    185
2 no_work    117                  69                    109
  Diet_milk_curd_daily Diet_milk_curd_week Diet_milk_curd_oc
1 0                    1                   0
2 0                    1                   0
  Diet_milk_curd_never Diet_pulses_beans_daily Diet_pulses_beans_week
1 0                    0                       1
2 0                    0                       1
  Diet_pulses_beans_oc Diet_pulses_beans_never Diet_green_veg_daily
1 0                    0                       0
2 0                    0                       0
  Diet_green_veg_week Diet_green_veg_oc Diet_green_veg_never Diet_fruits_daily
1 1                   0                 0                    0
2 1                   0                 0                    0
  Diet_fruits_week Diet_fruits_oc Diet_fruits_never Diet_eggs_daily
1 1                0              0                 0
2 1                0              0                 0
  Diet_eggs_week Diet_eggs_oc Diet_eggs_never Diet_fish_daily Diet_fish_week
1 1              0            0               0               1
2 1              0            0               0               1
  Diet_fish_oc Diet_fish_never Diet_chicken_meat_daily Diet_chicken_meat_week
1 0            0               0                       1
2 0            0               0                       1
  Diet_chicken_meat_oc Diet_chicken_meat_never Diet_fried_food_daily
1 0                    0                       0
2 0                    0                       0
  Diet_fried_food_week Diet_fried_food_oc Diet_fried_food_never
1 1                    0                  0
2 1                    0                  0
  Diet_aerated_drinks_daily Diet_aerated_drinks_week Diet_aerated_drinks_oc
1 0                         0                        1
2 0                         0                        1
  Diet_aerated_drinks_never Wealth_lowest Wealth_second Wealth_middle
1 0                         0             0             1
2 0                         0             0             0
  Wealth_fourth Wealth_highest Urban Usual_resident Blood_hemo_level_alti
1 0             0              1     1              162
2 1             0              1     1              150
  Body_mass_index Bednet_slept HH_time_water_source HH_air_conditioner
1 24.16           1            0                    0
2 21.48           1            0                    0
  HH_treat_water HH_no_toilet HH_well_water cell_x.x cell_y.x cell_x.y cell_y.y
1 0              0            0             92.7     11.7     92.75    11.75
2 1              0            0             92.7     11.7     92.75    11.75
  Measured_month Measured_year Men_anemia Men_severe_anemia Men_moderate_anemia
1 7              2015          0          0                 0
2 7              2015          0          0                 0
  Men_mild_anemia Men_no_anemia BMI_category Blood_hypertension
1 0               1000          Normal       1000
2 0               1000          Normal          0
  Water_fetching_risk District_ID                            T_i30    T_i20
1 0                   Andaman & Nicobar Island_South Andaman 26.98750 27.00625
2 0                   Andaman & Nicobar Island_South Andaman 26.97361 26.94375
  T_i10  T_i30_bin T_i20_bin T_i10_bin T_Bin_17_21_Nhours_on30
1 26.700 25,27]    (27,29]   (25,27]   0
2 26.875 25,27]    (25,27]   (25,27]   0
  T_Bin_21_23_Nhours_on30 T_Bin_23_25_Nhours_on30 T_Bin_25_27_Nhours_on30
1 0                       6                       525
2 0                       4                       535
  T_Bin_27_29_Nhours_on30 T_Bin_29_31_Nhours_on30 T_Bin_inf17_Nhours_on30
1 189                     0                       0
2 181                     0                       0
  T_Bin_31_33_Nhours_on30 T_Bin_sup33_Nhours_on30 T_Bin_17_21_Nhours_on20
1 0                       0                       0
2 0                       0                       0
  T_Bin_21_23_Nhours_on20 T_Bin_23_25_Nhours_on20 T_Bin_25_27_Nhours_on20
1 0                       5                       346
2 0                       4                       360
  T_Bin_27_29_Nhours_on20 T_Bin_29_31_Nhours_on20 T_Bin_inf17_Nhours_on20
1 129                     0                       0
2 116                     0                       0
  T_Bin_31_33_Nhours_on20 T_Bin_sup33_Nhours_on20 T_Bin_17_21_Nhours_on10
1 0                       0                       0
2 0                       0                       0
  T_Bin_21_23_Nhours_on10 T_Bin_23_25_Nhours_on10 T_Bin_25_27_Nhours_on10
1 0                       5                       211
2 0                       3                       194
  T_Bin_27_29_Nhours_on10 T_Bin_29_31_Nhours_on10 T_Bin_inf17_Nhours_on10
1 24                      0                       0
2 43                      0                       0
  T_Bin_31_33_Nhours_on10 T_Bin_sup33_Nhours_on10 T_MeanBin_23_25_Ndays_on30
1 0                       0                       0
2 0                       0                       0
  T_MeanBin_21_23_Ndays_on30 T_MeanBin_25_27_Ndays_on30
1 0                          16
2 0                          16
  T_MeanBin_inf17_Ndays_on30 T_MeanBin_17_21_Ndays_on30
1 0                          0
2 0                          0
  T_MeanBin_27_29_Ndays_on30 T_MeanBin_29_31_Ndays_on30
1 14                         0
2 14                         0
  T_MeanBin_31_33_Ndays_on30 T_MeanBin_sup33_Ndays_on30
1 0                          0
2 0                          0
  T_MeanBin_23_25_Ndays_on20 T_MeanBin_21_23_Ndays_on20
1 0                          0
2 0                          0
  T_MeanBin_25_27_Ndays_on20 T_MeanBin_inf17_Ndays_on20
1 12                         0
2 12                         0
  T_MeanBin_17_21_Ndays_on20 T_MeanBin_27_29_Ndays_on20
1 0                          8
2 0                          8
  T_MeanBin_29_31_Ndays_on20 T_MeanBin_31_33_Ndays_on20
1 0                          0
2 0                          0
  T_MeanBin_sup33_Ndays_on20 T_MeanBin_23_25_Ndays_on10
1 0                          0
2 0                          0
  T_MeanBin_21_23_Ndays_on10 T_MeanBin_25_27_Ndays_on10
1 0                          9
2 0                          7
  T_MeanBin_inf17_Ndays_on10 T_MeanBin_17_21_Ndays_on10
1 0                          0
2 0                          0
  T_MeanBin_27_29_Ndays_on10 T_MeanBin_29_31_Ndays_on10
1 1                          0
2 3                          0
  T_MeanBin_31_33_Ndays_on10 T_MeanBin_sup33_Ndays_on10
1 0                          0
2 0                          0
  T_MinBin_17_19_Ndays_on30 T_MinBin_15_17_Ndays_on30 T_MinBin_19_21_Ndays_on30
1 0                         0                         0
2 0                         0                         0
  T_MinBin_21_23_Ndays_on30 T_MinBin_inf11_Ndays_on30 T_MinBin_11_13_Ndays_on30
1 0                         0                         0
2 0                         0                         0
  T_MinBin_13_15_Ndays_on30 T_MinBin_23_25_Ndays_on30 T_MinBin_sup25_Ndays_on30
1 0                         4                         26
2 0                         3                         27
  T_MinBin_17_19_Ndays_on20 T_MinBin_15_17_Ndays_on20 T_MinBin_19_21_Ndays_on20
1 0                         0                         0
2 0                         0                         0
  T_MinBin_21_23_Ndays_on20 T_MinBin_inf11_Ndays_on20 T_MinBin_11_13_Ndays_on20
1 0                         0                         0
2 0                         0                         0
  T_MinBin_13_15_Ndays_on20 T_MinBin_23_25_Ndays_on20 T_MinBin_sup25_Ndays_on20
1 0                         3                         17
2 0                         3                         17
  T_MinBin_17_19_Ndays_on10 T_MinBin_15_17_Ndays_on10 T_MinBin_19_21_Ndays_on10
1 0                         0                         0
2 0                         0                         0
  T_MinBin_21_23_Ndays_on10 T_MinBin_inf11_Ndays_on10 T_MinBin_11_13_Ndays_on10
1 0                         0                         0
2 0                         0                         0
  T_MinBin_13_15_Ndays_on10 T_MinBin_23_25_Ndays_on10 T_MinBin_sup25_Ndays_on10
1 0                         3                         7
2 0                         2                         8
  T_MaxBin_29_31_Ndays_on30 T_MaxBin_31_33_Ndays_on30 T_MaxBin_27_29_Ndays_on30
1 0                         0                         21
2 0                         0                         20
  T_MaxBin_25_27_Ndays_on30 T_MaxBin_23_25_Ndays_on30 T_MaxBin_inf21_Ndays_on30
1  9                        0                         0
2 10                        0                         0
  T_MaxBin_21_23_Ndays_on30 T_MaxBin_33_35_Ndays_on30 T_MaxBin_sup35_Ndays_on30
1 0                         0                         0
2 0                         0                         0
  T_MaxBin_29_31_Ndays_on20 T_MaxBin_31_33_Ndays_on20 T_MaxBin_27_29_Ndays_on20
1 0                         0                         15
2 0                         0                         13
  T_MaxBin_25_27_Ndays_on20 T_MaxBin_23_25_Ndays_on20 T_MaxBin_inf21_Ndays_on20
1 5                         0                         0
2 7                         0                         0
  T_MaxBin_21_23_Ndays_on20 T_MaxBin_33_35_Ndays_on20 T_MaxBin_sup35_Ndays_on20
1 0                         0                         0
2 0                         0                         0
  T_MaxBin_29_31_Ndays_on10 T_MaxBin_31_33_Ndays_on10 T_MaxBin_27_29_Ndays_on10
1 0                         0                         6
2 0                         0                         6
  T_MaxBin_25_27_Ndays_on10 T_MaxBin_23_25_Ndays_on10 T_MaxBin_inf21_Ndays_on10
1 4                         0                         0
2 4                         0                         0
  T_MaxBin_21_23_Ndays_on10 T_MaxBin_33_35_Ndays_on10 T_MaxBin_sup35_Ndays_on10
1 0                         0                         0
2 0                         0                         0
  WB_i30   WB_i20   WB_i10   WB_i30_bin WB_i20_bin WB_i10_bin
1 26.08611 26.08333 25.90833 (26,28]    (26,28]    (24,26]
2 26.08472 26.01042 25.99167 (26,28]    (26,28]    (24,26]
  WB_Bin_18_20_Nhours_on30 WB_Bin_20_22_Nhours_on30 WB_Bin_22_24_Nhours_on30
1 0                        0                        0
2 0                        0                        0
  WB_Bin_24_26_Nhours_on30 WB_Bin_16_18_Nhours_on30 WB_Bin_14_16_Nhours_on30
1 559                      0                        0
2 566                      0                        0
  WB_Bin_inf14_Nhours_on30 WB_Bin_26_28_Nhours_on30 WB_Bin_sup28_Nhours_on30
1 0                        161                      0
2 0                        154                      0
  WB_Bin_18_20_Nhours_on20 WB_Bin_20_22_Nhours_on20 WB_Bin_22_24_Nhours_on20
1 0                        0                        0
2 0                        0                        0
  WB_Bin_24_26_Nhours_on20 WB_Bin_16_18_Nhours_on20 WB_Bin_14_16_Nhours_on20
1 385                      0                        0
2 396                      0                        0
  WB_Bin_inf14_Nhours_on20 WB_Bin_26_28_Nhours_on20 WB_Bin_sup28_Nhours_on20
1 0                        95                       0
2 0                        84                       0
  WB_Bin_18_20_Nhours_on10 WB_Bin_20_22_Nhours_on10 WB_Bin_22_24_Nhours_on10
1 0                        0                        0
2 0                        0                        0
  WB_Bin_24_26_Nhours_on10 WB_Bin_16_18_Nhours_on10 WB_Bin_14_16_Nhours_on10
1 217                      0                        0
2 205                      0                        0
  WB_Bin_inf14_Nhours_on10 WB_Bin_26_28_Nhours_on10 WB_Bin_sup28_Nhours_on10
1 0                        23                       0
2 0                        35                       0
  WB_MeanBin_20_22_Ndays_on30 WB_MeanBin_18_20_Ndays_on30
1 0                           0
2 0                           0
  WB_MeanBin_22_24_Ndays_on30 WB_MeanBin_16_18_Ndays_on30
1 0                           0
2 0                           0
  WB_MeanBin_inf14_Ndays_on30 WB_MeanBin_14_16_Ndays_on30
1 0                           0
2 0                           0
  WB_MeanBin_24_26_Ndays_on30 WB_MeanBin_26_28_Ndays_on30
1 13                          17
2 14                          16
  WB_MeanBin_sup28_Ndays_on30 WB_MeanBin_20_22_Ndays_on20
1 0                           0
2 0                           0
  WB_MeanBin_18_20_Ndays_on20 WB_MeanBin_22_24_Ndays_on20
1 0                           0
2 0                           0
  WB_MeanBin_16_18_Ndays_on20 WB_MeanBin_inf14_Ndays_on20
1 0                           0
2 0                           0
  WB_MeanBin_14_16_Ndays_on20 WB_MeanBin_24_26_Ndays_on20
1 0                           10
2 0                           12
  WB_MeanBin_26_28_Ndays_on20 WB_MeanBin_sup28_Ndays_on20
1 10                          0
2  8                          0
  WB_MeanBin_20_22_Ndays_on10 WB_MeanBin_18_20_Ndays_on10
1 0                           0
2 0                           0
  WB_MeanBin_22_24_Ndays_on10 WB_MeanBin_16_18_Ndays_on10
1 0                           0
2 0                           0
  WB_MeanBin_inf14_Ndays_on10 WB_MeanBin_14_16_Ndays_on10
1 0                           0
2 0                           0
  WB_MeanBin_24_26_Ndays_on10 WB_MeanBin_26_28_Ndays_on10
1 7                           3
2 7                           3
  WB_MeanBin_sup28_Ndays_on10 WB_MinBin_18_20_Ndays_on30
1 0                           0
2 0                           0
  WB_MinBin_16_18_Ndays_on30 WB_MinBin_14_16_Ndays_on30
1 0                          0
2 0                          0
  WB_MinBin_12_14_Ndays_on30 WB_MinBin_10_12_Ndays_on30
1 0                          0
2 0                          0
  WB_MinBin_inf10_Ndays_on30 WB_MinBin_20_22_Ndays_on30
1 0                          0
2 0                          0
  WB_MinBin_22_24_Ndays_on30 WB_MinBin_sup24_Ndays_on30
1 0                          30
2 0                          30
  WB_MinBin_18_20_Ndays_on20 WB_MinBin_16_18_Ndays_on20
1 0                          0
2 0                          0
  WB_MinBin_14_16_Ndays_on20 WB_MinBin_12_14_Ndays_on20
1 0                          0
2 0                          0
  WB_MinBin_10_12_Ndays_on20 WB_MinBin_inf10_Ndays_on20
1 0                          0
2 0                          0
  WB_MinBin_20_22_Ndays_on20 WB_MinBin_22_24_Ndays_on20
1 0                          0
2 0                          0
  WB_MinBin_sup24_Ndays_on20 WB_MinBin_18_20_Ndays_on10
1 20                         0
2 20                         0
  WB_MinBin_16_18_Ndays_on10 WB_MinBin_14_16_Ndays_on10
1 0                          0
2 0                          0
  WB_MinBin_12_14_Ndays_on10 WB_MinBin_10_12_Ndays_on10
1 0                          0
2 0                          0
  WB_MinBin_inf10_Ndays_on10 WB_MinBin_20_22_Ndays_on10
1 0                          0
2 0                          0
  WB_MinBin_22_24_Ndays_on10 WB_MinBin_sup24_Ndays_on10
1 0                          10
2 0                          10
  WB_MaxBin_24_26_Ndays_on30 WB_MaxBin_22_24_Ndays_on30
1 10                         0
2 11                         0
  WB_MaxBin_26_28_Ndays_on30 WB_MaxBin_inf18_Ndays_on30
1 20                         0
2 19                         0
  WB_MaxBin_18_20_Ndays_on30 WB_MaxBin_20_22_Ndays_on30
1 0                          0
2 0                          0
  WB_MaxBin_28_30_Ndays_on30 WB_MaxBin_30_32_Ndays_on30
1 0                          0
2 0                          0
  WB_MaxBin_sup32_Ndays_on30 WB_MaxBin_24_26_Ndays_on20
1 0                          7
2 0                          9
  WB_MaxBin_22_24_Ndays_on20 WB_MaxBin_26_28_Ndays_on20
1 0                          13
2 0                          11
  WB_MaxBin_inf18_Ndays_on20 WB_MaxBin_18_20_Ndays_on20
1 0                          0
2 0                          0
  WB_MaxBin_20_22_Ndays_on20 WB_MaxBin_28_30_Ndays_on20
1 0                          0
2 0                          0
  WB_MaxBin_30_32_Ndays_on20 WB_MaxBin_sup32_Ndays_on20
1 0                          0
2 0                          0
  WB_MaxBin_24_26_Ndays_on10 WB_MaxBin_22_24_Ndays_on10
1 5                          0
2 5                          0
  WB_MaxBin_26_28_Ndays_on10 WB_MaxBin_inf18_Ndays_on10
1 5                          0
2 5                          0
  WB_MaxBin_18_20_Ndays_on10 WB_MaxBin_20_22_Ndays_on10
1 0                          0
2 0                          0
  WB_MaxBin_28_30_Ndays_on10 WB_MaxBin_30_32_Ndays_on10
1 0                          0
2 0                          0
  WB_MaxBin_sup32_Ndays_on10 P_tot_30  P_tot_20  P_tot_10   API_sup_1
1 0                          0.2839093 0.1787939 0.11706638 0
2 0                          0.2566433 0.1496382 0.09978867 0
  Underweight Normal Overweight Obese Agriculture Clerical Manual No_work TAM
1 0           1      0          0     0           0        1      0       0
2 0           1      0          0     0           0        0      1       0
  Sales Services
1 0     0
2 0     0

In [14]:
df_men_dum %>% 
    filter(!is.na(Blood_hemo_level_alti))%>%
    mutate(#Hemoglobin
           Men_anemia =  Men_anemia/1000,
           Men_severe_anemia = Men_severe_anemia/1000,
           Men_moderate_anemia = Men_moderate_anemia/1000,
           Men_mild_anemia = Men_mild_anemia/1000)%>%
    select(#Hemoglobin
           Blood_hemo_level_alti,Men_anemia,Men_severe_anemia,Men_moderate_anemia,Men_mild_anemia,
           #Malnutrition
           Body_mass_index,Underweight,Normal,Overweight,Obese,
           #Blood
           Blood_pressure_systo,Blood_pressure_diasto,Blood_glucose_level,
           #Individual controls
           Current_age,
           N_year_educ,
           Ethni_SC,Ethni_ST,Ethni_OBC,Ethni_other,
           Religion_hindu, Religion_muslim, Religion_not_hindu_nor_muslim,
           Smoker,Health_insurance,
           #Diet
           Diet_milk_curd_daily,Diet_pulses_beans_daily,Diet_green_veg_daily,
           Diet_fruits_daily,Diet_eggs_daily,Diet_fish_daily,Diet_chicken_meat_daily,Diet_fried_food_daily,
           Diet_aerated_drinks_daily,
           #Bednet
           Bednet_slept,
           #Occupation
           Agriculture,Clerical,Manual,No_work,Sales,Services,TAM,
           #HH controls
           Wealth_lowest,Wealth_second,Wealth_middle,Wealth_fourth,Wealth_highest,
           HH_air_conditioner,
           Urban,
           #Water
           HH_time_water_source,
           Water_fetching_risk,
           #Malaria
           API_sup_1
          )%>%
    stargazer(nobs=TRUE, digits = 2,
              summary.stat = c("n","mean", "sd","min","p25","median","p75","max"),
              title = c("Summary statistics"),
              covariate.labels = c(#Hemoglobin
                                   "Hemoglobin level (g/L)",
                                   "Anemia (hemo <130)",
                                   "Severe anemia (hemo <80)",
                                   "Moderate anemia (80<hemo<110)",
                                   "Mild anemia (110<hemo<130)",
                                   #Acute malnutrition
                                   "Body Mass Index (BMI)",
                                   "BMI underweight (BMI<18.5)",
                                   "BMI normal (18.5<BMI<25)",
                                   "BMI overweight (25<BMI<30)",
                                   "BMI obese (BMI>30)",
                                   #Other blood measures
                                   "Blood pressure systolic (mmHG)",
                                   "Blood pressure diastolic (mmHG)",
                                   "Blood glucose level (mg/dL)",
                                   #Individual controls
                                   "Age in years",
                                   "N years education",
                                   "Ethnicity scheduled caste (SC)",
                                   "Ethnicity scheduled tribe (ST)",
                                   "Ethnicity other backward caste (OBC)",
                                   "Ethnicity other",
                                   "Religion hindu",
                                   "Religion muslim",
                                   "Religion not hindu nor muslim",
                                   "Smoker",
                                   "Covered by health insurance",                                   
                                   #Diets
                                   "Daily diet (past 30 days): milk, curd",
                                   "Daily diet (past 30 days): beans",
                                   "Daily diet (past 30 days): green vegetables", 
                                   "Daily diet (past 30 days): fruits",
                                   "Daily diet (past 30 days): eggs",
                                   "Daily diet (past 30 days): chicken, meat",
                                   "Daily diet (past 30 days): fish",
                                   "Daily diet (past 30 days): fried food",
                                   "Daily diet (past 30 days): aerated drinks",
                                   #Bednet
                                   "Slept under any bednet",
                                   #Occupation
                                   "Occupation agriculture",
                                   "Occupation clerical",
                                   "Occupation manual",
                                   "No Occupation",  
                                   "Occupation sales",
                                   "Occupation services",
                                   "Occupation TAM",                                  
                                   #HH controls
                                   "Wealth 1st quintile (poorest)",
                                   "Wealth 2nd quintile",
                                   "Wealth 3rd quintile",
                                   "Wealth 4th quintile",
                                   "Wealth 5th quintile (richest)",
                                   "Air conditioner",
                                   "Urban",
                                   #Water
                                   "Time to water source (minutes)",
                                   "Water fetching risk",
                                   #Malaria
                                   "API > 1"
                                   ),
              type="latex"
             )

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: jeu., avril 16, 2026 - 17:54:25
\begin{table}[!htbp] \centering
  \caption{Summary statistics}
  \label{}
\begin{tabular}{@{\extracolsep{5pt}}lcccccccc}
\\[-1.8ex]\hline
\hline \\[-1.8ex]
Statistic & \multicolumn{1}{c}{N} & \multicolumn{1}{c}{Mean} & \multicolumn{1}{c}{St. Dev.} & \multicolumn{1}{c}{Min} & \multicolumn{1}{c}{Pctl(25)} & \multicolumn{1}{c}{Median} & \multicolumn{1}{c}{Pctl(75)} & \multicolumn{1}{c}{Max} \\
\hline \\[-1.8ex]
Hemoglobin level (g/L) & 140,552 & 140.09 & 18.16 & 16 & 130 & 142 & 152 & 256 \\
Anemia (hemo <130) & 140,552 & 0.24 & 0.43 & 0 & 0 & 0 & 0 & 1 \\
Severe anemia (hemo <80) & 140,552 & 0.01 & 0.07 & 0 & 0 & 0 & 0 & 1 \\
Moderate anemia (80<hemo<110) & 140,552 & 0.05 & 0.21 & 0 & 0 & 0 & 0 & 1 \\
Mild anemia (110<hemo<130) & 140,552 & 0.19 & 0.39 & 0 & 0 & 0 & 0 & 1 \\
Body Mass Index (BMI) & 140,160 & 21.98 & 3.88 & 12.05 & 19.22 & 21.60 & 24.19 & 59.96 \\
BMI underweight (BMI<18.5) & 140,160 & 0.18 & 0.38 & 0 & 0 & 0 & 0 & 1 \\
BMI normal (18.5<BMI<25) & 140,160 & 0.63 & 0.48 & 0 & 0 & 1 & 1 & 1 \\
BMI overweight (25<BMI<30) & 140,160 & 0.16 & 0.37 & 0 & 0 & 0 & 0 & 1 \\
BMI obese (BMI>30) & 140,160 & 0.03 & 0.17 & 0 & 0 & 0 & 0 & 1 \\
Blood pressure systolic (mmHG) & 140,432 & 124.22 & 14.75 & 0 & 115 & 123 & 132 & 299 \\
Blood pressure diastolic (mmHG) & 140,432 & 81.65 & 11.61 & 0 & 75 & 81 & 88 & 268 \\
Blood glucose level (mg/dL) & 140,520 & 110.57 & 34.73 & 20 & 92 & 104 & 121 & 499 \\
Age in years & 140,552 & 32.08 & 11.15 & 15 & 22 & 31 & 41 & 54 \\
N years education & 140,552 & 8.42 & 4.67 & 0 & 5 & 9 & 12 & 20 \\
Ethnicity scheduled caste (SC) & 140,552 & 0.18 & 0.39 & 0 & 0 & 0 & 0 & 1 \\
Ethnicity scheduled tribe (ST) & 140,552 & 0.20 & 0.40 & 0 & 0 & 0 & 0 & 1 \\
Ethnicity other backward caste (OBC) & 140,552 & 0.40 & 0.49 & 0 & 0 & 0 & 1 & 1 \\
Ethnicity other & 140,552 & 0.21 & 0.41 & 0 & 0 & 0 & 0 & 1 \\
Religion hindu & 140,552 & 0.76 & 0.43 & 0 & 1 & 1 & 1 & 1 \\
Religion muslim & 140,552 & 0.11 & 0.31 & 0 & 0 & 0 & 0 & 1 \\
Religion not hindu nor muslim & 140,552 & 0.13 & 0.34 & 0 & 0 & 0 & 0 & 1 \\
Smoker & 140,552 & 0.48 & 0.50 & 0 & 0 & 0 & 1 & 1 \\
Covered by health insurance & 140,552 & 0.26 & 0.44 & 0 & 0 & 0 & 1 & 1 \\
Daily diet (past 30 days): milk, curd & 140,552 & 0.44 & 0.50 & 0 & 0 & 0 & 1 & 1 \\
Daily diet (past 30 days): beans & 140,552 & 0.45 & 0.50 & 0 & 0 & 0 & 1 & 1 \\
Daily diet (past 30 days): green vegetables & 140,552 & 0.47 & 0.50 & 0 & 0 & 0 & 1 & 1 \\
Daily diet (past 30 days): fruits & 140,552 & 0.10 & 0.31 & 0 & 0 & 0 & 0 & 1 \\
Daily diet (past 30 days): eggs & 140,552 & 0.05 & 0.21 & 0 & 0 & 0 & 0 & 1 \\
Daily diet (past 30 days): chicken, meat & 140,552 & 0.05 & 0.21 & 0 & 0 & 0 & 0 & 1 \\
Daily diet (past 30 days): fish & 140,552 & 0.02 & 0.13 & 0 & 0 & 0 & 0 & 1 \\
Daily diet (past 30 days): fried food & 140,552 & 0.12 & 0.32 & 0 & 0 & 0 & 0 & 1 \\
Daily diet (past 30 days): aerated drinks & 140,552 & 0.06 & 0.23 & 0 & 0 & 0 & 0 & 1 \\
Slept under any bednet & 140,552 & 0.24 & 0.43 & 0 & 0 & 0 & 0 & 1 \\
Occupation agriculture & 140,220 & 0.31 & 0.46 & 0 & 0 & 0 & 1 & 1 \\
Occupation clerical & 140,166 & 0.02 & 0.13 & 0 & 0 & 0 & 0 & 1 \\
Occupation manual & 140,238 & 0.24 & 0.43 & 0 & 0 & 0 & 0 & 1 \\
No Occupation & 140,316 & 0.21 & 0.41 & 0 & 0 & 0 & 0 & 1 \\
Occupation sales & 140,207 & 0.08 & 0.28 & 0 & 0 & 0 & 0 & 1 \\
Occupation services & 140,180 & 0.07 & 0.25 & 0 & 0 & 0 & 0 & 1 \\
Occupation TAM & 140,177 & 0.06 & 0.23 & 0 & 0 & 0 & 0 & 1 \\
Wealth 1st quintile (poorest) & 140,552 & 0.17 & 0.38 & 0 & 0 & 0 & 0 & 1 \\
Wealth 2nd quintile & 140,552 & 0.21 & 0.41 & 0 & 0 & 0 & 0 & 1 \\
Wealth 3rd quintile & 140,552 & 0.22 & 0.42 & 0 & 0 & 0 & 0 & 1 \\
Wealth 4th quintile & 140,552 & 0.21 & 0.41 & 0 & 0 & 0 & 0 & 1 \\
Wealth 5th quintile (richest) & 140,552 & 0.18 & 0.39 & 0 & 0 & 0 & 0 & 1 \\
Air conditioner & 140,552 & 0.19 & 0.39 & 0 & 0 & 0 & 0 & 1 \\
Urban & 140,552 & 0.29 & 0.46 & 0 & 0 & 0 & 1 & 1 \\
Time to water source (minutes) & 140,425 & 5.36 & 12.55 & 0 & 0 & 0 & 5 & 900 \\
Water fetching risk & 140,425 & 0.31 & 0.46 & 0 & 0 & 0 & 1 & 1 \\
API > 1 & 138,559 & 0.07 & 0.26 & 0 & 0 & 0 & 0 & 1 \\
\hline \\[-1.8ex]
\end{tabular}
\end{table}

# Women

In [21]:
df_women <- fread("./2_Regression_datasets/output/df_reg_women.csv")
sprintf("%i rows x %i columns", nrow(df_women), ncol(df_women))
head(df_women,2)

[1] "973462 rows x 330 columns"

  DHS_round DHSCLUST State_2011               District_2011 cell_x_01 cell_y_01
1 2015      10001    Andaman & Nicobar Island South Andaman 92.7      11.7
2 2015      10001    Andaman & Nicobar Island South Andaman 92.7      11.7
  cell_x_025 cell_y_025 HH_ID Women_id       Resp_nb Interview_month
1 92.75      11.75      1     01000101    02 2       7
2 92.75      11.75      1     01000101    04 4       7
  Interview_year Interview_day Measured_date_CDC Measured_date Current_age
1 2015           18            42201             2015-07-18    46
2 2015           18            42201             2015-07-18    20
  Age_group Religion_hindu Religion_muslim Religion_not_hindu_nor_muslim
1 45-49     0              0               1
2 20-24     0              0               1
  Ethni_SC Ethni_ST Ethni_OBC Ethni_other N_year_educ Smoker Health_insurance
1 0        0        0         1            0          1      0
2 0        0        0         1           14          0      0
  Currently_pregnant Blood_hemo_level_alti Blood_pressure_systo
1 0                   81                   115
2 0                  113                    96
  Blood_pressure_diasto Blood_glucose_level Body_mass_index
1 76                    116                 22.95
2 72                     83                 22.03
  Diet_milk_curd_daily Diet_milk_curd_week Diet_milk_curd_oc
1 0                    0                   0
2 0                    0                   1
  Diet_milk_curd_never Diet_pulses_beans_daily Diet_pulses_beans_week
1 1                    1                       0
2 0                    1                       0
  Diet_pulses_beans_oc Diet_pulses_beans_never Diet_green_veg_daily
1 0                    0                       0
2 0                    0                       0
  Diet_green_veg_week Diet_green_veg_oc Diet_green_veg_never Diet_fruits_daily
1 1                   0                 0                    0
2 1                   0                 0                    0
  Diet_fruits_week Diet_fruits_oc Diet_fruits_never Diet_eggs_daily
1 1                0              0                 0
2 0                1              0                 0
  Diet_eggs_week Diet_eggs_oc Diet_eggs_never Diet_fish_daily Diet_fish_week
1 1              0            0               0               1
2 1              0            0               0               1
  Diet_fish_oc Diet_fish_never Diet_chicken_meat_daily Diet_chicken_meat_week
1 0            0               0                       0
2 0            0               0                       1
  Diet_chicken_meat_oc Diet_chicken_meat_never Diet_fried_food_daily
1 1                    0                       0
2 0                    0                       0
  Diet_fried_food_week Diet_fried_food_oc Diet_fried_food_never
1 1                    0                  0
2 1                    0                  0
  Diet_aerated_drinks_daily Diet_aerated_drinks_week Diet_aerated_drinks_oc
1 0                         1                        0
2 0                         1                        0
  Diet_aerated_drinks_never Wealth_lowest Wealth_second Wealth_middle
1 0                         0             0             1
2 0                         0             0             1
  Wealth_fourth Wealth_highest Urban Usual_resident Bednet_slept
1 0             0              1     1              0
2 0             0              1     1              0
  HH_time_water_source HH_air_conditioner HH_treat_water HH_no_toilet
1 0                    0                  0              0
2 0                    0                  0              0
  HH_well_water cell_x.x cell_y.x cell_x.y cell_y.y Measured_month
1 0             92.7     11.7     92.75    11.75    7
2 0             92.7     11.7     92.75    11.75    7
  Measured_year Women_anemia Women_severe_anemia Women_moderate_anemia
1 2015          1000         0                   1000
2 2015          1000         0                      0
  Women_mild_anemia Women_no_anemia BMI_category Blood_hypertension
1    0              0               Normal       0
2 1000              0               Normal       0
  Water_fetching_risk District_ID                            T_i30    T_i20
1 0                   Andaman & Nicobar Island_South Andaman 26.94861 26.89167
2 0                   Andaman & Nicobar Island_South Andaman 26.94861 26.89167
  T_i10    T_i30_bin T_i20_bin T_i10_bin T_Bin_17_21_Nhours_on30
1 26.92083 (25,27]   (25,27]   (25,27]   0
2 26.92083 (25,27]   (25,27]   (25,27]   0
  T_Bin_21_23_Nhours_on30 T_Bin_23_25_Nhours_on30 T_Bin_25_27_Nhours_on30
1 0                       7                       536
2 0                       7                       536
  T_Bin_27_29_Nhours_on30 T_Bin_29_31_Nhours_on30 T_Bin_inf17_Nhours_on30
1 177                     0                       0
2 177                     0                       0
  T_Bin_31_33_Nhours_on30 T_Bin_sup33_Nhours_on30 T_Bin_17_21_Nhours_on20
1 0                       0                       0
2 0                       0                       0
  T_Bin_21_23_Nhours_on20 T_Bin_23_25_Nhours_on20 T_Bin_25_27_Nhours_on20
1 0                       4                       367
2 0                       4                       367
  T_Bin_27_29_Nhours_on20 T_Bin_29_31_Nhours_on20 T_Bin_inf17_Nhours_on20
1 109                     0                       0
2 109                     0                       0
  T_Bin_31_33_Nhours_on20 T_Bin_sup33_Nhours_on20 T_Bin_17_21_Nhours_on10
1 0                       0                       0
2 0                       0                       0
  T_Bin_21_23_Nhours_on10 T_Bin_23_25_Nhours_on10 T_Bin_25_27_Nhours_on10
1 0                       3                       183
2 0                       3                       183
  T_Bin_27_29_Nhours_on10 T_Bin_29_31_Nhours_on10 T_Bin_inf17_Nhours_on10
1 54                      0                       0
2 54                      0                       0
  T_Bin_31_33_Nhours_on10 T_Bin_sup33_Nhours_on10 T_MeanBin_23_25_Ndays_on30
1 0                       0                       0
2 0                       0                       0
  T_MeanBin_21_23_Ndays_on30 T_MeanBin_25_27_Ndays_on30
1 0                          17
2 0                          17
  T_MeanBin_inf17_Ndays_on30 T_MeanBin_17_21_Ndays_on30
1 0                          0
2 0                          0
  T_MeanBin_27_29_Ndays_on30 T_MeanBin_29_31_Ndays_on30
1 13                         0
2 13                         0
  T_MeanBin_31_33_Ndays_on30 T_MeanBin_sup33_Ndays_on30
1 0                          0
2 0                          0
  T_MeanBin_23_25_Ndays_on20 T_MeanBin_21_23_Ndays_on20
1 0                          0
2 0                          0
  T_MeanBin_25_27_Ndays_on20 T_MeanBin_inf17_Ndays_on20
1 13                         0
2 13                         0
  T_MeanBin_17_21_Ndays_on20 T_MeanBin_27_29_Ndays_on20
1 0                          7
2 0                          7
  T_MeanBin_29_31_Ndays_on20 T_MeanBin_31_33_Ndays_on20
1 0                          0
2 0                          0
  T_MeanBin_sup33_Ndays_on20 T_MeanBin_23_25_Ndays_on10
1 0                          0
2 0                          0
  T_MeanBin_21_23_Ndays_on10 T_MeanBin_25_27_Ndays_on10
1 0                          7
2 0                          7
  T_MeanBin_inf17_Ndays_on10 T_MeanBin_17_21_Ndays_on10
1 0                          0
2 0                          0
  T_MeanBin_27_29_Ndays_on10 T_MeanBin_29_31_Ndays_on10
1 3                          0
2 3                          0
  T_MeanBin_31_33_Ndays_on10 T_MeanBin_sup33_Ndays_on10
1 0                          0
2 0                          0
  T_MinBin_17_19_Ndays_on30 T_MinBin_15_17_Ndays_on30 T_MinBin_19_21_Ndays_on30
1 0                         0                         0
2 0                         0                         0
  T_MinBin_21_23_Ndays_on30 T_MinBin_inf11_Ndays_on30 T_MinBin_11_13_Ndays_on30
1 0                         0                         0
2 0                         0                         0
  T_MinBin_13_15_Ndays_on30 T_MinBin_23_25_Ndays_on30 T_MinBin_sup25_Ndays_on30
1 0                         4                         26
2 0                         4                         26
  T_MinBin_17_19_Ndays_on20 T_MinBin_15_17_Ndays_on20 T_MinBin_19_21_Ndays_on20
1 0                         0                         0
2 0                         0                         0
  T_MinBin_21_23_Ndays_on20 T_MinBin_inf11_Ndays_on20 T_MinBin_11_13_Ndays_on20
1 0                         0                         0
2 0                         0                         0
  T_MinBin_13_15_Ndays_on20 T_MinBin_23_25_Ndays_on20 T_MinBin_sup25_Ndays_on20
1 0                         3                         17
2 0                         3                         17
  T_MinBin_17_19_Ndays_on10 T_MinBin_15_17_Ndays_on10 T_MinBin_19_21_Ndays_on10
1 0                         0                         0
2 0                         0                         0
  T_MinBin_21_23_Ndays_on10 T_MinBin_inf11_Ndays_on10 T_MinBin_11_13_Ndays_on10
1 0                         0                         0
2 0                         0                         0
  T_MinBin_13_15_Ndays_on10 T_MinBin_23_25_Ndays_on10 T_MinBin_sup25_Ndays_on10
1 0                         2                         8
2 0                         2                         8
  T_MaxBin_29_31_Ndays_on30 T_MaxBin_31_33_Ndays_on30 T_MaxBin_27_29_Ndays_on30
1 0                         0                         20
2 0                         0                         20
  T_MaxBin_25_27_Ndays_on30 T_MaxBin_23_25_Ndays_on30 T_MaxBin_inf21_Ndays_on30
1 10                        0                         0
2 10                        0                         0
  T_MaxBin_21_23_Ndays_on30 T_MaxBin_33_35_Ndays_on30 T_MaxBin_sup35_Ndays_on30
1 0                         0                         0
2 0                         0                         0
  T_MaxBin_29_31_Ndays_on20 T_MaxBin_31_33_Ndays_on20 T_MaxBin_27_29_Ndays_on20
1 0                         0                         12
2 0                         0                         12
  T_MaxBin_25_27_Ndays_on20 T_MaxBin_23_25_Ndays_on20 T_MaxBin_inf21_Ndays_on20
1 8                         0                         0
2 8                         0                         0
  T_MaxBin_21_23_Ndays_on20 T_MaxBin_33_35_Ndays_on20 T_MaxBin_sup35_Ndays_on20
1 0                         0                         0
2 0                         0                         0
  T_MaxBin_29_31_Ndays_on10 T_MaxBin_31_33_Ndays_on10 T_MaxBin_27_29_Ndays_on10
1 0                         0                         6
2 0                         0                         6
  T_MaxBin_25_27_Ndays_on10 T_MaxBin_23_25_Ndays_on10 T_MaxBin_inf21_Ndays_on10
1 4                         0                         0
2 4                         0                         0
  T_MaxBin_21_23_Ndays_on10 T_MaxBin_33_35_Ndays_on10 T_MaxBin_sup35_Ndays_on10
1 0                         0                         0
2 0                         0                         0
  WB_i30   WB_i20   WB_i10   WB_i30_bin WB_i20_bin WB_i10_bin
1 26.05833 25.96875 25.99167 (26,28]    (24,26]    (24,26]
2 26.05833 25.96875 25.99167 (26,28]    (24,26]    (24,26]
  WB_Bin_18_20_Nhours_on30 WB_Bin_20_22_Nhours_on30 WB_Bin_22_24_Nhours_on30
1 0                        0                        0
2 0                        0                        0
  WB_Bin_24_26_Nhours_on30 WB_Bin_16_18_Nhours_on30 WB_Bin_14_16_Nhours_on30
1 576                      0                        0
2 576                      0                        0
  WB_Bin_inf14_Nhours_on30 WB_Bin_26_28_Nhours_on30 WB_Bin_sup28_Nhours_on30
1 0                        144                      0
2 0                        144                      0
  WB_Bin_18_20_Nhours_on20 WB_Bin_20_22_Nhours_on20 WB_Bin_22_24_Nhours_on20
1 0                        0                        0
2 0                        0                        0
  WB_Bin_24_26_Nhours_on20 WB_Bin_16_18_Nhours_on20 WB_Bin_14_16_Nhours_on20
1 406                      0                        0
2 406                      0                        0
  WB_Bin_inf14_Nhours_on20 WB_Bin_26_28_Nhours_on20 WB_Bin_sup28_Nhours_on20
1 0                        74                       0
2 0                        74                       0
  WB_Bin_18_20_Nhours_on10 WB_Bin_20_22_Nhours_on10 WB_Bin_22_24_Nhours_on10
1 0                        0                        0
2 0                        0                        0
  WB_Bin_24_26_Nhours_on10 WB_Bin_16_18_Nhours_on10 WB_Bin_14_16_Nhours_on10
1 205                      0                        0
2 205                      0                        0
  WB_Bin_inf14_Nhours_on10 WB_Bin_26_28_Nhours_on10 WB_Bin_sup28_Nhours_on10
1 0                        35                       0
2 0                        35                       0
  WB_MeanBin_20_22_Ndays_on30 WB_MeanBin_18_20_Ndays_on30
1 0                           0
2 0                           0
  WB_MeanBin_22_24_Ndays_on30 WB_MeanBin_16_18_Ndays_on30
1 0                           0
2 0                           0
  WB_MeanBin_inf14_Ndays_on30 WB_MeanBin_14_16_Ndays_on30
1 0                           0
2 0                           0
  WB_MeanBin_24_26_Ndays_on30 WB_MeanBin_26_28_Ndays_on30
1 15                          15
2 15                          15
  WB_MeanBin_sup28_Ndays_on30 WB_MeanBin_20_22_Ndays_on20
1 0                           0
2 0                           0
  WB_MeanBin_18_20_Ndays_on20 WB_MeanBin_22_24_Ndays_on20
1 0                           0
2 0                           0
  WB_MeanBin_16_18_Ndays_on20 WB_MeanBin_inf14_Ndays_on20
1 0                           0
2 0                           0
  WB_MeanBin_14_16_Ndays_on20 WB_MeanBin_24_26_Ndays_on20
1 0                           13
2 0                           13
  WB_MeanBin_26_28_Ndays_on20 WB_MeanBin_sup28_Ndays_on20
1 7                           0
2 7                           0
  WB_MeanBin_20_22_Ndays_on10 WB_MeanBin_18_20_Ndays_on10
1 0                           0
2 0                           0
  WB_MeanBin_22_24_Ndays_on10 WB_MeanBin_16_18_Ndays_on10
1 0                           0
2 0                           0
  WB_MeanBin_inf14_Ndays_on10 WB_MeanBin_14_16_Ndays_on10
1 0                           0
2 0                           0
  WB_MeanBin_24_26_Ndays_on10 WB_MeanBin_26_28_Ndays_on10
1 7                           3
2 7                           3
  WB_MeanBin_sup28_Ndays_on10 WB_MinBin_18_20_Ndays_on30
1 0                           0
2 0                           0
  WB_MinBin_16_18_Ndays_on30 WB_MinBin_14_16_Ndays_on30
1 0                          0
2 0                          0
  WB_MinBin_12_14_Ndays_on30 WB_MinBin_10_12_Ndays_on30
1 0                          0
2 0                          0
  WB_MinBin_inf10_Ndays_on30 WB_MinBin_20_22_Ndays_on30
1 0                          0
2 0                          0
  WB_MinBin_22_24_Ndays_on30 WB_MinBin_sup24_Ndays_on30
1 0                          30
2 0                          30
  WB_MinBin_18_20_Ndays_on20 WB_MinBin_16_18_Ndays_on20
1 0                          0
2 0                          0
  WB_MinBin_14_16_Ndays_on20 WB_MinBin_12_14_Ndays_on20
1 0                          0
2 0                          0
  WB_MinBin_10_12_Ndays_on20 WB_MinBin_inf10_Ndays_on20
1 0                          0
2 0                          0
  WB_MinBin_20_22_Ndays_on20 WB_MinBin_22_24_Ndays_on20
1 0                          0
2 0                          0
  WB_MinBin_sup24_Ndays_on20 WB_MinBin_18_20_Ndays_on10
1 20                         0
2 20                         0
  WB_MinBin_16_18_Ndays_on10 WB_MinBin_14_16_Ndays_on10
1 0                          0
2 0                          0
  WB_MinBin_12_14_Ndays_on10 WB_MinBin_10_12_Ndays_on10
1 0                          0
2 0                          0
  WB_MinBin_inf10_Ndays_on10 WB_MinBin_20_22_Ndays_on10
1 0                          0
2 0                          0
  WB_MinBin_22_24_Ndays_on10 WB_MinBin_sup24_Ndays_on10
1 0                          10
2 0                          10
  WB_MaxBin_24_26_Ndays_on30 WB_MaxBin_22_24_Ndays_on30
1 12                         0
2 12                         0
  WB_MaxBin_26_28_Ndays_on30 WB_MaxBin_inf18_Ndays_on30
1 18                         0
2 18                         0
  WB_MaxBin_18_20_Ndays_on30 WB_MaxBin_20_22_Ndays_on30
1 0                          0
2 0                          0
  WB_MaxBin_28_30_Ndays_on30 WB_MaxBin_30_32_Ndays_on30
1 0                          0
2 0                          0
  WB_MaxBin_sup32_Ndays_on30 WB_MaxBin_24_26_Ndays_on20
1 0                          10
2 0                          10
  WB_MaxBin_22_24_Ndays_on20 WB_MaxBin_26_28_Ndays_on20
1 0                          10
2 0                          10
  WB_MaxBin_inf18_Ndays_on20 WB_MaxBin_18_20_Ndays_on20
1 0                          0
2 0                          0
  WB_MaxBin_20_22_Ndays_on20 WB_MaxBin_28_30_Ndays_on20
1 0                          0
2 0                          0
  WB_MaxBin_30_32_Ndays_on20 WB_MaxBin_sup32_Ndays_on20
1 0                          0
2 0                          0
  WB_MaxBin_24_26_Ndays_on10 WB_MaxBin_22_24_Ndays_on10
1 5                          0
2 5                          0
  WB_MaxBin_26_28_Ndays_on10 WB_MaxBin_inf18_Ndays_on10
1 5                          0
2 5                          0
  WB_MaxBin_18_20_Ndays_on10 WB_MaxBin_20_22_Ndays_on10
1 0                          0
2 0                          0
  WB_MaxBin_28_30_Ndays_on10 WB_MaxBin_30_32_Ndays_on10
1 0                          0
2 0                          0
  WB_MaxBin_sup32_Ndays_on10 P_tot_30  P_tot_20  P_tot_10   API_sup_1
1 0                          0.2628756 0.1457701 0.08272409 0
2 0                          0.2628756 0.1457701 0.08272409 0

In [22]:
df_reg_women <- df_women %>%
                mutate(T_i30_bin=factor(gsub("\\(","",T_i30_bin),levels=T_bins_labels))

In [23]:
reg_women_T <- feols(Blood_hemo_level_alti ~ i(T_i30_bin,ref=bin_ref_T) + P_tot_30 +
                                        Current_age + N_year_educ + Smoker + Health_insurance + 
                                        Religion_muslim + Religion_not_hindu_nor_muslim + 
                                        Ethni_SC + Ethni_ST + Ethni_OBC +
                                        Wealth_lowest + Wealth_second + Wealth_fourth + Wealth_highest + 
                                        Urban 
                                        |District_ID^Measured_month + District_ID^Measured_year,
                           vcov = ~District_ID,
                    df_reg_women)

NOTES: 59,850 observations removed because of NA values (RHS: 59,850).
       17/1 fixed-effect singletons were removed (17 observations).

In [24]:
main_sample_women <- df_reg_women[obs(reg_women_T), ]

In [25]:
df_women_dum <- data.frame(main_sample_women)%>%
                  mutate(Underweight = case_when(BMI_category=="Underweight" ~1,
                                                 is.na(BMI_category) ~ NA,
                                                 TRUE ~ 0),
                         Normal = case_when(BMI_category=="Normal" ~1,
                                                 is.na(BMI_category) ~ NA,
                                                 TRUE ~ 0),
                         Overweight = case_when(BMI_category=="Overweight" ~1,
                                                 is.na(BMI_category) ~ NA,
                                                 TRUE ~ 0),
                         Obese = case_when(BMI_category=="Obese" ~1,
                                                 is.na(BMI_category) ~ NA,
                                                 TRUE ~ 0))
head(df_women_dum,2)

  DHS_round DHSCLUST State_2011               District_2011 cell_x_01 cell_y_01
1 2015      10001    Andaman & Nicobar Island South Andaman 92.7      11.7
2 2015      10001    Andaman & Nicobar Island South Andaman 92.7      11.7
  cell_x_025 cell_y_025 HH_ID Women_id       Resp_nb Interview_month
1 92.75      11.75      1     01000101    02 2       7
2 92.75      11.75      1     01000101    04 4       7
  Interview_year Interview_day Measured_date_CDC Measured_date Current_age
1 2015           18            42201             2015-07-18    46
2 2015           18            42201             2015-07-18    20
  Age_group Religion_hindu Religion_muslim Religion_not_hindu_nor_muslim
1 45-49     0              0               1
2 20-24     0              0               1
  Ethni_SC Ethni_ST Ethni_OBC Ethni_other N_year_educ Smoker Health_insurance
1 0        0        0         1            0          1      0
2 0        0        0         1           14          0      0
  Currently_pregnant Blood_hemo_level_alti Blood_pressure_systo
1 0                   81                   115
2 0                  113                    96
  Blood_pressure_diasto Blood_glucose_level Body_mass_index
1 76                    116                 22.95
2 72                     83                 22.03
  Diet_milk_curd_daily Diet_milk_curd_week Diet_milk_curd_oc
1 0                    0                   0
2 0                    0                   1
  Diet_milk_curd_never Diet_pulses_beans_daily Diet_pulses_beans_week
1 1                    1                       0
2 0                    1                       0
  Diet_pulses_beans_oc Diet_pulses_beans_never Diet_green_veg_daily
1 0                    0                       0
2 0                    0                       0
  Diet_green_veg_week Diet_green_veg_oc Diet_green_veg_never Diet_fruits_daily
1 1                   0                 0                    0
2 1                   0                 0                    0
  Diet_fruits_week Diet_fruits_oc Diet_fruits_never Diet_eggs_daily
1 1                0              0                 0
2 0                1              0                 0
  Diet_eggs_week Diet_eggs_oc Diet_eggs_never Diet_fish_daily Diet_fish_week
1 1              0            0               0               1
2 1              0            0               0               1
  Diet_fish_oc Diet_fish_never Diet_chicken_meat_daily Diet_chicken_meat_week
1 0            0               0                       0
2 0            0               0                       1
  Diet_chicken_meat_oc Diet_chicken_meat_never Diet_fried_food_daily
1 1                    0                       0
2 0                    0                       0
  Diet_fried_food_week Diet_fried_food_oc Diet_fried_food_never
1 1                    0                  0
2 1                    0                  0
  Diet_aerated_drinks_daily Diet_aerated_drinks_week Diet_aerated_drinks_oc
1 0                         1                        0
2 0                         1                        0
  Diet_aerated_drinks_never Wealth_lowest Wealth_second Wealth_middle
1 0                         0             0             1
2 0                         0             0             1
  Wealth_fourth Wealth_highest Urban Usual_resident Bednet_slept
1 0             0              1     1              0
2 0             0              1     1              0
  HH_time_water_source HH_air_conditioner HH_treat_water HH_no_toilet
1 0                    0                  0              0
2 0                    0                  0              0
  HH_well_water cell_x.x cell_y.x cell_x.y cell_y.y Measured_month
1 0             92.7     11.7     92.75    11.75    7
2 0             92.7     11.7     92.75    11.75    7
  Measured_year Women_anemia Women_severe_anemia Women_moderate_anemia
1 2015          1000         0                   1000
2 2015          1000         0                      0
  Women_mild_anemia Women_no_anemia BMI_category Blood_hypertension
1    0              0               Normal       0
2 1000              0               Normal       0
  Water_fetching_risk District_ID                            T_i30    T_i20
1 0                   Andaman & Nicobar Island_South Andaman 26.94861 26.89167
2 0                   Andaman & Nicobar Island_South Andaman 26.94861 26.89167
  T_i10    T_i30_bin T_i20_bin T_i10_bin T_Bin_17_21_Nhours_on30
1 26.92083 25,27]    (25,27]   (25,27]   0
2 26.92083 25,27]    (25,27]   (25,27]   0
  T_Bin_21_23_Nhours_on30 T_Bin_23_25_Nhours_on30 T_Bin_25_27_Nhours_on30
1 0                       7                       536
2 0                       7                       536
  T_Bin_27_29_Nhours_on30 T_Bin_29_31_Nhours_on30 T_Bin_inf17_Nhours_on30
1 177                     0                       0
2 177                     0                       0
  T_Bin_31_33_Nhours_on30 T_Bin_sup33_Nhours_on30 T_Bin_17_21_Nhours_on20
1 0                       0                       0
2 0                       0                       0
  T_Bin_21_23_Nhours_on20 T_Bin_23_25_Nhours_on20 T_Bin_25_27_Nhours_on20
1 0                       4                       367
2 0                       4                       367
  T_Bin_27_29_Nhours_on20 T_Bin_29_31_Nhours_on20 T_Bin_inf17_Nhours_on20
1 109                     0                       0
2 109                     0                       0
  T_Bin_31_33_Nhours_on20 T_Bin_sup33_Nhours_on20 T_Bin_17_21_Nhours_on10
1 0                       0                       0
2 0                       0                       0
  T_Bin_21_23_Nhours_on10 T_Bin_23_25_Nhours_on10 T_Bin_25_27_Nhours_on10
1 0                       3                       183
2 0                       3                       183
  T_Bin_27_29_Nhours_on10 T_Bin_29_31_Nhours_on10 T_Bin_inf17_Nhours_on10
1 54                      0                       0
2 54                      0                       0
  T_Bin_31_33_Nhours_on10 T_Bin_sup33_Nhours_on10 T_MeanBin_23_25_Ndays_on30
1 0                       0                       0
2 0                       0                       0
  T_MeanBin_21_23_Ndays_on30 T_MeanBin_25_27_Ndays_on30
1 0                          17
2 0                          17
  T_MeanBin_inf17_Ndays_on30 T_MeanBin_17_21_Ndays_on30
1 0                          0
2 0                          0
  T_MeanBin_27_29_Ndays_on30 T_MeanBin_29_31_Ndays_on30
1 13                         0
2 13                         0
  T_MeanBin_31_33_Ndays_on30 T_MeanBin_sup33_Ndays_on30
1 0                          0
2 0                          0
  T_MeanBin_23_25_Ndays_on20 T_MeanBin_21_23_Ndays_on20
1 0                          0
2 0                          0
  T_MeanBin_25_27_Ndays_on20 T_MeanBin_inf17_Ndays_on20
1 13                         0
2 13                         0
  T_MeanBin_17_21_Ndays_on20 T_MeanBin_27_29_Ndays_on20
1 0                          7
2 0                          7
  T_MeanBin_29_31_Ndays_on20 T_MeanBin_31_33_Ndays_on20
1 0                          0
2 0                          0
  T_MeanBin_sup33_Ndays_on20 T_MeanBin_23_25_Ndays_on10
1 0                          0
2 0                          0
  T_MeanBin_21_23_Ndays_on10 T_MeanBin_25_27_Ndays_on10
1 0                          7
2 0                          7
  T_MeanBin_inf17_Ndays_on10 T_MeanBin_17_21_Ndays_on10
1 0                          0
2 0                          0
  T_MeanBin_27_29_Ndays_on10 T_MeanBin_29_31_Ndays_on10
1 3                          0
2 3                          0
  T_MeanBin_31_33_Ndays_on10 T_MeanBin_sup33_Ndays_on10
1 0                          0
2 0                          0
  T_MinBin_17_19_Ndays_on30 T_MinBin_15_17_Ndays_on30 T_MinBin_19_21_Ndays_on30
1 0                         0                         0
2 0                         0                         0
  T_MinBin_21_23_Ndays_on30 T_MinBin_inf11_Ndays_on30 T_MinBin_11_13_Ndays_on30
1 0                         0                         0
2 0                         0                         0
  T_MinBin_13_15_Ndays_on30 T_MinBin_23_25_Ndays_on30 T_MinBin_sup25_Ndays_on30
1 0                         4                         26
2 0                         4                         26
  T_MinBin_17_19_Ndays_on20 T_MinBin_15_17_Ndays_on20 T_MinBin_19_21_Ndays_on20
1 0                         0                         0
2 0                         0                         0
  T_MinBin_21_23_Ndays_on20 T_MinBin_inf11_Ndays_on20 T_MinBin_11_13_Ndays_on20
1 0                         0                         0
2 0                         0                         0
  T_MinBin_13_15_Ndays_on20 T_MinBin_23_25_Ndays_on20 T_MinBin_sup25_Ndays_on20
1 0                         3                         17
2 0                         3                         17
  T_MinBin_17_19_Ndays_on10 T_MinBin_15_17_Ndays_on10 T_MinBin_19_21_Ndays_on10
1 0                         0                         0
2 0                         0                         0
  T_MinBin_21_23_Ndays_on10 T_MinBin_inf11_Ndays_on10 T_MinBin_11_13_Ndays_on10
1 0                         0                         0
2 0                         0                         0
  T_MinBin_13_15_Ndays_on10 T_MinBin_23_25_Ndays_on10 T_MinBin_sup25_Ndays_on10
1 0                         2                         8
2 0                         2                         8
  T_MaxBin_29_31_Ndays_on30 T_MaxBin_31_33_Ndays_on30 T_MaxBin_27_29_Ndays_on30
1 0                         0                         20
2 0                         0                         20
  T_MaxBin_25_27_Ndays_on30 T_MaxBin_23_25_Ndays_on30 T_MaxBin_inf21_Ndays_on30
1 10                        0                         0
2 10                        0                         0
  T_MaxBin_21_23_Ndays_on30 T_MaxBin_33_35_Ndays_on30 T_MaxBin_sup35_Ndays_on30
1 0                         0                         0
2 0                         0                         0
  T_MaxBin_29_31_Ndays_on20 T_MaxBin_31_33_Ndays_on20 T_MaxBin_27_29_Ndays_on20
1 0                         0                         12
2 0                         0                         12
  T_MaxBin_25_27_Ndays_on20 T_MaxBin_23_25_Ndays_on20 T_MaxBin_inf21_Ndays_on20
1 8                         0                         0
2 8                         0                         0
  T_MaxBin_21_23_Ndays_on20 T_MaxBin_33_35_Ndays_on20 T_MaxBin_sup35_Ndays_on20
1 0                         0                         0
2 0                         0                         0
  T_MaxBin_29_31_Ndays_on10 T_MaxBin_31_33_Ndays_on10 T_MaxBin_27_29_Ndays_on10
1 0                         0                         6
2 0                         0                         6
  T_MaxBin_25_27_Ndays_on10 T_MaxBin_23_25_Ndays_on10 T_MaxBin_inf21_Ndays_on10
1 4                         0                         0
2 4                         0                         0
  T_MaxBin_21_23_Ndays_on10 T_MaxBin_33_35_Ndays_on10 T_MaxBin_sup35_Ndays_on10
1 0                         0                         0
2 0                         0                         0
  WB_i30   WB_i20   WB_i10   WB_i30_bin WB_i20_bin WB_i10_bin
1 26.05833 25.96875 25.99167 (26,28]    (24,26]    (24,26]
2 26.05833 25.96875 25.99167 (26,28]    (24,26]    (24,26]
  WB_Bin_18_20_Nhours_on30 WB_Bin_20_22_Nhours_on30 WB_Bin_22_24_Nhours_on30
1 0                        0                        0
2 0                        0                        0
  WB_Bin_24_26_Nhours_on30 WB_Bin_16_18_Nhours_on30 WB_Bin_14_16_Nhours_on30
1 576                      0                        0
2 576                      0                        0
  WB_Bin_inf14_Nhours_on30 WB_Bin_26_28_Nhours_on30 WB_Bin_sup28_Nhours_on30
1 0                        144                      0
2 0                        144                      0
  WB_Bin_18_20_Nhours_on20 WB_Bin_20_22_Nhours_on20 WB_Bin_22_24_Nhours_on20
1 0                        0                        0
2 0                        0                        0
  WB_Bin_24_26_Nhours_on20 WB_Bin_16_18_Nhours_on20 WB_Bin_14_16_Nhours_on20
1 406                      0                        0
2 406                      0                        0
  WB_Bin_inf14_Nhours_on20 WB_Bin_26_28_Nhours_on20 WB_Bin_sup28_Nhours_on20
1 0                        74                       0
2 0                        74                       0
  WB_Bin_18_20_Nhours_on10 WB_Bin_20_22_Nhours_on10 WB_Bin_22_24_Nhours_on10
1 0                        0                        0
2 0                        0                        0
  WB_Bin_24_26_Nhours_on10 WB_Bin_16_18_Nhours_on10 WB_Bin_14_16_Nhours_on10
1 205                      0                        0
2 205                      0                        0
  WB_Bin_inf14_Nhours_on10 WB_Bin_26_28_Nhours_on10 WB_Bin_sup28_Nhours_on10
1 0                        35                       0
2 0                        35                       0
  WB_MeanBin_20_22_Ndays_on30 WB_MeanBin_18_20_Ndays_on30
1 0                           0
2 0                           0
  WB_MeanBin_22_24_Ndays_on30 WB_MeanBin_16_18_Ndays_on30
1 0                           0
2 0                           0
  WB_MeanBin_inf14_Ndays_on30 WB_MeanBin_14_16_Ndays_on30
1 0                           0
2 0                           0
  WB_MeanBin_24_26_Ndays_on30 WB_MeanBin_26_28_Ndays_on30
1 15                          15
2 15                          15
  WB_MeanBin_sup28_Ndays_on30 WB_MeanBin_20_22_Ndays_on20
1 0                           0
2 0                           0
  WB_MeanBin_18_20_Ndays_on20 WB_MeanBin_22_24_Ndays_on20
1 0                           0
2 0                           0
  WB_MeanBin_16_18_Ndays_on20 WB_MeanBin_inf14_Ndays_on20
1 0                           0
2 0                           0
  WB_MeanBin_14_16_Ndays_on20 WB_MeanBin_24_26_Ndays_on20
1 0                           13
2 0                           13
  WB_MeanBin_26_28_Ndays_on20 WB_MeanBin_sup28_Ndays_on20
1 7                           0
2 7                           0
  WB_MeanBin_20_22_Ndays_on10 WB_MeanBin_18_20_Ndays_on10
1 0                           0
2 0                           0
  WB_MeanBin_22_24_Ndays_on10 WB_MeanBin_16_18_Ndays_on10
1 0                           0
2 0                           0
  WB_MeanBin_inf14_Ndays_on10 WB_MeanBin_14_16_Ndays_on10
1 0                           0
2 0                           0
  WB_MeanBin_24_26_Ndays_on10 WB_MeanBin_26_28_Ndays_on10
1 7                           3
2 7                           3
  WB_MeanBin_sup28_Ndays_on10 WB_MinBin_18_20_Ndays_on30
1 0                           0
2 0                           0
  WB_MinBin_16_18_Ndays_on30 WB_MinBin_14_16_Ndays_on30
1 0                          0
2 0                          0
  WB_MinBin_12_14_Ndays_on30 WB_MinBin_10_12_Ndays_on30
1 0                          0
2 0                          0
  WB_MinBin_inf10_Ndays_on30 WB_MinBin_20_22_Ndays_on30
1 0                          0
2 0                          0
  WB_MinBin_22_24_Ndays_on30 WB_MinBin_sup24_Ndays_on30
1 0                          30
2 0                          30
  WB_MinBin_18_20_Ndays_on20 WB_MinBin_16_18_Ndays_on20
1 0                          0
2 0                          0
  WB_MinBin_14_16_Ndays_on20 WB_MinBin_12_14_Ndays_on20
1 0                          0
2 0                          0
  WB_MinBin_10_12_Ndays_on20 WB_MinBin_inf10_Ndays_on20
1 0                          0
2 0                          0
  WB_MinBin_20_22_Ndays_on20 WB_MinBin_22_24_Ndays_on20
1 0                          0
2 0                          0
  WB_MinBin_sup24_Ndays_on20 WB_MinBin_18_20_Ndays_on10
1 20                         0
2 20                         0
  WB_MinBin_16_18_Ndays_on10 WB_MinBin_14_16_Ndays_on10
1 0                          0
2 0                          0
  WB_MinBin_12_14_Ndays_on10 WB_MinBin_10_12_Ndays_on10
1 0                          0
2 0                          0
  WB_MinBin_inf10_Ndays_on10 WB_MinBin_20_22_Ndays_on10
1 0                          0
2 0                          0
  WB_MinBin_22_24_Ndays_on10 WB_MinBin_sup24_Ndays_on10
1 0                          10
2 0                          10
  WB_MaxBin_24_26_Ndays_on30 WB_MaxBin_22_24_Ndays_on30
1 12                         0
2 12                         0
  WB_MaxBin_26_28_Ndays_on30 WB_MaxBin_inf18_Ndays_on30
1 18                         0
2 18                         0
  WB_MaxBin_18_20_Ndays_on30 WB_MaxBin_20_22_Ndays_on30
1 0                          0
2 0                          0
  WB_MaxBin_28_30_Ndays_on30 WB_MaxBin_30_32_Ndays_on30
1 0                          0
2 0                          0
  WB_MaxBin_sup32_Ndays_on30 WB_MaxBin_24_26_Ndays_on20
1 0                          10
2 0                          10
  WB_MaxBin_22_24_Ndays_on20 WB_MaxBin_26_28_Ndays_on20
1 0                          10
2 0                          10
  WB_MaxBin_inf18_Ndays_on20 WB_MaxBin_18_20_Ndays_on20
1 0                          0
2 0                          0
  WB_MaxBin_20_22_Ndays_on20 WB_MaxBin_28_30_Ndays_on20
1 0                          0
2 0                          0
  WB_MaxBin_30_32_Ndays_on20 WB_MaxBin_sup32_Ndays_on20
1 0                          0
2 0                          0
  WB_MaxBin_24_26_Ndays_on10 WB_MaxBin_22_24_Ndays_on10
1 5                          0
2 5                          0
  WB_MaxBin_26_28_Ndays_on10 WB_MaxBin_inf18_Ndays_on10
1 5                          0
2 5                          0
  WB_MaxBin_18_20_Ndays_on10 WB_MaxBin_20_22_Ndays_on10
1 0                          0
2 0                          0
  WB_MaxBin_28_30_Ndays_on10 WB_MaxBin_30_32_Ndays_on10
1 0                          0
2 0                          0
  WB_MaxBin_sup32_Ndays_on10 P_tot_30  P_tot_20  P_tot_10   API_sup_1
1 0                          0.2628756 0.1457701 0.08272409 0
2 0                          0.2628756 0.1457701 0.08272409 0
  Underweight Normal Overweight Obese
1 0           1      0          0
2 0           1      0          0

In [28]:
df_women_dum %>% 
    filter(!is.na(Blood_hemo_level_alti))%>%
    mutate(#Hemoglobin
           Women_anemia =  Women_anemia/1000,
           Women_severe_anemia = Women_severe_anemia/1000,
           Women_moderate_anemia = Women_moderate_anemia/1000,
           Women_mild_anemia = Women_mild_anemia/1000)%>%
    select(#Hemoglobin
           Blood_hemo_level_alti,Women_anemia,Women_severe_anemia,Women_moderate_anemia,Women_mild_anemia,
           #Malnutrition
           Body_mass_index,Underweight,Normal,Overweight,Obese,
           #Blood
           Blood_pressure_systo,Blood_pressure_diasto,Blood_glucose_level,
           #Individual controls
           Current_age,Currently_pregnant,
           N_year_educ,
           Ethni_SC,Ethni_ST,Ethni_OBC,Ethni_other,
           Religion_hindu, Religion_muslim, Religion_not_hindu_nor_muslim,
           Smoker,Health_insurance,
           #Diet
           Diet_milk_curd_daily,Diet_pulses_beans_daily,Diet_green_veg_daily,
           Diet_fruits_daily,Diet_eggs_daily,Diet_fish_daily,Diet_chicken_meat_daily,Diet_fried_food_daily,
           Diet_aerated_drinks_daily,
           #Bednet
           Bednet_slept,
           #HH controls
           Wealth_lowest,Wealth_second,Wealth_middle,Wealth_fourth,Wealth_highest,
           HH_air_conditioner,
           Urban,
           #Water
           HH_time_water_source,
           Water_fetching_risk,
           #Malaria
           API_sup_1
          )%>%
    stargazer(nobs=TRUE, digits = 2,
              summary.stat = c("n","mean", "sd","min","p25","median","p75","max"),
              title = c("Summary statistics"),
              covariate.labels = c(#Hemoglobin
                                   "Hemoglobin level (g/L)",
                                   "Anemia (hemo <130)",
                                   "Severe anemia (hemo <80)",
                                   "Moderate anemia (80<hemo<110)",
                                   "Mild anemia (110<hemo<130)",
                                   #Acute malnutrition
                                   "Body Mass Index (BMI)",
                                   "BMI underweight (BMI<18.5)",
                                   "BMI normal (18.5<BMI<25)",
                                   "BMI overweight (25<BMI<30)",
                                   "BMI obese (BMI>30)",
                                   #Other blood measures
                                   "Blood pressure systolic (mmHG)",
                                   "Blood pressure diastolic (mmHG)",
                                   "Blood glucose level (mg/dL)",
                                   #Individual controls
                                   "Age in years",
                                   "Currently pregnant",
                                   "N years education",
                                   "Ethnicity scheduled caste (SC)",
                                   "Ethnicity scheduled tribe (ST)",
                                   "Ethnicity other backward caste (OBC)",
                                   "Ethnicity other",
                                   "Religion hindu",
                                   "Religion muslim",
                                   "Religion not hindu nor muslim",
                                   "Smoker",
                                   "Covered by health insurance",                                   
                                   #Diets
                                   "Daily diet (past 30 days): milk, curd",
                                   "Daily diet (past 30 days): beans",
                                   "Daily diet (past 30 days): green vegetables", 
                                   "Daily diet (past 30 days): fruits",
                                   "Daily diet (past 30 days): eggs",
                                   "Daily diet (past 30 days): chicken, meat",
                                   "Daily diet (past 30 days): fish",
                                   "Daily diet (past 30 days): fried food",
                                   "Daily diet (past 30 days): aerated drinks",
                                   #Bednet and malaria
                                   "Slept under any bednet",                               
                                   #HH controls
                                   "Wealth 1st quintile (poorest)",
                                   "Wealth 2nd quintile",
                                   "Wealth 3rd quintile",
                                   "Wealth 4th quintile",
                                   "Wealth 5th quintile (richest)",
                                   "Air conditioner",
                                   "Urban",
                                   #Water
                                   "Time to water source (minutes)",
                                   "Water fetching risk",
                                   #Malaria
                                   "API > 1"
                                   ),
              type="latex"
             )

% Table created by stargazer v.5.2.3 by Marek Hlavac, Social Policy Institute. E-mail: marek.hlavac at gmail.com
% Date and time: jeu., avril 16, 2026 - 18:02:51
\begin{table}[!htbp] \centering
  \caption{Summary statistics}
  \label{}
\begin{tabular}{@{\extracolsep{5pt}}lcccccccc}
\\[-1.8ex]\hline
\hline \\[-1.8ex]
Statistic & \multicolumn{1}{c}{N} & \multicolumn{1}{c}{Mean} & \multicolumn{1}{c}{St. Dev.} & \multicolumn{1}{c}{Min} & \multicolumn{1}{c}{Pctl(25)} & \multicolumn{1}{c}{Median} & \multicolumn{1}{c}{Pctl(75)} & \multicolumn{1}{c}{Max} \\
\hline \\[-1.8ex]
Hemoglobin level (g/L) & 913,595 & 116.30 & 16.49 & 3 & 107 & 118 & 127 & 254 \\
Anemia (hemo <130) & 913,595 & 0.53 & 0.50 & 0 & 0 & 1 & 1 & 1 \\
Severe anemia (hemo <80) & 913,595 & 0.02 & 0.16 & 0 & 0 & 0 & 0 & 1 \\
Moderate anemia (80<hemo<110) & 913,595 & 0.26 & 0.44 & 0 & 0 & 0 & 1 & 1 \\
Mild anemia (110<hemo<130) & 913,595 & 0.24 & 0.43 & 0 & 0 & 0 & 0 & 1 \\
Body Mass Index (BMI) & 872,524 & 21.87 & 4.22 & 12.01 & 18.89 & 21.24 & 24.07 & 59.99 \\
BMI underweight (BMI<18.5) & 913,595 & 0.20 & 0.40 & 0 & 0 & 0 & 0 & 1 \\
BMI normal (18.5<BMI<25) & 913,595 & 0.57 & 0.50 & 0 & 0 & 1 & 1 & 1 \\
BMI overweight (25<BMI<30) & 913,595 & 0.14 & 0.35 & 0 & 0 & 0 & 0 & 1 \\
BMI obese (BMI>30) & 913,595 & 0.04 & 0.20 & 0 & 0 & 0 & 0 & 1 \\
Blood pressure systolic (mmHG) & 912,433 & 117.54 & 15.22 & 0 & 108 & 116 & 126 & 298 \\
Blood pressure diastolic (mmHG) & 912,418 & 78.83 & 11.07 & 0 & 72 & 78 & 85 & 297 \\
Blood glucose level (mg/dL) & 913,419 & 107.02 & 28.80 & 20 & 91 & 102 & 117 & 499 \\
Age in years & 913,595 & 30.29 & 9.84 & 15 & 22 & 30 & 38 & 49 \\
Currently pregnant & 913,595 & 0.04 & 0.20 & 0 & 0 & 0 & 0 & 1 \\
N years education & 913,595 & 6.91 & 5.14 & 0 & 0 & 8 & 10 & 20 \\
Ethnicity scheduled caste (SC) & 913,595 & 0.19 & 0.39 & 0 & 0 & 0 & 0 & 1 \\
Ethnicity scheduled tribe (ST) & 913,595 & 0.21 & 0.40 & 0 & 0 & 0 & 0 & 1 \\
Ethnicity other backward caste (OBC) & 913,595 & 0.40 & 0.49 & 0 & 0 & 0 & 1 & 1 \\
Ethnicity other & 913,595 & 0.21 & 0.41 & 0 & 0 & 0 & 0 & 1 \\
Religion hindu & 913,595 & 0.75 & 0.43 & 0 & 0 & 1 & 1 & 1 \\
Religion muslim & 913,595 & 0.12 & 0.32 & 0 & 0 & 0 & 0 & 1 \\
Religion not hindu nor muslim & 913,595 & 0.14 & 0.34 & 0 & 0 & 0 & 0 & 1 \\
Smoker & 913,595 & 0.10 & 0.30 & 0 & 0 & 0 & 0 & 1 \\
Covered by health insurance & 913,595 & 0.23 & 0.42 & 0 & 0 & 0 & 0 & 1 \\
Daily diet (past 30 days): milk, curd & 913,595 & 0.42 & 0.49 & 0 & 0 & 0 & 1 & 1 \\
Daily diet (past 30 days): beans & 913,595 & 0.45 & 0.50 & 0 & 0 & 0 & 1 & 1 \\
Daily diet (past 30 days): green vegetables & 913,595 & 0.49 & 0.50 & 0 & 0 & 0 & 1 & 1 \\
Daily diet (past 30 days): fruits & 913,595 & 0.11 & 0.32 & 0 & 0 & 0 & 0 & 1 \\
Daily diet (past 30 days): eggs & 913,595 & 0.04 & 0.20 & 0 & 0 & 0 & 0 & 1 \\
Daily diet (past 30 days): chicken, meat & 913,595 & 0.05 & 0.21 & 0 & 0 & 0 & 0 & 1 \\
Daily diet (past 30 days): fish & 913,595 & 0.01 & 0.12 & 0 & 0 & 0 & 0 & 1 \\
Daily diet (past 30 days): fried food & 913,595 & 0.12 & 0.32 & 0 & 0 & 0 & 0 & 1 \\
Daily diet (past 30 days): aerated drinks & 913,595 & 0.04 & 0.20 & 0 & 0 & 0 & 0 & 1 \\
Slept under any bednet & 913,595 & 0.28 & 0.45 & 0 & 0 & 0 & 1 & 1 \\
Wealth 1st quintile (poorest) & 913,595 & 0.19 & 0.40 & 0 & 0 & 0 & 0 & 1 \\
Wealth 2nd quintile & 913,595 & 0.22 & 0.41 & 0 & 0 & 0 & 0 & 1 \\
Wealth 3rd quintile & 913,595 & 0.22 & 0.41 & 0 & 0 & 0 & 0 & 1 \\
Wealth 4th quintile & 913,595 & 0.20 & 0.40 & 0 & 0 & 0 & 0 & 1 \\
Wealth 5th quintile (richest) & 913,595 & 0.17 & 0.37 & 0 & 0 & 0 & 0 & 1 \\
Air conditioner & 913,595 & 0.18 & 0.38 & 0 & 0 & 0 & 0 & 1 \\
Urban & 913,595 & 0.27 & 0.45 & 0 & 0 & 0 & 1 & 1 \\
Time to water source (minutes) & 912,564 & 5.34 & 13.68 & 0 & 0 & 0 & 5 & 900 \\
Water fetching risk & 912,564 & 0.31 & 0.46 & 0 & 0 & 0 & 1 & 1 \\
API > 1 & 902,502 & 0.08 & 0.27 & 0 & 0 & 0 & 0 & 1 \\
\hline \\[-1.8ex]
\end{tabular}
\end{table}