In [1]:
list.of.packages <- c("tidyverse","fixest","data.table")
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages, repos = "http://cran.us.r-project.org")

invisible(lapply(list.of.packages, library, character.only = TRUE))

options(repr.matrix.max.rows=500, repr.matrix.max.cols=500)

── Attaching core tidyverse packages ────────────────────────────────────────────────────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.2.0     ✔ readr     2.2.0
✔ forcats   1.0.1     ✔ stringr   1.6.0
✔ ggplot2   4.0.2     ✔ tibble    3.3.1
✔ lubridate 1.9.5     ✔ tidyr     1.3.2
✔ purrr     1.2.1
── Conflicts ──────────────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

Attachement du package : ‘data.table’


Les objets suivants sont masqués depuis ‘package:lubridate’:

    hour, isoweek, mday, minute, month, quarter, second, wday, week,
    yday, year


Les objets suivants sont masqués depuis ‘package:dplyr’:

    between, first, last


L'objet suivant est masqué depuis ‘package:purrr’:

    transpose

In [2]:
T_bins_labels <- c("<=17°C","17,21]","21,23]","23,25]","25,27]","27,29]","29,31]","31,33]",">33°C")
T_bins_labels_pretty <- c("≤17°C", "(17,21]", "(21,23]", "(23,25]", "(25,27]", "(27,29]", "(29,31]", "(31,33]", ">33°C")

bin_ref_T <-"17,21]"

In [3]:
varT <- "T_i30_bin"

dict <- setNames(paste0("T: ",T_bins_labels_pretty), paste0(varT, "::", T_bins_labels))

# Children

In [4]:
df_children <- fread("./2_Regression_datasets/output/df_reg_children.csv")
sprintf("%i rows x %i columns", nrow(df_children), ncol(df_children))
head(df_children,2)

[1] "281812 rows x 321 columns"

  DHS_round DHSCLUST State_2011               District_2011 cell_x_01 cell_y_01
1 2015      10001    Andaman & Nicobar Island South Andaman 92.7      11.7
2 2015      10001    Andaman & Nicobar Island South Andaman 92.7      11.7
  cell_x_025 cell_y_025 HH_ID Mother_id      Child_id Resp_nb Interview_month
1 92.75      11.75      10    01000110    02 1        2       7
2 92.75      11.75      23    01000123    02 1        2       7
  Interview_year Measured_date_CDC Measured_date Measured_day Measured_month
1 2015           42203             2015-07-20    20           7
2 2015           42203             2015-07-20    20           7
  Measured_year Birth_month Birth_year Child_female Child_birth_order
1 2015          6           2011       1            1
2 2015          2           2013       1            1
  Child_alive_age_month Child_hemo_level_alti Child_weight_for_height_zscore
1 49                    112                    0.16
2 29                    118                   -1.10
  Child_diarrhea Child_fever Child_cough Child_still_breastfeeding
1 0              0           1           0
2 0              0           0           0
  Child_given_plain_water Child_given_juice Child_given_milk
1 NA                      NA                NA
2 NA                      NA                NA
  Child_given_baby_formula Child_given_fortified_baby_food Child_given_soup
1 NA                       NA                              NA
2 NA                       NA                              NA
  Child_given_other_liquid Child_given_chicken_duck_birds
1 NA                       NA
2 NA                       NA
  Child_given_bread_noodles_grains Child_given_potatoes_cassava_tubers
1 NA                               NA
2 NA                               NA
  Child_given_eggs Child_given_pumkins_carrots_squash
1 NA               NA
2 NA               NA
  Child_given_green_vegetables Child_given_mangoes_papaya_vitaminAfruits
1 NA                           NA
2 NA                           NA
  Child_given_other_fruits Child_given_liver_heart_organs
1 NA                       NA
2 NA                       NA
  Child_given_fish_sellfish Child_given_beans_peas_lentils_nuts
1 NA                        NA
2 NA                        NA
  Child_given_cheese_yogurt_milk_products
1 NA
2 NA
  Child_given_other_solid_semisolid_food Child_given_other_meat
1 NA                                     NA
2 NA                                     NA
  Child_given_yogurt Child_iron_supplem_7d Mother_no_educ Mother_prim_educ
1 NA                 1                     0              0
2 NA                 0                     0              0
  Mother_second_educ Mother_higher_educ Mother_hindu Mother_muslim
1 1                  0                  1            0
2 0                  1                  1            0
  Mother_not_hindu_nor_muslim Mother_ethni_SC Mother_ethni_ST Mother_ethni_OBC
1 0                            0               0               0
2 0                           NA              NA              NA
  Mother_ethni_other Mother_height Wealth_lowest Wealth_second Wealth_middle
1  1                 1599          0             0             0
2 NA                 1537          0             0             0
  Wealth_fourth Wealth_highest Urban Usual_resident Bednet_slept
1 1             0              1     1              0
2 1             0              1     1              0
  HH_time_water_source HH_air_conditioner HH_treat_water HH_no_toilet
1 0                    0                  1              0
2 0                    0                  1              0
  HH_well_water Interview_cdc Wasted Age_rounded Children_anemia
1 0             NA            0      54          0
2 0             NA            0      30          0
  Child_severe_anemia Child_moderate_anemia Child_mild_anemia Child_no_anemia
1 0                   0                     0                 1000
2 0                   0                     0                 1000
  Season Water_fetching_risk District_ID                            T_i30
1 Kharif 0                   Andaman & Nicobar Island_South Andaman 26.97639
2 Kharif 0                   Andaman & Nicobar Island_South Andaman 26.97639
  T_i20    T_i10   T_i30_bin T_i20_bin T_i10_bin T_Bin_17_21_Nhours_on30
1 26.97292 26.7875 (25,27]   (25,27]   (25,27]   0
2 26.97292 26.7875 (25,27]   (25,27]   (25,27]   0
  T_Bin_21_23_Nhours_on30 T_Bin_23_25_Nhours_on30 T_Bin_25_27_Nhours_on30
1 0                       4                       534
2 0                       4                       534
  T_Bin_27_29_Nhours_on30 T_Bin_29_31_Nhours_on30 T_Bin_inf17_Nhours_on30
1 182                     0                       0
2 182                     0                       0
  T_Bin_31_33_Nhours_on30 T_Bin_sup33_Nhours_on30 T_Bin_17_21_Nhours_on20
1 0                       0                       0
2 0                       0                       0
  T_Bin_21_23_Nhours_on20 T_Bin_23_25_Nhours_on20 T_Bin_25_27_Nhours_on20
1 0                       4                       354
2 0                       4                       354
  T_Bin_27_29_Nhours_on20 T_Bin_29_31_Nhours_on20 T_Bin_inf17_Nhours_on20
1 122                     0                       0
2 122                     0                       0
  T_Bin_31_33_Nhours_on20 T_Bin_sup33_Nhours_on20 T_Bin_17_21_Nhours_on10
1 0                       0                       0
2 0                       0                       0
  T_Bin_21_23_Nhours_on10 T_Bin_23_25_Nhours_on10 T_Bin_25_27_Nhours_on10
1 0                       3                       205
2 0                       3                       205
  T_Bin_27_29_Nhours_on10 T_Bin_29_31_Nhours_on10 T_Bin_inf17_Nhours_on10
1 32                      0                       0
2 32                      0                       0
  T_Bin_31_33_Nhours_on10 T_Bin_sup33_Nhours_on10 T_MeanBin_23_25_Ndays_on30
1 0                       0                       0
2 0                       0                       0
  T_MeanBin_21_23_Ndays_on30 T_MeanBin_25_27_Ndays_on30
1 0                          16
2 0                          16
  T_MeanBin_inf17_Ndays_on30 T_MeanBin_17_21_Ndays_on30
1 0                          0
2 0                          0
  T_MeanBin_27_29_Ndays_on30 T_MeanBin_29_31_Ndays_on30
1 14                         0
2 14                         0
  T_MeanBin_31_33_Ndays_on30 T_MeanBin_sup33_Ndays_on30
1 0                          0
2 0                          0
  T_MeanBin_23_25_Ndays_on20 T_MeanBin_21_23_Ndays_on20
1 0                          0
2 0                          0
  T_MeanBin_25_27_Ndays_on20 T_MeanBin_inf17_Ndays_on20
1 12                         0
2 12                         0
  T_MeanBin_17_21_Ndays_on20 T_MeanBin_27_29_Ndays_on20
1 0                          8
2 0                          8
  T_MeanBin_29_31_Ndays_on20 T_MeanBin_31_33_Ndays_on20
1 0                          0
2 0                          0
  T_MeanBin_sup33_Ndays_on20 T_MeanBin_23_25_Ndays_on10
1 0                          0
2 0                          0
  T_MeanBin_21_23_Ndays_on10 T_MeanBin_25_27_Ndays_on10
1 0                          8
2 0                          8
  T_MeanBin_inf17_Ndays_on10 T_MeanBin_17_21_Ndays_on10
1 0                          0
2 0                          0
  T_MeanBin_27_29_Ndays_on10 T_MeanBin_29_31_Ndays_on10
1 2                          0
2 2                          0
  T_MeanBin_31_33_Ndays_on10 T_MeanBin_sup33_Ndays_on10
1 0                          0
2 0                          0
  T_MinBin_17_19_Ndays_on30 T_MinBin_15_17_Ndays_on30 T_MinBin_19_21_Ndays_on30
1 0                         0                         0
2 0                         0                         0
  T_MinBin_21_23_Ndays_on30 T_MinBin_inf11_Ndays_on30 T_MinBin_11_13_Ndays_on30
1 0                         0                         0
2 0                         0                         0
  T_MinBin_13_15_Ndays_on30 T_MinBin_23_25_Ndays_on30 T_MinBin_sup25_Ndays_on30
1 0                         3                         27
2 0                         3                         27
  T_MinBin_17_19_Ndays_on20 T_MinBin_15_17_Ndays_on20 T_MinBin_19_21_Ndays_on20
1 0                         0                         0
2 0                         0                         0
  T_MinBin_21_23_Ndays_on20 T_MinBin_inf11_Ndays_on20 T_MinBin_11_13_Ndays_on20
1 0                         0                         0
2 0                         0                         0
  T_MinBin_13_15_Ndays_on20 T_MinBin_23_25_Ndays_on20 T_MinBin_sup25_Ndays_on20
1 0                         3                         17
2 0                         3                         17
  T_MinBin_17_19_Ndays_on10 T_MinBin_15_17_Ndays_on10 T_MinBin_19_21_Ndays_on10
1 0                         0                         0
2 0                         0                         0
  T_MinBin_21_23_Ndays_on10 T_MinBin_inf11_Ndays_on10 T_MinBin_11_13_Ndays_on10
1 0                         0                         0
2 0                         0                         0
  T_MinBin_13_15_Ndays_on10 T_MinBin_23_25_Ndays_on10 T_MinBin_sup25_Ndays_on10
1 0                         2                         8
2 0                         2                         8
  T_MaxBin_29_31_Ndays_on30 T_MaxBin_31_33_Ndays_on30 T_MaxBin_27_29_Ndays_on30
1 0                         0                         20
2 0                         0                         20
  T_MaxBin_25_27_Ndays_on30 T_MaxBin_23_25_Ndays_on30 T_MaxBin_inf21_Ndays_on30
1 10                        0                         0
2 10                        0                         0
  T_MaxBin_21_23_Ndays_on30 T_MaxBin_33_35_Ndays_on30 T_MaxBin_sup35_Ndays_on30
1 0                         0                         0
2 0                         0                         0
  T_MaxBin_29_31_Ndays_on20 T_MaxBin_31_33_Ndays_on20 T_MaxBin_27_29_Ndays_on20
1 0                         0                         14
2 0                         0                         14
  T_MaxBin_25_27_Ndays_on20 T_MaxBin_23_25_Ndays_on20 T_MaxBin_inf21_Ndays_on20
1 6                         0                         0
2 6                         0                         0
  T_MaxBin_21_23_Ndays_on20 T_MaxBin_33_35_Ndays_on20 T_MaxBin_sup35_Ndays_on20
1 0                         0                         0
2 0                         0                         0
  T_MaxBin_29_31_Ndays_on10 T_MaxBin_31_33_Ndays_on10 T_MaxBin_27_29_Ndays_on10
1 0                         0                         6
2 0                         0                         6
  T_MaxBin_25_27_Ndays_on10 T_MaxBin_23_25_Ndays_on10 T_MaxBin_inf21_Ndays_on10
1 4                         0                         0
2 4                         0                         0
  T_MaxBin_21_23_Ndays_on10 T_MaxBin_33_35_Ndays_on10 T_MaxBin_sup35_Ndays_on10
1 0                         0                         0
2 0                         0                         0
  WB_i30   WB_i20   WB_i10 WB_i30_bin WB_i20_bin WB_i10_bin
1 26.08194 26.04792 25.95  (26,28]    (26,28]    (24,26]
2 26.08194 26.04792 25.95  (26,28]    (26,28]    (24,26]
  WB_Bin_18_20_Nhours_on30 WB_Bin_20_22_Nhours_on30 WB_Bin_22_24_Nhours_on30
1 0                        0                        0
2 0                        0                        0
  WB_Bin_24_26_Nhours_on30 WB_Bin_16_18_Nhours_on30 WB_Bin_14_16_Nhours_on30
1 564                      0                        0
2 564                      0                        0
  WB_Bin_inf14_Nhours_on30 WB_Bin_26_28_Nhours_on30 WB_Bin_sup28_Nhours_on30
1 0                        156                      0
2 0                        156                      0
  WB_Bin_18_20_Nhours_on20 WB_Bin_20_22_Nhours_on20 WB_Bin_22_24_Nhours_on20
1 0                        0                        0
2 0                        0                        0
  WB_Bin_24_26_Nhours_on20 WB_Bin_16_18_Nhours_on20 WB_Bin_14_16_Nhours_on20
1 390                      0                        0
2 390                      0                        0
  WB_Bin_inf14_Nhours_on20 WB_Bin_26_28_Nhours_on20 WB_Bin_sup28_Nhours_on20
1 0                        90                       0
2 0                        90                       0
  WB_Bin_18_20_Nhours_on10 WB_Bin_20_22_Nhours_on10 WB_Bin_22_24_Nhours_on10
1 0                        0                        0
2 0                        0                        0
  WB_Bin_24_26_Nhours_on10 WB_Bin_16_18_Nhours_on10 WB_Bin_14_16_Nhours_on10
1 211                      0                        0
2 211                      0                        0
  WB_Bin_inf14_Nhours_on10 WB_Bin_26_28_Nhours_on10 WB_Bin_sup28_Nhours_on10
1 0                        29                       0
2 0                        29                       0
  WB_MeanBin_20_22_Ndays_on30 WB_MeanBin_18_20_Ndays_on30
1 0                           0
2 0                           0
  WB_MeanBin_22_24_Ndays_on30 WB_MeanBin_16_18_Ndays_on30
1 0                           0
2 0                           0
  WB_MeanBin_inf14_Ndays_on30 WB_MeanBin_14_16_Ndays_on30
1 0                           0
2 0                           0
  WB_MeanBin_24_26_Ndays_on30 WB_MeanBin_26_28_Ndays_on30
1 14                          16
2 14                          16
  WB_MeanBin_sup28_Ndays_on30 WB_MeanBin_20_22_Ndays_on20
1 0                           0
2 0                           0
  WB_MeanBin_18_20_Ndays_on20 WB_MeanBin_22_24_Ndays_on20
1 0                           0
2 0                           0
  WB_MeanBin_16_18_Ndays_on20 WB_MeanBin_inf14_Ndays_on20
1 0                           0
2 0                           0
  WB_MeanBin_14_16_Ndays_on20 WB_MeanBin_24_26_Ndays_on20
1 0                           11
2 0                           11
  WB_MeanBin_26_28_Ndays_on20 WB_MeanBin_sup28_Ndays_on20
1 9                           0
2 9                           0
  WB_MeanBin_20_22_Ndays_on10 WB_MeanBin_18_20_Ndays_on10
1 0                           0
2 0                           0
  WB_MeanBin_22_24_Ndays_on10 WB_MeanBin_16_18_Ndays_on10
1 0                           0
2 0                           0
  WB_MeanBin_inf14_Ndays_on10 WB_MeanBin_14_16_Ndays_on10
1 0                           0
2 0                           0
  WB_MeanBin_24_26_Ndays_on10 WB_MeanBin_26_28_Ndays_on10
1 7                           3
2 7                           3
  WB_MeanBin_sup28_Ndays_on10 WB_MinBin_18_20_Ndays_on30
1 0                           0
2 0                           0
  WB_MinBin_16_18_Ndays_on30 WB_MinBin_14_16_Ndays_on30
1 0                          0
2 0                          0
  WB_MinBin_12_14_Ndays_on30 WB_MinBin_10_12_Ndays_on30
1 0                          0
2 0                          0
  WB_MinBin_inf10_Ndays_on30 WB_MinBin_20_22_Ndays_on30
1 0                          0
2 0                          0
  WB_MinBin_22_24_Ndays_on30 WB_MinBin_sup24_Ndays_on30
1 0                          30
2 0                          30
  WB_MinBin_18_20_Ndays_on20 WB_MinBin_16_18_Ndays_on20
1 0                          0
2 0                          0
  WB_MinBin_14_16_Ndays_on20 WB_MinBin_12_14_Ndays_on20
1 0                          0
2 0                          0
  WB_MinBin_10_12_Ndays_on20 WB_MinBin_inf10_Ndays_on20
1 0                          0
2 0                          0
  WB_MinBin_20_22_Ndays_on20 WB_MinBin_22_24_Ndays_on20
1 0                          0
2 0                          0
  WB_MinBin_sup24_Ndays_on20 WB_MinBin_18_20_Ndays_on10
1 20                         0
2 20                         0
  WB_MinBin_16_18_Ndays_on10 WB_MinBin_14_16_Ndays_on10
1 0                          0
2 0                          0
  WB_MinBin_12_14_Ndays_on10 WB_MinBin_10_12_Ndays_on10
1 0                          0
2 0                          0
  WB_MinBin_inf10_Ndays_on10 WB_MinBin_20_22_Ndays_on10
1 0                          0
2 0                          0
  WB_MinBin_22_24_Ndays_on10 WB_MinBin_sup24_Ndays_on10
1 0                          10
2 0                          10
  WB_MaxBin_24_26_Ndays_on30 WB_MaxBin_22_24_Ndays_on30
1 11                         0
2 11                         0
  WB_MaxBin_26_28_Ndays_on30 WB_MaxBin_inf18_Ndays_on30
1 19                         0
2 19                         0
  WB_MaxBin_18_20_Ndays_on30 WB_MaxBin_20_22_Ndays_on30
1 0                          0
2 0                          0
  WB_MaxBin_28_30_Ndays_on30 WB_MaxBin_30_32_Ndays_on30
1 0                          0
2 0                          0
  WB_MaxBin_sup32_Ndays_on30 WB_MaxBin_24_26_Ndays_on20
1 0                          8
2 0                          8
  WB_MaxBin_22_24_Ndays_on20 WB_MaxBin_26_28_Ndays_on20
1 0                          12
2 0                          12
  WB_MaxBin_inf18_Ndays_on20 WB_MaxBin_18_20_Ndays_on20
1 0                          0
2 0                          0
  WB_MaxBin_20_22_Ndays_on20 WB_MaxBin_28_30_Ndays_on20
1 0                          0
2 0                          0
  WB_MaxBin_30_32_Ndays_on20 WB_MaxBin_sup32_Ndays_on20
1 0                          0
2 0                          0
  WB_MaxBin_24_26_Ndays_on10 WB_MaxBin_22_24_Ndays_on10
1 5                          0
2 5                          0
  WB_MaxBin_26_28_Ndays_on10 WB_MaxBin_inf18_Ndays_on10
1 5                          0
2 5                          0
  WB_MaxBin_18_20_Ndays_on10 WB_MaxBin_20_22_Ndays_on10
1 0                          0
2 0                          0
  WB_MaxBin_28_30_Ndays_on10 WB_MaxBin_30_32_Ndays_on10
1 0                          0
2 0                          0
  WB_MaxBin_sup32_Ndays_on10 P_tot_30  P_tot_20  P_tot_10 API_sup_1
1 0                          0.2802348 0.1772218 0.117177 0
2 0                          0.2802348 0.1772218 0.117177 0

In [5]:
df_reg_children <- df_children %>%
                mutate(T_i30_bin=factor(gsub("\\(","",T_i30_bin),levels=T_bins_labels))

# Women

In [6]:
df_women <- fread("./2_Regression_datasets/output/df_reg_women.csv")
sprintf("%i rows x %i columns", nrow(df_women), ncol(df_women))
head(df_women,2)

[1] "973462 rows x 330 columns"

  DHS_round DHSCLUST State_2011               District_2011 cell_x_01 cell_y_01
1 2015      10001    Andaman & Nicobar Island South Andaman 92.7      11.7
2 2015      10001    Andaman & Nicobar Island South Andaman 92.7      11.7
  cell_x_025 cell_y_025 HH_ID Women_id       Resp_nb Interview_month
1 92.75      11.75      1     01000101    02 2       7
2 92.75      11.75      1     01000101    04 4       7
  Interview_year Interview_day Measured_date_CDC Measured_date Current_age
1 2015           18            42201             2015-07-18    46
2 2015           18            42201             2015-07-18    20
  Age_group Religion_hindu Religion_muslim Religion_not_hindu_nor_muslim
1 45-49     0              0               1
2 20-24     0              0               1
  Ethni_SC Ethni_ST Ethni_OBC Ethni_other N_year_educ Smoker Health_insurance
1 0        0        0         1            0          1      0
2 0        0        0         1           14          0      0
  Currently_pregnant Blood_hemo_level_alti Blood_pressure_systo
1 0                   81                   115
2 0                  113                    96
  Blood_pressure_diasto Blood_glucose_level Body_mass_index
1 76                    116                 22.95
2 72                     83                 22.03
  Diet_milk_curd_daily Diet_milk_curd_week Diet_milk_curd_oc
1 0                    0                   0
2 0                    0                   1
  Diet_milk_curd_never Diet_pulses_beans_daily Diet_pulses_beans_week
1 1                    1                       0
2 0                    1                       0
  Diet_pulses_beans_oc Diet_pulses_beans_never Diet_green_veg_daily
1 0                    0                       0
2 0                    0                       0
  Diet_green_veg_week Diet_green_veg_oc Diet_green_veg_never Diet_fruits_daily
1 1                   0                 0                    0
2 1                   0                 0                    0
  Diet_fruits_week Diet_fruits_oc Diet_fruits_never Diet_eggs_daily
1 1                0              0                 0
2 0                1              0                 0
  Diet_eggs_week Diet_eggs_oc Diet_eggs_never Diet_fish_daily Diet_fish_week
1 1              0            0               0               1
2 1              0            0               0               1
  Diet_fish_oc Diet_fish_never Diet_chicken_meat_daily Diet_chicken_meat_week
1 0            0               0                       0
2 0            0               0                       1
  Diet_chicken_meat_oc Diet_chicken_meat_never Diet_fried_food_daily
1 1                    0                       0
2 0                    0                       0
  Diet_fried_food_week Diet_fried_food_oc Diet_fried_food_never
1 1                    0                  0
2 1                    0                  0
  Diet_aerated_drinks_daily Diet_aerated_drinks_week Diet_aerated_drinks_oc
1 0                         1                        0
2 0                         1                        0
  Diet_aerated_drinks_never Wealth_lowest Wealth_second Wealth_middle
1 0                         0             0             1
2 0                         0             0             1
  Wealth_fourth Wealth_highest Urban Usual_resident Bednet_slept
1 0             0              1     1              0
2 0             0              1     1              0
  HH_time_water_source HH_air_conditioner HH_treat_water HH_no_toilet
1 0                    0                  0              0
2 0                    0                  0              0
  HH_well_water cell_x.x cell_y.x cell_x.y cell_y.y Measured_month
1 0             92.7     11.7     92.75    11.75    7
2 0             92.7     11.7     92.75    11.75    7
  Measured_year Women_anemia Women_severe_anemia Women_moderate_anemia
1 2015          1000         0                   1000
2 2015          1000         0                      0
  Women_mild_anemia Women_no_anemia BMI_category Blood_hypertension
1    0              0               Normal       0
2 1000              0               Normal       0
  Water_fetching_risk District_ID                            T_i30    T_i20
1 0                   Andaman & Nicobar Island_South Andaman 26.94861 26.89167
2 0                   Andaman & Nicobar Island_South Andaman 26.94861 26.89167
  T_i10    T_i30_bin T_i20_bin T_i10_bin T_Bin_17_21_Nhours_on30
1 26.92083 (25,27]   (25,27]   (25,27]   0
2 26.92083 (25,27]   (25,27]   (25,27]   0
  T_Bin_21_23_Nhours_on30 T_Bin_23_25_Nhours_on30 T_Bin_25_27_Nhours_on30
1 0                       7                       536
2 0                       7                       536
  T_Bin_27_29_Nhours_on30 T_Bin_29_31_Nhours_on30 T_Bin_inf17_Nhours_on30
1 177                     0                       0
2 177                     0                       0
  T_Bin_31_33_Nhours_on30 T_Bin_sup33_Nhours_on30 T_Bin_17_21_Nhours_on20
1 0                       0                       0
2 0                       0                       0
  T_Bin_21_23_Nhours_on20 T_Bin_23_25_Nhours_on20 T_Bin_25_27_Nhours_on20
1 0                       4                       367
2 0                       4                       367
  T_Bin_27_29_Nhours_on20 T_Bin_29_31_Nhours_on20 T_Bin_inf17_Nhours_on20
1 109                     0                       0
2 109                     0                       0
  T_Bin_31_33_Nhours_on20 T_Bin_sup33_Nhours_on20 T_Bin_17_21_Nhours_on10
1 0                       0                       0
2 0                       0                       0
  T_Bin_21_23_Nhours_on10 T_Bin_23_25_Nhours_on10 T_Bin_25_27_Nhours_on10
1 0                       3                       183
2 0                       3                       183
  T_Bin_27_29_Nhours_on10 T_Bin_29_31_Nhours_on10 T_Bin_inf17_Nhours_on10
1 54                      0                       0
2 54                      0                       0
  T_Bin_31_33_Nhours_on10 T_Bin_sup33_Nhours_on10 T_MeanBin_23_25_Ndays_on30
1 0                       0                       0
2 0                       0                       0
  T_MeanBin_21_23_Ndays_on30 T_MeanBin_25_27_Ndays_on30
1 0                          17
2 0                          17
  T_MeanBin_inf17_Ndays_on30 T_MeanBin_17_21_Ndays_on30
1 0                          0
2 0                          0
  T_MeanBin_27_29_Ndays_on30 T_MeanBin_29_31_Ndays_on30
1 13                         0
2 13                         0
  T_MeanBin_31_33_Ndays_on30 T_MeanBin_sup33_Ndays_on30
1 0                          0
2 0                          0
  T_MeanBin_23_25_Ndays_on20 T_MeanBin_21_23_Ndays_on20
1 0                          0
2 0                          0
  T_MeanBin_25_27_Ndays_on20 T_MeanBin_inf17_Ndays_on20
1 13                         0
2 13                         0
  T_MeanBin_17_21_Ndays_on20 T_MeanBin_27_29_Ndays_on20
1 0                          7
2 0                          7
  T_MeanBin_29_31_Ndays_on20 T_MeanBin_31_33_Ndays_on20
1 0                          0
2 0                          0
  T_MeanBin_sup33_Ndays_on20 T_MeanBin_23_25_Ndays_on10
1 0                          0
2 0                          0
  T_MeanBin_21_23_Ndays_on10 T_MeanBin_25_27_Ndays_on10
1 0                          7
2 0                          7
  T_MeanBin_inf17_Ndays_on10 T_MeanBin_17_21_Ndays_on10
1 0                          0
2 0                          0
  T_MeanBin_27_29_Ndays_on10 T_MeanBin_29_31_Ndays_on10
1 3                          0
2 3                          0
  T_MeanBin_31_33_Ndays_on10 T_MeanBin_sup33_Ndays_on10
1 0                          0
2 0                          0
  T_MinBin_17_19_Ndays_on30 T_MinBin_15_17_Ndays_on30 T_MinBin_19_21_Ndays_on30
1 0                         0                         0
2 0                         0                         0
  T_MinBin_21_23_Ndays_on30 T_MinBin_inf11_Ndays_on30 T_MinBin_11_13_Ndays_on30
1 0                         0                         0
2 0                         0                         0
  T_MinBin_13_15_Ndays_on30 T_MinBin_23_25_Ndays_on30 T_MinBin_sup25_Ndays_on30
1 0                         4                         26
2 0                         4                         26
  T_MinBin_17_19_Ndays_on20 T_MinBin_15_17_Ndays_on20 T_MinBin_19_21_Ndays_on20
1 0                         0                         0
2 0                         0                         0
  T_MinBin_21_23_Ndays_on20 T_MinBin_inf11_Ndays_on20 T_MinBin_11_13_Ndays_on20
1 0                         0                         0
2 0                         0                         0
  T_MinBin_13_15_Ndays_on20 T_MinBin_23_25_Ndays_on20 T_MinBin_sup25_Ndays_on20
1 0                         3                         17
2 0                         3                         17
  T_MinBin_17_19_Ndays_on10 T_MinBin_15_17_Ndays_on10 T_MinBin_19_21_Ndays_on10
1 0                         0                         0
2 0                         0                         0
  T_MinBin_21_23_Ndays_on10 T_MinBin_inf11_Ndays_on10 T_MinBin_11_13_Ndays_on10
1 0                         0                         0
2 0                         0                         0
  T_MinBin_13_15_Ndays_on10 T_MinBin_23_25_Ndays_on10 T_MinBin_sup25_Ndays_on10
1 0                         2                         8
2 0                         2                         8
  T_MaxBin_29_31_Ndays_on30 T_MaxBin_31_33_Ndays_on30 T_MaxBin_27_29_Ndays_on30
1 0                         0                         20
2 0                         0                         20
  T_MaxBin_25_27_Ndays_on30 T_MaxBin_23_25_Ndays_on30 T_MaxBin_inf21_Ndays_on30
1 10                        0                         0
2 10                        0                         0
  T_MaxBin_21_23_Ndays_on30 T_MaxBin_33_35_Ndays_on30 T_MaxBin_sup35_Ndays_on30
1 0                         0                         0
2 0                         0                         0
  T_MaxBin_29_31_Ndays_on20 T_MaxBin_31_33_Ndays_on20 T_MaxBin_27_29_Ndays_on20
1 0                         0                         12
2 0                         0                         12
  T_MaxBin_25_27_Ndays_on20 T_MaxBin_23_25_Ndays_on20 T_MaxBin_inf21_Ndays_on20
1 8                         0                         0
2 8                         0                         0
  T_MaxBin_21_23_Ndays_on20 T_MaxBin_33_35_Ndays_on20 T_MaxBin_sup35_Ndays_on20
1 0                         0                         0
2 0                         0                         0
  T_MaxBin_29_31_Ndays_on10 T_MaxBin_31_33_Ndays_on10 T_MaxBin_27_29_Ndays_on10
1 0                         0                         6
2 0                         0                         6
  T_MaxBin_25_27_Ndays_on10 T_MaxBin_23_25_Ndays_on10 T_MaxBin_inf21_Ndays_on10
1 4                         0                         0
2 4                         0                         0
  T_MaxBin_21_23_Ndays_on10 T_MaxBin_33_35_Ndays_on10 T_MaxBin_sup35_Ndays_on10
1 0                         0                         0
2 0                         0                         0
  WB_i30   WB_i20   WB_i10   WB_i30_bin WB_i20_bin WB_i10_bin
1 26.05833 25.96875 25.99167 (26,28]    (24,26]    (24,26]
2 26.05833 25.96875 25.99167 (26,28]    (24,26]    (24,26]
  WB_Bin_18_20_Nhours_on30 WB_Bin_20_22_Nhours_on30 WB_Bin_22_24_Nhours_on30
1 0                        0                        0
2 0                        0                        0
  WB_Bin_24_26_Nhours_on30 WB_Bin_16_18_Nhours_on30 WB_Bin_14_16_Nhours_on30
1 576                      0                        0
2 576                      0                        0
  WB_Bin_inf14_Nhours_on30 WB_Bin_26_28_Nhours_on30 WB_Bin_sup28_Nhours_on30
1 0                        144                      0
2 0                        144                      0
  WB_Bin_18_20_Nhours_on20 WB_Bin_20_22_Nhours_on20 WB_Bin_22_24_Nhours_on20
1 0                        0                        0
2 0                        0                        0
  WB_Bin_24_26_Nhours_on20 WB_Bin_16_18_Nhours_on20 WB_Bin_14_16_Nhours_on20
1 406                      0                        0
2 406                      0                        0
  WB_Bin_inf14_Nhours_on20 WB_Bin_26_28_Nhours_on20 WB_Bin_sup28_Nhours_on20
1 0                        74                       0
2 0                        74                       0
  WB_Bin_18_20_Nhours_on10 WB_Bin_20_22_Nhours_on10 WB_Bin_22_24_Nhours_on10
1 0                        0                        0
2 0                        0                        0
  WB_Bin_24_26_Nhours_on10 WB_Bin_16_18_Nhours_on10 WB_Bin_14_16_Nhours_on10
1 205                      0                        0
2 205                      0                        0
  WB_Bin_inf14_Nhours_on10 WB_Bin_26_28_Nhours_on10 WB_Bin_sup28_Nhours_on10
1 0                        35                       0
2 0                        35                       0
  WB_MeanBin_20_22_Ndays_on30 WB_MeanBin_18_20_Ndays_on30
1 0                           0
2 0                           0
  WB_MeanBin_22_24_Ndays_on30 WB_MeanBin_16_18_Ndays_on30
1 0                           0
2 0                           0
  WB_MeanBin_inf14_Ndays_on30 WB_MeanBin_14_16_Ndays_on30
1 0                           0
2 0                           0
  WB_MeanBin_24_26_Ndays_on30 WB_MeanBin_26_28_Ndays_on30
1 15                          15
2 15                          15
  WB_MeanBin_sup28_Ndays_on30 WB_MeanBin_20_22_Ndays_on20
1 0                           0
2 0                           0
  WB_MeanBin_18_20_Ndays_on20 WB_MeanBin_22_24_Ndays_on20
1 0                           0
2 0                           0
  WB_MeanBin_16_18_Ndays_on20 WB_MeanBin_inf14_Ndays_on20
1 0                           0
2 0                           0
  WB_MeanBin_14_16_Ndays_on20 WB_MeanBin_24_26_Ndays_on20
1 0                           13
2 0                           13
  WB_MeanBin_26_28_Ndays_on20 WB_MeanBin_sup28_Ndays_on20
1 7                           0
2 7                           0
  WB_MeanBin_20_22_Ndays_on10 WB_MeanBin_18_20_Ndays_on10
1 0                           0
2 0                           0
  WB_MeanBin_22_24_Ndays_on10 WB_MeanBin_16_18_Ndays_on10
1 0                           0
2 0                           0
  WB_MeanBin_inf14_Ndays_on10 WB_MeanBin_14_16_Ndays_on10
1 0                           0
2 0                           0
  WB_MeanBin_24_26_Ndays_on10 WB_MeanBin_26_28_Ndays_on10
1 7                           3
2 7                           3
  WB_MeanBin_sup28_Ndays_on10 WB_MinBin_18_20_Ndays_on30
1 0                           0
2 0                           0
  WB_MinBin_16_18_Ndays_on30 WB_MinBin_14_16_Ndays_on30
1 0                          0
2 0                          0
  WB_MinBin_12_14_Ndays_on30 WB_MinBin_10_12_Ndays_on30
1 0                          0
2 0                          0
  WB_MinBin_inf10_Ndays_on30 WB_MinBin_20_22_Ndays_on30
1 0                          0
2 0                          0
  WB_MinBin_22_24_Ndays_on30 WB_MinBin_sup24_Ndays_on30
1 0                          30
2 0                          30
  WB_MinBin_18_20_Ndays_on20 WB_MinBin_16_18_Ndays_on20
1 0                          0
2 0                          0
  WB_MinBin_14_16_Ndays_on20 WB_MinBin_12_14_Ndays_on20
1 0                          0
2 0                          0
  WB_MinBin_10_12_Ndays_on20 WB_MinBin_inf10_Ndays_on20
1 0                          0
2 0                          0
  WB_MinBin_20_22_Ndays_on20 WB_MinBin_22_24_Ndays_on20
1 0                          0
2 0                          0
  WB_MinBin_sup24_Ndays_on20 WB_MinBin_18_20_Ndays_on10
1 20                         0
2 20                         0
  WB_MinBin_16_18_Ndays_on10 WB_MinBin_14_16_Ndays_on10
1 0                          0
2 0                          0
  WB_MinBin_12_14_Ndays_on10 WB_MinBin_10_12_Ndays_on10
1 0                          0
2 0                          0
  WB_MinBin_inf10_Ndays_on10 WB_MinBin_20_22_Ndays_on10
1 0                          0
2 0                          0
  WB_MinBin_22_24_Ndays_on10 WB_MinBin_sup24_Ndays_on10
1 0                          10
2 0                          10
  WB_MaxBin_24_26_Ndays_on30 WB_MaxBin_22_24_Ndays_on30
1 12                         0
2 12                         0
  WB_MaxBin_26_28_Ndays_on30 WB_MaxBin_inf18_Ndays_on30
1 18                         0
2 18                         0
  WB_MaxBin_18_20_Ndays_on30 WB_MaxBin_20_22_Ndays_on30
1 0                          0
2 0                          0
  WB_MaxBin_28_30_Ndays_on30 WB_MaxBin_30_32_Ndays_on30
1 0                          0
2 0                          0
  WB_MaxBin_sup32_Ndays_on30 WB_MaxBin_24_26_Ndays_on20
1 0                          10
2 0                          10
  WB_MaxBin_22_24_Ndays_on20 WB_MaxBin_26_28_Ndays_on20
1 0                          10
2 0                          10
  WB_MaxBin_inf18_Ndays_on20 WB_MaxBin_18_20_Ndays_on20
1 0                          0
2 0                          0
  WB_MaxBin_20_22_Ndays_on20 WB_MaxBin_28_30_Ndays_on20
1 0                          0
2 0                          0
  WB_MaxBin_30_32_Ndays_on20 WB_MaxBin_sup32_Ndays_on20
1 0                          0
2 0                          0
  WB_MaxBin_24_26_Ndays_on10 WB_MaxBin_22_24_Ndays_on10
1 5                          0
2 5                          0
  WB_MaxBin_26_28_Ndays_on10 WB_MaxBin_inf18_Ndays_on10
1 5                          0
2 5                          0
  WB_MaxBin_18_20_Ndays_on10 WB_MaxBin_20_22_Ndays_on10
1 0                          0
2 0                          0
  WB_MaxBin_28_30_Ndays_on10 WB_MaxBin_30_32_Ndays_on10
1 0                          0
2 0                          0
  WB_MaxBin_sup32_Ndays_on10 P_tot_30  P_tot_20  P_tot_10   API_sup_1
1 0                          0.2628756 0.1457701 0.08272409 0
2 0                          0.2628756 0.1457701 0.08272409 0

In [7]:
df_reg_women <- df_women %>%
                mutate(T_i30_bin=factor(gsub("\\(","",T_i30_bin),levels=T_bins_labels))

# Men

In [8]:
df_men <- fread("./2_Regression_datasets/output/df_reg_men.csv")
sprintf("%i rows x %i columns", nrow(df_men), ncol(df_men))
head(df_men,2)

[1] "150101 rows x 330 columns"

  DHS_round DHSCLUST State_2011               District_2011 cell_x_01 cell_y_01
1 2015      10001    Andaman & Nicobar Island South Andaman 92.7      11.7
2 2015      10001    Andaman & Nicobar Island South Andaman 92.7      11.7
  cell_x_025 cell_y_025 HH_ID Men_id         Resp_nb Interview_month
1 92.75      11.75      17    01000117     1 1       7
2 92.75      11.75      20    01000120     2 2       7
  Interview_year Interview_day Measured_date_CDC Measured_date Current_age
1 2015           21            42204             2015-07-21    28
2 2015           19            42202             2015-07-19    16
  Age_group Religion_hindu Religion_muslim Religion_not_hindu_nor_muslim
1 25-29     1              0               0
2 15-19     1              0               0
  Ethni_SC Ethni_ST Ethni_OBC Ethni_other N_year_educ Smoker Health_insurance
1 0        0        0         1           10          1      0
2 0        0        0         1           10          0      0
  Profession Blood_pressure_systo Blood_pressure_diasto Blood_glucose_level
1 manual     137                  99                    185
2 no_work    117                  69                    109
  Diet_milk_curd_daily Diet_milk_curd_week Diet_milk_curd_oc
1 0                    1                   0
2 0                    1                   0
  Diet_milk_curd_never Diet_pulses_beans_daily Diet_pulses_beans_week
1 0                    0                       1
2 0                    0                       1
  Diet_pulses_beans_oc Diet_pulses_beans_never Diet_green_veg_daily
1 0                    0                       0
2 0                    0                       0
  Diet_green_veg_week Diet_green_veg_oc Diet_green_veg_never Diet_fruits_daily
1 1                   0                 0                    0
2 1                   0                 0                    0
  Diet_fruits_week Diet_fruits_oc Diet_fruits_never Diet_eggs_daily
1 1                0              0                 0
2 1                0              0                 0
  Diet_eggs_week Diet_eggs_oc Diet_eggs_never Diet_fish_daily Diet_fish_week
1 1              0            0               0               1
2 1              0            0               0               1
  Diet_fish_oc Diet_fish_never Diet_chicken_meat_daily Diet_chicken_meat_week
1 0            0               0                       1
2 0            0               0                       1
  Diet_chicken_meat_oc Diet_chicken_meat_never Diet_fried_food_daily
1 0                    0                       0
2 0                    0                       0
  Diet_fried_food_week Diet_fried_food_oc Diet_fried_food_never
1 1                    0                  0
2 1                    0                  0
  Diet_aerated_drinks_daily Diet_aerated_drinks_week Diet_aerated_drinks_oc
1 0                         0                        1
2 0                         0                        1
  Diet_aerated_drinks_never Wealth_lowest Wealth_second Wealth_middle
1 0                         0             0             1
2 0                         0             0             0
  Wealth_fourth Wealth_highest Urban Usual_resident Blood_hemo_level_alti
1 0             0              1     1              162
2 1             0              1     1              150
  Body_mass_index Bednet_slept HH_time_water_source HH_air_conditioner
1 24.16           1            0                    0
2 21.48           1            0                    0
  HH_treat_water HH_no_toilet HH_well_water cell_x.x cell_y.x cell_x.y cell_y.y
1 0              0            0             92.7     11.7     92.75    11.75
2 1              0            0             92.7     11.7     92.75    11.75
  Measured_month Measured_year Men_anemia Men_severe_anemia Men_moderate_anemia
1 7              2015          0          0                 0
2 7              2015          0          0                 0
  Men_mild_anemia Men_no_anemia BMI_category Blood_hypertension
1 0               1000          Normal       1000
2 0               1000          Normal          0
  Water_fetching_risk District_ID                            T_i30    T_i20
1 0                   Andaman & Nicobar Island_South Andaman 26.98750 27.00625
2 0                   Andaman & Nicobar Island_South Andaman 26.97361 26.94375
  T_i10  T_i30_bin T_i20_bin T_i10_bin T_Bin_17_21_Nhours_on30
1 26.700 (25,27]   (27,29]   (25,27]   0
2 26.875 (25,27]   (25,27]   (25,27]   0
  T_Bin_21_23_Nhours_on30 T_Bin_23_25_Nhours_on30 T_Bin_25_27_Nhours_on30
1 0                       6                       525
2 0                       4                       535
  T_Bin_27_29_Nhours_on30 T_Bin_29_31_Nhours_on30 T_Bin_inf17_Nhours_on30
1 189                     0                       0
2 181                     0                       0
  T_Bin_31_33_Nhours_on30 T_Bin_sup33_Nhours_on30 T_Bin_17_21_Nhours_on20
1 0                       0                       0
2 0                       0                       0
  T_Bin_21_23_Nhours_on20 T_Bin_23_25_Nhours_on20 T_Bin_25_27_Nhours_on20
1 0                       5                       346
2 0                       4                       360
  T_Bin_27_29_Nhours_on20 T_Bin_29_31_Nhours_on20 T_Bin_inf17_Nhours_on20
1 129                     0                       0
2 116                     0                       0
  T_Bin_31_33_Nhours_on20 T_Bin_sup33_Nhours_on20 T_Bin_17_21_Nhours_on10
1 0                       0                       0
2 0                       0                       0
  T_Bin_21_23_Nhours_on10 T_Bin_23_25_Nhours_on10 T_Bin_25_27_Nhours_on10
1 0                       5                       211
2 0                       3                       194
  T_Bin_27_29_Nhours_on10 T_Bin_29_31_Nhours_on10 T_Bin_inf17_Nhours_on10
1 24                      0                       0
2 43                      0                       0
  T_Bin_31_33_Nhours_on10 T_Bin_sup33_Nhours_on10 T_MeanBin_23_25_Ndays_on30
1 0                       0                       0
2 0                       0                       0
  T_MeanBin_21_23_Ndays_on30 T_MeanBin_25_27_Ndays_on30
1 0                          16
2 0                          16
  T_MeanBin_inf17_Ndays_on30 T_MeanBin_17_21_Ndays_on30
1 0                          0
2 0                          0
  T_MeanBin_27_29_Ndays_on30 T_MeanBin_29_31_Ndays_on30
1 14                         0
2 14                         0
  T_MeanBin_31_33_Ndays_on30 T_MeanBin_sup33_Ndays_on30
1 0                          0
2 0                          0
  T_MeanBin_23_25_Ndays_on20 T_MeanBin_21_23_Ndays_on20
1 0                          0
2 0                          0
  T_MeanBin_25_27_Ndays_on20 T_MeanBin_inf17_Ndays_on20
1 12                         0
2 12                         0
  T_MeanBin_17_21_Ndays_on20 T_MeanBin_27_29_Ndays_on20
1 0                          8
2 0                          8
  T_MeanBin_29_31_Ndays_on20 T_MeanBin_31_33_Ndays_on20
1 0                          0
2 0                          0
  T_MeanBin_sup33_Ndays_on20 T_MeanBin_23_25_Ndays_on10
1 0                          0
2 0                          0
  T_MeanBin_21_23_Ndays_on10 T_MeanBin_25_27_Ndays_on10
1 0                          9
2 0                          7
  T_MeanBin_inf17_Ndays_on10 T_MeanBin_17_21_Ndays_on10
1 0                          0
2 0                          0
  T_MeanBin_27_29_Ndays_on10 T_MeanBin_29_31_Ndays_on10
1 1                          0
2 3                          0
  T_MeanBin_31_33_Ndays_on10 T_MeanBin_sup33_Ndays_on10
1 0                          0
2 0                          0
  T_MinBin_17_19_Ndays_on30 T_MinBin_15_17_Ndays_on30 T_MinBin_19_21_Ndays_on30
1 0                         0                         0
2 0                         0                         0
  T_MinBin_21_23_Ndays_on30 T_MinBin_inf11_Ndays_on30 T_MinBin_11_13_Ndays_on30
1 0                         0                         0
2 0                         0                         0
  T_MinBin_13_15_Ndays_on30 T_MinBin_23_25_Ndays_on30 T_MinBin_sup25_Ndays_on30
1 0                         4                         26
2 0                         3                         27
  T_MinBin_17_19_Ndays_on20 T_MinBin_15_17_Ndays_on20 T_MinBin_19_21_Ndays_on20
1 0                         0                         0
2 0                         0                         0
  T_MinBin_21_23_Ndays_on20 T_MinBin_inf11_Ndays_on20 T_MinBin_11_13_Ndays_on20
1 0                         0                         0
2 0                         0                         0
  T_MinBin_13_15_Ndays_on20 T_MinBin_23_25_Ndays_on20 T_MinBin_sup25_Ndays_on20
1 0                         3                         17
2 0                         3                         17
  T_MinBin_17_19_Ndays_on10 T_MinBin_15_17_Ndays_on10 T_MinBin_19_21_Ndays_on10
1 0                         0                         0
2 0                         0                         0
  T_MinBin_21_23_Ndays_on10 T_MinBin_inf11_Ndays_on10 T_MinBin_11_13_Ndays_on10
1 0                         0                         0
2 0                         0                         0
  T_MinBin_13_15_Ndays_on10 T_MinBin_23_25_Ndays_on10 T_MinBin_sup25_Ndays_on10
1 0                         3                         7
2 0                         2                         8
  T_MaxBin_29_31_Ndays_on30 T_MaxBin_31_33_Ndays_on30 T_MaxBin_27_29_Ndays_on30
1 0                         0                         21
2 0                         0                         20
  T_MaxBin_25_27_Ndays_on30 T_MaxBin_23_25_Ndays_on30 T_MaxBin_inf21_Ndays_on30
1  9                        0                         0
2 10                        0                         0
  T_MaxBin_21_23_Ndays_on30 T_MaxBin_33_35_Ndays_on30 T_MaxBin_sup35_Ndays_on30
1 0                         0                         0
2 0                         0                         0
  T_MaxBin_29_31_Ndays_on20 T_MaxBin_31_33_Ndays_on20 T_MaxBin_27_29_Ndays_on20
1 0                         0                         15
2 0                         0                         13
  T_MaxBin_25_27_Ndays_on20 T_MaxBin_23_25_Ndays_on20 T_MaxBin_inf21_Ndays_on20
1 5                         0                         0
2 7                         0                         0
  T_MaxBin_21_23_Ndays_on20 T_MaxBin_33_35_Ndays_on20 T_MaxBin_sup35_Ndays_on20
1 0                         0                         0
2 0                         0                         0
  T_MaxBin_29_31_Ndays_on10 T_MaxBin_31_33_Ndays_on10 T_MaxBin_27_29_Ndays_on10
1 0                         0                         6
2 0                         0                         6
  T_MaxBin_25_27_Ndays_on10 T_MaxBin_23_25_Ndays_on10 T_MaxBin_inf21_Ndays_on10
1 4                         0                         0
2 4                         0                         0
  T_MaxBin_21_23_Ndays_on10 T_MaxBin_33_35_Ndays_on10 T_MaxBin_sup35_Ndays_on10
1 0                         0                         0
2 0                         0                         0
  WB_i30   WB_i20   WB_i10   WB_i30_bin WB_i20_bin WB_i10_bin
1 26.08611 26.08333 25.90833 (26,28]    (26,28]    (24,26]
2 26.08472 26.01042 25.99167 (26,28]    (26,28]    (24,26]
  WB_Bin_18_20_Nhours_on30 WB_Bin_20_22_Nhours_on30 WB_Bin_22_24_Nhours_on30
1 0                        0                        0
2 0                        0                        0
  WB_Bin_24_26_Nhours_on30 WB_Bin_16_18_Nhours_on30 WB_Bin_14_16_Nhours_on30
1 559                      0                        0
2 566                      0                        0
  WB_Bin_inf14_Nhours_on30 WB_Bin_26_28_Nhours_on30 WB_Bin_sup28_Nhours_on30
1 0                        161                      0
2 0                        154                      0
  WB_Bin_18_20_Nhours_on20 WB_Bin_20_22_Nhours_on20 WB_Bin_22_24_Nhours_on20
1 0                        0                        0
2 0                        0                        0
  WB_Bin_24_26_Nhours_on20 WB_Bin_16_18_Nhours_on20 WB_Bin_14_16_Nhours_on20
1 385                      0                        0
2 396                      0                        0
  WB_Bin_inf14_Nhours_on20 WB_Bin_26_28_Nhours_on20 WB_Bin_sup28_Nhours_on20
1 0                        95                       0
2 0                        84                       0
  WB_Bin_18_20_Nhours_on10 WB_Bin_20_22_Nhours_on10 WB_Bin_22_24_Nhours_on10
1 0                        0                        0
2 0                        0                        0
  WB_Bin_24_26_Nhours_on10 WB_Bin_16_18_Nhours_on10 WB_Bin_14_16_Nhours_on10
1 217                      0                        0
2 205                      0                        0
  WB_Bin_inf14_Nhours_on10 WB_Bin_26_28_Nhours_on10 WB_Bin_sup28_Nhours_on10
1 0                        23                       0
2 0                        35                       0
  WB_MeanBin_20_22_Ndays_on30 WB_MeanBin_18_20_Ndays_on30
1 0                           0
2 0                           0
  WB_MeanBin_22_24_Ndays_on30 WB_MeanBin_16_18_Ndays_on30
1 0                           0
2 0                           0
  WB_MeanBin_inf14_Ndays_on30 WB_MeanBin_14_16_Ndays_on30
1 0                           0
2 0                           0
  WB_MeanBin_24_26_Ndays_on30 WB_MeanBin_26_28_Ndays_on30
1 13                          17
2 14                          16
  WB_MeanBin_sup28_Ndays_on30 WB_MeanBin_20_22_Ndays_on20
1 0                           0
2 0                           0
  WB_MeanBin_18_20_Ndays_on20 WB_MeanBin_22_24_Ndays_on20
1 0                           0
2 0                           0
  WB_MeanBin_16_18_Ndays_on20 WB_MeanBin_inf14_Ndays_on20
1 0                           0
2 0                           0
  WB_MeanBin_14_16_Ndays_on20 WB_MeanBin_24_26_Ndays_on20
1 0                           10
2 0                           12
  WB_MeanBin_26_28_Ndays_on20 WB_MeanBin_sup28_Ndays_on20
1 10                          0
2  8                          0
  WB_MeanBin_20_22_Ndays_on10 WB_MeanBin_18_20_Ndays_on10
1 0                           0
2 0                           0
  WB_MeanBin_22_24_Ndays_on10 WB_MeanBin_16_18_Ndays_on10
1 0                           0
2 0                           0
  WB_MeanBin_inf14_Ndays_on10 WB_MeanBin_14_16_Ndays_on10
1 0                           0
2 0                           0
  WB_MeanBin_24_26_Ndays_on10 WB_MeanBin_26_28_Ndays_on10
1 7                           3
2 7                           3
  WB_MeanBin_sup28_Ndays_on10 WB_MinBin_18_20_Ndays_on30
1 0                           0
2 0                           0
  WB_MinBin_16_18_Ndays_on30 WB_MinBin_14_16_Ndays_on30
1 0                          0
2 0                          0
  WB_MinBin_12_14_Ndays_on30 WB_MinBin_10_12_Ndays_on30
1 0                          0
2 0                          0
  WB_MinBin_inf10_Ndays_on30 WB_MinBin_20_22_Ndays_on30
1 0                          0
2 0                          0
  WB_MinBin_22_24_Ndays_on30 WB_MinBin_sup24_Ndays_on30
1 0                          30
2 0                          30
  WB_MinBin_18_20_Ndays_on20 WB_MinBin_16_18_Ndays_on20
1 0                          0
2 0                          0
  WB_MinBin_14_16_Ndays_on20 WB_MinBin_12_14_Ndays_on20
1 0                          0
2 0                          0
  WB_MinBin_10_12_Ndays_on20 WB_MinBin_inf10_Ndays_on20
1 0                          0
2 0                          0
  WB_MinBin_20_22_Ndays_on20 WB_MinBin_22_24_Ndays_on20
1 0                          0
2 0                          0
  WB_MinBin_sup24_Ndays_on20 WB_MinBin_18_20_Ndays_on10
1 20                         0
2 20                         0
  WB_MinBin_16_18_Ndays_on10 WB_MinBin_14_16_Ndays_on10
1 0                          0
2 0                          0
  WB_MinBin_12_14_Ndays_on10 WB_MinBin_10_12_Ndays_on10
1 0                          0
2 0                          0
  WB_MinBin_inf10_Ndays_on10 WB_MinBin_20_22_Ndays_on10
1 0                          0
2 0                          0
  WB_MinBin_22_24_Ndays_on10 WB_MinBin_sup24_Ndays_on10
1 0                          10
2 0                          10
  WB_MaxBin_24_26_Ndays_on30 WB_MaxBin_22_24_Ndays_on30
1 10                         0
2 11                         0
  WB_MaxBin_26_28_Ndays_on30 WB_MaxBin_inf18_Ndays_on30
1 20                         0
2 19                         0
  WB_MaxBin_18_20_Ndays_on30 WB_MaxBin_20_22_Ndays_on30
1 0                          0
2 0                          0
  WB_MaxBin_28_30_Ndays_on30 WB_MaxBin_30_32_Ndays_on30
1 0                          0
2 0                          0
  WB_MaxBin_sup32_Ndays_on30 WB_MaxBin_24_26_Ndays_on20
1 0                          7
2 0                          9
  WB_MaxBin_22_24_Ndays_on20 WB_MaxBin_26_28_Ndays_on20
1 0                          13
2 0                          11
  WB_MaxBin_inf18_Ndays_on20 WB_MaxBin_18_20_Ndays_on20
1 0                          0
2 0                          0
  WB_MaxBin_20_22_Ndays_on20 WB_MaxBin_28_30_Ndays_on20
1 0                          0
2 0                          0
  WB_MaxBin_30_32_Ndays_on20 WB_MaxBin_sup32_Ndays_on20
1 0                          0
2 0                          0
  WB_MaxBin_24_26_Ndays_on10 WB_MaxBin_22_24_Ndays_on10
1 5                          0
2 5                          0
  WB_MaxBin_26_28_Ndays_on10 WB_MaxBin_inf18_Ndays_on10
1 5                          0
2 5                          0
  WB_MaxBin_18_20_Ndays_on10 WB_MaxBin_20_22_Ndays_on10
1 0                          0
2 0                          0
  WB_MaxBin_28_30_Ndays_on10 WB_MaxBin_30_32_Ndays_on10
1 0                          0
2 0                          0
  WB_MaxBin_sup32_Ndays_on10 P_tot_30  P_tot_20  P_tot_10   API_sup_1
1 0                          0.2839093 0.1787939 0.11706638 0
2 0                          0.2566433 0.1496382 0.09978867 0

In [9]:
df_reg_men <- df_men %>%
                mutate(T_i30_bin=factor(gsub("\\(","",T_i30_bin),levels=T_bins_labels))

# Hemoglobin level

# Temperature reg

## Air conditioner

In [10]:
reg_children_AC <- feols(Child_hemo_level_alti ~ HH_air_conditioner*i(T_i30_bin,ref=bin_ref_T) + P_tot_30 + 
                                        Child_female + Child_birth_order + Child_alive_age_month + 
                                        Mother_prim_educ + Mother_second_educ + Mother_higher_educ +
                                        Mother_muslim + Mother_not_hindu_nor_muslim  + 
                                        Mother_ethni_SC + Mother_ethni_ST + Mother_ethni_OBC +
                                        Wealth_lowest + Wealth_second + Wealth_fourth + Wealth_highest + 
                                        Urban
                                        |District_ID^Measured_month + District_ID^Measured_year,
                        vcov = ~District_ID,
                    df_reg_children)

NOTES: 16,652 observations removed because of NA values (RHS: 16,652).
       38/7 fixed-effect singletons were removed (38 observations).

In [11]:
reg_women_AC <- feols(Blood_hemo_level_alti ~ HH_air_conditioner*i(T_i30_bin,ref=bin_ref_T) + P_tot_30 + 
                                        Current_age + N_year_educ + Smoker + Health_insurance + 
                                        Religion_muslim + Religion_not_hindu_nor_muslim + 
                                        Ethni_SC + Ethni_ST + Ethni_OBC +
                                        Wealth_lowest + Wealth_second + Wealth_fourth + Wealth_highest + 
                                        Urban
                                        |District_ID^Measured_month + District_ID^Measured_year,
                        vcov = ~District_ID,
                    df_reg_women)

NOTES: 59,850 observations removed because of NA values (RHS: 59,850).
       17/1 fixed-effect singletons were removed (17 observations).

In [12]:
reg_men_AC <- feols(Blood_hemo_level_alti ~ HH_air_conditioner*i(T_i30_bin,ref=bin_ref_T) + P_tot_30 + 
                                        Current_age + N_year_educ + Smoker + Health_insurance + 
                                        Religion_muslim + Religion_not_hindu_nor_muslim + 
                                        Ethni_SC + Ethni_ST + Ethni_OBC +
                                        Wealth_lowest + Wealth_second + Wealth_fourth + Wealth_highest + 
                                        Urban
                                        |District_ID^Measured_month + District_ID^Measured_year,
                        vcov = ~District_ID,
                    df_reg_men)

NOTES: 9,536 observations removed because of NA values (RHS: 9,536).
       13/1 fixed-effect singletons were removed (13 observations).

In [13]:
etable(reg_children_AC,reg_women_AC,reg_men_AC,
       tex=TRUE,
       fitstat = ~ n + r2 + my,
       dict=c(dict,HH_air_conditioner= "Air conditioner"),
       drop="%!T_i30_bin|conditioner")

\begingroup
\centering
\begin{tabular}{lccc}
   \tabularnewline \midrule \midrule
   Dependent Variables: & Child\_hemo\_level\_alti & \multicolumn{2}{c}{Blood\_hemo\_level\_alti}\\
   Model:                               & (1)             & (2)             & (3)\\
   \midrule
   \emph{Variables}\\
   Air conditioner                      & -0.5410$^{**}$  & -0.6824$^{***}$ & -0.0764\\
                                        & (0.2656)        & (0.2358)        & (0.4905)\\
   T: ≤17°C                             & -0.9527$^{***}$ & -0.1051         & -0.8433\\
                                        & (0.3405)        & (0.2665)        & (0.5979)\\
   T: (21,23]                           & 0.2242          & -0.6804$^{***}$ & -1.198$^{**}$\\
                                        & (0.3005)        & (0.2146)        & (0.4804)\\
   T: (23,25]                           & -0.2315         & -1.500$^{***}$  & -1.965$^{***}$\\
                                        & (0.3920)        & (0.3314)        & (0.6108)\\
   T: (25,27]                           & -1.006$^{**}$   & -2.590$^{***}$  & -3.081$^{***}$\\
                                        & (0.4525)        & (0.4142)        & (0.7216)\\
   T: (27,29]                           & -1.908$^{***}$  & -3.224$^{***}$  & -2.798$^{***}$\\
                                        & (0.5436)        & (0.4605)        & (0.8279)\\
   T: (29,31]                           & -2.851$^{***}$  & -3.842$^{***}$  & -3.365$^{***}$\\
                                        & (0.6651)        & (0.5003)        & (0.9379)\\
   T: (31,33]                           & -3.399$^{***}$  & -3.747$^{***}$  & -2.944$^{***}$\\
                                        & (0.7222)        & (0.5284)        & (1.035)\\
   T: >33°C                             & -3.257$^{***}$  & -3.651$^{***}$  & -3.412$^{**}$\\
                                        & (0.8300)        & (0.6429)        & (1.396)\\
   Air conditioner $\times$ T: ≤17°C    & 0.7323          & 0.2430          & 0.3934\\
                                        & (0.4518)        & (0.3296)        & (0.7371)\\
   Air conditioner $\times$ T: (21,23]  & 0.1731          & 0.3130          & 0.4704\\
                                        & (0.4704)        & (0.3090)        & (0.7933)\\
   Air conditioner $\times$ T: (23,25]  & 0.4043          & 0.2750          & -0.3461\\
                                        & (0.4195)        & (0.2883)        & (0.6781)\\
   Air conditioner $\times$ T: (25,27]  & 1.025$^{***}$   & 0.9094$^{***}$  & 0.5609\\
                                        & (0.3356)        & (0.2676)        & (0.5827)\\
   Air conditioner $\times$ T: (27,29]  & 0.4444          & 0.3900          & -0.1826\\
                                        & (0.3868)        & (0.2927)        & (0.6093)\\
   Air conditioner $\times$ T: (29,31]  & 0.8023$^{**}$   & 0.9271$^{***}$  & 0.5311\\
                                        & (0.4006)        & (0.2939)        & (0.6470)\\
   Air conditioner $\times$ T: (31,33]  & 1.226$^{***}$   & 1.072$^{***}$   & 0.3972\\
                                        & (0.4572)        & (0.3113)        & (0.6817)\\
   Air conditioner $\times$ T: >33°C    & 0.6756          & 0.6329          & 1.296$^{*}$\\
                                        & (0.4571)        & (0.4130)        & (0.7207)\\
   \midrule
   \emph{Fixed-effects}\\
   District\_ID-Measured\_month         & Yes             & Yes             & Yes\\
   District\_ID-Measured\_year          & Yes             & Yes             & Yes\\
   \midrule
   \emph{Fit statistics}\\
   Observations                         & 265,122         & 913,595         & 140,552\\
   R$^2$                                & 0.20169         & 0.09445         & 0.11415\\
   Dependent variable mean              & 105.03          & 116.30          & 140.09\\
   \midrule \midrule
   \multicolumn{4}{l}{\emph{Clustered (District\_ID) standard-errors in parentheses}}\\
   \multicolumn{4}{l}{\emph{Signif. Codes: ***: 0.01, **: 0.05, *: 0.1}}\\
\end{tabular}
\par\endgroup

## Urban-Rural

In [14]:
reg_children_urb <- feols(Child_hemo_level_alti ~ Urban*i(T_i30_bin,ref=bin_ref_T) + P_tot_30 + 
                                        Child_female + Child_birth_order + Child_alive_age_month + 
                                        Mother_prim_educ + Mother_second_educ + Mother_higher_educ +
                                        Mother_muslim + Mother_not_hindu_nor_muslim  + 
                                        Mother_ethni_SC + Mother_ethni_ST + Mother_ethni_OBC +
                                        Wealth_lowest + Wealth_second + Wealth_fourth + Wealth_highest #+ 
                                        #Urban
                                        |District_ID^Measured_month + District_ID^Measured_year,
                        vcov = ~District_ID,
                    df_reg_children)

NOTES: 16,652 observations removed because of NA values (RHS: 16,652).
       38/7 fixed-effect singletons were removed (38 observations).

In [15]:
reg_women_urb <- feols(Blood_hemo_level_alti ~ Urban*i(T_i30_bin,ref=bin_ref_T) + P_tot_30 +
                                        Current_age + N_year_educ + Smoker + Health_insurance + 
                                        Religion_muslim + Religion_not_hindu_nor_muslim + 
                                        Ethni_SC + Ethni_ST + Ethni_OBC +
                                        Wealth_lowest + Wealth_second + Wealth_fourth + Wealth_highest #+ 
                                        #Urban
                                        |District_ID^Measured_month + District_ID^Measured_year,
                        vcov = ~District_ID,
                    df_reg_women)

NOTES: 59,850 observations removed because of NA values (RHS: 59,850).
       17/1 fixed-effect singletons were removed (17 observations).

In [16]:
reg_men_urb <- feols(Blood_hemo_level_alti ~ Urban*i(T_i30_bin,ref=bin_ref_T) + P_tot_30 + 
                                        Current_age + N_year_educ + Smoker + Health_insurance + 
                                        Religion_muslim + Religion_not_hindu_nor_muslim + 
                                        Ethni_SC + Ethni_ST + Ethni_OBC +
                                        Wealth_lowest + Wealth_second + Wealth_fourth + Wealth_highest #+ 
                                        #Urban
                                        |District_ID^Measured_month + District_ID^Measured_year,
                        vcov = ~District_ID,
                    df_reg_men)

NOTES: 9,536 observations removed because of NA values (RHS: 9,536).
       13/1 fixed-effect singletons were removed (13 observations).

In [17]:
etable(reg_children_urb,reg_women_urb,reg_men_urb,
       tex=TRUE,
       drop="%!T_i30_bin|Urban",
       fitstat = ~ n + r2 + my,
       dict=dict
      )

\begingroup
\centering
\begin{tabular}{lccc}
   \tabularnewline \midrule \midrule
   Dependent Variables: & Child\_hemo\_level\_alti & \multicolumn{2}{c}{Blood\_hemo\_level\_alti}\\
   Model:                         & (1)             & (2)             & (3)\\
   \midrule
   \emph{Variables}\\
   Urban                          & -0.9022$^{**}$  & 0.0550          & 1.220$^{**}$\\
                                  & (0.3509)        & (0.2560)        & (0.4975)\\
   T: ≤17°C                       & -0.8936$^{***}$ & -0.0826         & -0.7510\\
                                  & (0.3391)        & (0.2712)        & (0.6080)\\
   T: (21,23]                     & 0.1096          & -0.6521$^{***}$ & -1.006$^{**}$\\
                                  & (0.2952)        & (0.2200)        & (0.5071)\\
   T: (23,25]                     & -0.3535         & -1.457$^{***}$  & -1.850$^{***}$\\
                                  & (0.3967)        & (0.3305)        & (0.6308)\\
   T: (25,27]                     & -1.032$^{**}$   & -2.506$^{***}$  & -3.069$^{***}$\\
                                  & (0.4502)        & (0.4084)        & (0.7344)\\
   T: (27,29]                     & -1.896$^{***}$  & -3.183$^{***}$  & -2.668$^{***}$\\
                                  & (0.5450)        & (0.4598)        & (0.8438)\\
   T: (29,31]                     & -2.735$^{***}$  & -3.763$^{***}$  & -3.365$^{***}$\\
                                  & (0.6577)        & (0.4981)        & (0.9539)\\
   T: (31,33]                     & -3.377$^{***}$  & -3.545$^{***}$  & -2.645$^{**}$\\
                                  & (0.7315)        & (0.5312)        & (1.052)\\
   T: >33°C                       & -3.279$^{***}$  & -3.514$^{***}$  & -3.057$^{**}$\\
                                  & (0.8256)        & (0.6362)        & (1.393)\\
   Urban $\times$ T: ≤17°C        & 0.1338          & 0.1452          & -0.1445\\
                                  & (0.5315)        & (0.3863)        & (0.8979)\\
   Urban $\times$ T: (21,23]      & 0.7884$^{**}$   & 0.0429          & -0.5386\\
                                  & (0.4010)        & (0.2877)        & (0.7528)\\
   Urban $\times$ T: (23,25]      & 0.9622$^{**}$   & -0.0468         & -0.5696\\
                                  & (0.4718)        & (0.3100)        & (0.6946)\\
   Urban $\times$ T: (25,27]      & 0.9918$^{**}$   & 0.2320          & 0.3882\\
                                  & (0.4101)        & (0.2980)        & (0.6266)\\
   Urban $\times$ T: (27,29]      & 0.4341          & 0.0515          & -0.4433\\
                                  & (0.4426)        & (0.3087)        & (0.6239)\\
   Urban $\times$ T: (29,31]      & 0.2795          & 0.2806          & 0.3866\\
                                  & (0.4493)        & (0.3276)        & (0.6830)\\
   Urban $\times$ T: (31,33]      & 1.036$^{**}$    & 0.0610          & -0.5107\\
                                  & (0.5018)        & (0.3721)        & (0.7180)\\
   Urban $\times$ T: >33°C        & 0.6662          & -0.1742         & 0.3873\\
                                  & (0.5179)        & (0.3986)        & (0.8457)\\
   \midrule
   \emph{Fixed-effects}\\
   District\_ID-Measured\_month   & Yes             & Yes             & Yes\\
   District\_ID-Measured\_year    & Yes             & Yes             & Yes\\
   \midrule
   \emph{Fit statistics}\\
   Observations                   & 265,122         & 913,595         & 140,552\\
   R$^2$                          & 0.20171         & 0.09441         & 0.11415\\
   Dependent variable mean        & 105.03          & 116.30          & 140.09\\
   \midrule \midrule
   \multicolumn{4}{l}{\emph{Clustered (District\_ID) standard-errors in parentheses}}\\
   \multicolumn{4}{l}{\emph{Signif. Codes: ***: 0.01, **: 0.05, *: 0.1}}\\
\end{tabular}
\par\endgroup