In [1]:
list.of.packages <- c("tidyverse","data.table","stargazer")
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages, repos = "http://cran.us.r-project.org")

invisible(lapply(list.of.packages, library, character.only = TRUE))

options(repr.matrix.max.rows=500, repr.matrix.max.cols=1200, message=FALSE, warning=TRUE)

── Attaching core tidyverse packages ─────────────────────────────────────────────────────────────────────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.2.0     ✔ readr     2.2.0
✔ forcats   1.0.1     ✔ stringr   1.6.0
✔ ggplot2   4.0.2     ✔ tibble    3.3.1
✔ lubridate 1.9.5     ✔ tidyr     1.3.2
✔ purrr     1.2.1
── Conflicts ───────────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

Attachement du package : ‘data.table’


Les objets suivants sont masqués depuis ‘package:lubridate’:

    hour, isoweek, mday, minute, month, quarter, second, wday, week,
    yday, year


Les objets suivants sont masqués depuis ‘package:dplyr’:

    between, first, last


L'objet suivant est masqué depuis ‘package:purrr’:

    transpose



Please cite as:


 Hlavac, Marek (2022). stargazer: Well-Formatted Regression and Summary Statistics Tables.

 R package version 5.2.3. https://CRAN.R-project.org/package=stargazer

# Negative temperature dataframe

In [2]:
df_deg_bins_neg <- fread("./interm/df_T_cells_CDC_negative.csv")
sprintf("%i x %i dataframe", nrow(df_deg_bins_neg), ncol(df_deg_bins_neg))
head(df_deg_bins_neg,2)

[1] "173657 x 933 dataframe"

  Measured_date_CDC cell_x cell_y T-1DayMin31 T-1DayMin32 T-1DayMin33
1 42203             92.7   11.7   0           0           0
2 42205             92.8    9.2   0           0           0
  T-1DayMin34 T-1DayMin35 T-1DayMin36 T-1DayMin37 T-1DayMin38 T-1DayMin39
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-1DayMin40 T-1DayMin41 T-1DayMin42 T-1DayMin43 T-1DayMin44 T-1DayMin45
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-1DayMin46 T-1DayMin47 T-1DayMin48 T-1DayMin49 T-1DayMin50 T-1DayMin51
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-1DayMin52 T-1DayMin53 T-1DayMin54 T-1DayMin55 T-1DayMin56 T-1DayMin57
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-1DayMin58 T-1DayMin59 T-1DayMin60 T-2DayMin31 T-2DayMin32 T-2DayMin33
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-2DayMin34 T-2DayMin35 T-2DayMin36 T-2DayMin37 T-2DayMin38 T-2DayMin39
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-2DayMin40 T-2DayMin41 T-2DayMin42 T-2DayMin43 T-2DayMin44 T-2DayMin45
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-2DayMin46 T-2DayMin47 T-2DayMin48 T-2DayMin49 T-2DayMin50 T-2DayMin51
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-2DayMin52 T-2DayMin53 T-2DayMin54 T-2DayMin55 T-2DayMin56 T-2DayMin57
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-2DayMin58 T-2DayMin59 T-2DayMin60 T-3DayMin31 T-3DayMin32 T-3DayMin33
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-3DayMin34 T-3DayMin35 T-3DayMin36 T-3DayMin37 T-3DayMin38 T-3DayMin39
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-3DayMin40 T-3DayMin41 T-3DayMin42 T-3DayMin43 T-3DayMin44 T-3DayMin45
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-3DayMin46 T-3DayMin47 T-3DayMin48 T-3DayMin49 T-3DayMin50 T-3DayMin51
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-3DayMin52 T-3DayMin53 T-3DayMin54 T-3DayMin55 T-3DayMin56 T-3DayMin57
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-3DayMin58 T-3DayMin59 T-3DayMin60 T-4DayMin31 T-4DayMin32 T-4DayMin33
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-4DayMin34 T-4DayMin35 T-4DayMin36 T-4DayMin37 T-4DayMin38 T-4DayMin39
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-4DayMin40 T-4DayMin41 T-4DayMin42 T-4DayMin43 T-4DayMin44 T-4DayMin45
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-4DayMin46 T-4DayMin47 T-4DayMin48 T-4DayMin49 T-4DayMin50 T-4DayMin51
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-4DayMin52 T-4DayMin53 T-4DayMin54 T-4DayMin55 T-4DayMin56 T-4DayMin57
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-4DayMin58 T-4DayMin59 T-4DayMin60 T-5DayMin31 T-5DayMin32 T-5DayMin33
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-5DayMin34 T-5DayMin35 T-5DayMin36 T-5DayMin37 T-5DayMin38 T-5DayMin39
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-5DayMin40 T-5DayMin41 T-5DayMin42 T-5DayMin43 T-5DayMin44 T-5DayMin45
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-5DayMin46 T-5DayMin47 T-5DayMin48 T-5DayMin49 T-5DayMin50 T-5DayMin51
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-5DayMin52 T-5DayMin53 T-5DayMin54 T-5DayMin55 T-5DayMin56 T-5DayMin57
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-5DayMin58 T-5DayMin59 T-5DayMin60 T-6DayMin31 T-6DayMin32 T-6DayMin33
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-6DayMin34 T-6DayMin35 T-6DayMin36 T-6DayMin37 T-6DayMin38 T-6DayMin39
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-6DayMin40 T-6DayMin41 T-6DayMin42 T-6DayMin43 T-6DayMin44 T-6DayMin45
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-6DayMin46 T-6DayMin47 T-6DayMin48 T-6DayMin49 T-6DayMin50 T-6DayMin51
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-6DayMin52 T-6DayMin53 T-6DayMin54 T-6DayMin55 T-6DayMin56 T-6DayMin57
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-6DayMin58 T-6DayMin59 T-6DayMin60 T-7DayMin31 T-7DayMin32 T-7DayMin33
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-7DayMin34 T-7DayMin35 T-7DayMin36 T-7DayMin37 T-7DayMin38 T-7DayMin39
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-7DayMin40 T-7DayMin41 T-7DayMin42 T-7DayMin43 T-7DayMin44 T-7DayMin45
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-7DayMin46 T-7DayMin47 T-7DayMin48 T-7DayMin49 T-7DayMin50 T-7DayMin51
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-7DayMin52 T-7DayMin53 T-7DayMin54 T-7DayMin55 T-7DayMin56 T-7DayMin57
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-7DayMin58 T-7DayMin59 T-7DayMin60 T-8DayMin31 T-8DayMin32 T-8DayMin33
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-8DayMin34 T-8DayMin35 T-8DayMin36 T-8DayMin37 T-8DayMin38 T-8DayMin39
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-8DayMin40 T-8DayMin41 T-8DayMin42 T-8DayMin43 T-8DayMin44 T-8DayMin45
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-8DayMin46 T-8DayMin47 T-8DayMin48 T-8DayMin49 T-8DayMin50 T-8DayMin51
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-8DayMin52 T-8DayMin53 T-8DayMin54 T-8DayMin55 T-8DayMin56 T-8DayMin57
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-8DayMin58 T-8DayMin59 T-8DayMin60 T-9DayMin31 T-9DayMin32 T-9DayMin33
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-9DayMin34 T-9DayMin35 T-9DayMin36 T-9DayMin37 T-9DayMin38 T-9DayMin39
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-9DayMin40 T-9DayMin41 T-9DayMin42 T-9DayMin43 T-9DayMin44 T-9DayMin45
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-9DayMin46 T-9DayMin47 T-9DayMin48 T-9DayMin49 T-9DayMin50 T-9DayMin51
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-9DayMin52 T-9DayMin53 T-9DayMin54 T-9DayMin55 T-9DayMin56 T-9DayMin57
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-9DayMin58 T-9DayMin59 T-9DayMin60 T-10DayMin31 T-10DayMin32 T-10DayMin33
1 0           0           0           0            0            0
2 0           0           0           0            0            0
  T-10DayMin34 T-10DayMin35 T-10DayMin36 T-10DayMin37 T-10DayMin38 T-10DayMin39
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-10DayMin40 T-10DayMin41 T-10DayMin42 T-10DayMin43 T-10DayMin44 T-10DayMin45
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-10DayMin46 T-10DayMin47 T-10DayMin48 T-10DayMin49 T-10DayMin50 T-10DayMin51
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-10DayMin52 T-10DayMin53 T-10DayMin54 T-10DayMin55 T-10DayMin56 T-10DayMin57
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-10DayMin58 T-10DayMin59 T-10DayMin60 T-11DayMin31 T-11DayMin32 T-11DayMin33
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-11DayMin34 T-11DayMin35 T-11DayMin36 T-11DayMin37 T-11DayMin38 T-11DayMin39
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-11DayMin40 T-11DayMin41 T-11DayMin42 T-11DayMin43 T-11DayMin44 T-11DayMin45
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-11DayMin46 T-11DayMin47 T-11DayMin48 T-11DayMin49 T-11DayMin50 T-11DayMin51
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-11DayMin52 T-11DayMin53 T-11DayMin54 T-11DayMin55 T-11DayMin56 T-11DayMin57
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-11DayMin58 T-11DayMin59 T-11DayMin60 T-12DayMin31 T-12DayMin32 T-12DayMin33
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-12DayMin34 T-12DayMin35 T-12DayMin36 T-12DayMin37 T-12DayMin38 T-12DayMin39
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-12DayMin40 T-12DayMin41 T-12DayMin42 T-12DayMin43 T-12DayMin44 T-12DayMin45
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-12DayMin46 T-12DayMin47 T-12DayMin48 T-12DayMin49 T-12DayMin50 T-12DayMin51
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-12DayMin52 T-12DayMin53 T-12DayMin54 T-12DayMin55 T-12DayMin56 T-12DayMin57
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-12DayMin58 T-12DayMin59 T-12DayMin60 T-13DayMin31 T-13DayMin32 T-13DayMin33
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-13DayMin34 T-13DayMin35 T-13DayMin36 T-13DayMin37 T-13DayMin38 T-13DayMin39
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-13DayMin40 T-13DayMin41 T-13DayMin42 T-13DayMin43 T-13DayMin44 T-13DayMin45
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-13DayMin46 T-13DayMin47 T-13DayMin48 T-13DayMin49 T-13DayMin50 T-13DayMin51
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-13DayMin52 T-13DayMin53 T-13DayMin54 T-13DayMin55 T-13DayMin56 T-13DayMin57
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-13DayMin58 T-13DayMin59 T-13DayMin60 T-14DayMin31 T-14DayMin32 T-14DayMin33
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-14DayMin34 T-14DayMin35 T-14DayMin36 T-14DayMin37 T-14DayMin38 T-14DayMin39
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-14DayMin40 T-14DayMin41 T-14DayMin42 T-14DayMin43 T-14DayMin44 T-14DayMin45
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-14DayMin46 T-14DayMin47 T-14DayMin48 T-14DayMin49 T-14DayMin50 T-14DayMin51
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-14DayMin52 T-14DayMin53 T-14DayMin54 T-14DayMin55 T-14DayMin56 T-14DayMin57
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-14DayMin58 T-14DayMin59 T-14DayMin60 T-15DayMin31 T-15DayMin32 T-15DayMin33
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-15DayMin34 T-15DayMin35 T-15DayMin36 T-15DayMin37 T-15DayMin38 T-15DayMin39
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-15DayMin40 T-15DayMin41 T-15DayMin42 T-15DayMin43 T-15DayMin44 T-15DayMin45
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-15DayMin46 T-15DayMin47 T-15DayMin48 T-15DayMin49 T-15DayMin50 T-15DayMin51
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-15DayMin52 T-15DayMin53 T-15DayMin54 T-15DayMin55 T-15DayMin56 T-15DayMin57
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-15DayMin58 T-15DayMin59 T-15DayMin60 T-16DayMin31 T-16DayMin32 T-16DayMin33
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-16DayMin34 T-16DayMin35 T-16DayMin36 T-16DayMin37 T-16DayMin38 T-16DayMin39
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-16DayMin40 T-16DayMin41 T-16DayMin42 T-16DayMin43 T-16DayMin44 T-16DayMin45
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-16DayMin46 T-16DayMin47 T-16DayMin48 T-16DayMin49 T-16DayMin50 T-16DayMin51
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-16DayMin52 T-16DayMin53 T-16DayMin54 T-16DayMin55 T-16DayMin56 T-16DayMin57
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-16DayMin58 T-16DayMin59 T-16DayMin60 T-17DayMin31 T-17DayMin32 T-17DayMin33
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-17DayMin34 T-17DayMin35 T-17DayMin36 T-17DayMin37 T-17DayMin38 T-17DayMin39
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-17DayMin40 T-17DayMin41 T-17DayMin42 T-17DayMin43 T-17DayMin44 T-17DayMin45
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-17DayMin46 T-17DayMin47 T-17DayMin48 T-17DayMin49 T-17DayMin50 T-17DayMin51
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-17DayMin52 T-17DayMin53 T-17DayMin54 T-17DayMin55 T-17DayMin56 T-17DayMin57
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-17DayMin58 T-17DayMin59 T-17DayMin60 T-18DayMin31 T-18DayMin32 T-18DayMin33
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-18DayMin34 T-18DayMin35 T-18DayMin36 T-18DayMin37 T-18DayMin38 T-18DayMin39
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-18DayMin40 T-18DayMin41 T-18DayMin42 T-18DayMin43 T-18DayMin44 T-18DayMin45
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-18DayMin46 T-18DayMin47 T-18DayMin48 T-18DayMin49 T-18DayMin50 T-18DayMin51
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-18DayMin52 T-18DayMin53 T-18DayMin54 T-18DayMin55 T-18DayMin56 T-18DayMin57
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-18DayMin58 T-18DayMin59 T-18DayMin60 T-19DayMin31 T-19DayMin32 T-19DayMin33
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-19DayMin34 T-19DayMin35 T-19DayMin36 T-19DayMin37 T-19DayMin38 T-19DayMin39
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-19DayMin40 T-19DayMin41 T-19DayMin42 T-19DayMin43 T-19DayMin44 T-19DayMin45
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-19DayMin46 T-19DayMin47 T-19DayMin48 T-19DayMin49 T-19DayMin50 T-19DayMin51
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-19DayMin52 T-19DayMin53 T-19DayMin54 T-19DayMin55 T-19DayMin56 T-19DayMin57
1 0            0            0            0            0            0
2 0            0            0            0            0            0

## Pivot longer dataframe

In [4]:
df_deg_bins_piv_neg <- melt(df_deg_bins_neg%>%filter(!is.na(`T-1DayMin31`)), 
                       id.vars = c("Measured_date_CDC", "cell_x", "cell_y"),
                       variable.name = "Temp_bin",
                       value.name = "N_hours")
sprintf("%i x %i dataframe", nrow(df_deg_bins_piv_neg), ncol(df_deg_bins_piv_neg))
head(df_deg_bins_piv_neg,2)

[1] "161501010 x 5 dataframe"

  Measured_date_CDC cell_x cell_y Temp_bin    N_hours
1 42203             92.7   11.7   T-1DayMin31 0
2 42205             92.8    9.2   T-1DayMin31 0

In [5]:
df_deg_bins_piv_neg_wo0 <- df_deg_bins_piv_neg[N_hours!=0]

In [6]:
#Keep memory
rm(df_deg_bins_neg)
rm(df_deg_bins_piv_neg)

# Positive temperature dataframe

In [7]:
df_deg_bins_pos <- fread("./interm/df_T_cells_CDC_positive.csv")
sprintf("%i x %i dataframe", nrow(df_deg_bins_pos), ncol(df_deg_bins_pos))
head(df_deg_bins_pos,2)

[1] "173657 x 1383 dataframe"

  Measured_date_CDC cell_x cell_y T0DayMin31 T0DayMin32 T0DayMin33 T0DayMin34
1 42203             92.7   11.7   0          0          0          0
2 42205             92.8    9.2   0          0          0          0
  T0DayMin35 T0DayMin36 T0DayMin37 T0DayMin38 T0DayMin39 T0DayMin40 T0DayMin41
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T0DayMin42 T0DayMin43 T0DayMin44 T0DayMin45 T0DayMin46 T0DayMin47 T0DayMin48
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T0DayMin49 T0DayMin50 T0DayMin51 T0DayMin52 T0DayMin53 T0DayMin54 T0DayMin55
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T0DayMin56 T0DayMin57 T0DayMin58 T0DayMin59 T0DayMin60 T1DayMin31 T1DayMin32
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T1DayMin33 T1DayMin34 T1DayMin35 T1DayMin36 T1DayMin37 T1DayMin38 T1DayMin39
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T1DayMin40 T1DayMin41 T1DayMin42 T1DayMin43 T1DayMin44 T1DayMin45 T1DayMin46
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T1DayMin47 T1DayMin48 T1DayMin49 T1DayMin50 T1DayMin51 T1DayMin52 T1DayMin53
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T1DayMin54 T1DayMin55 T1DayMin56 T1DayMin57 T1DayMin58 T1DayMin59 T1DayMin60
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T2DayMin31 T2DayMin32 T2DayMin33 T2DayMin34 T2DayMin35 T2DayMin36 T2DayMin37
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T2DayMin38 T2DayMin39 T2DayMin40 T2DayMin41 T2DayMin42 T2DayMin43 T2DayMin44
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T2DayMin45 T2DayMin46 T2DayMin47 T2DayMin48 T2DayMin49 T2DayMin50 T2DayMin51
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T2DayMin52 T2DayMin53 T2DayMin54 T2DayMin55 T2DayMin56 T2DayMin57 T2DayMin58
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T2DayMin59 T2DayMin60 T3DayMin31 T3DayMin32 T3DayMin33 T3DayMin34 T3DayMin35
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T3DayMin36 T3DayMin37 T3DayMin38 T3DayMin39 T3DayMin40 T3DayMin41 T3DayMin42
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T3DayMin43 T3DayMin44 T3DayMin45 T3DayMin46 T3DayMin47 T3DayMin48 T3DayMin49
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T3DayMin50 T3DayMin51 T3DayMin52 T3DayMin53 T3DayMin54 T3DayMin55 T3DayMin56
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T3DayMin57 T3DayMin58 T3DayMin59 T3DayMin60 T4DayMin31 T4DayMin32 T4DayMin33
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T4DayMin34 T4DayMin35 T4DayMin36 T4DayMin37 T4DayMin38 T4DayMin39 T4DayMin40
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T4DayMin41 T4DayMin42 T4DayMin43 T4DayMin44 T4DayMin45 T4DayMin46 T4DayMin47
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T4DayMin48 T4DayMin49 T4DayMin50 T4DayMin51 T4DayMin52 T4DayMin53 T4DayMin54
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T4DayMin55 T4DayMin56 T4DayMin57 T4DayMin58 T4DayMin59 T4DayMin60 T5DayMin31
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T5DayMin32 T5DayMin33 T5DayMin34 T5DayMin35 T5DayMin36 T5DayMin37 T5DayMin38
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T5DayMin39 T5DayMin40 T5DayMin41 T5DayMin42 T5DayMin43 T5DayMin44 T5DayMin45
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T5DayMin46 T5DayMin47 T5DayMin48 T5DayMin49 T5DayMin50 T5DayMin51 T5DayMin52
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T5DayMin53 T5DayMin54 T5DayMin55 T5DayMin56 T5DayMin57 T5DayMin58 T5DayMin59
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T5DayMin60 T6DayMin31 T6DayMin32 T6DayMin33 T6DayMin34 T6DayMin35 T6DayMin36
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T6DayMin37 T6DayMin38 T6DayMin39 T6DayMin40 T6DayMin41 T6DayMin42 T6DayMin43
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T6DayMin44 T6DayMin45 T6DayMin46 T6DayMin47 T6DayMin48 T6DayMin49 T6DayMin50
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T6DayMin51 T6DayMin52 T6DayMin53 T6DayMin54 T6DayMin55 T6DayMin56 T6DayMin57
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T6DayMin58 T6DayMin59 T6DayMin60 T7DayMin31 T7DayMin32 T7DayMin33 T7DayMin34
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T7DayMin35 T7DayMin36 T7DayMin37 T7DayMin38 T7DayMin39 T7DayMin40 T7DayMin41
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T7DayMin42 T7DayMin43 T7DayMin44 T7DayMin45 T7DayMin46 T7DayMin47 T7DayMin48
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T7DayMin49 T7DayMin50 T7DayMin51 T7DayMin52 T7DayMin53 T7DayMin54 T7DayMin55
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T7DayMin56 T7DayMin57 T7DayMin58 T7DayMin59 T7DayMin60 T8DayMin31 T8DayMin32
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T8DayMin33 T8DayMin34 T8DayMin35 T8DayMin36 T8DayMin37 T8DayMin38 T8DayMin39
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T8DayMin40 T8DayMin41 T8DayMin42 T8DayMin43 T8DayMin44 T8DayMin45 T8DayMin46
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T8DayMin47 T8DayMin48 T8DayMin49 T8DayMin50 T8DayMin51 T8DayMin52 T8DayMin53
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T8DayMin54 T8DayMin55 T8DayMin56 T8DayMin57 T8DayMin58 T8DayMin59 T8DayMin60
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T9DayMin31 T9DayMin32 T9DayMin33 T9DayMin34 T9DayMin35 T9DayMin36 T9DayMin37
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T9DayMin38 T9DayMin39 T9DayMin40 T9DayMin41 T9DayMin42 T9DayMin43 T9DayMin44
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T9DayMin45 T9DayMin46 T9DayMin47 T9DayMin48 T9DayMin49 T9DayMin50 T9DayMin51
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T9DayMin52 T9DayMin53 T9DayMin54 T9DayMin55 T9DayMin56 T9DayMin57 T9DayMin58
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T9DayMin59 T9DayMin60 T10DayMin31 T10DayMin32 T10DayMin33 T10DayMin34
1 0          0          0           0           0           0
2 0          0          0           0           0           0
  T10DayMin35 T10DayMin36 T10DayMin37 T10DayMin38 T10DayMin39 T10DayMin40
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T10DayMin41 T10DayMin42 T10DayMin43 T10DayMin44 T10DayMin45 T10DayMin46
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T10DayMin47 T10DayMin48 T10DayMin49 T10DayMin50 T10DayMin51 T10DayMin52
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T10DayMin53 T10DayMin54 T10DayMin55 T10DayMin56 T10DayMin57 T10DayMin58
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T10DayMin59 T10DayMin60 T11DayMin31 T11DayMin32 T11DayMin33 T11DayMin34
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T11DayMin35 T11DayMin36 T11DayMin37 T11DayMin38 T11DayMin39 T11DayMin40
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T11DayMin41 T11DayMin42 T11DayMin43 T11DayMin44 T11DayMin45 T11DayMin46
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T11DayMin47 T11DayMin48 T11DayMin49 T11DayMin50 T11DayMin51 T11DayMin52
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T11DayMin53 T11DayMin54 T11DayMin55 T11DayMin56 T11DayMin57 T11DayMin58
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T11DayMin59 T11DayMin60 T12DayMin31 T12DayMin32 T12DayMin33 T12DayMin34
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T12DayMin35 T12DayMin36 T12DayMin37 T12DayMin38 T12DayMin39 T12DayMin40
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T12DayMin41 T12DayMin42 T12DayMin43 T12DayMin44 T12DayMin45 T12DayMin46
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T12DayMin47 T12DayMin48 T12DayMin49 T12DayMin50 T12DayMin51 T12DayMin52
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T12DayMin53 T12DayMin54 T12DayMin55 T12DayMin56 T12DayMin57 T12DayMin58
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T12DayMin59 T12DayMin60 T13DayMin31 T13DayMin32 T13DayMin33 T13DayMin34
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T13DayMin35 T13DayMin36 T13DayMin37 T13DayMin38 T13DayMin39 T13DayMin40
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T13DayMin41 T13DayMin42 T13DayMin43 T13DayMin44 T13DayMin45 T13DayMin46
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T13DayMin47 T13DayMin48 T13DayMin49 T13DayMin50 T13DayMin51 T13DayMin52
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T13DayMin53 T13DayMin54 T13DayMin55 T13DayMin56 T13DayMin57 T13DayMin58
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T13DayMin59 T13DayMin60 T14DayMin31 T14DayMin32 T14DayMin33 T14DayMin34
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T14DayMin35 T14DayMin36 T14DayMin37 T14DayMin38 T14DayMin39 T14DayMin40
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T14DayMin41 T14DayMin42 T14DayMin43 T14DayMin44 T14DayMin45 T14DayMin46
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T14DayMin47 T14DayMin48 T14DayMin49 T14DayMin50 T14DayMin51 T14DayMin52
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T14DayMin53 T14DayMin54 T14DayMin55 T14DayMin56 T14DayMin57 T14DayMin58
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T14DayMin59 T14DayMin60 T15DayMin31 T15DayMin32 T15DayMin33 T15DayMin34
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T15DayMin35 T15DayMin36 T15DayMin37 T15DayMin38 T15DayMin39 T15DayMin40
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T15DayMin41 T15DayMin42 T15DayMin43 T15DayMin44 T15DayMin45 T15DayMin46
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T15DayMin47 T15DayMin48 T15DayMin49 T15DayMin50 T15DayMin51 T15DayMin52
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T15DayMin53 T15DayMin54 T15DayMin55 T15DayMin56 T15DayMin57 T15DayMin58
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T15DayMin59 T15DayMin60 T16DayMin31 T16DayMin32 T16DayMin33 T16DayMin34
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T16DayMin35 T16DayMin36 T16DayMin37 T16DayMin38 T16DayMin39 T16DayMin40
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T16DayMin41 T16DayMin42 T16DayMin43 T16DayMin44 T16DayMin45 T16DayMin46
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T16DayMin47 T16DayMin48 T16DayMin49 T16DayMin50 T16DayMin51 T16DayMin52
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T16DayMin53 T16DayMin54 T16DayMin55 T16DayMin56 T16DayMin57 T16DayMin58
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T16DayMin59 T16DayMin60 T17DayMin31 T17DayMin32 T17DayMin33 T17DayMin34
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T17DayMin35 T17DayMin36 T17DayMin37 T17DayMin38 T17DayMin39 T17DayMin40
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T17DayMin41 T17DayMin42 T17DayMin43 T17DayMin44 T17DayMin45 T17DayMin46
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T17DayMin47 T17DayMin48 T17DayMin49 T17DayMin50 T17DayMin51 T17DayMin52
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T17DayMin53 T17DayMin54 T17DayMin55 T17DayMin56 T17DayMin57 T17DayMin58
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T17DayMin59 T17DayMin60 T18DayMin31 T18DayMin32 T18DayMin33 T18DayMin34
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T18DayMin35 T18DayMin36 T18DayMin37 T18DayMin38 T18DayMin39 T18DayMin40
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T18DayMin41 T18DayMin42 T18DayMin43 T18DayMin44 T18DayMin45 T18DayMin46
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T18DayMin47 T18DayMin48 T18DayMin49 T18DayMin50 T18DayMin51 T18DayMin52
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T18DayMin53 T18DayMin54 T18DayMin55 T18DayMin56 T18DayMin57 T18DayMin58
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T18DayMin59 T18DayMin60 T19DayMin31 T19DayMin32 T19DayMin33 T19DayMin34
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T19DayMin35 T19DayMin36 T19DayMin37 T19DayMin38 T19DayMin39 T19DayMin40
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T19DayMin41 T19DayMin42 T19DayMin43 T19DayMin44 T19DayMin45 T19DayMin46
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T19DayMin47 T19DayMin48 T19DayMin49 T19DayMin50 T19DayMin51 T19DayMin52
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T19DayMin53 T19DayMin54 T19DayMin55 T19DayMin56 T19DayMin57 ⋯ T26DayMin31
1 0           0           0           0           0           ⋯ 11
2 0           0           0           0           0           ⋯  0
  T26DayMin32 T26DayMin33 T26DayMin34 T26DayMin35 T26DayMin36 T26DayMin37
1 8           4            9          1           0           7
2 9           5           12          7           7           8
  T26DayMin38 T26DayMin39 T26DayMin40 T26DayMin41 T26DayMin42 T26DayMin43
1 10          0           5           5           0            0
2  1          3           8           3           5           10
  T26DayMin44 T26DayMin45 T26DayMin46 T26DayMin47 T26DayMin48 T26DayMin49

## Pivot longer dataframe

In [9]:
df_deg_bins_piv_pos <- melt(df_deg_bins_pos%>%filter(!is.na(T0DayMin31)), 
                       id.vars = c("Measured_date_CDC", "cell_x", "cell_y"),
                       variable.name = "Temp_bin",
                       value.name = "N_hours")
sprintf("%i x %i dataframe", nrow(df_deg_bins_piv_pos), ncol(df_deg_bins_piv_pos))
head(df_deg_bins_piv_pos,2)

[1] "239646660 x 5 dataframe"

  Measured_date_CDC cell_x cell_y Temp_bin   N_hours
1 42203             92.7   11.7   T0DayMin31 0
2 42205             92.8    9.2   T0DayMin31 0

In [10]:
df_deg_bins_piv_pos_wo0 <- df_deg_bins_piv_pos[N_hours!=0]

In [11]:
#Keep memory
rm(df_deg_bins_pos,df_deg_bins_piv_pos)
gc()

       used      (Mb)   gc trigger (Mb)   max used   (Mb)
Ncells   1315343   70.3    2453447  131.1    2453447   131.1
Vcells 190730449 1455.2 1263670391 9641.1 1428257743 10896.8

# Rbind positive and negative temp

In [12]:
df_deg_bins_piv_wo0 <- rbind(df_deg_bins_piv_pos_wo0,df_deg_bins_piv_neg_wo0)

In [13]:
rm(df_deg_bins_piv_neg_wo0,df_deg_bins_piv_pos_wo0)
gc()

       used      (Mb)   gc trigger (Mb)   max used   (Mb)
Ncells   1316350   70.4    2453447  131.1    2453447   131.1
Vcells 190727052 1455.2 1010936313 7712.9 1428257743 10896.8

# Extract temperature value

In [14]:
df_deg_bins_piv_wo0[, Temp := as.numeric(sub("Day","",sub("T","",str_extract(Temp_bin, "\\s*(.+)Day"))))]
sprintf("%i x %i dataframe", nrow(df_deg_bins_piv_wo0), ncol(df_deg_bins_piv_wo0))
head(df_deg_bins_piv_wo0,2)

[1] "53825127 x 6 dataframe"

  Measured_date_CDC cell_x cell_y Temp_bin   N_hours Temp
1 42474             91.9   27.6   T0DayMin31 1       0
2 42473             91.9   27.6   T0DayMin31 3       0

# Extract day value

In [15]:
df_deg_bins_piv_wo0[, Day_Min := as.numeric(sub("Min","",str_extract(Temp_bin, "Min\\s*(.+)")))]
sprintf("%i x %i dataframe", nrow(df_deg_bins_piv_wo0), ncol(df_deg_bins_piv_wo0))
head(df_deg_bins_piv_wo0,2)

[1] "53825127 x 7 dataframe"

  Measured_date_CDC cell_x cell_y Temp_bin   N_hours Temp Day_Min
1 42474             91.9   27.6   T0DayMin31 1       0    31
2 42473             91.9   27.6   T0DayMin31 3       0    31

## SAVE

In [16]:
fwrite(df_deg_bins_piv_wo0,"./interm/df_T_cells_CDC_longer.csv")