In [1]:
list.of.packages <- c("tidyverse","data.table","stargazer")
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages, repos = "http://cran.us.r-project.org")


invisible(lapply(list.of.packages, library, character.only = TRUE))

options(repr.matrix.max.rows=500, repr.matrix.max.cols=1200, message=FALSE, warning=TRUE)

── Attaching core tidyverse packages ─────────────────────────────────────────────────────────────────────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.2.0     ✔ readr     2.2.0
✔ forcats   1.0.1     ✔ stringr   1.6.0
✔ ggplot2   4.0.2     ✔ tibble    3.3.1
✔ lubridate 1.9.5     ✔ tidyr     1.3.2
✔ purrr     1.2.1
── Conflicts ───────────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

Attachement du package : ‘data.table’


Les objets suivants sont masqués depuis ‘package:lubridate’:

    hour, isoweek, mday, minute, month, quarter, second, wday, week,
    yday, year


Les objets suivants sont masqués depuis ‘package:dplyr’:

    between, first, last


L'objet suivant est masqué depuis ‘package:purrr’:

    transpose



Please cite as:


 Hlavac, Marek (2022). stargazer: Well-Formatted Regression and Summary Statistics Tables.

 R package version 5.2.3. https://CRAN.R-project.org/package=stargazer

# Longer dataframe

In [2]:
df_deg_bins <- fread("./interm/df_T_cells_CDC_longer.csv")
sprintf("%i x %i dataframe", nrow(df_deg_bins), ncol(df_deg_bins))
head(df_deg_bins,2)

[1] "53825127 x 7 dataframe"

  Measured_date_CDC cell_x cell_y Temp_bin   N_hours Temp Day_Min
1 42474             91.9   27.6   T0DayMin31 1       0    31
2 42473             91.9   27.6   T0DayMin31 3       0    31

In [3]:
df_deg_bins%>%count(Day_Min)

   Day_Min n
1  31      1788080
2  32      1788309
3  33      1788823
4  34      1789474
5  35      1789523
6  36      1789415
7  37      1788840
8  38      1789314
9  39      1790291
10 40      1790719
11 41      1791102
12 42      1790818
13 43      1791319
14 44      1791701
15 45      1792487
16 46      1793102
17 47      1794388
18 48      1795729
19 49      1797259
20 50      1798221
21 51      1798587
22 52      1798513
23 53      1799220
24 54      1798631
25 55      1798675
26 56      1798814
27 57      1799683
28 58      1800163
29 59      1801347
30 60      1802580

In [4]:
df_deg_bins%>%count(N_hours)

   N_hours n
1   1      18807015
2   2      18066562
3   3       8338614
4   4       4309174
5   5       2004607
6   6        936469
7   7        496513
8   8        296651
9   9        184994
10 10        119574
11 11         81316
12 12         57721
13 13         39846
14 14         28850
15 15         17730
16 16         11951
17 17          8080
18 18          5665
19 19          4671
20 20          3285
21 21          2400
22 22          1409
23 23          1060
24 24           970

In [5]:
df_deg_bins%>%count(Temp)

   Temp n
1  -31        3
2  -30       25
3  -29       25
4  -28       71
5  -27      124
6  -26      155
7  -25      256
8  -24      382
9  -23      518
10 -22      738
11 -21     1137
12 -20     1442
13 -19     1995
14 -18     2541
15 -17     3421
16 -16     4344
17 -15     5532
18 -14     6661
19 -13     8214
20 -12     9892
21 -11    12257
22 -10    14569
23  -9    17521
24  -8    20665
25  -7    24960
26  -6    30143
27  -5    35372
28  -4    41830
29  -3    49776
30  -2    58806
31  -1    69263
32   0    80423
33   1    94134
34   2   113573
35   3   140872
36   4   188471
37   5   261503
38   6   368251
39   7   495732
40   8   637704
41   9   781419
42  10   922791
43  11  1064686
44  12  1211387
45  13  1369908
46  14  1512348
47  15  1657573
48  16  1788151
49  17  1912183
50  18  2003349
51  19  2094848
52  20  2177041
53  21  2270523
54  22  2373095
55  23  2515506
56  24  2685012
57  25  2813594
58  26  2840546
59  27  2720929
60  28  2494415
61  29  2184710
62  30  1883979
63  31  1582509
64  32  1291196
65  33  1044327
66  34   863272
67  35   715397
68  36   597362
69  37   484327
70  38   392520
71  39   298192
72  40   215130
73  41   139163
74  42    74163
75  43    32476
76  44    11321
77  45     2478

# Computation $$T_{i}^{30}= \sum_{b} \frac{h_{ib}^{30} \times T_b}{24 \times 30}$$

## 30-day exposure

In [6]:
result_30 <- df_deg_bins[, .(T_i31_60 = sum(N_hours * Temp / 24 / 30, na.rm = TRUE)), 
                          by = .(Measured_date_CDC, cell_x, cell_y)]
sprintf("%i x %i dataframe", nrow(result_30), ncol(result_30))
head(result_30,2)

[1] "173657 x 4 dataframe"

  Measured_date_CDC cell_x cell_y T_i31_60
1 42474             91.9   27.6   0.8430556
2 42473             91.9   27.6   0.7833333

In [7]:
data.frame(result_30) %>% 
        select(T_i31_60)%>%
        stargazer(nobs=TRUE, digits = 2,
                  summary.stat = c("n","mean", "sd","min","p25","median","p75","max"),
                  title = c("Summary statistics"),
                  type="text"
                     )

Summary statistics
======================================================================
Statistic    N    Mean  St. Dev.  Min   Pctl(25) Median Pctl(75)  Max
----------------------------------------------------------------------
T_i31_60  173,657 22.23   6.82   -17.13  17.27   23.32   27.17   37.23
----------------------------------------------------------------------

# Categorize temperature into bins

### Air temperature thresholds

In [8]:
thresholds_T <- c(-18,17,21,23,25,27,29,31,33,40)

In [9]:
T_bins_labels <- c("<=17°C","(17,21]","(21,23]","(23,25]","(25,27]","(27,29]","(29,31]","(31,33]",">33°C")

In [10]:
result_bins <- result_30 %>%
                    mutate(T_i31_60_bin = cut(T_i31_60, breaks = thresholds_T, 
                                           labels = T_bins_labels ,
                                           include.lowest = TRUE))
sprintf("%i x %i dataframe", nrow(result_bins), ncol(result_bins))
head(result_bins,2)

[1] "173657 x 5 dataframe"

  Measured_date_CDC cell_x cell_y T_i31_60  T_i31_60_bin
1 42474             91.9   27.6   0.8430556 <=17°C
2 42473             91.9   27.6   0.7833333 <=17°C

## SAVE

In [11]:
fwrite(result_bins,"./output/df_T_cells_CDC_31_60.csv")