In [1]:
list.of.packages <- c("tidyverse","data.table","sf")
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages, repos = "http://cran.us.r-project.org")

invisible(lapply(list.of.packages, library, character.only = TRUE))

options(repr.matrix.max.rows=500, repr.matrix.max.cols=1200, message=FALSE, warning=TRUE)

── Attaching core tidyverse packages ───────────────────────────────────────────────────────────────────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.2.0     ✔ readr     2.2.0
✔ forcats   1.0.1     ✔ stringr   1.6.0
✔ ggplot2   4.0.2     ✔ tibble    3.3.1
✔ lubridate 1.9.5     ✔ tidyr     1.3.2
✔ purrr     1.2.1
── Conflicts ─────────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

Attachement du package : ‘data.table’


Les objets suivants sont masqués depuis ‘package:lubridate’:

    hour, isoweek, mday, minute, month, quarter, second, wday, week,
    yday, year


Les objets suivants sont masqués depuis ‘package:dplyr’:

    between, first, last


L'objet suivant est masqué depuis ‘package:purrr’:

    transpose


Linking to GEOS 3.14.1, GDAL 3.12.2, PROJ 9.7.1; sf_use_s2() is TRUE

# DHS 2015

In [2]:
df_DHS_15 <- readRDS("../0_input/DHS_data/output/df_men_2015_16.rds")
sprintf("%i x %i dataframe", nrow(df_DHS_15), ncol(df_DHS_15))
head(df_DHS_15,2)

[1] "111674 x 87 dataframe"

  DHS_round DHSCLUST State_2011               District_2011 cell_x_01 cell_y_01
1 2015      10001    Andaman & Nicobar Island South Andaman 92.7      11.7
2 2015      10001    Andaman & Nicobar Island South Andaman 92.7      11.7
  cell_x_025 cell_y_025 HH_ID Men_id          Resp_nb Interview_month
1 92.75      11.75      17     01000117     1 1       7
2 92.75      11.75      20     01000120     2 2       7
  Interview_year Interview_day Measured_date_CDC Measured_date Current_age
1 2015           21            42204             2015-07-21    28
2 2015           19            42202             2015-07-19    16
  Age_group Religion_hindu Religion_muslim Religion_not_hindu_nor_muslim
1 25-29     1              0               0
2 15-19     1              0               0
  Ethni_SC Ethni_ST Ethni_OBC Ethni_other N_year_educ Smoker Health_insurance
1 0        0        0         1           10          1      0
2 0        0        0         1           10          0      0
  Profession Blood_pressure_systo Blood_pressure_diasto Blood_glucose_level
1 manual     137                  99                    185
2 no_work    117                  69                    109
  Diet_milk_curd_daily Diet_milk_curd_week Diet_milk_curd_oc
1 0                    1                   0
2 0                    1                   0
  Diet_milk_curd_never Diet_pulses_beans_daily Diet_pulses_beans_week
1 0                    0                       1
2 0                    0                       1
  Diet_pulses_beans_oc Diet_pulses_beans_never Diet_green_veg_daily
1 0                    0                       0
2 0                    0                       0
  Diet_green_veg_week Diet_green_veg_oc Diet_green_veg_never Diet_fruits_daily
1 1                   0                 0                    0
2 1                   0                 0                    0
  Diet_fruits_week Diet_fruits_oc Diet_fruits_never Diet_eggs_daily
1 1                0              0                 0
2 1                0              0                 0
  Diet_eggs_week Diet_eggs_oc Diet_eggs_never Diet_fish_daily Diet_fish_week
1 1              0            0               0               1
2 1              0            0               0               1
  Diet_fish_oc Diet_fish_never Diet_chicken_meat_daily Diet_chicken_meat_week
1 0            0               0                       1
2 0            0               0                       1
  Diet_chicken_meat_oc Diet_chicken_meat_never Diet_fried_food_daily
1 0                    0                       0
2 0                    0                       0
  Diet_fried_food_week Diet_fried_food_oc Diet_fried_food_never
1 1                    0                  0
2 1                    0                  0
  Diet_aerated_drinks_daily Diet_aerated_drinks_week Diet_aerated_drinks_oc
1 0                         0                        1
2 0                         0                        1
  Diet_aerated_drinks_never Wealth_lowest Wealth_second Wealth_middle
1 0                         0             0             1
2 0                         0             0             0
  Wealth_fourth Wealth_highest Urban Usual_resident Blood_hemo_level_alti
1 0             0              1     1              162
2 1             0              1     1              150
  Body_mass_index Bednet_slept HH_time_water_source HH_air_conditioner
1 24.16           1            0                    0
2 21.48           1            0                    0
  HH_treat_water HH_no_toilet HH_well_water cell_x.x cell_y.x cell_x.y cell_y.y
1 0              0            0             92.7     11.7     92.75    11.75
2 1              0            0             92.7     11.7     92.75    11.75

# DHS 2019

In [3]:
df_DHS_19 <- readRDS("../0_input/DHS_data/output/df_men_2019.rds")
sprintf("%i x %i dataframe", nrow(df_DHS_19), ncol(df_DHS_19))
head(df_DHS_19,2)

[1] "47587 x 87 dataframe"

  DHS_round DHSCLUST State_2011      District_2011 cell_x_01 cell_y_01
1 2019      130      Jammu & Kashmir Kupwara       74.2      34.4
2 2019      130      Jammu & Kashmir Kupwara       74.2      34.4
  cell_x_025 cell_y_025 HH_ID Men_id          Resp_nb Interview_month
1 74.25      34.5       80      0100103080  5 5       12
2 74.25      34.5       80      0100103080  6 6       12
  Interview_year Interview_day Measured_date_CDC Measured_date Current_age
1 2019           2             43799             2019-12-02    24
2 2019           2             43799             2019-12-02    21
  Age_group Religion_hindu Religion_muslim Religion_not_hindu_nor_muslim
1 20-24     0              1               0
2 20-24     0              1               0
  Ethni_SC Ethni_ST Ethni_OBC Ethni_other N_year_educ Smoker Health_insurance
1 0        0        0         1           8           0      0
2 0        0        0         1           4           0      0
  Profession Blood_pressure_systo Blood_pressure_diasto Blood_glucose_level
1 no_work    134                  91                    101
2 agri       105                  70                    105
  Diet_milk_curd_daily Diet_milk_curd_week Diet_milk_curd_oc
1 0                    1                   0
2 0                    1                   0
  Diet_milk_curd_never Diet_pulses_beans_daily Diet_pulses_beans_week
1 0                    0                       0
2 0                    0                       0
  Diet_pulses_beans_oc Diet_pulses_beans_never Diet_green_veg_daily
1 1                    0                       0
2 1                    0                       0
  Diet_green_veg_week Diet_green_veg_oc Diet_green_veg_never Diet_fruits_daily
1 1                   0                 0                    0
2 1                   0                 0                    0
  Diet_fruits_week Diet_fruits_oc Diet_fruits_never Diet_eggs_daily
1 1                0              0                 0
2 0                1              0                 0
  Diet_eggs_week Diet_eggs_oc Diet_eggs_never Diet_fish_daily Diet_fish_week
1 0              1            0               0               0
2 1              0            0               0               0
  Diet_fish_oc Diet_fish_never Diet_chicken_meat_daily Diet_chicken_meat_week
1 1            0               0                       1
2 1            0               0                       1
  Diet_chicken_meat_oc Diet_chicken_meat_never Diet_fried_food_daily
1 0                    0                       0
2 0                    0                       0
  Diet_fried_food_week Diet_fried_food_oc Diet_fried_food_never
1 0                    1                  0
2 1                    0                  0
  Diet_aerated_drinks_daily Diet_aerated_drinks_week Diet_aerated_drinks_oc
1 0                         0                        1
2 0                         1                        0
  Diet_aerated_drinks_never Wealth_lowest Wealth_second Wealth_middle
1 0                         0             1             0
2 0                         0             1             0
  Wealth_fourth Wealth_highest Urban Usual_resident Blood_hemo_level_alti
1 0             0              0     1              117
2 0             0              0     1              155
  Body_mass_index Bednet_slept HH_time_water_source HH_air_conditioner
1 21.53           0            0                    0
2 20.40           0            0                    0
  HH_treat_water HH_no_toilet HH_well_water cell_x.x cell_y.x cell_x.y cell_y.y
1 1              0            0             74.2     34.4     74.25    34.5
2 1              0            0             74.2     34.4     74.25    34.5

# Merge DHS

In [4]:
df_DHS <- bind_rows(df_DHS_15,df_DHS_19)
sprintf("%i x %i dataframe", nrow(df_DHS), ncol(df_DHS))
head(df_DHS,2)

[1] "159261 x 87 dataframe"

  DHS_round DHSCLUST State_2011               District_2011 cell_x_01 cell_y_01
1 2015      10001    Andaman & Nicobar Island South Andaman 92.7      11.7
2 2015      10001    Andaman & Nicobar Island South Andaman 92.7      11.7
  cell_x_025 cell_y_025 HH_ID Men_id          Resp_nb Interview_month
1 92.75      11.75      17     01000117     1 1       7
2 92.75      11.75      20     01000120     2 2       7
  Interview_year Interview_day Measured_date_CDC Measured_date Current_age
1 2015           21            42204             2015-07-21    28
2 2015           19            42202             2015-07-19    16
  Age_group Religion_hindu Religion_muslim Religion_not_hindu_nor_muslim
1 25-29     1              0               0
2 15-19     1              0               0
  Ethni_SC Ethni_ST Ethni_OBC Ethni_other N_year_educ Smoker Health_insurance
1 0        0        0         1           10          1      0
2 0        0        0         1           10          0      0
  Profession Blood_pressure_systo Blood_pressure_diasto Blood_glucose_level
1 manual     137                  99                    185
2 no_work    117                  69                    109
  Diet_milk_curd_daily Diet_milk_curd_week Diet_milk_curd_oc
1 0                    1                   0
2 0                    1                   0
  Diet_milk_curd_never Diet_pulses_beans_daily Diet_pulses_beans_week
1 0                    0                       1
2 0                    0                       1
  Diet_pulses_beans_oc Diet_pulses_beans_never Diet_green_veg_daily
1 0                    0                       0
2 0                    0                       0
  Diet_green_veg_week Diet_green_veg_oc Diet_green_veg_never Diet_fruits_daily
1 1                   0                 0                    0
2 1                   0                 0                    0
  Diet_fruits_week Diet_fruits_oc Diet_fruits_never Diet_eggs_daily
1 1                0              0                 0
2 1                0              0                 0
  Diet_eggs_week Diet_eggs_oc Diet_eggs_never Diet_fish_daily Diet_fish_week
1 1              0            0               0               1
2 1              0            0               0               1
  Diet_fish_oc Diet_fish_never Diet_chicken_meat_daily Diet_chicken_meat_week
1 0            0               0                       1
2 0            0               0                       1
  Diet_chicken_meat_oc Diet_chicken_meat_never Diet_fried_food_daily
1 0                    0                       0
2 0                    0                       0
  Diet_fried_food_week Diet_fried_food_oc Diet_fried_food_never
1 1                    0                  0
2 1                    0                  0
  Diet_aerated_drinks_daily Diet_aerated_drinks_week Diet_aerated_drinks_oc
1 0                         0                        1
2 0                         0                        1
  Diet_aerated_drinks_never Wealth_lowest Wealth_second Wealth_middle
1 0                         0             0             1
2 0                         0             0             0
  Wealth_fourth Wealth_highest Urban Usual_resident Blood_hemo_level_alti
1 0             0              1     1              162
2 1             0              1     1              150
  Body_mass_index Bednet_slept HH_time_water_source HH_air_conditioner
1 24.16           1            0                    0
2 21.48           1            0                    0
  HH_treat_water HH_no_toilet HH_well_water cell_x.x cell_y.x cell_x.y cell_y.y
1 0              0            0             92.7     11.7     92.75    11.75
2 1              0            0             92.7     11.7     92.75    11.75

# Create variables

In [5]:
df_DHS_sel <- df_DHS %>%
                #Remove missing values
                filter(Usual_resident==1 & !is.na(State_2011) & !is.na(Measured_date_CDC))%>% 
                mutate(cell_x_01=round(cell_x_01,1),
                       cell_y_01=round(cell_y_01,1),
                       Measured_month = Interview_month,
                       Measured_year = Interview_year,
                       Men_anemia = case_when(is.na(Blood_hemo_level_alti) ~ NA,
                                              Blood_hemo_level_alti <130 ~ 1000,
                                              TRUE ~ 0),
                       Men_severe_anemia = case_when(is.na(Blood_hemo_level_alti) ~ NA,
                                                     Blood_hemo_level_alti <80 ~ 1000,
                                                     TRUE ~ 0),
                       Men_moderate_anemia = case_when(is.na(Blood_hemo_level_alti) ~ NA,
                                                       Blood_hemo_level_alti >= 80 & Blood_hemo_level_alti < 110 ~ 1000,
                                                       TRUE ~ 0),
                       Men_mild_anemia = case_when(is.na(Blood_hemo_level_alti) ~ NA,
                                                   Blood_hemo_level_alti >= 110 & Blood_hemo_level_alti < 130 ~ 1000,
                                                   TRUE ~ 0),
                       Men_no_anemia = case_when(is.na(Blood_hemo_level_alti) ~ NA,
                                                 Blood_hemo_level_alti >= 130 ~ 1000,
                                                 TRUE ~ 0),
                       BMI_category = case_when(is.na(Body_mass_index) ~ NA,
                                                Body_mass_index <18.5 ~ "Underweight",
                                                Body_mass_index >=18.5 & Body_mass_index <25 ~ "Normal",
                                                Body_mass_index >= 25 & Body_mass_index <30 ~ "Overweight",
                                                Body_mass_index >=30 ~ "Obese"),
                       Blood_hypertension = case_when(is.na(Blood_pressure_systo) ~ NA,
                                                      Blood_pressure_systo >=140 |Blood_pressure_diasto >= 90 ~ 1000,
                                                      TRUE ~ 0),
                       Water_fetching_risk = case_when(is.na(HH_time_water_source) ~ NA,
                                                       HH_time_water_source>0 ~ 1,
                                                       TRUE ~ 0),
                       District_ID = paste0(State_2011,"_",District_2011))
sprintf("%i x %i dataframe", nrow(df_DHS_sel), ncol(df_DHS_sel))
head(df_DHS_sel,2)

[1] "156724 x 98 dataframe"

  DHS_round DHSCLUST State_2011               District_2011 cell_x_01 cell_y_01
1 2015      10001    Andaman & Nicobar Island South Andaman 92.7      11.7
2 2015      10001    Andaman & Nicobar Island South Andaman 92.7      11.7
  cell_x_025 cell_y_025 HH_ID Men_id          Resp_nb Interview_month
1 92.75      11.75      17     01000117     1 1       7
2 92.75      11.75      20     01000120     2 2       7
  Interview_year Interview_day Measured_date_CDC Measured_date Current_age
1 2015           21            42204             2015-07-21    28
2 2015           19            42202             2015-07-19    16
  Age_group Religion_hindu Religion_muslim Religion_not_hindu_nor_muslim
1 25-29     1              0               0
2 15-19     1              0               0
  Ethni_SC Ethni_ST Ethni_OBC Ethni_other N_year_educ Smoker Health_insurance
1 0        0        0         1           10          1      0
2 0        0        0         1           10          0      0
  Profession Blood_pressure_systo Blood_pressure_diasto Blood_glucose_level
1 manual     137                  99                    185
2 no_work    117                  69                    109
  Diet_milk_curd_daily Diet_milk_curd_week Diet_milk_curd_oc
1 0                    1                   0
2 0                    1                   0
  Diet_milk_curd_never Diet_pulses_beans_daily Diet_pulses_beans_week
1 0                    0                       1
2 0                    0                       1
  Diet_pulses_beans_oc Diet_pulses_beans_never Diet_green_veg_daily
1 0                    0                       0
2 0                    0                       0
  Diet_green_veg_week Diet_green_veg_oc Diet_green_veg_never Diet_fruits_daily
1 1                   0                 0                    0
2 1                   0                 0                    0
  Diet_fruits_week Diet_fruits_oc Diet_fruits_never Diet_eggs_daily
1 1                0              0                 0
2 1                0              0                 0
  Diet_eggs_week Diet_eggs_oc Diet_eggs_never Diet_fish_daily Diet_fish_week
1 1              0            0               0               1
2 1              0            0               0               1
  Diet_fish_oc Diet_fish_never Diet_chicken_meat_daily Diet_chicken_meat_week
1 0            0               0                       1
2 0            0               0                       1
  Diet_chicken_meat_oc Diet_chicken_meat_never Diet_fried_food_daily
1 0                    0                       0
2 0                    0                       0
  Diet_fried_food_week Diet_fried_food_oc Diet_fried_food_never
1 1                    0                  0
2 1                    0                  0
  Diet_aerated_drinks_daily Diet_aerated_drinks_week Diet_aerated_drinks_oc
1 0                         0                        1
2 0                         0                        1
  Diet_aerated_drinks_never Wealth_lowest Wealth_second Wealth_middle
1 0                         0             0             1
2 0                         0             0             0
  Wealth_fourth Wealth_highest Urban Usual_resident Blood_hemo_level_alti
1 0             0              1     1              162
2 1             0              1     1              150
  Body_mass_index Bednet_slept HH_time_water_source HH_air_conditioner
1 24.16           1            0                    0
2 21.48           1            0                    0
  HH_treat_water HH_no_toilet HH_well_water cell_x.x cell_y.x cell_x.y cell_y.y
1 0              0            0             92.7     11.7     92.75    11.75
2 1              0            0             92.7     11.7     92.75    11.75
  Measured_month Measured_year Men_anemia Men_severe_anemia Men_moderate_anemia
1 7              2015          0          0                 0
2 7              2015          0          0                 0
  Men_mild_anemia Men_no_anemia BMI_category Blood_hypertension
1 0               1000          Normal       1000
2 0               1000          Normal          0
  Water_fetching_risk District_ID
1 0                   Andaman & Nicobar Island_South Andaman
2 0                   Andaman & Nicobar Island_South Andaman

# Air temperature by CDC and grid cell

## Mean temperature over past 30/20/10 days preceding measurement

In [6]:
df_T_cells <- read_csv(".././1_Grid_cell_date_data/output/df_T_cells_CDC_30_20_10.csv",show_col_types = FALSE)
sprintf("%i x %i dataframe", nrow(df_T_cells), ncol(df_T_cells))
head(df_T_cells,2)

[1] "173657 x 9 dataframe"

  Measured_date_CDC cell_x cell_y T_i30    T_i20    T_i10    T_i30_bin
1 42474             91.9   27.6   3.495833 4.510417 5.112500 <=17°C
2 42667             96.7   28.3   9.127778 8.314583 7.016667 <=17°C
  T_i20_bin T_i10_bin
1 <=17°C    <=17°C
2 <=17°C    <=17°C

## Number of hours in each temperature bin over past 30/20/10 days

In [7]:
df_T_cells_hours <- read_csv(".././1_Grid_cell_date_data/output/df_T_cells_CDC_Nhours.csv",show_col_types = FALSE)
sprintf("%i x %i dataframe", nrow(df_T_cells_hours), ncol(df_T_cells_hours))
head(df_T_cells_hours,2)

[1] "173657 x 30 dataframe"

  Measured_date_CDC cell_x cell_y T_Bin_17_21_Nhours_on30
1 42022             74.0   15.4   239
2 42022             74.1   15.2   234
  T_Bin_21_23_Nhours_on30 T_Bin_23_25_Nhours_on30 T_Bin_25_27_Nhours_on30
1 113                     90                      78
2 113                     91                      82
  T_Bin_27_29_Nhours_on30 T_Bin_29_31_Nhours_on30 T_Bin_inf17_Nhours_on30
1 72                       93                     30
2 71                      106                     15
  T_Bin_31_33_Nhours_on30 T_Bin_sup33_Nhours_on30 T_Bin_17_21_Nhours_on20
1 5                       0                       157
2 8                       0                       157
  T_Bin_21_23_Nhours_on20 T_Bin_23_25_Nhours_on20 T_Bin_25_27_Nhours_on20
1 73                      63                      50
2 77                      58                      60
  T_Bin_27_29_Nhours_on20 T_Bin_29_31_Nhours_on20 T_Bin_inf17_Nhours_on20
1 45                      57                      30
2 44                      61                      15
  T_Bin_31_33_Nhours_on20 T_Bin_sup33_Nhours_on20 T_Bin_17_21_Nhours_on10
1 5                       0                       72
2 8                       0                       81
  T_Bin_21_23_Nhours_on10 T_Bin_23_25_Nhours_on10 T_Bin_25_27_Nhours_on10
1 24                      23                      21
2 23                      23                      25
  T_Bin_27_29_Nhours_on10 T_Bin_29_31_Nhours_on10 T_Bin_inf17_Nhours_on10
1 22                      43                      30
2 21                      44                      15
  T_Bin_31_33_Nhours_on10 T_Bin_sup33_Nhours_on10
1 5                       0
2 8                       0

## Number of days in each temperature bin over past 30/20/10 days

In [8]:
df_T_cells_days <- read_csv(".././1_Grid_cell_date_data/output/df_T_cells_CDC_Ndays.csv",show_col_types = FALSE)
sprintf("%i x %i dataframe", nrow(df_T_cells_days), ncol(df_T_cells_days))
head(df_T_cells_days,2)

[1] "173657 x 84 dataframe"

  Measured_date_CDC cell_x cell_y T_MeanBin_23_25_Ndays_on30
1 42022             74.0   15.4   23
2 42022             74.1   15.2   24
  T_MeanBin_21_23_Ndays_on30 T_MeanBin_25_27_Ndays_on30
1 6                          1
2 3                          3
  T_MeanBin_inf17_Ndays_on30 T_MeanBin_17_21_Ndays_on30
1 0                          0
2 0                          0
  T_MeanBin_27_29_Ndays_on30 T_MeanBin_29_31_Ndays_on30
1 0                          0
2 0                          0
  T_MeanBin_31_33_Ndays_on30 T_MeanBin_sup33_Ndays_on30
1 0                          0
2 0                          0
  T_MeanBin_23_25_Ndays_on20 T_MeanBin_21_23_Ndays_on20
1 14                         6
2 16                         3
  T_MeanBin_25_27_Ndays_on20 T_MeanBin_inf17_Ndays_on20
1 0                          0
2 1                          0
  T_MeanBin_17_21_Ndays_on20 T_MeanBin_27_29_Ndays_on20
1 0                          0
2 0                          0
  T_MeanBin_29_31_Ndays_on20 T_MeanBin_31_33_Ndays_on20
1 0                          0
2 0                          0
  T_MeanBin_sup33_Ndays_on20 T_MeanBin_23_25_Ndays_on10
1 0                           7
2 0                          10
  T_MeanBin_21_23_Ndays_on10 T_MeanBin_25_27_Ndays_on10
1 3                          0
2 0                          0
  T_MeanBin_inf17_Ndays_on10 T_MeanBin_17_21_Ndays_on10
1 0                          0
2 0                          0
  T_MeanBin_27_29_Ndays_on10 T_MeanBin_29_31_Ndays_on10
1 0                          0
2 0                          0
  T_MeanBin_31_33_Ndays_on10 T_MeanBin_sup33_Ndays_on10
1 0                          0
2 0                          0
  T_MinBin_17_19_Ndays_on30 T_MinBin_15_17_Ndays_on30 T_MinBin_19_21_Ndays_on30
1 17                        7                         5
2 15                        5                         9
  T_MinBin_21_23_Ndays_on30 T_MinBin_inf11_Ndays_on30 T_MinBin_11_13_Ndays_on30
1 1                         0                         0
2 1                         0                         0
  T_MinBin_13_15_Ndays_on30 T_MinBin_23_25_Ndays_on30 T_MinBin_sup25_Ndays_on30
1 0                         0                         0
2 0                         0                         0
  T_MinBin_17_19_Ndays_on20 T_MinBin_15_17_Ndays_on20 T_MinBin_19_21_Ndays_on20
1  9                        7                         4
2 10                        5                         5
  T_MinBin_21_23_Ndays_on20 T_MinBin_inf11_Ndays_on20 T_MinBin_11_13_Ndays_on20
1 0                         0                         0
2 0                         0                         0
  T_MinBin_13_15_Ndays_on20 T_MinBin_23_25_Ndays_on20 T_MinBin_sup25_Ndays_on20
1 0                         0                         0
2 0                         0                         0
  T_MinBin_17_19_Ndays_on10 T_MinBin_15_17_Ndays_on10 T_MinBin_19_21_Ndays_on10
1 3                         7                         0
2 5                         5                         0
  T_MinBin_21_23_Ndays_on10 T_MinBin_inf11_Ndays_on10 T_MinBin_11_13_Ndays_on10
1 0                         0                         0
2 0                         0                         0
  T_MinBin_13_15_Ndays_on10 T_MinBin_23_25_Ndays_on10 T_MinBin_sup25_Ndays_on10
1 0                         0                         0
2 0                         0                         0
  T_MaxBin_29_31_Ndays_on30 T_MaxBin_31_33_Ndays_on30 T_MaxBin_27_29_Ndays_on30
1 21                        3                         2
2 19                        5                         2
  T_MaxBin_25_27_Ndays_on30 T_MaxBin_23_25_Ndays_on30 T_MaxBin_inf21_Ndays_on30
1 3                         1                         0
2 4                         0                         0
  T_MaxBin_21_23_Ndays_on30 T_MaxBin_33_35_Ndays_on30 T_MaxBin_sup35_Ndays_on30
1 0                         0                         0
2 0                         0                         0
  T_MaxBin_29_31_Ndays_on20 T_MaxBin_31_33_Ndays_on20 T_MaxBin_27_29_Ndays_on20
1 11                        3                         2
2  9                        5                         2
  T_MaxBin_25_27_Ndays_on20 T_MaxBin_23_25_Ndays_on20 T_MaxBin_inf21_Ndays_on20
1 3                         1                         0
2 4                         0                         0
  T_MaxBin_21_23_Ndays_on20 T_MaxBin_33_35_Ndays_on20 T_MaxBin_sup35_Ndays_on20
1 0                         0                         0
2 0                         0                         0
  T_MaxBin_29_31_Ndays_on10 T_MaxBin_31_33_Ndays_on10 T_MaxBin_27_29_Ndays_on10
1 7                         3                         0
2 5                         5                         0
  T_MaxBin_25_27_Ndays_on10 T_MaxBin_23_25_Ndays_on10 T_MaxBin_inf21_Ndays_on10
1 0                         0                         0
2 0                         0                         0
  T_MaxBin_21_23_Ndays_on10 T_MaxBin_33_35_Ndays_on10 T_MaxBin_sup35_Ndays_on10
1 0                         0                         0
2 0                         0                         0

# Wet-bulb temperature by CDC and grid cell

## Mean temperature over past 30/20/10 days preceding measurement

In [9]:
df_WB_cells <- read_csv(".././1_Grid_cell_date_data/output/df_WB_cells_CDC_30_20_10.csv",show_col_types = FALSE)
sprintf("%i x %i dataframe", nrow(df_WB_cells), ncol(df_WB_cells))
head(df_WB_cells,2)

[1] "126725 x 9 dataframe"

  Measured_date_CDC cell_x cell_y WB_i30    WB_i20    WB_i10   WB_i30_bin
1 42474             91.75  27.50   5.580556  6.608333 7.283333 <=14°C
2 42660             96.75  28.25  10.943056 10.629167 9.354167 <=14°C
  WB_i20_bin WB_i10_bin
1 <=14°C     <=14°C
2 <=14°C     <=14°C

## Number of hours in each temperature bin over past 30/20/10 days

In [10]:
df_WB_cells_hours <- read_csv(".././1_Grid_cell_date_data/output/df_WB_cells_CDC_Nhours.csv",show_col_types = FALSE)
sprintf("%i x %i dataframe", nrow(df_WB_cells_hours), ncol(df_WB_cells_hours))
head(df_WB_cells_hours,2)

[1] "126725 x 30 dataframe"

  Measured_date_CDC cell_x cell_y WB_Bin_18_20_Nhours_on30
1 42022             74     15.25  183
2 42022             74     15.50  124
  WB_Bin_20_22_Nhours_on30 WB_Bin_22_24_Nhours_on30 WB_Bin_24_26_Nhours_on30
1 153                      180                       91
2  97                      140                      107
  WB_Bin_16_18_Nhours_on30 WB_Bin_14_16_Nhours_on30 WB_Bin_inf14_Nhours_on30
1  82                      25                        4
2 118                      79                       48
  WB_Bin_26_28_Nhours_on30 WB_Bin_sup28_Nhours_on30 WB_Bin_18_20_Nhours_on20
1 2                        0                        110
2 7                        0                         90
  WB_Bin_20_22_Nhours_on20 WB_Bin_22_24_Nhours_on20 WB_Bin_24_26_Nhours_on20
1 112                      119                      55
2  68                       96                      68
  WB_Bin_16_18_Nhours_on20 WB_Bin_14_16_Nhours_on20 WB_Bin_inf14_Nhours_on20
1 54                       25                        4
2 72                       41                       43
  WB_Bin_26_28_Nhours_on20 WB_Bin_sup28_Nhours_on20 WB_Bin_18_20_Nhours_on10
1 1                        0                        53
2 2                        0                        28
  WB_Bin_20_22_Nhours_on10 WB_Bin_22_24_Nhours_on10 WB_Bin_24_26_Nhours_on10
1 35                       52                       24
2 27                       46                       24
  WB_Bin_16_18_Nhours_on10 WB_Bin_14_16_Nhours_on10 WB_Bin_inf14_Nhours_on10
1 47                       25                        4
2 36                       36                       43
  WB_Bin_26_28_Nhours_on10 WB_Bin_sup28_Nhours_on10
1 0                        0
2 0                        0

## Number of days in each temperature bin over past 30/20/10 days

In [11]:
df_WB_cells_days <- read_csv(".././1_Grid_cell_date_data/output/df_WB_cells_CDC_Ndays.csv",show_col_types = FALSE)
sprintf("%i x %i dataframe", nrow(df_WB_cells_days), ncol(df_WB_cells_days))
head(df_WB_cells_days,2)

[1] "126725 x 84 dataframe"

  Measured_date_CDC cell_x cell_y WB_MeanBin_20_22_Ndays_on30
1 42022             74     15.25  18
2 42022             74     15.50  15
  WB_MeanBin_18_20_Ndays_on30 WB_MeanBin_22_24_Ndays_on30
1 4                           8
2 6                           5
  WB_MeanBin_16_18_Ndays_on30 WB_MeanBin_inf14_Ndays_on30
1 0                           0
2 4                           0
  WB_MeanBin_14_16_Ndays_on30 WB_MeanBin_24_26_Ndays_on30
1 0                           0
2 0                           0
  WB_MeanBin_26_28_Ndays_on30 WB_MeanBin_sup28_Ndays_on30
1 0                           0
2 0                           0
  WB_MeanBin_20_22_Ndays_on20 WB_MeanBin_18_20_Ndays_on20
1 11                          4
2  9                          3
  WB_MeanBin_22_24_Ndays_on20 WB_MeanBin_16_18_Ndays_on20
1 5                           0
2 4                           4
  WB_MeanBin_inf14_Ndays_on20 WB_MeanBin_14_16_Ndays_on20
1 0                           0
2 0                           0
  WB_MeanBin_24_26_Ndays_on20 WB_MeanBin_26_28_Ndays_on20
1 0                           0
2 0                           0
  WB_MeanBin_sup28_Ndays_on20 WB_MeanBin_20_22_Ndays_on10
1 0                           6
2 0                           3
  WB_MeanBin_18_20_Ndays_on10 WB_MeanBin_22_24_Ndays_on10
1 4                           0
2 3                           0
  WB_MeanBin_16_18_Ndays_on10 WB_MeanBin_inf14_Ndays_on10
1 0                           0
2 4                           0
  WB_MeanBin_14_16_Ndays_on10 WB_MeanBin_24_26_Ndays_on10
1 0                           0
2 0                           0
  WB_MeanBin_26_28_Ndays_on10 WB_MeanBin_sup28_Ndays_on10
1 0                           0
2 0                           0
  WB_MinBin_18_20_Ndays_on30 WB_MinBin_16_18_Ndays_on30
1 13                         11
2  1                          8
  WB_MinBin_14_16_Ndays_on30 WB_MinBin_12_14_Ndays_on30
1  4                         2
2 11                         5
  WB_MinBin_10_12_Ndays_on30 WB_MinBin_inf10_Ndays_on30
1 0                          0
2 5                          0
  WB_MinBin_20_22_Ndays_on30 WB_MinBin_22_24_Ndays_on30
1 0                          0
2 0                          0
  WB_MinBin_sup24_Ndays_on30 WB_MinBin_18_20_Ndays_on20
1 0                          8
2 0                          1
  WB_MinBin_16_18_Ndays_on20 WB_MinBin_14_16_Ndays_on20
1 6                          4
2 7                          4
  WB_MinBin_12_14_Ndays_on20 WB_MinBin_10_12_Ndays_on20
1 2                          0
2 3                          5
  WB_MinBin_inf10_Ndays_on20 WB_MinBin_20_22_Ndays_on20
1 0                          0
2 0                          0
  WB_MinBin_22_24_Ndays_on20 WB_MinBin_sup24_Ndays_on20
1 0                          0
2 0                          0
  WB_MinBin_18_20_Ndays_on10 WB_MinBin_16_18_Ndays_on10
1 1                          3
2 0                          1
  WB_MinBin_14_16_Ndays_on10 WB_MinBin_12_14_Ndays_on10
1 4                          2
2 1                          3
  WB_MinBin_10_12_Ndays_on10 WB_MinBin_inf10_Ndays_on10
1 0                          0
2 5                          0
  WB_MinBin_20_22_Ndays_on10 WB_MinBin_22_24_Ndays_on10
1 0                          0
2 0                          0
  WB_MinBin_sup24_Ndays_on10 WB_MaxBin_24_26_Ndays_on30
1 0                          16
2 0                          18
  WB_MaxBin_22_24_Ndays_on30 WB_MaxBin_26_28_Ndays_on30
1 12                         2
2  7                         5
  WB_MaxBin_inf18_Ndays_on30 WB_MaxBin_18_20_Ndays_on30
1 0                          0
2 0                          0
  WB_MaxBin_20_22_Ndays_on30 WB_MaxBin_28_30_Ndays_on30
1 0                          0
2 0                          0
  WB_MaxBin_30_32_Ndays_on30 WB_MaxBin_sup32_Ndays_on30
1 0                          0
2 0                          0
  WB_MaxBin_24_26_Ndays_on20 WB_MaxBin_22_24_Ndays_on20
1  9                         10
2 12                          7
  WB_MaxBin_26_28_Ndays_on20 WB_MaxBin_inf18_Ndays_on20
1 1                          0
2 1                          0
  WB_MaxBin_18_20_Ndays_on20 WB_MaxBin_20_22_Ndays_on20
1 0                          0
2 0                          0
  WB_MaxBin_28_30_Ndays_on20 WB_MaxBin_30_32_Ndays_on20
1 0                          0
2 0                          0
  WB_MaxBin_sup32_Ndays_on20 WB_MaxBin_24_26_Ndays_on10
1 0                          4
2 0                          5
  WB_MaxBin_22_24_Ndays_on10 WB_MaxBin_26_28_Ndays_on10
1 6                          0
2 5                          0
  WB_MaxBin_inf18_Ndays_on10 WB_MaxBin_18_20_Ndays_on10
1 0                          0
2 0                          0
  WB_MaxBin_20_22_Ndays_on10 WB_MaxBin_28_30_Ndays_on10
1 0                          0
2 0                          0
  WB_MaxBin_30_32_Ndays_on10 WB_MaxBin_sup32_Ndays_on10
1 0                          0
2 0                          0

# Total Precipitations by CDC and grid cell

In [12]:
df_P_cells <- read_csv(".././1_Grid_cell_date_data/output/df_precip_cells_CDC_30_20_10.csv",show_col_types = FALSE)
sprintf("%i x %i dataframe", nrow(df_P_cells), ncol(df_P_cells))
head(df_P_cells,2)

[1] "126725 x 6 dataframe"

  Measured_date_CDC cell_x cell_y P_tot_30  P_tot_20  P_tot_10
1 42203             92.75  11.75  0.2802348 0.1772218 0.11717701
2 42205             92.75   9.25  0.1929393 0.1285033 0.09183168

# Malaria

In [13]:
sf_malaria <- st_read("../0_input/malaria/output/2011_Dist_malaria.gpkg")

Reading layer `districts' from data source
  `/diskdata/cired/lepault/V6_Heat_India_30_20_10/0_input/malaria/2011_Dist_malaria.gpkg'
  using driver `GPKG'
Simple feature collection with 641 features and 13 fields
Geometry type: MULTIPOLYGON
Dimension:     XY
Bounding box:  xmin: 68.18625 ymin: 6.755953 xmax: 97.41529 ymax: 37.07827
Geodetic CRS:  WGS 84

In [14]:
districts_telan <- unlist(df_DHS_15%>%
                                filter(State_2011=="Telangana")%>%distinct(District_2011),
                          use.names=FALSE)
districts_telan

 [1] "Nalgonda"    "Mahbubnagar" "Nizamabad"   "Medak"       "Khammam"
 [6] "Rangareddy"  "Adilabad"    "Warangal"    "Hyderabad"   "Karimnagar"

In [15]:
df_malaria <- sf_malaria %>%
                    st_drop_geometry()%>%
                    mutate(API_sup_1 = ifelse(API>1,1,ifelse(!is.na(API),0,NA)),
                           ST_NM = ifelse(ST_NM=="Andhra Pradesh" & DISTRICT %in% districts_telan, "Telangana",ST_NM))
sprintf("%i x %i dataframe", nrow(df_malaria), ncol(df_malaria))
head(df_malaria,2)

[1] "641 x 14 dataframe"

  DISTRICT ST_NM         ST_CEN_CD DT_CEN_CD censuscode PF    ABER  API  SPR
1 Adilabad Telangana     28         1        532        71.43 13.07 0.01 0.01
2 Agra     Uttar Pradesh  9        15        146         2.44  3.18 0.02 0.05
  AFI  SFR  death.Pv death.Pf API_sup_1
1 0.01 0.01 0        0        0
2 0.00 0.00 0        0        0

## Join to men measures

In [16]:
df_DHS_final <- df_DHS_sel %>%
                        left_join(df_T_cells,by=c("Measured_date_CDC","cell_x_01"="cell_x","cell_y_01"="cell_y"))%>%
                        left_join(df_T_cells_hours,by=c("Measured_date_CDC","cell_x_01"="cell_x","cell_y_01"="cell_y"))%>%
                        left_join(df_T_cells_days,by=c("Measured_date_CDC","cell_x_01"="cell_x","cell_y_01"="cell_y"))%>%
                        left_join(df_WB_cells,by=c("Measured_date_CDC","cell_x_025"="cell_x","cell_y_025"="cell_y"))%>%
                        left_join(df_WB_cells_hours,by=c("Measured_date_CDC","cell_x_025"="cell_x","cell_y_025"="cell_y"))%>%
                        left_join(df_WB_cells_days,by=c("Measured_date_CDC","cell_x_025"="cell_x","cell_y_025"="cell_y"))%>%
                        left_join(df_P_cells,by=c("Measured_date_CDC","cell_x_025"="cell_x","cell_y_025"="cell_y"))%>%
                        left_join(df_malaria%>%select(ST_NM,DISTRICT,API_sup_1),
                                  by=c("State_2011"="ST_NM","District_2011"="DISTRICT"))%>%
                        filter(!is.na(Men_anemia)&!is.na(T_i30))
sprintf("%i x %i dataframe", nrow(df_DHS_final), ncol(df_DHS_final))
head(df_DHS_final,2)

[1] "150101 x 330 dataframe"

  DHS_round DHSCLUST State_2011               District_2011 cell_x_01 cell_y_01
1 2015      10001    Andaman & Nicobar Island South Andaman 92.7      11.7
2 2015      10001    Andaman & Nicobar Island South Andaman 92.7      11.7
  cell_x_025 cell_y_025 HH_ID Men_id          Resp_nb Interview_month
1 92.75      11.75      17     01000117     1 1       7
2 92.75      11.75      20     01000120     2 2       7
  Interview_year Interview_day Measured_date_CDC Measured_date Current_age
1 2015           21            42204             2015-07-21    28
2 2015           19            42202             2015-07-19    16
  Age_group Religion_hindu Religion_muslim Religion_not_hindu_nor_muslim
1 25-29     1              0               0
2 15-19     1              0               0
  Ethni_SC Ethni_ST Ethni_OBC Ethni_other N_year_educ Smoker Health_insurance
1 0        0        0         1           10          1      0
2 0        0        0         1           10          0      0
  Profession Blood_pressure_systo Blood_pressure_diasto Blood_glucose_level
1 manual     137                  99                    185
2 no_work    117                  69                    109
  Diet_milk_curd_daily Diet_milk_curd_week Diet_milk_curd_oc
1 0                    1                   0
2 0                    1                   0
  Diet_milk_curd_never Diet_pulses_beans_daily Diet_pulses_beans_week
1 0                    0                       1
2 0                    0                       1
  Diet_pulses_beans_oc Diet_pulses_beans_never Diet_green_veg_daily
1 0                    0                       0
2 0                    0                       0
  Diet_green_veg_week Diet_green_veg_oc Diet_green_veg_never Diet_fruits_daily
1 1                   0                 0                    0
2 1                   0                 0                    0
  Diet_fruits_week Diet_fruits_oc Diet_fruits_never Diet_eggs_daily
1 1                0              0                 0
2 1                0              0                 0
  Diet_eggs_week Diet_eggs_oc Diet_eggs_never Diet_fish_daily Diet_fish_week
1 1              0            0               0               1
2 1              0            0               0               1
  Diet_fish_oc Diet_fish_never Diet_chicken_meat_daily Diet_chicken_meat_week
1 0            0               0                       1
2 0            0               0                       1
  Diet_chicken_meat_oc Diet_chicken_meat_never Diet_fried_food_daily
1 0                    0                       0
2 0                    0                       0
  Diet_fried_food_week Diet_fried_food_oc Diet_fried_food_never
1 1                    0                  0
2 1                    0                  0
  Diet_aerated_drinks_daily Diet_aerated_drinks_week Diet_aerated_drinks_oc
1 0                         0                        1
2 0                         0                        1
  Diet_aerated_drinks_never Wealth_lowest Wealth_second Wealth_middle
1 0                         0             0             1
2 0                         0             0             0
  Wealth_fourth Wealth_highest Urban Usual_resident Blood_hemo_level_alti
1 0             0              1     1              162
2 1             0              1     1              150
  Body_mass_index Bednet_slept HH_time_water_source HH_air_conditioner
1 24.16           1            0                    0
2 21.48           1            0                    0
  HH_treat_water HH_no_toilet HH_well_water cell_x.x cell_y.x cell_x.y cell_y.y
1 0              0            0             92.7     11.7     92.75    11.75
2 1              0            0             92.7     11.7     92.75    11.75
  Measured_month Measured_year Men_anemia Men_severe_anemia Men_moderate_anemia
1 7              2015          0          0                 0
2 7              2015          0          0                 0
  Men_mild_anemia Men_no_anemia BMI_category Blood_hypertension
1 0               1000          Normal       1000
2 0               1000          Normal          0
  Water_fetching_risk District_ID                            T_i30    T_i20
1 0                   Andaman & Nicobar Island_South Andaman 26.98750 27.00625
2 0                   Andaman & Nicobar Island_South Andaman 26.97361 26.94375
  T_i10  T_i30_bin T_i20_bin T_i10_bin T_Bin_17_21_Nhours_on30
1 26.700 (25,27]   (27,29]   (25,27]   0
2 26.875 (25,27]   (25,27]   (25,27]   0
  T_Bin_21_23_Nhours_on30 T_Bin_23_25_Nhours_on30 T_Bin_25_27_Nhours_on30
1 0                       6                       525
2 0                       4                       535
  T_Bin_27_29_Nhours_on30 T_Bin_29_31_Nhours_on30 T_Bin_inf17_Nhours_on30
1 189                     0                       0
2 181                     0                       0
  T_Bin_31_33_Nhours_on30 T_Bin_sup33_Nhours_on30 T_Bin_17_21_Nhours_on20
1 0                       0                       0
2 0                       0                       0
  T_Bin_21_23_Nhours_on20 T_Bin_23_25_Nhours_on20 T_Bin_25_27_Nhours_on20
1 0                       5                       346
2 0                       4                       360
  T_Bin_27_29_Nhours_on20 T_Bin_29_31_Nhours_on20 T_Bin_inf17_Nhours_on20
1 129                     0                       0
2 116                     0                       0
  T_Bin_31_33_Nhours_on20 T_Bin_sup33_Nhours_on20 T_Bin_17_21_Nhours_on10
1 0                       0                       0
2 0                       0                       0
  T_Bin_21_23_Nhours_on10 T_Bin_23_25_Nhours_on10 T_Bin_25_27_Nhours_on10
1 0                       5                       211
2 0                       3                       194
  T_Bin_27_29_Nhours_on10 T_Bin_29_31_Nhours_on10 T_Bin_inf17_Nhours_on10
1 24                      0                       0
2 43                      0                       0
  T_Bin_31_33_Nhours_on10 T_Bin_sup33_Nhours_on10 T_MeanBin_23_25_Ndays_on30
1 0                       0                       0
2 0                       0                       0
  T_MeanBin_21_23_Ndays_on30 T_MeanBin_25_27_Ndays_on30
1 0                          16
2 0                          16
  T_MeanBin_inf17_Ndays_on30 T_MeanBin_17_21_Ndays_on30
1 0                          0
2 0                          0
  T_MeanBin_27_29_Ndays_on30 T_MeanBin_29_31_Ndays_on30
1 14                         0
2 14                         0
  T_MeanBin_31_33_Ndays_on30 T_MeanBin_sup33_Ndays_on30
1 0                          0
2 0                          0
  T_MeanBin_23_25_Ndays_on20 T_MeanBin_21_23_Ndays_on20
1 0                          0
2 0                          0
  T_MeanBin_25_27_Ndays_on20 T_MeanBin_inf17_Ndays_on20
1 12                         0
2 12                         0
  T_MeanBin_17_21_Ndays_on20 T_MeanBin_27_29_Ndays_on20
1 0                          8
2 0                          8
  T_MeanBin_29_31_Ndays_on20 T_MeanBin_31_33_Ndays_on20
1 0                          0
2 0                          0
  T_MeanBin_sup33_Ndays_on20 T_MeanBin_23_25_Ndays_on10
1 0                          0
2 0                          0
  T_MeanBin_21_23_Ndays_on10 T_MeanBin_25_27_Ndays_on10
1 0                          9
2 0                          7
  T_MeanBin_inf17_Ndays_on10 T_MeanBin_17_21_Ndays_on10
1 0                          0
2 0                          0
  T_MeanBin_27_29_Ndays_on10 T_MeanBin_29_31_Ndays_on10
1 1                          0
2 3                          0
  T_MeanBin_31_33_Ndays_on10 T_MeanBin_sup33_Ndays_on10
1 0                          0
2 0                          0
  T_MinBin_17_19_Ndays_on30 T_MinBin_15_17_Ndays_on30 T_MinBin_19_21_Ndays_on30
1 0                         0                         0
2 0                         0                         0
  T_MinBin_21_23_Ndays_on30 T_MinBin_inf11_Ndays_on30 T_MinBin_11_13_Ndays_on30
1 0                         0                         0
2 0                         0                         0
  T_MinBin_13_15_Ndays_on30 T_MinBin_23_25_Ndays_on30 T_MinBin_sup25_Ndays_on30
1 0                         4                         26
2 0                         3                         27
  T_MinBin_17_19_Ndays_on20 T_MinBin_15_17_Ndays_on20 T_MinBin_19_21_Ndays_on20
1 0                         0                         0
2 0                         0                         0
  T_MinBin_21_23_Ndays_on20 T_MinBin_inf11_Ndays_on20 T_MinBin_11_13_Ndays_on20
1 0                         0                         0
2 0                         0                         0
  T_MinBin_13_15_Ndays_on20 T_MinBin_23_25_Ndays_on20 T_MinBin_sup25_Ndays_on20
1 0                         3                         17
2 0                         3                         17
  T_MinBin_17_19_Ndays_on10 T_MinBin_15_17_Ndays_on10 T_MinBin_19_21_Ndays_on10
1 0                         0                         0
2 0                         0                         0
  T_MinBin_21_23_Ndays_on10 T_MinBin_inf11_Ndays_on10 T_MinBin_11_13_Ndays_on10
1 0                         0                         0
2 0                         0                         0
  T_MinBin_13_15_Ndays_on10 T_MinBin_23_25_Ndays_on10 T_MinBin_sup25_Ndays_on10
1 0                         3                         7
2 0                         2                         8
  T_MaxBin_29_31_Ndays_on30 T_MaxBin_31_33_Ndays_on30 T_MaxBin_27_29_Ndays_on30
1 0                         0                         21
2 0                         0                         20
  T_MaxBin_25_27_Ndays_on30 T_MaxBin_23_25_Ndays_on30 T_MaxBin_inf21_Ndays_on30
1  9                        0                         0
2 10                        0                         0
  T_MaxBin_21_23_Ndays_on30 T_MaxBin_33_35_Ndays_on30 T_MaxBin_sup35_Ndays_on30
1 0                         0                         0
2 0                         0                         0
  T_MaxBin_29_31_Ndays_on20 T_MaxBin_31_33_Ndays_on20 T_MaxBin_27_29_Ndays_on20
1 0                         0                         15
2 0                         0                         13
  T_MaxBin_25_27_Ndays_on20 T_MaxBin_23_25_Ndays_on20 T_MaxBin_inf21_Ndays_on20
1 5                         0                         0
2 7                         0                         0
  T_MaxBin_21_23_Ndays_on20 T_MaxBin_33_35_Ndays_on20 T_MaxBin_sup35_Ndays_on20
1 0                         0                         0
2 0                         0                         0
  T_MaxBin_29_31_Ndays_on10 T_MaxBin_31_33_Ndays_on10 T_MaxBin_27_29_Ndays_on10
1 0                         0                         6
2 0                         0                         6
  T_MaxBin_25_27_Ndays_on10 T_MaxBin_23_25_Ndays_on10 T_MaxBin_inf21_Ndays_on10
1 4                         0                         0
2 4                         0                         0
  T_MaxBin_21_23_Ndays_on10 T_MaxBin_33_35_Ndays_on10 T_MaxBin_sup35_Ndays_on10
1 0                         0                         0
2 0                         0                         0
  WB_i30   WB_i20   WB_i10   WB_i30_bin WB_i20_bin WB_i10_bin
1 26.08611 26.08333 25.90833 (26,28]    (26,28]    (24,26]
2 26.08472 26.01042 25.99167 (26,28]    (26,28]    (24,26]
  WB_Bin_18_20_Nhours_on30 WB_Bin_20_22_Nhours_on30 WB_Bin_22_24_Nhours_on30
1 0                        0                        0
2 0                        0                        0
  WB_Bin_24_26_Nhours_on30 WB_Bin_16_18_Nhours_on30 WB_Bin_14_16_Nhours_on30
1 559                      0                        0
2 566                      0                        0
  WB_Bin_inf14_Nhours_on30 WB_Bin_26_28_Nhours_on30 WB_Bin_sup28_Nhours_on30
1 0                        161                      0
2 0                        154                      0
  WB_Bin_18_20_Nhours_on20 WB_Bin_20_22_Nhours_on20 WB_Bin_22_24_Nhours_on20
1 0                        0                        0
2 0                        0                        0
  WB_Bin_24_26_Nhours_on20 WB_Bin_16_18_Nhours_on20 WB_Bin_14_16_Nhours_on20
1 385                      0                        0
2 396                      0                        0
  WB_Bin_inf14_Nhours_on20 WB_Bin_26_28_Nhours_on20 WB_Bin_sup28_Nhours_on20
1 0                        95                       0
2 0                        84                       0
  WB_Bin_18_20_Nhours_on10 WB_Bin_20_22_Nhours_on10 WB_Bin_22_24_Nhours_on10
1 0                        0                        0
2 0                        0                        0
  WB_Bin_24_26_Nhours_on10 WB_Bin_16_18_Nhours_on10 WB_Bin_14_16_Nhours_on10
1 217                      0                        0
2 205                      0                        0
  WB_Bin_inf14_Nhours_on10 WB_Bin_26_28_Nhours_on10 WB_Bin_sup28_Nhours_on10
1 0                        23                       0
2 0                        35                       0
  WB_MeanBin_20_22_Ndays_on30 WB_MeanBin_18_20_Ndays_on30
1 0                           0
2 0                           0
  WB_MeanBin_22_24_Ndays_on30 WB_MeanBin_16_18_Ndays_on30
1 0                           0
2 0                           0
  WB_MeanBin_inf14_Ndays_on30 WB_MeanBin_14_16_Ndays_on30
1 0                           0
2 0                           0
  WB_MeanBin_24_26_Ndays_on30 WB_MeanBin_26_28_Ndays_on30
1 13                          17
2 14                          16
  WB_MeanBin_sup28_Ndays_on30 WB_MeanBin_20_22_Ndays_on20
1 0                           0
2 0                           0
  WB_MeanBin_18_20_Ndays_on20 WB_MeanBin_22_24_Ndays_on20
1 0                           0
2 0                           0
  WB_MeanBin_16_18_Ndays_on20 WB_MeanBin_inf14_Ndays_on20
1 0                           0
2 0                           0
  WB_MeanBin_14_16_Ndays_on20 WB_MeanBin_24_26_Ndays_on20
1 0                           10
2 0                           12
  WB_MeanBin_26_28_Ndays_on20 WB_MeanBin_sup28_Ndays_on20
1 10                          0
2  8                          0
  WB_MeanBin_20_22_Ndays_on10 WB_MeanBin_18_20_Ndays_on10
1 0                           0
2 0                           0
  WB_MeanBin_22_24_Ndays_on10 WB_MeanBin_16_18_Ndays_on10
1 0                           0
2 0                           0
  WB_MeanBin_inf14_Ndays_on10 WB_MeanBin_14_16_Ndays_on10
1 0                           0
2 0                           0
  WB_MeanBin_24_26_Ndays_on10 WB_MeanBin_26_28_Ndays_on10
1 7                           3
2 7                           3
  WB_MeanBin_sup28_Ndays_on10 WB_MinBin_18_20_Ndays_on30
1 0                           0
2 0                           0
  WB_MinBin_16_18_Ndays_on30 WB_MinBin_14_16_Ndays_on30
1 0                          0
2 0                          0
  WB_MinBin_12_14_Ndays_on30 WB_MinBin_10_12_Ndays_on30
1 0                          0
2 0                          0
  WB_MinBin_inf10_Ndays_on30 WB_MinBin_20_22_Ndays_on30
1 0                          0
2 0                          0
  WB_MinBin_22_24_Ndays_on30 WB_MinBin_sup24_Ndays_on30
1 0                          30
2 0                          30
  WB_MinBin_18_20_Ndays_on20 WB_MinBin_16_18_Ndays_on20
1 0                          0
2 0                          0
  WB_MinBin_14_16_Ndays_on20 WB_MinBin_12_14_Ndays_on20
1 0                          0
2 0                          0
  WB_MinBin_10_12_Ndays_on20 WB_MinBin_inf10_Ndays_on20
1 0                          0
2 0                          0
  WB_MinBin_20_22_Ndays_on20 WB_MinBin_22_24_Ndays_on20
1 0                          0
2 0                          0
  WB_MinBin_sup24_Ndays_on20 WB_MinBin_18_20_Ndays_on10
1 20                         0
2 20                         0
  WB_MinBin_16_18_Ndays_on10 WB_MinBin_14_16_Ndays_on10
1 0                          0
2 0                          0
  WB_MinBin_12_14_Ndays_on10 WB_MinBin_10_12_Ndays_on10
1 0                          0
2 0                          0
  WB_MinBin_inf10_Ndays_on10 WB_MinBin_20_22_Ndays_on10
1 0                          0
2 0                          0
  WB_MinBin_22_24_Ndays_on10 WB_MinBin_sup24_Ndays_on10
1 0                          10
2 0                          10
  WB_MaxBin_24_26_Ndays_on30 WB_MaxBin_22_24_Ndays_on30
1 10                         0
2 11                         0
  WB_MaxBin_26_28_Ndays_on30 WB_MaxBin_inf18_Ndays_on30
1 20                         0
2 19                         0
  WB_MaxBin_18_20_Ndays_on30 WB_MaxBin_20_22_Ndays_on30
1 0                          0
2 0                          0
  WB_MaxBin_28_30_Ndays_on30 WB_MaxBin_30_32_Ndays_on30
1 0                          0
2 0                          0
  WB_MaxBin_sup32_Ndays_on30 WB_MaxBin_24_26_Ndays_on20
1 0                          7
2 0                          9
  WB_MaxBin_22_24_Ndays_on20 WB_MaxBin_26_28_Ndays_on20
1 0                          13
2 0                          11
  WB_MaxBin_inf18_Ndays_on20 WB_MaxBin_18_20_Ndays_on20
1 0                          0
2 0                          0
  WB_MaxBin_20_22_Ndays_on20 WB_MaxBin_28_30_Ndays_on20
1 0                          0
2 0                          0
  WB_MaxBin_30_32_Ndays_on20 WB_MaxBin_sup32_Ndays_on20
1 0                          0
2 0                          0
  WB_MaxBin_24_26_Ndays_on10 WB_MaxBin_22_24_Ndays_on10
1 5                          0
2 5                          0
  WB_MaxBin_26_28_Ndays_on10 WB_MaxBin_inf18_Ndays_on10
1 5                          0
2 5                          0
  WB_MaxBin_18_20_Ndays_on10 WB_MaxBin_20_22_Ndays_on10
1 0                          0
2 0                          0
  WB_MaxBin_28_30_Ndays_on10 WB_MaxBin_30_32_Ndays_on10
1 0                          0
2 0                          0
  WB_MaxBin_sup32_Ndays_on10 P_tot_30  P_tot_20  P_tot_10   API_sup_1
1 0                          0.2839093 0.1787939 0.11706638 0
2 0                          0.2566433 0.1496382 0.09978867 0

## SAVE

In [17]:
write_csv(df_DHS_final,"./output/df_reg_men.csv")