In [1]:
list.of.packages <- c("tidyverse","data.table","stargazer")
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages, repos = "http://cran.us.r-project.org")


invisible(lapply(list.of.packages, library, character.only = TRUE))

options(repr.matrix.max.rows=500, repr.matrix.max.cols=1200, message=FALSE, warning=TRUE)

── Attaching core tidyverse packages ─────────────────────────────────────────────────────────────────────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.2.0     ✔ readr     2.2.0
✔ forcats   1.0.1     ✔ stringr   1.6.0
✔ ggplot2   4.0.2     ✔ tibble    3.3.1
✔ lubridate 1.9.5     ✔ tidyr     1.3.2
✔ purrr     1.2.1
── Conflicts ───────────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

Attachement du package : ‘data.table’


Les objets suivants sont masqués depuis ‘package:lubridate’:

    hour, isoweek, mday, minute, month, quarter, second, wday, week,
    yday, year


Les objets suivants sont masqués depuis ‘package:dplyr’:

    between, first, last


L'objet suivant est masqué depuis ‘package:purrr’:

    transpose



Please cite as:


 Hlavac, Marek (2022). stargazer: Well-Formatted Regression and Summary Statistics Tables.

 R package version 5.2.3. https://CRAN.R-project.org/package=stargazer

# Longer dataframe

In [2]:
df_deg_bins <- fread("./interm/df_T_cells_CDC_longer.csv")
sprintf("%i x %i dataframe", nrow(df_deg_bins), ncol(df_deg_bins))
head(df_deg_bins,2)

[1] "54270555 x 7 dataframe"

  Measured_date_CDC cell_x cell_y Temp_bin   N_hours Temp Day_Min
1 42474             91.9   27.6   T0DayMin61 3       0    61
2 42473             91.9   27.6   T0DayMin61 4       0    61

In [3]:
df_deg_bins%>%count(Day_Min)

   Day_Min n
1  61      1803481
2  62      1804867
3  63      1806547
4  64      1807270
5  65      1806454
6  66      1805860
7  67      1805450
8  68      1804412
9  69      1805029
10 70      1805411
11 71      1805599
12 72      1805688
13 73      1807176
14 74      1807550
15 75      1807949
16 76      1808527
17 77      1809001
18 78      1809044
19 79      1809204
20 80      1809938
21 81      1811225
22 82      1812379
23 83      1812572
24 84      1813078
25 85      1813476
26 86      1814179
27 87      1814986
28 88      1815750
29 89      1814311
30 90      1814142

In [4]:
df_deg_bins%>%count(N_hours)

   N_hours n
1   1      19048233
2   2      18330953
3   3       8387996
4   4       4311069
5   5       2004206
6   6        909201
7   7        473273
8   8        276921
9   9        171160
10 10        109118
11 11         75693
12 12         52887
13 13         37932
14 14         25672
15 15         17675
16 16         12229
17 17          8353
18 18          5666
19 19          4074
20 20          2747
21 21          2123
22 22          1484
23 23          1004
24 24           886

In [5]:
df_deg_bins%>%count(Temp)

   Temp n
1  -31       49
2  -30       39
3  -29      106
4  -28      171
5  -27      307
6  -26      539
7  -25      875
8  -24     1173
9  -23     1679
10 -22     2116
11 -21     2837
12 -20     3575
13 -19     4797
14 -18     5851
15 -17     6863
16 -16     8131
17 -15     9962
18 -14    11522
19 -13    13349
20 -12    15808
21 -11    18885
22 -10    21927
23  -9    25633
24  -8    29551
25  -7    34823
26  -6    40566
27  -5    46078
28  -4    52131
29  -3    58642
30  -2    66220
31  -1    73418
32   0    81887
33   1    92952
34   2   107295
35   3   130912
36   4   165383
37   5   224445
38   6   319667
39   7   433723
40   8   554232
41   9   687954
42  10   828254
43  11   983594
44  12  1141866
45  13  1313912
46  14  1481959
47  15  1655091
48  16  1843009
49  17  2010722
50  18  2151719
51  19  2274306
52  20  2371909
53  21  2471378
54  22  2588578
55  23  2718103
56  24  2872963
57  25  3006806
58  26  2984111
59  27  2796549
60  28  2481624
61  29  2122521
62  30  1795248
63  31  1494025
64  32  1204462
65  33   950725
66  34   776189
67  35   641343
68  36   535130
69  37   434954
70  38   344617
71  39   263201
72  40   180925
73  41   108428
74  42    55038
75  43    22651
76  44     7500
77  45     1072

# Computation $$T_{i}^{30}= \sum_{b} \frac{h_{ib}^{30} \times T_b}{24 \times 30}$$

## 30-day exposure

In [6]:
result_30 <- df_deg_bins[, .(T_i61_90 = sum(N_hours * Temp / 24 / 30, na.rm = TRUE)), 
                          by = .(Measured_date_CDC, cell_x, cell_y)]
sprintf("%i x %i dataframe", nrow(result_30), ncol(result_30))
head(result_30,2)

[1] "173657 x 4 dataframe"

  Measured_date_CDC cell_x cell_y T_i61_90
1 42474             91.9   27.6   -3.343056
2 42473             91.9   27.6   -3.468056

In [7]:
data.frame(result_30) %>% 
        select(T_i61_90)%>%
        stargazer(nobs=TRUE, digits = 2,
                  summary.stat = c("n","mean", "sd","min","p25","median","p75","max"),
                  title = c("Summary statistics"),
                  type="text"
                     )

Summary statistics
======================================================================
Statistic    N    Mean  St. Dev.  Min   Pctl(25) Median Pctl(75)  Max
----------------------------------------------------------------------
T_i61_90  173,657 22.11   6.68   -15.96  17.93   22.82   26.86   37.32
----------------------------------------------------------------------

# Categorize temperature into bins

### Air temperature thresholds

In [8]:
thresholds_T <- c(-18,17,21,23,25,27,29,31,33,40)

In [9]:
T_bins_labels <- c("<=17°C","(17,21]","(21,23]","(23,25]","(25,27]","(27,29]","(29,31]","(31,33]",">33°C")

In [10]:
result_bins <- result_30 %>%
                    mutate(T_i61_90_bin = cut(T_i61_90, breaks = thresholds_T, 
                                           labels = T_bins_labels ,
                                           include.lowest = TRUE))
sprintf("%i x %i dataframe", nrow(result_bins), ncol(result_bins))
head(result_bins,2)

[1] "173657 x 5 dataframe"

  Measured_date_CDC cell_x cell_y T_i61_90  T_i61_90_bin
1 42474             91.9   27.6   -3.343056 <=17°C
2 42473             91.9   27.6   -3.468056 <=17°C

## SAVE

In [11]:
fwrite(result_bins,"./output/df_T_cells_CDC_61_90.csv")