In [1]:
list.of.packages <- c("tidyverse","data.table","stargazer")
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages, repos = "http://cran.us.r-project.org")

invisible(lapply(list.of.packages, library, character.only = TRUE))

options(repr.matrix.max.rows=500, repr.matrix.max.cols=1200, message=FALSE, warning=TRUE)

── Attaching core tidyverse packages ─────────────────────────────────────────────────────────────────────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.2.0     ✔ readr     2.2.0
✔ forcats   1.0.1     ✔ stringr   1.6.0
✔ ggplot2   4.0.2     ✔ tibble    3.3.1
✔ lubridate 1.9.5     ✔ tidyr     1.3.2
✔ purrr     1.2.1
── Conflicts ───────────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

Attachement du package : ‘data.table’


Les objets suivants sont masqués depuis ‘package:lubridate’:

    hour, isoweek, mday, minute, month, quarter, second, wday, week,
    yday, year


Les objets suivants sont masqués depuis ‘package:dplyr’:

    between, first, last


L'objet suivant est masqué depuis ‘package:purrr’:

    transpose



Please cite as:


 Hlavac, Marek (2022). stargazer: Well-Formatted Regression and Summary Statistics Tables.

 R package version 5.2.3. https://CRAN.R-project.org/package=stargazer

# Negative temperature

## Dataframe

In [2]:
df_deg_bins_neg <- fread("./interm/df_WB_cells_CDC_negative.csv")
sprintf("%i x %i dataframe", nrow(df_deg_bins_neg), ncol(df_deg_bins_neg))
head(df_deg_bins_neg,2)

[1] "126725 x 933 dataframe"

  Measured_date_CDC cell_x cell_y T-1DayMin61 T-1DayMin62 T-1DayMin63
1 42203             92.75  11.75  0           0           0
2 42205             92.75   9.25  0           0           0
  T-1DayMin64 T-1DayMin65 T-1DayMin66 T-1DayMin67 T-1DayMin68 T-1DayMin69
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-1DayMin70 T-1DayMin71 T-1DayMin72 T-1DayMin73 T-1DayMin74 T-1DayMin75
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-1DayMin76 T-1DayMin77 T-1DayMin78 T-1DayMin79 T-1DayMin80 T-1DayMin81
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-1DayMin82 T-1DayMin83 T-1DayMin84 T-1DayMin85 T-1DayMin86 T-1DayMin87
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-1DayMin88 T-1DayMin89 T-1DayMin90 T-2DayMin61 T-2DayMin62 T-2DayMin63
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-2DayMin64 T-2DayMin65 T-2DayMin66 T-2DayMin67 T-2DayMin68 T-2DayMin69
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-2DayMin70 T-2DayMin71 T-2DayMin72 T-2DayMin73 T-2DayMin74 T-2DayMin75
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-2DayMin76 T-2DayMin77 T-2DayMin78 T-2DayMin79 T-2DayMin80 T-2DayMin81
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-2DayMin82 T-2DayMin83 T-2DayMin84 T-2DayMin85 T-2DayMin86 T-2DayMin87
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-2DayMin88 T-2DayMin89 T-2DayMin90 T-3DayMin61 T-3DayMin62 T-3DayMin63
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-3DayMin64 T-3DayMin65 T-3DayMin66 T-3DayMin67 T-3DayMin68 T-3DayMin69
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-3DayMin70 T-3DayMin71 T-3DayMin72 T-3DayMin73 T-3DayMin74 T-3DayMin75
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-3DayMin76 T-3DayMin77 T-3DayMin78 T-3DayMin79 T-3DayMin80 T-3DayMin81
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-3DayMin82 T-3DayMin83 T-3DayMin84 T-3DayMin85 T-3DayMin86 T-3DayMin87
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-3DayMin88 T-3DayMin89 T-3DayMin90 T-4DayMin61 T-4DayMin62 T-4DayMin63
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-4DayMin64 T-4DayMin65 T-4DayMin66 T-4DayMin67 T-4DayMin68 T-4DayMin69
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-4DayMin70 T-4DayMin71 T-4DayMin72 T-4DayMin73 T-4DayMin74 T-4DayMin75
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-4DayMin76 T-4DayMin77 T-4DayMin78 T-4DayMin79 T-4DayMin80 T-4DayMin81
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-4DayMin82 T-4DayMin83 T-4DayMin84 T-4DayMin85 T-4DayMin86 T-4DayMin87
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-4DayMin88 T-4DayMin89 T-4DayMin90 T-5DayMin61 T-5DayMin62 T-5DayMin63
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-5DayMin64 T-5DayMin65 T-5DayMin66 T-5DayMin67 T-5DayMin68 T-5DayMin69
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-5DayMin70 T-5DayMin71 T-5DayMin72 T-5DayMin73 T-5DayMin74 T-5DayMin75
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-5DayMin76 T-5DayMin77 T-5DayMin78 T-5DayMin79 T-5DayMin80 T-5DayMin81
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-5DayMin82 T-5DayMin83 T-5DayMin84 T-5DayMin85 T-5DayMin86 T-5DayMin87
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-5DayMin88 T-5DayMin89 T-5DayMin90 T-6DayMin61 T-6DayMin62 T-6DayMin63
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-6DayMin64 T-6DayMin65 T-6DayMin66 T-6DayMin67 T-6DayMin68 T-6DayMin69
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-6DayMin70 T-6DayMin71 T-6DayMin72 T-6DayMin73 T-6DayMin74 T-6DayMin75
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-6DayMin76 T-6DayMin77 T-6DayMin78 T-6DayMin79 T-6DayMin80 T-6DayMin81
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-6DayMin82 T-6DayMin83 T-6DayMin84 T-6DayMin85 T-6DayMin86 T-6DayMin87
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-6DayMin88 T-6DayMin89 T-6DayMin90 T-7DayMin61 T-7DayMin62 T-7DayMin63
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-7DayMin64 T-7DayMin65 T-7DayMin66 T-7DayMin67 T-7DayMin68 T-7DayMin69
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-7DayMin70 T-7DayMin71 T-7DayMin72 T-7DayMin73 T-7DayMin74 T-7DayMin75
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-7DayMin76 T-7DayMin77 T-7DayMin78 T-7DayMin79 T-7DayMin80 T-7DayMin81
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-7DayMin82 T-7DayMin83 T-7DayMin84 T-7DayMin85 T-7DayMin86 T-7DayMin87
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-7DayMin88 T-7DayMin89 T-7DayMin90 T-8DayMin61 T-8DayMin62 T-8DayMin63
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-8DayMin64 T-8DayMin65 T-8DayMin66 T-8DayMin67 T-8DayMin68 T-8DayMin69
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-8DayMin70 T-8DayMin71 T-8DayMin72 T-8DayMin73 T-8DayMin74 T-8DayMin75
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-8DayMin76 T-8DayMin77 T-8DayMin78 T-8DayMin79 T-8DayMin80 T-8DayMin81
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-8DayMin82 T-8DayMin83 T-8DayMin84 T-8DayMin85 T-8DayMin86 T-8DayMin87
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-8DayMin88 T-8DayMin89 T-8DayMin90 T-9DayMin61 T-9DayMin62 T-9DayMin63
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-9DayMin64 T-9DayMin65 T-9DayMin66 T-9DayMin67 T-9DayMin68 T-9DayMin69
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-9DayMin70 T-9DayMin71 T-9DayMin72 T-9DayMin73 T-9DayMin74 T-9DayMin75
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-9DayMin76 T-9DayMin77 T-9DayMin78 T-9DayMin79 T-9DayMin80 T-9DayMin81
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-9DayMin82 T-9DayMin83 T-9DayMin84 T-9DayMin85 T-9DayMin86 T-9DayMin87
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-9DayMin88 T-9DayMin89 T-9DayMin90 T-10DayMin61 T-10DayMin62 T-10DayMin63
1 0           0           0           0            0            0
2 0           0           0           0            0            0
  T-10DayMin64 T-10DayMin65 T-10DayMin66 T-10DayMin67 T-10DayMin68 T-10DayMin69
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-10DayMin70 T-10DayMin71 T-10DayMin72 T-10DayMin73 T-10DayMin74 T-10DayMin75
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-10DayMin76 T-10DayMin77 T-10DayMin78 T-10DayMin79 T-10DayMin80 T-10DayMin81
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-10DayMin82 T-10DayMin83 T-10DayMin84 T-10DayMin85 T-10DayMin86 T-10DayMin87
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-10DayMin88 T-10DayMin89 T-10DayMin90 T-11DayMin61 T-11DayMin62 T-11DayMin63
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-11DayMin64 T-11DayMin65 T-11DayMin66 T-11DayMin67 T-11DayMin68 T-11DayMin69
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-11DayMin70 T-11DayMin71 T-11DayMin72 T-11DayMin73 T-11DayMin74 T-11DayMin75
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-11DayMin76 T-11DayMin77 T-11DayMin78 T-11DayMin79 T-11DayMin80 T-11DayMin81
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-11DayMin82 T-11DayMin83 T-11DayMin84 T-11DayMin85 T-11DayMin86 T-11DayMin87
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-11DayMin88 T-11DayMin89 T-11DayMin90 T-12DayMin61 T-12DayMin62 T-12DayMin63
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-12DayMin64 T-12DayMin65 T-12DayMin66 T-12DayMin67 T-12DayMin68 T-12DayMin69
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-12DayMin70 T-12DayMin71 T-12DayMin72 T-12DayMin73 T-12DayMin74 T-12DayMin75
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-12DayMin76 T-12DayMin77 T-12DayMin78 T-12DayMin79 T-12DayMin80 T-12DayMin81
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-12DayMin82 T-12DayMin83 T-12DayMin84 T-12DayMin85 T-12DayMin86 T-12DayMin87
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-12DayMin88 T-12DayMin89 T-12DayMin90 T-13DayMin61 T-13DayMin62 T-13DayMin63
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-13DayMin64 T-13DayMin65 T-13DayMin66 T-13DayMin67 T-13DayMin68 T-13DayMin69
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-13DayMin70 T-13DayMin71 T-13DayMin72 T-13DayMin73 T-13DayMin74 T-13DayMin75
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-13DayMin76 T-13DayMin77 T-13DayMin78 T-13DayMin79 T-13DayMin80 T-13DayMin81
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-13DayMin82 T-13DayMin83 T-13DayMin84 T-13DayMin85 T-13DayMin86 T-13DayMin87
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-13DayMin88 T-13DayMin89 T-13DayMin90 T-14DayMin61 T-14DayMin62 T-14DayMin63
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-14DayMin64 T-14DayMin65 T-14DayMin66 T-14DayMin67 T-14DayMin68 T-14DayMin69
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-14DayMin70 T-14DayMin71 T-14DayMin72 T-14DayMin73 T-14DayMin74 T-14DayMin75
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-14DayMin76 T-14DayMin77 T-14DayMin78 T-14DayMin79 T-14DayMin80 T-14DayMin81
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-14DayMin82 T-14DayMin83 T-14DayMin84 T-14DayMin85 T-14DayMin86 T-14DayMin87
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-14DayMin88 T-14DayMin89 T-14DayMin90 T-15DayMin61 T-15DayMin62 T-15DayMin63
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-15DayMin64 T-15DayMin65 T-15DayMin66 T-15DayMin67 T-15DayMin68 T-15DayMin69
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-15DayMin70 T-15DayMin71 T-15DayMin72 T-15DayMin73 T-15DayMin74 T-15DayMin75
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-15DayMin76 T-15DayMin77 T-15DayMin78 T-15DayMin79 T-15DayMin80 T-15DayMin81
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-15DayMin82 T-15DayMin83 T-15DayMin84 T-15DayMin85 T-15DayMin86 T-15DayMin87
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-15DayMin88 T-15DayMin89 T-15DayMin90 T-16DayMin61 T-16DayMin62 T-16DayMin63
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-16DayMin64 T-16DayMin65 T-16DayMin66 T-16DayMin67 T-16DayMin68 T-16DayMin69
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-16DayMin70 T-16DayMin71 T-16DayMin72 T-16DayMin73 T-16DayMin74 T-16DayMin75
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-16DayMin76 T-16DayMin77 T-16DayMin78 T-16DayMin79 T-16DayMin80 T-16DayMin81
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-16DayMin82 T-16DayMin83 T-16DayMin84 T-16DayMin85 T-16DayMin86 T-16DayMin87
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-16DayMin88 T-16DayMin89 T-16DayMin90 T-17DayMin61 T-17DayMin62 T-17DayMin63
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-17DayMin64 T-17DayMin65 T-17DayMin66 T-17DayMin67 T-17DayMin68 T-17DayMin69
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-17DayMin70 T-17DayMin71 T-17DayMin72 T-17DayMin73 T-17DayMin74 T-17DayMin75
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-17DayMin76 T-17DayMin77 T-17DayMin78 T-17DayMin79 T-17DayMin80 T-17DayMin81
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-17DayMin82 T-17DayMin83 T-17DayMin84 T-17DayMin85 T-17DayMin86 T-17DayMin87
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-17DayMin88 T-17DayMin89 T-17DayMin90 T-18DayMin61 T-18DayMin62 T-18DayMin63
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-18DayMin64 T-18DayMin65 T-18DayMin66 T-18DayMin67 T-18DayMin68 T-18DayMin69
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-18DayMin70 T-18DayMin71 T-18DayMin72 T-18DayMin73 T-18DayMin74 T-18DayMin75
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-18DayMin76 T-18DayMin77 T-18DayMin78 T-18DayMin79 T-18DayMin80 T-18DayMin81
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-18DayMin82 T-18DayMin83 T-18DayMin84 T-18DayMin85 T-18DayMin86 T-18DayMin87
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-18DayMin88 T-18DayMin89 T-18DayMin90 T-19DayMin61 T-19DayMin62 T-19DayMin63
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-19DayMin64 T-19DayMin65 T-19DayMin66 T-19DayMin67 T-19DayMin68 T-19DayMin69
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-19DayMin70 T-19DayMin71 T-19DayMin72 T-19DayMin73 T-19DayMin74 T-19DayMin75
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-19DayMin76 T-19DayMin77 T-19DayMin78 T-19DayMin79 T-19DayMin80 T-19DayMin81
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-19DayMin82 T-19DayMin83 T-19DayMin84 T-19DayMin85 T-19DayMin86 T-19DayMin87
1 0            0            0            0            0            0
2 0            0            0            0            0            0

## Pivot longer dataframe

In [3]:
df_deg_bins_piv_neg <- melt(df_deg_bins_neg%>%filter(!is.na(`T-1DayMin61`)), 
                       id.vars = c("Measured_date_CDC", "cell_x", "cell_y"),
                       variable.name = "Temp_bin",
                       value.name = "N_hours")
sprintf("%i x %i dataframe", nrow(df_deg_bins_piv_neg), ncol(df_deg_bins_piv_neg))
head(df_deg_bins_piv_neg,2)

[1] "117854250 x 5 dataframe"

  Measured_date_CDC cell_x cell_y Temp_bin    N_hours
1 42203             92.75  11.75  T-1DayMin61 0
2 42205             92.75   9.25  T-1DayMin61 0

In [4]:
df_deg_bins_piv_neg_wo0 <- df_deg_bins_piv_neg[N_hours!=0]

In [5]:
#Keep memory
rm(df_deg_bins_neg)
rm(df_deg_bins_piv_neg)

# Positive temperature

## Dataframe

In [6]:
df_deg_bins_pos <- fread("./interm/df_WB_cells_CDC_positive.csv")
sprintf("%i x %i dataframe", nrow(df_deg_bins_pos), ncol(df_deg_bins_pos))
head(df_deg_bins_pos,2)

[1] "126725 x 1383 dataframe"

  Measured_date_CDC cell_x cell_y T0DayMin61 T0DayMin62 T0DayMin63 T0DayMin64
1 42203             92.75  11.75  0          0          0          0
2 42205             92.75   9.25  0          0          0          0
  T0DayMin65 T0DayMin66 T0DayMin67 T0DayMin68 T0DayMin69 T0DayMin70 T0DayMin71
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T0DayMin72 T0DayMin73 T0DayMin74 T0DayMin75 T0DayMin76 T0DayMin77 T0DayMin78
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T0DayMin79 T0DayMin80 T0DayMin81 T0DayMin82 T0DayMin83 T0DayMin84 T0DayMin85
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T0DayMin86 T0DayMin87 T0DayMin88 T0DayMin89 T0DayMin90 T1DayMin61 T1DayMin62
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T1DayMin63 T1DayMin64 T1DayMin65 T1DayMin66 T1DayMin67 T1DayMin68 T1DayMin69
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T1DayMin70 T1DayMin71 T1DayMin72 T1DayMin73 T1DayMin74 T1DayMin75 T1DayMin76
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T1DayMin77 T1DayMin78 T1DayMin79 T1DayMin80 T1DayMin81 T1DayMin82 T1DayMin83
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T1DayMin84 T1DayMin85 T1DayMin86 T1DayMin87 T1DayMin88 T1DayMin89 T1DayMin90
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T2DayMin61 T2DayMin62 T2DayMin63 T2DayMin64 T2DayMin65 T2DayMin66 T2DayMin67
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T2DayMin68 T2DayMin69 T2DayMin70 T2DayMin71 T2DayMin72 T2DayMin73 T2DayMin74
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T2DayMin75 T2DayMin76 T2DayMin77 T2DayMin78 T2DayMin79 T2DayMin80 T2DayMin81
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T2DayMin82 T2DayMin83 T2DayMin84 T2DayMin85 T2DayMin86 T2DayMin87 T2DayMin88
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T2DayMin89 T2DayMin90 T3DayMin61 T3DayMin62 T3DayMin63 T3DayMin64 T3DayMin65
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T3DayMin66 T3DayMin67 T3DayMin68 T3DayMin69 T3DayMin70 T3DayMin71 T3DayMin72
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T3DayMin73 T3DayMin74 T3DayMin75 T3DayMin76 T3DayMin77 T3DayMin78 T3DayMin79
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T3DayMin80 T3DayMin81 T3DayMin82 T3DayMin83 T3DayMin84 T3DayMin85 T3DayMin86
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T3DayMin87 T3DayMin88 T3DayMin89 T3DayMin90 T4DayMin61 T4DayMin62 T4DayMin63
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T4DayMin64 T4DayMin65 T4DayMin66 T4DayMin67 T4DayMin68 T4DayMin69 T4DayMin70
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T4DayMin71 T4DayMin72 T4DayMin73 T4DayMin74 T4DayMin75 T4DayMin76 T4DayMin77
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T4DayMin78 T4DayMin79 T4DayMin80 T4DayMin81 T4DayMin82 T4DayMin83 T4DayMin84
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T4DayMin85 T4DayMin86 T4DayMin87 T4DayMin88 T4DayMin89 T4DayMin90 T5DayMin61
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T5DayMin62 T5DayMin63 T5DayMin64 T5DayMin65 T5DayMin66 T5DayMin67 T5DayMin68
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T5DayMin69 T5DayMin70 T5DayMin71 T5DayMin72 T5DayMin73 T5DayMin74 T5DayMin75
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T5DayMin76 T5DayMin77 T5DayMin78 T5DayMin79 T5DayMin80 T5DayMin81 T5DayMin82
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T5DayMin83 T5DayMin84 T5DayMin85 T5DayMin86 T5DayMin87 T5DayMin88 T5DayMin89
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T5DayMin90 T6DayMin61 T6DayMin62 T6DayMin63 T6DayMin64 T6DayMin65 T6DayMin66
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T6DayMin67 T6DayMin68 T6DayMin69 T6DayMin70 T6DayMin71 T6DayMin72 T6DayMin73
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T6DayMin74 T6DayMin75 T6DayMin76 T6DayMin77 T6DayMin78 T6DayMin79 T6DayMin80
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T6DayMin81 T6DayMin82 T6DayMin83 T6DayMin84 T6DayMin85 T6DayMin86 T6DayMin87
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T6DayMin88 T6DayMin89 T6DayMin90 T7DayMin61 T7DayMin62 T7DayMin63 T7DayMin64
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T7DayMin65 T7DayMin66 T7DayMin67 T7DayMin68 T7DayMin69 T7DayMin70 T7DayMin71
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T7DayMin72 T7DayMin73 T7DayMin74 T7DayMin75 T7DayMin76 T7DayMin77 T7DayMin78
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T7DayMin79 T7DayMin80 T7DayMin81 T7DayMin82 T7DayMin83 T7DayMin84 T7DayMin85
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T7DayMin86 T7DayMin87 T7DayMin88 T7DayMin89 T7DayMin90 T8DayMin61 T8DayMin62
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T8DayMin63 T8DayMin64 T8DayMin65 T8DayMin66 T8DayMin67 T8DayMin68 T8DayMin69
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T8DayMin70 T8DayMin71 T8DayMin72 T8DayMin73 T8DayMin74 T8DayMin75 T8DayMin76
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T8DayMin77 T8DayMin78 T8DayMin79 T8DayMin80 T8DayMin81 T8DayMin82 T8DayMin83
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T8DayMin84 T8DayMin85 T8DayMin86 T8DayMin87 T8DayMin88 T8DayMin89 T8DayMin90
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T9DayMin61 T9DayMin62 T9DayMin63 T9DayMin64 T9DayMin65 T9DayMin66 T9DayMin67
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T9DayMin68 T9DayMin69 T9DayMin70 T9DayMin71 T9DayMin72 T9DayMin73 T9DayMin74
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T9DayMin75 T9DayMin76 T9DayMin77 T9DayMin78 T9DayMin79 T9DayMin80 T9DayMin81
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T9DayMin82 T9DayMin83 T9DayMin84 T9DayMin85 T9DayMin86 T9DayMin87 T9DayMin88
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T9DayMin89 T9DayMin90 T10DayMin61 T10DayMin62 T10DayMin63 T10DayMin64
1 0          0          0           0           0           0
2 0          0          0           0           0           0
  T10DayMin65 T10DayMin66 T10DayMin67 T10DayMin68 T10DayMin69 T10DayMin70
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T10DayMin71 T10DayMin72 T10DayMin73 T10DayMin74 T10DayMin75 T10DayMin76
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T10DayMin77 T10DayMin78 T10DayMin79 T10DayMin80 T10DayMin81 T10DayMin82
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T10DayMin83 T10DayMin84 T10DayMin85 T10DayMin86 T10DayMin87 T10DayMin88
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T10DayMin89 T10DayMin90 T11DayMin61 T11DayMin62 T11DayMin63 T11DayMin64
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T11DayMin65 T11DayMin66 T11DayMin67 T11DayMin68 T11DayMin69 T11DayMin70
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T11DayMin71 T11DayMin72 T11DayMin73 T11DayMin74 T11DayMin75 T11DayMin76
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T11DayMin77 T11DayMin78 T11DayMin79 T11DayMin80 T11DayMin81 T11DayMin82
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T11DayMin83 T11DayMin84 T11DayMin85 T11DayMin86 T11DayMin87 T11DayMin88
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T11DayMin89 T11DayMin90 T12DayMin61 T12DayMin62 T12DayMin63 T12DayMin64
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T12DayMin65 T12DayMin66 T12DayMin67 T12DayMin68 T12DayMin69 T12DayMin70
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T12DayMin71 T12DayMin72 T12DayMin73 T12DayMin74 T12DayMin75 T12DayMin76
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T12DayMin77 T12DayMin78 T12DayMin79 T12DayMin80 T12DayMin81 T12DayMin82
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T12DayMin83 T12DayMin84 T12DayMin85 T12DayMin86 T12DayMin87 T12DayMin88
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T12DayMin89 T12DayMin90 T13DayMin61 T13DayMin62 T13DayMin63 T13DayMin64
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T13DayMin65 T13DayMin66 T13DayMin67 T13DayMin68 T13DayMin69 T13DayMin70
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T13DayMin71 T13DayMin72 T13DayMin73 T13DayMin74 T13DayMin75 T13DayMin76
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T13DayMin77 T13DayMin78 T13DayMin79 T13DayMin80 T13DayMin81 T13DayMin82
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T13DayMin83 T13DayMin84 T13DayMin85 T13DayMin86 T13DayMin87 T13DayMin88
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T13DayMin89 T13DayMin90 T14DayMin61 T14DayMin62 T14DayMin63 T14DayMin64
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T14DayMin65 T14DayMin66 T14DayMin67 T14DayMin68 T14DayMin69 T14DayMin70
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T14DayMin71 T14DayMin72 T14DayMin73 T14DayMin74 T14DayMin75 T14DayMin76
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T14DayMin77 T14DayMin78 T14DayMin79 T14DayMin80 T14DayMin81 T14DayMin82
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T14DayMin83 T14DayMin84 T14DayMin85 T14DayMin86 T14DayMin87 T14DayMin88
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T14DayMin89 T14DayMin90 T15DayMin61 T15DayMin62 T15DayMin63 T15DayMin64
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T15DayMin65 T15DayMin66 T15DayMin67 T15DayMin68 T15DayMin69 T15DayMin70
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T15DayMin71 T15DayMin72 T15DayMin73 T15DayMin74 T15DayMin75 T15DayMin76
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T15DayMin77 T15DayMin78 T15DayMin79 T15DayMin80 T15DayMin81 T15DayMin82
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T15DayMin83 T15DayMin84 T15DayMin85 T15DayMin86 T15DayMin87 T15DayMin88
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T15DayMin89 T15DayMin90 T16DayMin61 T16DayMin62 T16DayMin63 T16DayMin64
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T16DayMin65 T16DayMin66 T16DayMin67 T16DayMin68 T16DayMin69 T16DayMin70
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T16DayMin71 T16DayMin72 T16DayMin73 T16DayMin74 T16DayMin75 T16DayMin76
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T16DayMin77 T16DayMin78 T16DayMin79 T16DayMin80 T16DayMin81 T16DayMin82
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T16DayMin83 T16DayMin84 T16DayMin85 T16DayMin86 T16DayMin87 T16DayMin88
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T16DayMin89 T16DayMin90 T17DayMin61 T17DayMin62 T17DayMin63 T17DayMin64
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T17DayMin65 T17DayMin66 T17DayMin67 T17DayMin68 T17DayMin69 T17DayMin70
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T17DayMin71 T17DayMin72 T17DayMin73 T17DayMin74 T17DayMin75 T17DayMin76
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T17DayMin77 T17DayMin78 T17DayMin79 T17DayMin80 T17DayMin81 T17DayMin82
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T17DayMin83 T17DayMin84 T17DayMin85 T17DayMin86 T17DayMin87 T17DayMin88
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T17DayMin89 T17DayMin90 T18DayMin61 T18DayMin62 T18DayMin63 T18DayMin64
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T18DayMin65 T18DayMin66 T18DayMin67 T18DayMin68 T18DayMin69 T18DayMin70
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T18DayMin71 T18DayMin72 T18DayMin73 T18DayMin74 T18DayMin75 T18DayMin76
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T18DayMin77 T18DayMin78 T18DayMin79 T18DayMin80 T18DayMin81 T18DayMin82
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T18DayMin83 T18DayMin84 T18DayMin85 T18DayMin86 T18DayMin87 T18DayMin88
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T18DayMin89 T18DayMin90 T19DayMin61 T19DayMin62 T19DayMin63 T19DayMin64
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T19DayMin65 T19DayMin66 T19DayMin67 T19DayMin68 T19DayMin69 T19DayMin70
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T19DayMin71 T19DayMin72 T19DayMin73 T19DayMin74 T19DayMin75 T19DayMin76
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T19DayMin77 T19DayMin78 T19DayMin79 T19DayMin80 T19DayMin81 T19DayMin82
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T19DayMin83 T19DayMin84 T19DayMin85 T19DayMin86 T19DayMin87 ⋯ T26DayMin61
1 0           0           0           0           0           ⋯ 11
2 0           0           0           0           0           ⋯ 13
  T26DayMin62 T26DayMin63 T26DayMin64 T26DayMin65 T26DayMin66 T26DayMin67
1 13          22          22          18          16          12
2 10           7          11          14          20          12
  T26DayMin68 T26DayMin69 T26DayMin70 T26DayMin71 T26DayMin72 T26DayMin73
1 17          12          12          12          12          12
2 16          20          14           5          21          16
  T26DayMin74 T26DayMin75 T26DayMin76 T26DayMin77 T26DayMin78 T26DayMin79

## Pivot longer dataframe

In [7]:
df_deg_bins_piv_pos <- melt(df_deg_bins_pos%>%filter(!is.na(T1DayMin61)), 
                       id.vars = c("Measured_date_CDC", "cell_x", "cell_y"),
                       variable.name = "Temp_bin",
                       value.name = "N_hours")
sprintf("%i x %i dataframe", nrow(df_deg_bins_piv_pos), ncol(df_deg_bins_piv_pos))
head(df_deg_bins_piv_pos,2)

[1] "174880500 x 5 dataframe"

  Measured_date_CDC cell_x cell_y Temp_bin   N_hours
1 42203             92.75  11.75  T0DayMin61 0
2 42205             92.75   9.25  T0DayMin61 0

In [8]:
df_deg_bins_piv_pos_wo0 <- df_deg_bins_piv_pos[N_hours!=0]

In [9]:
#Keep memory
rm(df_deg_bins_pos)
rm(df_deg_bins_piv_pos)

# Rbind positive and negative temp

In [10]:
df_deg_bins_piv_wo0 <- rbind(df_deg_bins_piv_pos_wo0,df_deg_bins_piv_neg_wo0)

# Extract temperature value

In [11]:
df_deg_bins_piv_wo0[, Temp := as.numeric(sub("Day","",sub("T","",str_extract(Temp_bin, "\\s*(.+)Day"))))]
sprintf("%i x %i dataframe", nrow(df_deg_bins_piv_wo0), ncol(df_deg_bins_piv_wo0))
head(df_deg_bins_piv_wo0,2)

[1] "31533375 x 6 dataframe"

  Measured_date_CDC cell_x cell_y Temp_bin   N_hours Temp
1 42489             92.50  27.5   T0DayMin61 1       0
2 42474             91.75  27.5   T0DayMin61 3       0

# Extract day value

In [12]:
df_deg_bins_piv_wo0[, Day_Min := as.numeric(sub("Min","",str_extract(Temp_bin, "Min\\s*(.+)")))]
sprintf("%i x %i dataframe", nrow(df_deg_bins_piv_wo0), ncol(df_deg_bins_piv_wo0))
head(df_deg_bins_piv_wo0,2)

[1] "31533375 x 7 dataframe"

  Measured_date_CDC cell_x cell_y Temp_bin   N_hours Temp Day_Min
1 42489             92.50  27.5   T0DayMin61 1       0    61
2 42474             91.75  27.5   T0DayMin61 3       0    61

## SAVE

In [13]:
fwrite(df_deg_bins_piv_wo0,"./interm/df_WB_cells_CDC_longer.csv")