In [1]:
list.of.packages <- c("tidyverse","data.table","stargazer")
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages, repos = "http://cran.us.r-project.org")

invisible(lapply(list.of.packages, library, character.only = TRUE))

options(repr.matrix.max.rows=500, repr.matrix.max.cols=1200, message=FALSE, warning=TRUE)

── Attaching core tidyverse packages ─────────────────────────────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.2.0     ✔ readr     2.2.0
✔ forcats   1.0.1     ✔ stringr   1.6.0
✔ ggplot2   4.0.2     ✔ tibble    3.3.1
✔ lubridate 1.9.5     ✔ tidyr     1.3.2
✔ purrr     1.2.1
── Conflicts ───────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

Attachement du package : ‘data.table’


Les objets suivants sont masqués depuis ‘package:lubridate’:

    hour, isoweek, mday, minute, month, quarter, second, wday, week,
    yday, year


Les objets suivants sont masqués depuis ‘package:dplyr’:

    between, first, last


L'objet suivant est masqué depuis ‘package:purrr’:

    transpose



Please cite as:


 Hlavac, Marek (2022). stargazer: Well-Formatted Regression and Summary Statistics Tables.

 R package version 5.2.3. https://CRAN.R-project.org/package=stargazer

# CHIDLREN

In [2]:
df_DHS_15 <- readRDS("../0_input/DHS_data/output/df_children_2015_16.rds")
sprintf("%i x %i dataframe", nrow(df_DHS_15), ncol(df_DHS_15))
head(df_DHS_15,2)

[1] "243371 x 78 dataframe"

  DHS_round DHSCLUST State_2011               District_2011 cell_x_01 cell_y_01
1 2015      10001    Andaman & Nicobar Island South Andaman 92.7      11.7
2 2015      10001    Andaman & Nicobar Island South Andaman 92.7      11.7
  cell_x_025 cell_y_025 HH_ID Mother_id       Child_id Resp_nb Interview_month
1 92.75      11.75      10     01000110    02 1        2       7
2 92.75      11.75      23     01000123    02 1        2       7
  Interview_year Measured_date_CDC Measured_date Measured_day Measured_month
1 2015           42203             2015-07-20    20           7
2 2015           42203             2015-07-20    20           7
  Measured_year Birth_month Birth_year Child_female Child_birth_order
1 2015          6           2011       1            1
2 2015          2           2013       1            1
  Child_alive_age_month Child_hemo_level_alti Child_weight_for_height_zscore
1 49                    112                    0.16
2 29                    118                   -1.10
  Child_diarrhea Child_fever Child_cough Child_still_breastfeeding
1 0              0           1           0
2 0              0           0           0
  Child_given_plain_water Child_given_juice Child_given_milk
1 NA                      NA                NA
2 NA                      NA                NA
  Child_given_baby_formula Child_given_fortified_baby_food Child_given_soup
1 NA                       NA                              NA
2 NA                       NA                              NA
  Child_given_other_liquid Child_given_chicken_duck_birds
1 NA                       NA
2 NA                       NA
  Child_given_bread_noodles_grains Child_given_potatoes_cassava_tubers
1 NA                               NA
2 NA                               NA
  Child_given_eggs Child_given_pumkins_carrots_squash
1 NA               NA
2 NA               NA
  Child_given_green_vegetables Child_given_mangoes_papaya_vitaminAfruits
1 NA                           NA
2 NA                           NA
  Child_given_other_fruits Child_given_liver_heart_organs
1 NA                       NA
2 NA                       NA
  Child_given_fish_sellfish Child_given_beans_peas_lentils_nuts
1 NA                        NA
2 NA                        NA
  Child_given_cheese_yogurt_milk_products
1 NA
2 NA
  Child_given_other_solid_semisolid_food Child_given_other_meat
1 NA                                     NA
2 NA                                     NA
  Child_given_yogurt Child_iron_supplem_7d Mother_no_educ Mother_prim_educ
1 NA                 1                     0              0
2 NA                 0                     0              0
  Mother_second_educ Mother_higher_educ Mother_hindu Mother_muslim
1 1                  0                  1            0
2 0                  1                  1            0
  Mother_not_hindu_nor_muslim Mother_ethni_SC Mother_ethni_ST Mother_ethni_OBC
1 0                            0               0               0
2 0                           NA              NA              NA
  Mother_ethni_other Mother_height Wealth_lowest Wealth_second Wealth_middle
1  1                 1599          0             0             0
2 NA                 1537          0             0             0
  Wealth_fourth Wealth_highest Urban Usual_resident Bednet_slept
1 1             0              1     1              0
2 1             0              1     1              0
  HH_time_water_source HH_air_conditioner HH_treat_water HH_no_toilet
1 0                    0                  1              0
2 0                    0                  1              0
  HH_well_water
1 0
2 0

In [3]:
df_DHS_19 <- readRDS(".././0_input/DHS_data/output/df_children_2019.rds")
sprintf("%i x %i dataframe", nrow(df_DHS_19), ncol(df_DHS_19))
head(df_DHS_19,2)

[1] "101068 x 79 dataframe"

  DHS_round DHSCLUST State_2011      District_2011 cell_x_01 cell_y_01
1 2019      113      Jammu & Kashmir Kupwara       74.4      34.7
2 2019      113      Jammu & Kashmir Kupwara       74.4      34.7
  cell_x_025 cell_y_025 HH_ID Mother_id       Child_id Resp_nb Interview_month
1 74.5       34.75      99      0100101399 02 1        2       9
2 74.5       34.75      57      0100101357 02 1        2       9
  Interview_year Interview_cdc Measured_date_CDC Measured_date Measured_day
1 2019           43719         43717             2019-09-11    11
2 2019           43719         43718             2019-09-12    12
  Measured_month Measured_year Birth_month Birth_year Child_female
1 9              2019          5           2015       0
2 9              2019          8           2018       1
  Child_birth_order Child_alive_age_month Child_hemo_level_alti
1 3                 51                    83
2 4                 12                    78
  Child_weight_for_height_zscore Child_diarrhea Child_fever Child_cough
1    NA                          0              0           0
2 -1.39                          0              0           1
  Child_still_breastfeeding Child_given_plain_water Child_given_juice
1 0                         NA                      NA
2 1                          1                       1
  Child_given_milk Child_given_baby_formula Child_given_fortified_baby_food
1 NA               NA                       NA
2  1                0                        0
  Child_given_soup Child_given_other_liquid Child_given_chicken_duck_birds
1 NA               NA                       NA
2  0                0                        0
  Child_given_bread_noodles_grains Child_given_potatoes_cassava_tubers
1 NA                               NA
2  1                                0
  Child_given_eggs Child_given_pumkins_carrots_squash
1 NA               NA
2  1                0
  Child_given_green_vegetables Child_given_mangoes_papaya_vitaminAfruits
1 NA                           NA
2  0                            0
  Child_given_other_fruits Child_given_liver_heart_organs
1 NA                       NA
2  1                        0
  Child_given_fish_sellfish Child_given_beans_peas_lentils_nuts
1 NA                        NA
2  0                         0
  Child_given_cheese_yogurt_milk_products
1 NA
2  0
  Child_given_other_solid_semisolid_food Child_given_other_meat
1 NA                                     NA
2  1                                      0
  Child_given_yogurt Child_iron_supplem_7d Mother_no_educ Mother_prim_educ
1 NA                 NA                    0              0
2  0                  1                    0              1
  Mother_second_educ Mother_higher_educ Mother_hindu Mother_muslim
1 1                  0                  0            1
2 0                  0                  0            1
  Mother_not_hindu_nor_muslim Mother_ethni_SC Mother_ethni_ST Mother_ethni_OBC
1 0                           0               0               0
2 0                           0               0               0
  Mother_ethni_other Mother_height Wealth_lowest Wealth_second Wealth_middle
1 1                  1614          0             0             1
2 1                  1406          1             0             0
  Wealth_fourth Wealth_highest Urban Usual_resident Bednet_slept
1 0             0              0     1              0
2 0             0              0     1              0
  HH_time_water_source HH_air_conditioner HH_treat_water HH_no_toilet
1 0                    0                  0              0
2 0                    0                  1              0
  HH_well_water
1 0
2 0

In [4]:
df_DHS <- bind_rows(df_DHS_15,df_DHS_19)
sprintf("%i x %i dataframe", nrow(df_DHS), ncol(df_DHS))
head(df_DHS,2)

[1] "344439 x 79 dataframe"

  DHS_round DHSCLUST State_2011               District_2011 cell_x_01 cell_y_01
1 2015      10001    Andaman & Nicobar Island South Andaman 92.7      11.7
2 2015      10001    Andaman & Nicobar Island South Andaman 92.7      11.7
  cell_x_025 cell_y_025 HH_ID Mother_id       Child_id Resp_nb Interview_month
1 92.75      11.75      10     01000110    02 1        2       7
2 92.75      11.75      23     01000123    02 1        2       7
  Interview_year Measured_date_CDC Measured_date Measured_day Measured_month
1 2015           42203             2015-07-20    20           7
2 2015           42203             2015-07-20    20           7
  Measured_year Birth_month Birth_year Child_female Child_birth_order
1 2015          6           2011       1            1
2 2015          2           2013       1            1
  Child_alive_age_month Child_hemo_level_alti Child_weight_for_height_zscore
1 49                    112                    0.16
2 29                    118                   -1.10
  Child_diarrhea Child_fever Child_cough Child_still_breastfeeding
1 0              0           1           0
2 0              0           0           0
  Child_given_plain_water Child_given_juice Child_given_milk
1 NA                      NA                NA
2 NA                      NA                NA
  Child_given_baby_formula Child_given_fortified_baby_food Child_given_soup
1 NA                       NA                              NA
2 NA                       NA                              NA
  Child_given_other_liquid Child_given_chicken_duck_birds
1 NA                       NA
2 NA                       NA
  Child_given_bread_noodles_grains Child_given_potatoes_cassava_tubers
1 NA                               NA
2 NA                               NA
  Child_given_eggs Child_given_pumkins_carrots_squash
1 NA               NA
2 NA               NA
  Child_given_green_vegetables Child_given_mangoes_papaya_vitaminAfruits
1 NA                           NA
2 NA                           NA
  Child_given_other_fruits Child_given_liver_heart_organs
1 NA                       NA
2 NA                       NA
  Child_given_fish_sellfish Child_given_beans_peas_lentils_nuts
1 NA                        NA
2 NA                        NA
  Child_given_cheese_yogurt_milk_products
1 NA
2 NA
  Child_given_other_solid_semisolid_food Child_given_other_meat
1 NA                                     NA
2 NA                                     NA
  Child_given_yogurt Child_iron_supplem_7d Mother_no_educ Mother_prim_educ
1 NA                 1                     0              0
2 NA                 0                     0              0
  Mother_second_educ Mother_higher_educ Mother_hindu Mother_muslim
1 1                  0                  1            0
2 0                  1                  1            0
  Mother_not_hindu_nor_muslim Mother_ethni_SC Mother_ethni_ST Mother_ethni_OBC
1 0                            0               0               0
2 0                           NA              NA              NA
  Mother_ethni_other Mother_height Wealth_lowest Wealth_second Wealth_middle
1  1                 1599          0             0             0
2 NA                 1537          0             0             0
  Wealth_fourth Wealth_highest Urban Usual_resident Bednet_slept
1 1             0              1     1              0
2 1             0              1     1              0
  HH_time_water_source HH_air_conditioner HH_treat_water HH_no_toilet
1 0                    0                  1              0
2 0                    0                  1              0
  HH_well_water Interview_cdc
1 0             NA
2 0             NA

In [5]:
df_DHS_sel <- df_DHS %>%
                #Remove missing values
                filter(Usual_resident==1 & !is.na(Measured_date_CDC))
sprintf("%i x %i dataframe", nrow(df_DHS_sel), ncol(df_DHS_sel))
head(df_DHS_sel,2)

[1] "327626 x 79 dataframe"

  DHS_round DHSCLUST State_2011               District_2011 cell_x_01 cell_y_01
1 2015      10001    Andaman & Nicobar Island South Andaman 92.7      11.7
2 2015      10001    Andaman & Nicobar Island South Andaman 92.7      11.7
  cell_x_025 cell_y_025 HH_ID Mother_id       Child_id Resp_nb Interview_month
1 92.75      11.75      10     01000110    02 1        2       7
2 92.75      11.75      23     01000123    02 1        2       7
  Interview_year Measured_date_CDC Measured_date Measured_day Measured_month
1 2015           42203             2015-07-20    20           7
2 2015           42203             2015-07-20    20           7
  Measured_year Birth_month Birth_year Child_female Child_birth_order
1 2015          6           2011       1            1
2 2015          2           2013       1            1
  Child_alive_age_month Child_hemo_level_alti Child_weight_for_height_zscore
1 49                    112                    0.16
2 29                    118                   -1.10
  Child_diarrhea Child_fever Child_cough Child_still_breastfeeding
1 0              0           1           0
2 0              0           0           0
  Child_given_plain_water Child_given_juice Child_given_milk
1 NA                      NA                NA
2 NA                      NA                NA
  Child_given_baby_formula Child_given_fortified_baby_food Child_given_soup
1 NA                       NA                              NA
2 NA                       NA                              NA
  Child_given_other_liquid Child_given_chicken_duck_birds
1 NA                       NA
2 NA                       NA
  Child_given_bread_noodles_grains Child_given_potatoes_cassava_tubers
1 NA                               NA
2 NA                               NA
  Child_given_eggs Child_given_pumkins_carrots_squash
1 NA               NA
2 NA               NA
  Child_given_green_vegetables Child_given_mangoes_papaya_vitaminAfruits
1 NA                           NA
2 NA                           NA
  Child_given_other_fruits Child_given_liver_heart_organs
1 NA                       NA
2 NA                       NA
  Child_given_fish_sellfish Child_given_beans_peas_lentils_nuts
1 NA                        NA
2 NA                        NA
  Child_given_cheese_yogurt_milk_products
1 NA
2 NA
  Child_given_other_solid_semisolid_food Child_given_other_meat
1 NA                                     NA
2 NA                                     NA
  Child_given_yogurt Child_iron_supplem_7d Mother_no_educ Mother_prim_educ
1 NA                 1                     0              0
2 NA                 0                     0              0
  Mother_second_educ Mother_higher_educ Mother_hindu Mother_muslim
1 1                  0                  1            0
2 0                  1                  1            0
  Mother_not_hindu_nor_muslim Mother_ethni_SC Mother_ethni_ST Mother_ethni_OBC
1 0                            0               0               0
2 0                           NA              NA              NA
  Mother_ethni_other Mother_height Wealth_lowest Wealth_second Wealth_middle
1  1                 1599          0             0             0
2 NA                 1537          0             0             0
  Wealth_fourth Wealth_highest Urban Usual_resident Bednet_slept
1 1             0              1     1              0
2 1             0              1     1              0
  HH_time_water_source HH_air_conditioner HH_treat_water HH_no_toilet
1 0                    0                  1              0
2 0                    0                  1              0
  HH_well_water Interview_cdc
1 0             NA
2 0             NA

# Distinct cells and dates

In [6]:
df_DHS_distinct_children <- df_DHS_sel%>% 
                                distinct(Measured_date_CDC,
                                         cell_x=round(cell_x_025,2),
                                         cell_y=round(cell_y_025,2))
sprintf("%i x %i dataframe", nrow(df_DHS_distinct_children), ncol(df_DHS_distinct_children))
head(df_DHS_distinct_children,2)

[1] "70549 x 3 dataframe"

  Measured_date_CDC cell_x cell_y
1 42203             92.75  11.75
2 42205             92.75   9.25

# MEN

In [7]:
df_DHS_15 <- readRDS(".././0_input/DHS_data/output/df_men_2015_16.rds")
sprintf("%i x %i dataframe", nrow(df_DHS_15), ncol(df_DHS_15))
head(df_DHS_15,2)

[1] "111674 x 87 dataframe"

  DHS_round DHSCLUST State_2011               District_2011 cell_x_01 cell_y_01
1 2015      10001    Andaman & Nicobar Island South Andaman 92.7      11.7
2 2015      10001    Andaman & Nicobar Island South Andaman 92.7      11.7
  cell_x_025 cell_y_025 HH_ID Men_id          Resp_nb Interview_month
1 92.75      11.75      17     01000117     1 1       7
2 92.75      11.75      20     01000120     2 2       7
  Interview_year Interview_day Measured_date_CDC Measured_date Current_age
1 2015           21            42204             2015-07-21    28
2 2015           19            42202             2015-07-19    16
  Age_group Religion_hindu Religion_muslim Religion_not_hindu_nor_muslim
1 25-29     1              0               0
2 15-19     1              0               0
  Ethni_SC Ethni_ST Ethni_OBC Ethni_other N_year_educ Smoker Health_insurance
1 0        0        0         1           10          1      0
2 0        0        0         1           10          0      0
  Profession Blood_pressure_systo Blood_pressure_diasto Blood_glucose_level
1 manual     137                  99                    185
2 no_work    117                  69                    109
  Diet_milk_curd_daily Diet_milk_curd_week Diet_milk_curd_oc
1 0                    1                   0
2 0                    1                   0
  Diet_milk_curd_never Diet_pulses_beans_daily Diet_pulses_beans_week
1 0                    0                       1
2 0                    0                       1
  Diet_pulses_beans_oc Diet_pulses_beans_never Diet_green_veg_daily
1 0                    0                       0
2 0                    0                       0
  Diet_green_veg_week Diet_green_veg_oc Diet_green_veg_never Diet_fruits_daily
1 1                   0                 0                    0
2 1                   0                 0                    0
  Diet_fruits_week Diet_fruits_oc Diet_fruits_never Diet_eggs_daily
1 1                0              0                 0
2 1                0              0                 0
  Diet_eggs_week Diet_eggs_oc Diet_eggs_never Diet_fish_daily Diet_fish_week
1 1              0            0               0               1
2 1              0            0               0               1
  Diet_fish_oc Diet_fish_never Diet_chicken_meat_daily Diet_chicken_meat_week
1 0            0               0                       1
2 0            0               0                       1
  Diet_chicken_meat_oc Diet_chicken_meat_never Diet_fried_food_daily
1 0                    0                       0
2 0                    0                       0
  Diet_fried_food_week Diet_fried_food_oc Diet_fried_food_never
1 1                    0                  0
2 1                    0                  0
  Diet_aerated_drinks_daily Diet_aerated_drinks_week Diet_aerated_drinks_oc
1 0                         0                        1
2 0                         0                        1
  Diet_aerated_drinks_never Wealth_lowest Wealth_second Wealth_middle
1 0                         0             0             1
2 0                         0             0             0
  Wealth_fourth Wealth_highest Urban Usual_resident Blood_hemo_level_alti
1 0             0              1     1              162
2 1             0              1     1              150
  Body_mass_index Bednet_slept HH_time_water_source HH_air_conditioner
1 24.16           1            0                    0
2 21.48           1            0                    0
  HH_treat_water HH_no_toilet HH_well_water cell_x.x cell_y.x cell_x.y cell_y.y
1 0              0            0             92.7     11.7     92.75    11.75
2 1              0            0             92.7     11.7     92.75    11.75

In [8]:
df_DHS_19 <- readRDS(".././0_input/DHS_data/output/df_men_2019.rds")
sprintf("%i x %i dataframe", nrow(df_DHS_19), ncol(df_DHS_19))
head(df_DHS_19,2)

[1] "47587 x 87 dataframe"

  DHS_round DHSCLUST State_2011      District_2011 cell_x_01 cell_y_01
1 2019      130      Jammu & Kashmir Kupwara       74.2      34.4
2 2019      130      Jammu & Kashmir Kupwara       74.2      34.4
  cell_x_025 cell_y_025 HH_ID Men_id          Resp_nb Interview_month
1 74.25      34.5       80      0100103080  5 5       12
2 74.25      34.5       80      0100103080  6 6       12
  Interview_year Interview_day Measured_date_CDC Measured_date Current_age
1 2019           2             43799             2019-12-02    24
2 2019           2             43799             2019-12-02    21
  Age_group Religion_hindu Religion_muslim Religion_not_hindu_nor_muslim
1 20-24     0              1               0
2 20-24     0              1               0
  Ethni_SC Ethni_ST Ethni_OBC Ethni_other N_year_educ Smoker Health_insurance
1 0        0        0         1           8           0      0
2 0        0        0         1           4           0      0
  Profession Blood_pressure_systo Blood_pressure_diasto Blood_glucose_level
1 no_work    134                  91                    101
2 agri       105                  70                    105
  Diet_milk_curd_daily Diet_milk_curd_week Diet_milk_curd_oc
1 0                    1                   0
2 0                    1                   0
  Diet_milk_curd_never Diet_pulses_beans_daily Diet_pulses_beans_week
1 0                    0                       0
2 0                    0                       0
  Diet_pulses_beans_oc Diet_pulses_beans_never Diet_green_veg_daily
1 1                    0                       0
2 1                    0                       0
  Diet_green_veg_week Diet_green_veg_oc Diet_green_veg_never Diet_fruits_daily
1 1                   0                 0                    0
2 1                   0                 0                    0
  Diet_fruits_week Diet_fruits_oc Diet_fruits_never Diet_eggs_daily
1 1                0              0                 0
2 0                1              0                 0
  Diet_eggs_week Diet_eggs_oc Diet_eggs_never Diet_fish_daily Diet_fish_week
1 0              1            0               0               0
2 1              0            0               0               0
  Diet_fish_oc Diet_fish_never Diet_chicken_meat_daily Diet_chicken_meat_week
1 1            0               0                       1
2 1            0               0                       1
  Diet_chicken_meat_oc Diet_chicken_meat_never Diet_fried_food_daily
1 0                    0                       0
2 0                    0                       0
  Diet_fried_food_week Diet_fried_food_oc Diet_fried_food_never
1 0                    1                  0
2 1                    0                  0
  Diet_aerated_drinks_daily Diet_aerated_drinks_week Diet_aerated_drinks_oc
1 0                         0                        1
2 0                         1                        0
  Diet_aerated_drinks_never Wealth_lowest Wealth_second Wealth_middle
1 0                         0             1             0
2 0                         0             1             0
  Wealth_fourth Wealth_highest Urban Usual_resident Blood_hemo_level_alti
1 0             0              0     1              117
2 0             0              0     1              155
  Body_mass_index Bednet_slept HH_time_water_source HH_air_conditioner
1 21.53           0            0                    0
2 20.40           0            0                    0
  HH_treat_water HH_no_toilet HH_well_water cell_x.x cell_y.x cell_x.y cell_y.y
1 1              0            0             74.2     34.4     74.25    34.5
2 1              0            0             74.2     34.4     74.25    34.5

In [9]:
df_DHS <- bind_rows(df_DHS_15,df_DHS_19)
sprintf("%i x %i dataframe", nrow(df_DHS), ncol(df_DHS))
head(df_DHS,2)

[1] "159261 x 87 dataframe"

  DHS_round DHSCLUST State_2011               District_2011 cell_x_01 cell_y_01
1 2015      10001    Andaman & Nicobar Island South Andaman 92.7      11.7
2 2015      10001    Andaman & Nicobar Island South Andaman 92.7      11.7
  cell_x_025 cell_y_025 HH_ID Men_id          Resp_nb Interview_month
1 92.75      11.75      17     01000117     1 1       7
2 92.75      11.75      20     01000120     2 2       7
  Interview_year Interview_day Measured_date_CDC Measured_date Current_age
1 2015           21            42204             2015-07-21    28
2 2015           19            42202             2015-07-19    16
  Age_group Religion_hindu Religion_muslim Religion_not_hindu_nor_muslim
1 25-29     1              0               0
2 15-19     1              0               0
  Ethni_SC Ethni_ST Ethni_OBC Ethni_other N_year_educ Smoker Health_insurance
1 0        0        0         1           10          1      0
2 0        0        0         1           10          0      0
  Profession Blood_pressure_systo Blood_pressure_diasto Blood_glucose_level
1 manual     137                  99                    185
2 no_work    117                  69                    109
  Diet_milk_curd_daily Diet_milk_curd_week Diet_milk_curd_oc
1 0                    1                   0
2 0                    1                   0
  Diet_milk_curd_never Diet_pulses_beans_daily Diet_pulses_beans_week
1 0                    0                       1
2 0                    0                       1
  Diet_pulses_beans_oc Diet_pulses_beans_never Diet_green_veg_daily
1 0                    0                       0
2 0                    0                       0
  Diet_green_veg_week Diet_green_veg_oc Diet_green_veg_never Diet_fruits_daily
1 1                   0                 0                    0
2 1                   0                 0                    0
  Diet_fruits_week Diet_fruits_oc Diet_fruits_never Diet_eggs_daily
1 1                0              0                 0
2 1                0              0                 0
  Diet_eggs_week Diet_eggs_oc Diet_eggs_never Diet_fish_daily Diet_fish_week
1 1              0            0               0               1
2 1              0            0               0               1
  Diet_fish_oc Diet_fish_never Diet_chicken_meat_daily Diet_chicken_meat_week
1 0            0               0                       1
2 0            0               0                       1
  Diet_chicken_meat_oc Diet_chicken_meat_never Diet_fried_food_daily
1 0                    0                       0
2 0                    0                       0
  Diet_fried_food_week Diet_fried_food_oc Diet_fried_food_never
1 1                    0                  0
2 1                    0                  0
  Diet_aerated_drinks_daily Diet_aerated_drinks_week Diet_aerated_drinks_oc
1 0                         0                        1
2 0                         0                        1
  Diet_aerated_drinks_never Wealth_lowest Wealth_second Wealth_middle
1 0                         0             0             1
2 0                         0             0             0
  Wealth_fourth Wealth_highest Urban Usual_resident Blood_hemo_level_alti
1 0             0              1     1              162
2 1             0              1     1              150
  Body_mass_index Bednet_slept HH_time_water_source HH_air_conditioner
1 24.16           1            0                    0
2 21.48           1            0                    0
  HH_treat_water HH_no_toilet HH_well_water cell_x.x cell_y.x cell_x.y cell_y.y
1 0              0            0             92.7     11.7     92.75    11.75
2 1              0            0             92.7     11.7     92.75    11.75

In [10]:
df_DHS_sel <- df_DHS %>%
                #Remove missing values
                filter(Usual_resident==1 & !is.na(Measured_date_CDC))
sprintf("%i x %i dataframe", nrow(df_DHS_sel), ncol(df_DHS_sel))
head(df_DHS_sel,2)

[1] "156818 x 87 dataframe"

  DHS_round DHSCLUST State_2011               District_2011 cell_x_01 cell_y_01
1 2015      10001    Andaman & Nicobar Island South Andaman 92.7      11.7
2 2015      10001    Andaman & Nicobar Island South Andaman 92.7      11.7
  cell_x_025 cell_y_025 HH_ID Men_id          Resp_nb Interview_month
1 92.75      11.75      17     01000117     1 1       7
2 92.75      11.75      20     01000120     2 2       7
  Interview_year Interview_day Measured_date_CDC Measured_date Current_age
1 2015           21            42204             2015-07-21    28
2 2015           19            42202             2015-07-19    16
  Age_group Religion_hindu Religion_muslim Religion_not_hindu_nor_muslim
1 25-29     1              0               0
2 15-19     1              0               0
  Ethni_SC Ethni_ST Ethni_OBC Ethni_other N_year_educ Smoker Health_insurance
1 0        0        0         1           10          1      0
2 0        0        0         1           10          0      0
  Profession Blood_pressure_systo Blood_pressure_diasto Blood_glucose_level
1 manual     137                  99                    185
2 no_work    117                  69                    109
  Diet_milk_curd_daily Diet_milk_curd_week Diet_milk_curd_oc
1 0                    1                   0
2 0                    1                   0
  Diet_milk_curd_never Diet_pulses_beans_daily Diet_pulses_beans_week
1 0                    0                       1
2 0                    0                       1
  Diet_pulses_beans_oc Diet_pulses_beans_never Diet_green_veg_daily
1 0                    0                       0
2 0                    0                       0
  Diet_green_veg_week Diet_green_veg_oc Diet_green_veg_never Diet_fruits_daily
1 1                   0                 0                    0
2 1                   0                 0                    0
  Diet_fruits_week Diet_fruits_oc Diet_fruits_never Diet_eggs_daily
1 1                0              0                 0
2 1                0              0                 0
  Diet_eggs_week Diet_eggs_oc Diet_eggs_never Diet_fish_daily Diet_fish_week
1 1              0            0               0               1
2 1              0            0               0               1
  Diet_fish_oc Diet_fish_never Diet_chicken_meat_daily Diet_chicken_meat_week
1 0            0               0                       1
2 0            0               0                       1
  Diet_chicken_meat_oc Diet_chicken_meat_never Diet_fried_food_daily
1 0                    0                       0
2 0                    0                       0
  Diet_fried_food_week Diet_fried_food_oc Diet_fried_food_never
1 1                    0                  0
2 1                    0                  0
  Diet_aerated_drinks_daily Diet_aerated_drinks_week Diet_aerated_drinks_oc
1 0                         0                        1
2 0                         0                        1
  Diet_aerated_drinks_never Wealth_lowest Wealth_second Wealth_middle
1 0                         0             0             1
2 0                         0             0             0
  Wealth_fourth Wealth_highest Urban Usual_resident Blood_hemo_level_alti
1 0             0              1     1              162
2 1             0              1     1              150
  Body_mass_index Bednet_slept HH_time_water_source HH_air_conditioner
1 24.16           1            0                    0
2 21.48           1            0                    0
  HH_treat_water HH_no_toilet HH_well_water cell_x.x cell_y.x cell_x.y cell_y.y
1 0              0            0             92.7     11.7     92.75    11.75
2 1              0            0             92.7     11.7     92.75    11.75

In [11]:
df_DHS_distinct_men <- df_DHS_sel%>% 
                        distinct(Measured_date_CDC,
                                 cell_x=round(cell_x_025,2),
                                 cell_y=round(cell_y_025,2))
sprintf("%i x %i dataframe", nrow(df_DHS_distinct_men), ncol(df_DHS_distinct_men))
head(df_DHS_distinct_men,2)

[1] "39765 x 3 dataframe"

  Measured_date_CDC cell_x cell_y
1 42204             92.75  11.75
2 42202             92.75  11.75

# WOMEN

In [12]:
df_DHS_15 <- readRDS(".././0_input/DHS_data/output/df_women_2015_16.rds")
sprintf("%i x %i dataframe", nrow(df_DHS_15), ncol(df_DHS_15))
head(df_DHS_15,2)

[1] "696459 x 87 dataframe"

  DHS_round DHSCLUST State_2011               District_2011 cell_x_01 cell_y_01
1 2015      10001    Andaman & Nicobar Island South Andaman 92.7      11.7
2 2015      10001    Andaman & Nicobar Island South Andaman 92.7      11.7
  cell_x_025 cell_y_025 HH_ID Women_id        Resp_nb Interview_month
1 92.75      11.75      1      01000101    02 2       7
2 92.75      11.75      1      01000101    04 4       7
  Interview_year Interview_day Measured_date_CDC Measured_date Current_age
1 2015           18            42201             2015-07-18    46
2 2015           18            42201             2015-07-18    20
  Age_group Religion_hindu Religion_muslim Religion_not_hindu_nor_muslim
1 45-49     0              0               1
2 20-24     0              0               1
  Ethni_SC Ethni_ST Ethni_OBC Ethni_other N_year_educ Smoker Health_insurance
1 0        0        0         1            0          1      0
2 0        0        0         1           14          0      0
  Currently_pregnant Blood_hemo_level_alti Blood_pressure_systo
1 0                   81                   115
2 0                  113                    96
  Blood_pressure_diasto Blood_glucose_level Body_mass_index
1 76                    116                 22.95
2 72                     83                 22.03
  Diet_milk_curd_daily Diet_milk_curd_week Diet_milk_curd_oc
1 0                    0                   0
2 0                    0                   1
  Diet_milk_curd_never Diet_pulses_beans_daily Diet_pulses_beans_week
1 1                    1                       0
2 0                    1                       0
  Diet_pulses_beans_oc Diet_pulses_beans_never Diet_green_veg_daily
1 0                    0                       0
2 0                    0                       0
  Diet_green_veg_week Diet_green_veg_oc Diet_green_veg_never Diet_fruits_daily
1 1                   0                 0                    0
2 1                   0                 0                    0
  Diet_fruits_week Diet_fruits_oc Diet_fruits_never Diet_eggs_daily
1 1                0              0                 0
2 0                1              0                 0
  Diet_eggs_week Diet_eggs_oc Diet_eggs_never Diet_fish_daily Diet_fish_week
1 1              0            0               0               1
2 1              0            0               0               1
  Diet_fish_oc Diet_fish_never Diet_chicken_meat_daily Diet_chicken_meat_week
1 0            0               0                       0
2 0            0               0                       1
  Diet_chicken_meat_oc Diet_chicken_meat_never Diet_fried_food_daily
1 1                    0                       0
2 0                    0                       0
  Diet_fried_food_week Diet_fried_food_oc Diet_fried_food_never
1 1                    0                  0
2 1                    0                  0
  Diet_aerated_drinks_daily Diet_aerated_drinks_week Diet_aerated_drinks_oc
1 0                         1                        0
2 0                         1                        0
  Diet_aerated_drinks_never Wealth_lowest Wealth_second Wealth_middle
1 0                         0             0             1
2 0                         0             0             1
  Wealth_fourth Wealth_highest Urban Usual_resident Bednet_slept
1 0             0              1     1              0
2 0             0              1     1              0
  HH_time_water_source HH_air_conditioner HH_treat_water HH_no_toilet
1 0                    0                  0              0
2 0                    0                  0              0
  HH_well_water cell_x.x cell_y.x cell_x.y cell_y.y
1 0             92.7     11.7     92.75    11.75
2 0             92.7     11.7     92.75    11.75

In [13]:
df_DHS_19 <- readRDS(".././0_input/DHS_data/output/df_women_2019.rds")
sprintf("%i x %i dataframe", nrow(df_DHS_19), ncol(df_DHS_19))
head(df_DHS_19,2)

[1] "334168 x 87 dataframe"

  DHS_round DHSCLUST State_2011      District_2011 cell_x_01 cell_y_01
1 2019      113      Jammu & Kashmir Kupwara       74.4      34.7
2 2019      113      Jammu & Kashmir Kupwara       74.4      34.7
  cell_x_025 cell_y_025 HH_ID Women_id        Resp_nb Interview_month
1 74.5       34.75      5       0100101305 04 4       9
2 74.5       34.75      5       0100101305 05 5       9
  Interview_year Interview_day Measured_date_CDC Measured_date Current_age
1 2019           11            43717             2019-09-11    22
2 2019           12            43718             2019-09-12    19
  Age_group Religion_hindu Religion_muslim Religion_not_hindu_nor_muslim
1 20-24     0              1               0
2 15-19     0              1               0
  Ethni_SC Ethni_ST Ethni_OBC Ethni_other N_year_educ Smoker Health_insurance
1 0        0        0         1           13          0      0
2 0        0        0         1           11          0      0
  Currently_pregnant Blood_hemo_level_alti Blood_pressure_systo
1 0                  106                   125
2 0                   82                   118
  Blood_pressure_diasto Blood_glucose_level Body_mass_index
1 79                    125                 17.34
2 75                    107                 15.86
  Diet_milk_curd_daily Diet_milk_curd_week Diet_milk_curd_oc
1 1                    0                   0
2 0                    0                   1
  Diet_milk_curd_never Diet_pulses_beans_daily Diet_pulses_beans_week
1 0                    0                       1
2 0                    0                       1
  Diet_pulses_beans_oc Diet_pulses_beans_never Diet_green_veg_daily
1 0                    0                       1
2 0                    0                       1
  Diet_green_veg_week Diet_green_veg_oc Diet_green_veg_never Diet_fruits_daily
1 0                   0                 0                    0
2 0                   0                 0                    0
  Diet_fruits_week Diet_fruits_oc Diet_fruits_never Diet_eggs_daily
1 0                1              0                 0
2 0                1              0                 0
  Diet_eggs_week Diet_eggs_oc Diet_eggs_never Diet_fish_daily Diet_fish_week
1 0              1            0               0               0
2 0              1            0               0               0
  Diet_fish_oc Diet_fish_never Diet_chicken_meat_daily Diet_chicken_meat_week
1 1            0               0                       0
2 1            0               0                       0
  Diet_chicken_meat_oc Diet_chicken_meat_never Diet_fried_food_daily
1 1                    0                       0
2 1                    0                       0
  Diet_fried_food_week Diet_fried_food_oc Diet_fried_food_never
1 0                    0                  1
2 0                    0                  1
  Diet_aerated_drinks_daily Diet_aerated_drinks_week Diet_aerated_drinks_oc
1 0                         0                        0
2 0                         0                        0
  Diet_aerated_drinks_never Wealth_lowest Wealth_second Wealth_middle
1 1                         0             0             1
2 1                         0             0             1
  Wealth_fourth Wealth_highest Urban Usual_resident Bednet_slept
1 0             0              0     1              0
2 0             0              0     1              0
  HH_time_water_source HH_air_conditioner HH_treat_water HH_no_toilet
1 0                    0                  0              0
2 0                    0                  0              0
  HH_well_water cell_x.x cell_y.x cell_x.y cell_y.y
1 0             74.4     34.7     74.5     34.75
2 0             74.4     34.7     74.5     34.75

In [14]:
df_DHS <- bind_rows(df_DHS_15,df_DHS_19)
sprintf("%i x %i dataframe", nrow(df_DHS), ncol(df_DHS))
head(df_DHS,2)

[1] "1030627 x 87 dataframe"

  DHS_round DHSCLUST State_2011               District_2011 cell_x_01 cell_y_01
1 2015      10001    Andaman & Nicobar Island South Andaman 92.7      11.7
2 2015      10001    Andaman & Nicobar Island South Andaman 92.7      11.7
  cell_x_025 cell_y_025 HH_ID Women_id        Resp_nb Interview_month
1 92.75      11.75      1      01000101    02 2       7
2 92.75      11.75      1      01000101    04 4       7
  Interview_year Interview_day Measured_date_CDC Measured_date Current_age
1 2015           18            42201             2015-07-18    46
2 2015           18            42201             2015-07-18    20
  Age_group Religion_hindu Religion_muslim Religion_not_hindu_nor_muslim
1 45-49     0              0               1
2 20-24     0              0               1
  Ethni_SC Ethni_ST Ethni_OBC Ethni_other N_year_educ Smoker Health_insurance
1 0        0        0         1            0          1      0
2 0        0        0         1           14          0      0
  Currently_pregnant Blood_hemo_level_alti Blood_pressure_systo
1 0                   81                   115
2 0                  113                    96
  Blood_pressure_diasto Blood_glucose_level Body_mass_index
1 76                    116                 22.95
2 72                     83                 22.03
  Diet_milk_curd_daily Diet_milk_curd_week Diet_milk_curd_oc
1 0                    0                   0
2 0                    0                   1
  Diet_milk_curd_never Diet_pulses_beans_daily Diet_pulses_beans_week
1 1                    1                       0
2 0                    1                       0
  Diet_pulses_beans_oc Diet_pulses_beans_never Diet_green_veg_daily
1 0                    0                       0
2 0                    0                       0
  Diet_green_veg_week Diet_green_veg_oc Diet_green_veg_never Diet_fruits_daily
1 1                   0                 0                    0
2 1                   0                 0                    0
  Diet_fruits_week Diet_fruits_oc Diet_fruits_never Diet_eggs_daily
1 1                0              0                 0
2 0                1              0                 0
  Diet_eggs_week Diet_eggs_oc Diet_eggs_never Diet_fish_daily Diet_fish_week
1 1              0            0               0               1
2 1              0            0               0               1
  Diet_fish_oc Diet_fish_never Diet_chicken_meat_daily Diet_chicken_meat_week
1 0            0               0                       0
2 0            0               0                       1
  Diet_chicken_meat_oc Diet_chicken_meat_never Diet_fried_food_daily
1 1                    0                       0
2 0                    0                       0
  Diet_fried_food_week Diet_fried_food_oc Diet_fried_food_never
1 1                    0                  0
2 1                    0                  0
  Diet_aerated_drinks_daily Diet_aerated_drinks_week Diet_aerated_drinks_oc
1 0                         1                        0
2 0                         1                        0
  Diet_aerated_drinks_never Wealth_lowest Wealth_second Wealth_middle
1 0                         0             0             1
2 0                         0             0             1
  Wealth_fourth Wealth_highest Urban Usual_resident Bednet_slept
1 0             0              1     1              0
2 0             0              1     1              0
  HH_time_water_source HH_air_conditioner HH_treat_water HH_no_toilet
1 0                    0                  0              0
2 0                    0                  0              0
  HH_well_water cell_x.x cell_y.x cell_x.y cell_y.y
1 0             92.7     11.7     92.75    11.75
2 0             92.7     11.7     92.75    11.75

In [15]:
df_DHS_sel <- df_DHS %>%
                #Remove missing values
                filter(Usual_resident==1 & !is.na(Measured_date_CDC))
sprintf("%i x %i dataframe", nrow(df_DHS_sel), ncol(df_DHS_sel))
head(df_DHS_sel,2)

[1] "1000562 x 87 dataframe"

  DHS_round DHSCLUST State_2011               District_2011 cell_x_01 cell_y_01
1 2015      10001    Andaman & Nicobar Island South Andaman 92.7      11.7
2 2015      10001    Andaman & Nicobar Island South Andaman 92.7      11.7
  cell_x_025 cell_y_025 HH_ID Women_id        Resp_nb Interview_month
1 92.75      11.75      1      01000101    02 2       7
2 92.75      11.75      1      01000101    04 4       7
  Interview_year Interview_day Measured_date_CDC Measured_date Current_age
1 2015           18            42201             2015-07-18    46
2 2015           18            42201             2015-07-18    20
  Age_group Religion_hindu Religion_muslim Religion_not_hindu_nor_muslim
1 45-49     0              0               1
2 20-24     0              0               1
  Ethni_SC Ethni_ST Ethni_OBC Ethni_other N_year_educ Smoker Health_insurance
1 0        0        0         1            0          1      0
2 0        0        0         1           14          0      0
  Currently_pregnant Blood_hemo_level_alti Blood_pressure_systo
1 0                   81                   115
2 0                  113                    96
  Blood_pressure_diasto Blood_glucose_level Body_mass_index
1 76                    116                 22.95
2 72                     83                 22.03
  Diet_milk_curd_daily Diet_milk_curd_week Diet_milk_curd_oc
1 0                    0                   0
2 0                    0                   1
  Diet_milk_curd_never Diet_pulses_beans_daily Diet_pulses_beans_week
1 1                    1                       0
2 0                    1                       0
  Diet_pulses_beans_oc Diet_pulses_beans_never Diet_green_veg_daily
1 0                    0                       0
2 0                    0                       0
  Diet_green_veg_week Diet_green_veg_oc Diet_green_veg_never Diet_fruits_daily
1 1                   0                 0                    0
2 1                   0                 0                    0
  Diet_fruits_week Diet_fruits_oc Diet_fruits_never Diet_eggs_daily
1 1                0              0                 0
2 0                1              0                 0
  Diet_eggs_week Diet_eggs_oc Diet_eggs_never Diet_fish_daily Diet_fish_week
1 1              0            0               0               1
2 1              0            0               0               1
  Diet_fish_oc Diet_fish_never Diet_chicken_meat_daily Diet_chicken_meat_week
1 0            0               0                       0
2 0            0               0                       1
  Diet_chicken_meat_oc Diet_chicken_meat_never Diet_fried_food_daily
1 1                    0                       0
2 0                    0                       0
  Diet_fried_food_week Diet_fried_food_oc Diet_fried_food_never
1 1                    0                  0
2 1                    0                  0
  Diet_aerated_drinks_daily Diet_aerated_drinks_week Diet_aerated_drinks_oc
1 0                         1                        0
2 0                         1                        0
  Diet_aerated_drinks_never Wealth_lowest Wealth_second Wealth_middle
1 0                         0             0             1
2 0                         0             0             1
  Wealth_fourth Wealth_highest Urban Usual_resident Bednet_slept
1 0             0              1     1              0
2 0             0              1     1              0
  HH_time_water_source HH_air_conditioner HH_treat_water HH_no_toilet
1 0                    0                  0              0
2 0                    0                  0              0
  HH_well_water cell_x.x cell_y.x cell_x.y cell_y.y
1 0             92.7     11.7     92.75    11.75
2 0             92.7     11.7     92.75    11.75

In [16]:
df_DHS_distinct_women <- df_DHS_sel%>% 
                        distinct(Measured_date_CDC,
                                 cell_x=round(cell_x_025,2),
                                 cell_y=round(cell_y_025,2))
sprintf("%i x %i dataframe", nrow(df_DHS_distinct_women), ncol(df_DHS_distinct_women))
head(df_DHS_distinct_women,2)

[1] "90873 x 3 dataframe"

  Measured_date_CDC cell_x cell_y
1 42201             92.75  11.75
2 42202             92.75  11.75

## Merge cells and dates

In [17]:
df_children_men <- rbind(df_DHS_distinct_children,df_DHS_distinct_men)%>%
                            distinct(Measured_date_CDC,cell_x,cell_y)
sprintf("%i x %i dataframe", nrow(df_children_men), ncol(df_children_men))
head(df_children_men,2)

[1] "80781 x 3 dataframe"

  Measured_date_CDC cell_x cell_y
1 42203             92.75  11.75
2 42205             92.75   9.25

In [18]:
nrow(df_DHS_distinct_children) + nrow(df_DHS_distinct_men)

[1] 110314

In [19]:
df_women_men <- rbind(df_DHS_distinct_women,df_DHS_distinct_men)%>%
                            distinct(Measured_date_CDC,cell_x,cell_y)
sprintf("%i x %i dataframe", nrow(df_women_men), ncol(df_women_men))
head(df_women_men,2)

[1] "92140 x 3 dataframe"

  Measured_date_CDC cell_x cell_y
1 42201             92.75  11.75
2 42202             92.75  11.75

In [20]:
nrow(df_DHS_distinct_women) + nrow(df_DHS_distinct_men)

[1] 130638

In [21]:
df_children_women <- rbind(df_DHS_distinct_children,df_DHS_distinct_women)%>%
                            distinct(Measured_date_CDC,cell_x,cell_y)
sprintf("%i x %i dataframe", nrow(df_children_women), ncol(df_children_women))
head(df_children_women,2)

[1] "93121 x 3 dataframe"

  Measured_date_CDC cell_x cell_y
1 42203             92.75  11.75
2 42205             92.75   9.25

In [22]:
df_children_men_women <- rbind(df_DHS_distinct_children,df_DHS_distinct_men,df_DHS_distinct_women)%>%
                            distinct(Measured_date_CDC,cell_x,cell_y)
sprintf("%i x %i dataframe", nrow(df_children_men_women), ncol(df_children_men_women))
head(df_children_men_women,2)

[1] "94121 x 3 dataframe"

  Measured_date_CDC cell_x cell_y
1 42203             92.75  11.75
2 42205             92.75   9.25

## SAVE

In [23]:
write_csv(df_children_men_women,"./interm/df_distinct_cells_CDC_025.csv")

# Description

In [24]:
as.Date(min(df_children_men_women$Measured_date_CDC), origin = "1900-01-01")

[1] "2015-01-20"

In [25]:
as.Date(max(df_children_men_women$Measured_date_CDC), origin = "1900-01-01")

[1] "2020-02-10"

In [26]:
nrow(df_children_men_women%>%filter(is.na(cell_x)))

[1] 0