In [1]:
list.of.packages <- c("tidyverse","data.table","stargazer")
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages, repos = "http://cran.us.r-project.org")

invisible(lapply(list.of.packages, library, character.only = TRUE))

options(repr.matrix.max.rows=500, repr.matrix.max.cols=1200, message=FALSE, warning=TRUE)

── Attaching core tidyverse packages ────────────────────────────────────────────────────────────────────────────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.1     ✔ stringr   1.6.0
✔ ggplot2   4.0.0     ✔ tibble    3.3.0
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.2.0
── Conflicts ──────────────────────────────────────────────────────────────────────────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

Attachement du package : ‘data.table’


Les objets suivants sont masqués depuis ‘package:lubridate’:

    hour, isoweek, mday, minute, month, quarter, second, wday, week,
    yday, year


Les objets suivants sont masqués depuis ‘package:dplyr’:

    between, first, last


L'objet suivant est masqué depuis ‘package:purrr’:

    transpose



Please cite as:


 Hlavac, Marek (2022). stargazer: Well-Formatted Regression and Summary Statistics Tables.

 R package version 5.2.3. https://CRAN.R-project.org/package=stargazer

# Negative temperature dataframe

In [2]:
df_deg_bins_neg <- fread("./interm/df_T_cells_CDC_negative.csv")
sprintf("%i x %i dataframe", nrow(df_deg_bins_neg), ncol(df_deg_bins_neg))
head(df_deg_bins_neg,2)

[1] "173657 x 933 dataframe"

  Measured_date_CDC cell_x cell_y T-1DayMin1 T-1DayMin2 T-1DayMin3 T-1DayMin4
1 42203             92.7   11.7   0          0          0          0
2 42205             92.8    9.2   0          0          0          0
  T-1DayMin5 T-1DayMin6 T-1DayMin7 T-1DayMin8 T-1DayMin9 T-1DayMin10
1 0          0          0          0          0          0
2 0          0          0          0          0          0
  T-1DayMin11 T-1DayMin12 T-1DayMin13 T-1DayMin14 T-1DayMin15 T-1DayMin16
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-1DayMin17 T-1DayMin18 T-1DayMin19 T-1DayMin20 T-1DayMin21 T-1DayMin22
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-1DayMin23 T-1DayMin24 T-1DayMin25 T-1DayMin26 T-1DayMin27 T-1DayMin28
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-1DayMin29 T-1DayMin30 T-2DayMin1 T-2DayMin2 T-2DayMin3 T-2DayMin4
1 0           0           0          0          0          0
2 0           0           0          0          0          0
  T-2DayMin5 T-2DayMin6 T-2DayMin7 T-2DayMin8 T-2DayMin9 T-2DayMin10
1 0          0          0          0          0          0
2 0          0          0          0          0          0
  T-2DayMin11 T-2DayMin12 T-2DayMin13 T-2DayMin14 T-2DayMin15 T-2DayMin16
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-2DayMin17 T-2DayMin18 T-2DayMin19 T-2DayMin20 T-2DayMin21 T-2DayMin22
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-2DayMin23 T-2DayMin24 T-2DayMin25 T-2DayMin26 T-2DayMin27 T-2DayMin28
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-2DayMin29 T-2DayMin30 T-3DayMin1 T-3DayMin2 T-3DayMin3 T-3DayMin4
1 0           0           0          0          0          0
2 0           0           0          0          0          0
  T-3DayMin5 T-3DayMin6 T-3DayMin7 T-3DayMin8 T-3DayMin9 T-3DayMin10
1 0          0          0          0          0          0
2 0          0          0          0          0          0
  T-3DayMin11 T-3DayMin12 T-3DayMin13 T-3DayMin14 T-3DayMin15 T-3DayMin16
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-3DayMin17 T-3DayMin18 T-3DayMin19 T-3DayMin20 T-3DayMin21 T-3DayMin22
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-3DayMin23 T-3DayMin24 T-3DayMin25 T-3DayMin26 T-3DayMin27 T-3DayMin28
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-3DayMin29 T-3DayMin30 T-4DayMin1 T-4DayMin2 T-4DayMin3 T-4DayMin4
1 0           0           0          0          0          0
2 0           0           0          0          0          0
  T-4DayMin5 T-4DayMin6 T-4DayMin7 T-4DayMin8 T-4DayMin9 T-4DayMin10
1 0          0          0          0          0          0
2 0          0          0          0          0          0
  T-4DayMin11 T-4DayMin12 T-4DayMin13 T-4DayMin14 T-4DayMin15 T-4DayMin16
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-4DayMin17 T-4DayMin18 T-4DayMin19 T-4DayMin20 T-4DayMin21 T-4DayMin22
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-4DayMin23 T-4DayMin24 T-4DayMin25 T-4DayMin26 T-4DayMin27 T-4DayMin28
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-4DayMin29 T-4DayMin30 T-5DayMin1 T-5DayMin2 T-5DayMin3 T-5DayMin4
1 0           0           0          0          0          0
2 0           0           0          0          0          0
  T-5DayMin5 T-5DayMin6 T-5DayMin7 T-5DayMin8 T-5DayMin9 T-5DayMin10
1 0          0          0          0          0          0
2 0          0          0          0          0          0
  T-5DayMin11 T-5DayMin12 T-5DayMin13 T-5DayMin14 T-5DayMin15 T-5DayMin16
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-5DayMin17 T-5DayMin18 T-5DayMin19 T-5DayMin20 T-5DayMin21 T-5DayMin22
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-5DayMin23 T-5DayMin24 T-5DayMin25 T-5DayMin26 T-5DayMin27 T-5DayMin28
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-5DayMin29 T-5DayMin30 T-6DayMin1 T-6DayMin2 T-6DayMin3 T-6DayMin4
1 0           0           0          0          0          0
2 0           0           0          0          0          0
  T-6DayMin5 T-6DayMin6 T-6DayMin7 T-6DayMin8 T-6DayMin9 T-6DayMin10
1 0          0          0          0          0          0
2 0          0          0          0          0          0
  T-6DayMin11 T-6DayMin12 T-6DayMin13 T-6DayMin14 T-6DayMin15 T-6DayMin16
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-6DayMin17 T-6DayMin18 T-6DayMin19 T-6DayMin20 T-6DayMin21 T-6DayMin22
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-6DayMin23 T-6DayMin24 T-6DayMin25 T-6DayMin26 T-6DayMin27 T-6DayMin28
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-6DayMin29 T-6DayMin30 T-7DayMin1 T-7DayMin2 T-7DayMin3 T-7DayMin4
1 0           0           0          0          0          0
2 0           0           0          0          0          0
  T-7DayMin5 T-7DayMin6 T-7DayMin7 T-7DayMin8 T-7DayMin9 T-7DayMin10
1 0          0          0          0          0          0
2 0          0          0          0          0          0
  T-7DayMin11 T-7DayMin12 T-7DayMin13 T-7DayMin14 T-7DayMin15 T-7DayMin16
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-7DayMin17 T-7DayMin18 T-7DayMin19 T-7DayMin20 T-7DayMin21 T-7DayMin22
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-7DayMin23 T-7DayMin24 T-7DayMin25 T-7DayMin26 T-7DayMin27 T-7DayMin28
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-7DayMin29 T-7DayMin30 T-8DayMin1 T-8DayMin2 T-8DayMin3 T-8DayMin4
1 0           0           0          0          0          0
2 0           0           0          0          0          0
  T-8DayMin5 T-8DayMin6 T-8DayMin7 T-8DayMin8 T-8DayMin9 T-8DayMin10
1 0          0          0          0          0          0
2 0          0          0          0          0          0
  T-8DayMin11 T-8DayMin12 T-8DayMin13 T-8DayMin14 T-8DayMin15 T-8DayMin16
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-8DayMin17 T-8DayMin18 T-8DayMin19 T-8DayMin20 T-8DayMin21 T-8DayMin22
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-8DayMin23 T-8DayMin24 T-8DayMin25 T-8DayMin26 T-8DayMin27 T-8DayMin28
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-8DayMin29 T-8DayMin30 T-9DayMin1 T-9DayMin2 T-9DayMin3 T-9DayMin4
1 0           0           0          0          0          0
2 0           0           0          0          0          0
  T-9DayMin5 T-9DayMin6 T-9DayMin7 T-9DayMin8 T-9DayMin9 T-9DayMin10
1 0          0          0          0          0          0
2 0          0          0          0          0          0
  T-9DayMin11 T-9DayMin12 T-9DayMin13 T-9DayMin14 T-9DayMin15 T-9DayMin16
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-9DayMin17 T-9DayMin18 T-9DayMin19 T-9DayMin20 T-9DayMin21 T-9DayMin22
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-9DayMin23 T-9DayMin24 T-9DayMin25 T-9DayMin26 T-9DayMin27 T-9DayMin28
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-9DayMin29 T-9DayMin30 T-10DayMin1 T-10DayMin2 T-10DayMin3 T-10DayMin4
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-10DayMin5 T-10DayMin6 T-10DayMin7 T-10DayMin8 T-10DayMin9 T-10DayMin10
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-10DayMin11 T-10DayMin12 T-10DayMin13 T-10DayMin14 T-10DayMin15 T-10DayMin16
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-10DayMin17 T-10DayMin18 T-10DayMin19 T-10DayMin20 T-10DayMin21 T-10DayMin22
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-10DayMin23 T-10DayMin24 T-10DayMin25 T-10DayMin26 T-10DayMin27 T-10DayMin28
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-10DayMin29 T-10DayMin30 T-11DayMin1 T-11DayMin2 T-11DayMin3 T-11DayMin4
1 0            0            0           0           0           0
2 0            0            0           0           0           0
  T-11DayMin5 T-11DayMin6 T-11DayMin7 T-11DayMin8 T-11DayMin9 T-11DayMin10
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-11DayMin11 T-11DayMin12 T-11DayMin13 T-11DayMin14 T-11DayMin15 T-11DayMin16
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-11DayMin17 T-11DayMin18 T-11DayMin19 T-11DayMin20 T-11DayMin21 T-11DayMin22
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-11DayMin23 T-11DayMin24 T-11DayMin25 T-11DayMin26 T-11DayMin27 T-11DayMin28
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-11DayMin29 T-11DayMin30 T-12DayMin1 T-12DayMin2 T-12DayMin3 T-12DayMin4
1 0            0            0           0           0           0
2 0            0            0           0           0           0
  T-12DayMin5 T-12DayMin6 T-12DayMin7 T-12DayMin8 T-12DayMin9 T-12DayMin10
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-12DayMin11 T-12DayMin12 T-12DayMin13 T-12DayMin14 T-12DayMin15 T-12DayMin16
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-12DayMin17 T-12DayMin18 T-12DayMin19 T-12DayMin20 T-12DayMin21 T-12DayMin22
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-12DayMin23 T-12DayMin24 T-12DayMin25 T-12DayMin26 T-12DayMin27 T-12DayMin28
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-12DayMin29 T-12DayMin30 T-13DayMin1 T-13DayMin2 T-13DayMin3 T-13DayMin4
1 0            0            0           0           0           0
2 0            0            0           0           0           0
  T-13DayMin5 T-13DayMin6 T-13DayMin7 T-13DayMin8 T-13DayMin9 T-13DayMin10
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-13DayMin11 T-13DayMin12 T-13DayMin13 T-13DayMin14 T-13DayMin15 T-13DayMin16
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-13DayMin17 T-13DayMin18 T-13DayMin19 T-13DayMin20 T-13DayMin21 T-13DayMin22
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-13DayMin23 T-13DayMin24 T-13DayMin25 T-13DayMin26 T-13DayMin27 T-13DayMin28
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-13DayMin29 T-13DayMin30 T-14DayMin1 T-14DayMin2 T-14DayMin3 T-14DayMin4
1 0            0            0           0           0           0
2 0            0            0           0           0           0
  T-14DayMin5 T-14DayMin6 T-14DayMin7 T-14DayMin8 T-14DayMin9 T-14DayMin10
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-14DayMin11 T-14DayMin12 T-14DayMin13 T-14DayMin14 T-14DayMin15 T-14DayMin16
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-14DayMin17 T-14DayMin18 T-14DayMin19 T-14DayMin20 T-14DayMin21 T-14DayMin22
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-14DayMin23 T-14DayMin24 T-14DayMin25 T-14DayMin26 T-14DayMin27 T-14DayMin28
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-14DayMin29 T-14DayMin30 T-15DayMin1 T-15DayMin2 T-15DayMin3 T-15DayMin4
1 0            0            0           0           0           0
2 0            0            0           0           0           0
  T-15DayMin5 T-15DayMin6 T-15DayMin7 T-15DayMin8 T-15DayMin9 T-15DayMin10
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-15DayMin11 T-15DayMin12 T-15DayMin13 T-15DayMin14 T-15DayMin15 T-15DayMin16
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-15DayMin17 T-15DayMin18 T-15DayMin19 T-15DayMin20 T-15DayMin21 T-15DayMin22
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-15DayMin23 T-15DayMin24 T-15DayMin25 T-15DayMin26 T-15DayMin27 T-15DayMin28
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-15DayMin29 T-15DayMin30 T-16DayMin1 T-16DayMin2 T-16DayMin3 T-16DayMin4
1 0            0            0           0           0           0
2 0            0            0           0           0           0
  T-16DayMin5 T-16DayMin6 T-16DayMin7 T-16DayMin8 T-16DayMin9 T-16DayMin10
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-16DayMin11 T-16DayMin12 T-16DayMin13 T-16DayMin14 T-16DayMin15 T-16DayMin16
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-16DayMin17 T-16DayMin18 T-16DayMin19 T-16DayMin20 T-16DayMin21 T-16DayMin22
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-16DayMin23 T-16DayMin24 T-16DayMin25 T-16DayMin26 T-16DayMin27 T-16DayMin28
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-16DayMin29 T-16DayMin30 T-17DayMin1 T-17DayMin2 T-17DayMin3 T-17DayMin4
1 0            0            0           0           0           0
2 0            0            0           0           0           0
  T-17DayMin5 T-17DayMin6 T-17DayMin7 T-17DayMin8 T-17DayMin9 T-17DayMin10
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-17DayMin11 T-17DayMin12 T-17DayMin13 T-17DayMin14 T-17DayMin15 T-17DayMin16
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-17DayMin17 T-17DayMin18 T-17DayMin19 T-17DayMin20 T-17DayMin21 T-17DayMin22
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-17DayMin23 T-17DayMin24 T-17DayMin25 T-17DayMin26 T-17DayMin27 T-17DayMin28
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-17DayMin29 T-17DayMin30 T-18DayMin1 T-18DayMin2 T-18DayMin3 T-18DayMin4
1 0            0            0           0           0           0
2 0            0            0           0           0           0
  T-18DayMin5 T-18DayMin6 T-18DayMin7 T-18DayMin8 T-18DayMin9 T-18DayMin10
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-18DayMin11 T-18DayMin12 T-18DayMin13 T-18DayMin14 T-18DayMin15 T-18DayMin16
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-18DayMin17 T-18DayMin18 T-18DayMin19 T-18DayMin20 T-18DayMin21 T-18DayMin22
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-18DayMin23 T-18DayMin24 T-18DayMin25 T-18DayMin26 T-18DayMin27 T-18DayMin28
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-18DayMin29 T-18DayMin30 T-19DayMin1 T-19DayMin2 T-19DayMin3 T-19DayMin4
1 0            0            0           0           0           0
2 0            0            0           0           0           0
  T-19DayMin5 T-19DayMin6 T-19DayMin7 T-19DayMin8 T-19DayMin9 T-19DayMin10
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T-19DayMin11 T-19DayMin12 T-19DayMin13 T-19DayMin14 T-19DayMin15 T-19DayMin16
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-19DayMin17 T-19DayMin18 T-19DayMin19 T-19DayMin20 T-19DayMin21 T-19DayMin22
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-19DayMin23 T-19DayMin24 T-19DayMin25 T-19DayMin26 T-19DayMin27 T-19DayMin28
1 0            0            0            0            0            0
2 0            0            0            0            0            0
  T-19DayMin29 T-19DayMin30 T-20DayMin1 T-20DayMin2 T-20DayMin3 T-20DayMin4
1 0            0            0           0           0           0
2 0            0            0           0           0           0
  T-20DayMin5 T-20DayMin6 T-20DayMin7 T-20DayMin8 T-20DayMin9 T-20DayMin10
1 0           0           0           0           0           0
2 0           0           0           0           0           0

## Pivot longer dataframe

In [3]:
df_deg_bins_piv_neg <- melt(df_deg_bins_neg%>%filter(!is.na(`T-1DayMin1`)), 
                       id.vars = c("Measured_date_CDC", "cell_x", "cell_y"),
                       variable.name = "Temp_bin",
                       value.name = "N_hours")
sprintf("%i x %i dataframe", nrow(df_deg_bins_piv_neg), ncol(df_deg_bins_piv_neg))
head(df_deg_bins_piv_neg,2)

[1] "161501010 x 5 dataframe"

  Measured_date_CDC cell_x cell_y Temp_bin   N_hours
1 42203             92.7   11.7   T-1DayMin1 0
2 42205             92.8    9.2   T-1DayMin1 0

In [4]:
df_deg_bins_piv_neg_wo0 <- df_deg_bins_piv_neg[N_hours!=0]

In [5]:
#Keep memory
rm(df_deg_bins_neg)
rm(df_deg_bins_piv_neg)

# Positive temperature dataframe

In [6]:
df_deg_bins_pos <- fread("./interm/df_T_cells_CDC_positive.csv")
sprintf("%i x %i dataframe", nrow(df_deg_bins_pos), ncol(df_deg_bins_pos))
head(df_deg_bins_pos,2)

[1] "173657 x 1383 dataframe"

  Measured_date_CDC cell_x cell_y T0DayMin1 T0DayMin2 T0DayMin3 T0DayMin4
1 42203             92.7   11.7   0         0         0         0
2 42205             92.8    9.2   0         0         0         0
  T0DayMin5 T0DayMin6 T0DayMin7 T0DayMin8 T0DayMin9 T0DayMin10 T0DayMin11
1 0         0         0         0         0         0          0
2 0         0         0         0         0         0          0
  T0DayMin12 T0DayMin13 T0DayMin14 T0DayMin15 T0DayMin16 T0DayMin17 T0DayMin18
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T0DayMin19 T0DayMin20 T0DayMin21 T0DayMin22 T0DayMin23 T0DayMin24 T0DayMin25
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T0DayMin26 T0DayMin27 T0DayMin28 T0DayMin29 T0DayMin30 T1DayMin1 T1DayMin2
1 0          0          0          0          0          0         0
2 0          0          0          0          0          0         0
  T1DayMin3 T1DayMin4 T1DayMin5 T1DayMin6 T1DayMin7 T1DayMin8 T1DayMin9
1 0         0         0         0         0         0         0
2 0         0         0         0         0         0         0
  T1DayMin10 T1DayMin11 T1DayMin12 T1DayMin13 T1DayMin14 T1DayMin15 T1DayMin16
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T1DayMin17 T1DayMin18 T1DayMin19 T1DayMin20 T1DayMin21 T1DayMin22 T1DayMin23
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T1DayMin24 T1DayMin25 T1DayMin26 T1DayMin27 T1DayMin28 T1DayMin29 T1DayMin30
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T2DayMin1 T2DayMin2 T2DayMin3 T2DayMin4 T2DayMin5 T2DayMin6 T2DayMin7
1 0         0         0         0         0         0         0
2 0         0         0         0         0         0         0
  T2DayMin8 T2DayMin9 T2DayMin10 T2DayMin11 T2DayMin12 T2DayMin13 T2DayMin14
1 0         0         0          0          0          0          0
2 0         0         0          0          0          0          0
  T2DayMin15 T2DayMin16 T2DayMin17 T2DayMin18 T2DayMin19 T2DayMin20 T2DayMin21
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T2DayMin22 T2DayMin23 T2DayMin24 T2DayMin25 T2DayMin26 T2DayMin27 T2DayMin28
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T2DayMin29 T2DayMin30 T3DayMin1 T3DayMin2 T3DayMin3 T3DayMin4 T3DayMin5
1 0          0          0         0         0         0         0
2 0          0          0         0         0         0         0
  T3DayMin6 T3DayMin7 T3DayMin8 T3DayMin9 T3DayMin10 T3DayMin11 T3DayMin12
1 0         0         0         0         0          0          0
2 0         0         0         0         0          0          0
  T3DayMin13 T3DayMin14 T3DayMin15 T3DayMin16 T3DayMin17 T3DayMin18 T3DayMin19
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T3DayMin20 T3DayMin21 T3DayMin22 T3DayMin23 T3DayMin24 T3DayMin25 T3DayMin26
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T3DayMin27 T3DayMin28 T3DayMin29 T3DayMin30 T4DayMin1 T4DayMin2 T4DayMin3
1 0          0          0          0          0         0         0
2 0          0          0          0          0         0         0
  T4DayMin4 T4DayMin5 T4DayMin6 T4DayMin7 T4DayMin8 T4DayMin9 T4DayMin10
1 0         0         0         0         0         0         0
2 0         0         0         0         0         0         0
  T4DayMin11 T4DayMin12 T4DayMin13 T4DayMin14 T4DayMin15 T4DayMin16 T4DayMin17
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T4DayMin18 T4DayMin19 T4DayMin20 T4DayMin21 T4DayMin22 T4DayMin23 T4DayMin24
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T4DayMin25 T4DayMin26 T4DayMin27 T4DayMin28 T4DayMin29 T4DayMin30 T5DayMin1
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T5DayMin2 T5DayMin3 T5DayMin4 T5DayMin5 T5DayMin6 T5DayMin7 T5DayMin8
1 0         0         0         0         0         0         0
2 0         0         0         0         0         0         0
  T5DayMin9 T5DayMin10 T5DayMin11 T5DayMin12 T5DayMin13 T5DayMin14 T5DayMin15
1 0         0          0          0          0          0          0
2 0         0          0          0          0          0          0
  T5DayMin16 T5DayMin17 T5DayMin18 T5DayMin19 T5DayMin20 T5DayMin21 T5DayMin22
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T5DayMin23 T5DayMin24 T5DayMin25 T5DayMin26 T5DayMin27 T5DayMin28 T5DayMin29
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T5DayMin30 T6DayMin1 T6DayMin2 T6DayMin3 T6DayMin4 T6DayMin5 T6DayMin6
1 0          0         0         0         0         0         0
2 0          0         0         0         0         0         0
  T6DayMin7 T6DayMin8 T6DayMin9 T6DayMin10 T6DayMin11 T6DayMin12 T6DayMin13
1 0         0         0         0          0          0          0
2 0         0         0         0          0          0          0
  T6DayMin14 T6DayMin15 T6DayMin16 T6DayMin17 T6DayMin18 T6DayMin19 T6DayMin20
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T6DayMin21 T6DayMin22 T6DayMin23 T6DayMin24 T6DayMin25 T6DayMin26 T6DayMin27
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T6DayMin28 T6DayMin29 T6DayMin30 T7DayMin1 T7DayMin2 T7DayMin3 T7DayMin4
1 0          0          0          0         0         0         0
2 0          0          0          0         0         0         0
  T7DayMin5 T7DayMin6 T7DayMin7 T7DayMin8 T7DayMin9 T7DayMin10 T7DayMin11
1 0         0         0         0         0         0          0
2 0         0         0         0         0         0          0
  T7DayMin12 T7DayMin13 T7DayMin14 T7DayMin15 T7DayMin16 T7DayMin17 T7DayMin18
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T7DayMin19 T7DayMin20 T7DayMin21 T7DayMin22 T7DayMin23 T7DayMin24 T7DayMin25
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T7DayMin26 T7DayMin27 T7DayMin28 T7DayMin29 T7DayMin30 T8DayMin1 T8DayMin2
1 0          0          0          0          0          0         0
2 0          0          0          0          0          0         0
  T8DayMin3 T8DayMin4 T8DayMin5 T8DayMin6 T8DayMin7 T8DayMin8 T8DayMin9
1 0         0         0         0         0         0         0
2 0         0         0         0         0         0         0
  T8DayMin10 T8DayMin11 T8DayMin12 T8DayMin13 T8DayMin14 T8DayMin15 T8DayMin16
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T8DayMin17 T8DayMin18 T8DayMin19 T8DayMin20 T8DayMin21 T8DayMin22 T8DayMin23
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T8DayMin24 T8DayMin25 T8DayMin26 T8DayMin27 T8DayMin28 T8DayMin29 T8DayMin30
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T9DayMin1 T9DayMin2 T9DayMin3 T9DayMin4 T9DayMin5 T9DayMin6 T9DayMin7
1 0         0         0         0         0         0         0
2 0         0         0         0         0         0         0
  T9DayMin8 T9DayMin9 T9DayMin10 T9DayMin11 T9DayMin12 T9DayMin13 T9DayMin14
1 0         0         0          0          0          0          0
2 0         0         0          0          0          0          0
  T9DayMin15 T9DayMin16 T9DayMin17 T9DayMin18 T9DayMin19 T9DayMin20 T9DayMin21
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T9DayMin22 T9DayMin23 T9DayMin24 T9DayMin25 T9DayMin26 T9DayMin27 T9DayMin28
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T9DayMin29 T9DayMin30 T10DayMin1 T10DayMin2 T10DayMin3 T10DayMin4 T10DayMin5
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T10DayMin6 T10DayMin7 T10DayMin8 T10DayMin9 T10DayMin10 T10DayMin11
1 0          0          0          0          0           0
2 0          0          0          0          0           0
  T10DayMin12 T10DayMin13 T10DayMin14 T10DayMin15 T10DayMin16 T10DayMin17
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T10DayMin18 T10DayMin19 T10DayMin20 T10DayMin21 T10DayMin22 T10DayMin23
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T10DayMin24 T10DayMin25 T10DayMin26 T10DayMin27 T10DayMin28 T10DayMin29
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T10DayMin30 T11DayMin1 T11DayMin2 T11DayMin3 T11DayMin4 T11DayMin5 T11DayMin6
1 0           0          0          0          0          0          0
2 0           0          0          0          0          0          0
  T11DayMin7 T11DayMin8 T11DayMin9 T11DayMin10 T11DayMin11 T11DayMin12
1 0          0          0          0           0           0
2 0          0          0          0           0           0
  T11DayMin13 T11DayMin14 T11DayMin15 T11DayMin16 T11DayMin17 T11DayMin18
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T11DayMin19 T11DayMin20 T11DayMin21 T11DayMin22 T11DayMin23 T11DayMin24
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T11DayMin25 T11DayMin26 T11DayMin27 T11DayMin28 T11DayMin29 T11DayMin30
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T12DayMin1 T12DayMin2 T12DayMin3 T12DayMin4 T12DayMin5 T12DayMin6 T12DayMin7
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T12DayMin8 T12DayMin9 T12DayMin10 T12DayMin11 T12DayMin12 T12DayMin13
1 0          0          0           0           0           0
2 0          0          0           0           0           0
  T12DayMin14 T12DayMin15 T12DayMin16 T12DayMin17 T12DayMin18 T12DayMin19
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T12DayMin20 T12DayMin21 T12DayMin22 T12DayMin23 T12DayMin24 T12DayMin25
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T12DayMin26 T12DayMin27 T12DayMin28 T12DayMin29 T12DayMin30 T13DayMin1
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T13DayMin2 T13DayMin3 T13DayMin4 T13DayMin5 T13DayMin6 T13DayMin7 T13DayMin8
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T13DayMin9 T13DayMin10 T13DayMin11 T13DayMin12 T13DayMin13 T13DayMin14
1 0          0           0           0           0           0
2 0          0           0           0           0           0
  T13DayMin15 T13DayMin16 T13DayMin17 T13DayMin18 T13DayMin19 T13DayMin20
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T13DayMin21 T13DayMin22 T13DayMin23 T13DayMin24 T13DayMin25 T13DayMin26
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T13DayMin27 T13DayMin28 T13DayMin29 T13DayMin30 T14DayMin1 T14DayMin2
1 0           0           0           0           0          0
2 0           0           0           0           0          0
  T14DayMin3 T14DayMin4 T14DayMin5 T14DayMin6 T14DayMin7 T14DayMin8 T14DayMin9
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T14DayMin10 T14DayMin11 T14DayMin12 T14DayMin13 T14DayMin14 T14DayMin15
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T14DayMin16 T14DayMin17 T14DayMin18 T14DayMin19 T14DayMin20 T14DayMin21
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T14DayMin22 T14DayMin23 T14DayMin24 T14DayMin25 T14DayMin26 T14DayMin27
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T14DayMin28 T14DayMin29 T14DayMin30 T15DayMin1 T15DayMin2 T15DayMin3
1 0           0           0           0          0          0
2 0           0           0           0          0          0
  T15DayMin4 T15DayMin5 T15DayMin6 T15DayMin7 T15DayMin8 T15DayMin9 T15DayMin10
1 0          0          0          0          0          0          0
2 0          0          0          0          0          0          0
  T15DayMin11 T15DayMin12 T15DayMin13 T15DayMin14 T15DayMin15 T15DayMin16
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T15DayMin17 T15DayMin18 T15DayMin19 T15DayMin20 T15DayMin21 T15DayMin22
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T15DayMin23 T15DayMin24 T15DayMin25 T15DayMin26 T15DayMin27 T15DayMin28
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T15DayMin29 T15DayMin30 T16DayMin1 T16DayMin2 T16DayMin3 T16DayMin4
1 0           0           0          0          0          0
2 0           0           0          0          0          0
  T16DayMin5 T16DayMin6 T16DayMin7 T16DayMin8 T16DayMin9 T16DayMin10
1 0          0          0          0          0          0
2 0          0          0          0          0          0
  T16DayMin11 T16DayMin12 T16DayMin13 T16DayMin14 T16DayMin15 T16DayMin16
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T16DayMin17 T16DayMin18 T16DayMin19 T16DayMin20 T16DayMin21 T16DayMin22
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T16DayMin23 T16DayMin24 T16DayMin25 T16DayMin26 T16DayMin27 T16DayMin28
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T16DayMin29 T16DayMin30 T17DayMin1 T17DayMin2 T17DayMin3 T17DayMin4
1 0           0           0          0          0          0
2 0           0           0          0          0          0
  T17DayMin5 T17DayMin6 T17DayMin7 T17DayMin8 T17DayMin9 T17DayMin10
1 0          0          0          0          0          0
2 0          0          0          0          0          0
  T17DayMin11 T17DayMin12 T17DayMin13 T17DayMin14 T17DayMin15 T17DayMin16
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T17DayMin17 T17DayMin18 T17DayMin19 T17DayMin20 T17DayMin21 T17DayMin22
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T17DayMin23 T17DayMin24 T17DayMin25 T17DayMin26 T17DayMin27 T17DayMin28
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T17DayMin29 T17DayMin30 T18DayMin1 T18DayMin2 T18DayMin3 T18DayMin4
1 0           0           0          0          0          0
2 0           0           0          0          0          0
  T18DayMin5 T18DayMin6 T18DayMin7 T18DayMin8 T18DayMin9 T18DayMin10
1 0          0          0          0          0          0
2 0          0          0          0          0          0
  T18DayMin11 T18DayMin12 T18DayMin13 T18DayMin14 T18DayMin15 T18DayMin16
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T18DayMin17 T18DayMin18 T18DayMin19 T18DayMin20 T18DayMin21 T18DayMin22
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T18DayMin23 T18DayMin24 T18DayMin25 T18DayMin26 T18DayMin27 T18DayMin28
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T18DayMin29 T18DayMin30 T19DayMin1 T19DayMin2 T19DayMin3 T19DayMin4
1 0           0           0          0          0          0
2 0           0           0          0          0          0
  T19DayMin5 T19DayMin6 T19DayMin7 T19DayMin8 T19DayMin9 T19DayMin10
1 0          0          0          0          0          0
2 0          0          0          0          0          0
  T19DayMin11 T19DayMin12 T19DayMin13 T19DayMin14 T19DayMin15 T19DayMin16
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T19DayMin17 T19DayMin18 T19DayMin19 T19DayMin20 T19DayMin21 T19DayMin22
1 0           0           0           0           0           0
2 0           0           0           0           0           0
  T19DayMin23 T19DayMin24 T19DayMin25 T19DayMin26 T19DayMin27 ⋯ T26DayMin1
1 0           0           0           0           0           ⋯ 10
2 0           0           0           0           0           ⋯ 10
  T26DayMin2 T26DayMin3 T26DayMin4 T26DayMin5 T26DayMin6 T26DayMin7 T26DayMin8
1 0          11         14         10          6         10         5
2 8           3          4          7         13         15         5
  T26DayMin9 T26DayMin10 T26DayMin11 T26DayMin12 T26DayMin13 T26DayMin14
1 12         0           0           0           0           4
2  8         4           0           0           0           0
  T26DayMin15 T26DayMin16 T26DayMin17 T26DayMin18 T26DayMin19 T26DayMin20
1 7           2           2           11          8           19
2 3           0           0            0          0            4
  T26DayMin21 T26DayMin22 T26DayMin23 T26DayMin24 T26DayMin25 T26DayMin26
1 18          18          3           3           1           0
2  2           9          8           8           3           0
  T26DayMin27 T26DayMin28 T26DayMin29 T26DayMin30 T27DayMin1 T27DayMin2
1 0           1           7           13           8         17

## Pivot longer dataframe

In [7]:
df_deg_bins_piv_pos <- melt(df_deg_bins_pos%>%filter(!is.na(T0DayMin1)), 
                       id.vars = c("Measured_date_CDC", "cell_x", "cell_y"),
                       variable.name = "Temp_bin",
                       value.name = "N_hours")
sprintf("%i x %i dataframe", nrow(df_deg_bins_piv_pos), ncol(df_deg_bins_piv_pos))
head(df_deg_bins_piv_pos,2)

[1] "239646660 x 5 dataframe"

  Measured_date_CDC cell_x cell_y Temp_bin  N_hours
1 42203             92.7   11.7   T0DayMin1 0
2 42205             92.8    9.2   T0DayMin1 0

In [8]:
df_deg_bins_piv_pos_wo0 <- df_deg_bins_piv_pos[N_hours!=0]

In [9]:
#Keep memory
rm(df_deg_bins_pos,df_deg_bins_piv_pos)
gc()

       used      (Mb)   gc trigger (Mb)   max used   (Mb)
Ncells   1294773   69.2    2425397  129.6    2425397   129.6
Vcells 188621922 1439.1 1263142932 9637.1 1425914691 10878.9

# Rbind positive and negative temp

In [10]:
df_deg_bins_piv_wo0 <- rbind(df_deg_bins_piv_pos_wo0,df_deg_bins_piv_neg_wo0)

In [11]:
rm(df_deg_bins_piv_neg_wo0,df_deg_bins_piv_pos_wo0)
gc()

       used      (Mb)   gc trigger (Mb)   max used   (Mb)
Ncells   1295780   69.3    2425397  129.6    2425397   129.6
Vcells 188618525 1439.1 1010514346 7709.7 1425914691 10878.9

# Extract temperature value

In [12]:
df_deg_bins_piv_wo0[, Temp := as.numeric(sub("Day","",sub("T","",str_extract(Temp_bin, "\\s*(.+)Day"))))]
sprintf("%i x %i dataframe", nrow(df_deg_bins_piv_wo0), ncol(df_deg_bins_piv_wo0))
head(df_deg_bins_piv_wo0,2)

[1] "53234477 x 6 dataframe"

  Measured_date_CDC cell_x cell_y Temp_bin  N_hours Temp
1 42474             91.9   27.6   T0DayMin1 2       0
2 42667             96.7   28.3   T0DayMin1 2       0

# Extract day value

In [13]:
df_deg_bins_piv_wo0[, Day_Min := as.numeric(sub("Min","",str_extract(Temp_bin, "Min\\s*(.+)")))]
sprintf("%i x %i dataframe", nrow(df_deg_bins_piv_wo0), ncol(df_deg_bins_piv_wo0))
head(df_deg_bins_piv_wo0,2)

[1] "53234477 x 7 dataframe"

  Measured_date_CDC cell_x cell_y Temp_bin  N_hours Temp Day_Min
1 42474             91.9   27.6   T0DayMin1 2       0    1
2 42667             96.7   28.3   T0DayMin1 2       0    1

## SAVE

In [14]:
fwrite(df_deg_bins_piv_wo0,"./interm/df_T_cells_CDC_longer.csv")